"""Per-page content specs for the SEO corpus (plan §5), commercial real estate batch. Same
contract as scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics
(shell, schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below
owns the UNIQUE, hand-written, commercial-real-estate-specific substance that clears the
uniqueness gate. Never templated find-and-replace, never the plumber content reworded.

Real Estate hub. Four service angles are here in one file (the ai-receptionist dict carries
"demo": True). Commercial real estate is a longer-cycle, higher-value, relationship business,
not a same-day-emergency trade, so the copy leans on pipeline, relationships, and credibility,
not the missed-call panic that fits the trades. Each example body ends with the literal
"Illustrative example, not a client." per the honesty rule; if the generator also appends that
line, dedupe there.
"""

SPECS = [
# ==================== AI Receptionist for Commercial Real Estate ====================
{
    "slug": "ai-receptionist-for-commercial-real-estate", "demo": True,
    "trade_slug": "commercial_real_estate", "trade_plural": "commercial real estate brokers",
    "hub_name": "Real Estate", "hub_slug": "industry-real-estate.html",
    "breadcrumb_leaf": "AI Receptionist for Commercial Real Estate",
    "title": "AI Receptionist for Commercial Real Estate | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Commercial Real Estate",
    "meta_desc": "A commercial real estate answering service answers every listing, lease, and investment inquiry, qualifies it, and books the call while you are on a site tour.",
    "service_schema_name": "AI Receptionist for Commercial Real Estate",
    "eyebrow": "For Commercial Real Estate",
    "h1_html": "AI Receptionist <em>for Commercial Real Estate</em>",
    "answer_block": "A commercial real estate answering service answers every inquiry the moment it comes in, whether you are on a site tour or in a negotiation, tells a serious tenant, landlord, or investor apart from a tire-kicker, qualifies the opportunity, and books the call on your calendar. You keep your own number, and every lead belongs to you.",
    "sections": [
        {"h2_html": "The inquiry about your listing does not wait for you to <em>leave the site tour</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A principal or a tenant rep who calls about a listing, an available suite, or an investment opportunity is not going to leave a voicemail and wait. They are working several brokers and several buildings at once, and if the call rolls to voicemail while you are out showing space or in the middle of a negotiation, the conversation simply happens with whoever picked up. Commercial inquiries do not carry the panic of a home emergency, but they carry real money and a short window of attention, and a serious one that goes unanswered is a mandate or a tenant that quietly lands with another broker.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An answering service built for commercial real estate answers on the first ring, finds out whether the caller is a tenant looking for space, a landlord who wants representation, or an investor asking about a specific listing, captures the property and the details, and books the follow-up on your calendar. The inquiry is captured and qualified instead of lost to voicemail while you are standing in an empty warehouse with no time to talk.</p>'},
        {"h2_html": "Built around how commercial brokers <em>actually get inquiries</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your inquiries do not arrive on a schedule and they do not all come from the same place. A sign call on a listing, a message off a marketing flyer, a referral from a past client, an out-of-market investor phoning from three time zones over, a tenant rep circling a submarket for a client, they all land while you are at a tour, in the car, or across the table closing something else. A voicemail box cannot tell a qualified principal from someone kicking tires, and a generic call center reading a script does not know a tenant representation call from a listing inquiry or a cooperating broker.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers every inquiry live, including the after-hours and weekend calls from investors and out-of-market principals working on their own clock.</li><li>Qualifies the way you would: is this a tenant, a landlord, a buyer, or a broker, what property or submarket, roughly what size and timeline, and who has the authority to decide.</li><li>Captures the property of interest and the details, books the call or tour on your calendar, and routes anything time-sensitive to you at once.</li><li>Treats a past client, a referral, or a broker you already work with differently from a first-time caller, so the relationships you have built never hit a voicemail.</li></ul>'},
        {"h2_html": "Qualify the opportunity before it ever reaches <em>your calendar</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Commercial leads vary more than almost any other business. One call is a funded buyer with a signed letter and a deadline, the next is a curious owner who will not transact for years, and your time is far too expensive to spend the same amount on both. The answering service asks the qualifying questions up front, what the caller needs, the rough size and use, the timeline, and whether they are the decision maker, so a real opportunity reaches you ready to move while the early tire-kicker is captured, logged, and set aside for follow-up rather than dropped. You walk into every call already knowing who you are talking to.</p>'},
        {"h2_html": "You own the number, the inquiries, and the <em>relationships</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing number, or a new one registered in your name, not ours. Every caller, every property they asked about, and every contact detail is yours and exportable any time, because in commercial real estate your relationships are the business and they should never be locked inside software you rent. The answering service is one piece of the Top Shelf platform, and it comes together with the CRM on the Signature plan, so a lead you catch today is still being nurtured when the deal is finally ready months from now. Nothing you capture is left to go cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "An out-of-state investor, captured while you are <em>at a tour</em>",
        "body_html": 'An investor two states away is scanning listings on a Saturday and calls about a property you have listed, ready to talk about a 1031 exchange with a clock running on it. You are across town walking a client through a space and cannot pick up. Instead of a voicemail the investor never leaves, your answering service takes the call, confirms what they are looking for and their timeline, captures their number and the property, and books a call with you for Monday morning while flagging it as time-sensitive. You start the week with a qualified buyer already on your calendar instead of hearing the opportunity went to another broker. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business line, or set up a new one registered in your name. Either way the number and every inquiry that comes through it belong to you and go with you if you ever leave.'),
        ("Can it tell a serious buyer or tenant from a tire-kicker?",
         'Yes, that is the point. It asks what the caller needs, the rough size and use, the timeline, and whether they can decide, then treats a funded, time-sensitive prospect differently from someone years away from transacting. You set what counts as a lead worth interrupting you for.'),
        ("Will it actually book the call on my calendar?",
         'Yes. Qualified calls and tours land on your calendar based on your availability, and you get the details right away. Anything time-sensitive is flagged to you at once so you decide whether to step out of what you are doing.'),
        ("Will it sound like a robot to a principal or another broker?",
         'It answers naturally and professionally, and it is upfront rather than pretending to be a person. A serious caller mostly needs to know their inquiry reached a real firm and that someone will follow up, and a capable voice that captures the details beats a voicemail box every time. You can hear it handle a live call before you decide.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We configure your qualifying questions, your calendar, and your routing rules for you, so it is answering in days, not weeks. Start with a free audit and we will find the gap in what your current setup is letting slip.')],
    "related": [
        ("industry-real-estate.html", "Everything Top Shelf does for commercial real estate"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-commercial-real-estate.html", "The CRM that keeps every captured lead warm"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting inquiries slip to <em>voicemail</em>",
    "cta_sub": "Get a free audit that finds the gap in how many listing, lease, and investment inquiries your current setup is letting slip, whether you work with us or not. No credit card, never a call center.",
},
# ======================== CRM for Commercial Real Estate ========================
{
    "slug": "crm-for-commercial-real-estate",
    "trade_slug": "commercial_real_estate", "trade_plural": "commercial real estate brokers",
    "hub_name": "Real Estate", "hub_slug": "industry-real-estate.html",
    "breadcrumb_leaf": "CRM for Commercial Real Estate",
    "title": "CRM for Commercial Real Estate | Top Shelf Business Solutions",
    "og_title": "CRM for Commercial Real Estate",
    "meta_desc": "A commercial real estate CRM keeps every landlord, tenant, and investor in one pipeline and follows up for months to years, so no relationship goes cold.",
    "service_schema_name": "CRM for Commercial Real Estate",
    "eyebrow": "For Commercial Real Estate",
    "h1_html": "CRM <em>for Commercial Real Estate</em>",
    "answer_block": "A commercial real estate CRM keeps every landlord, tenant, investor, and broker in one pipeline and follows up for you across a cycle that runs months to years, so the lease coming due in two years and the investor you met at a closing both call you first. Your relationships quietly become your pipeline.",
    "sections": [
        {"h2_html": "In commercial real estate, the deal is the relationship you kept <em>warm for years</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A tenant whose lease comes up in three years, an investor who buys once every few years, a landlord you meet today who will not list until next spring: the broker who is still in front of them when the timing finally arrives is the one who wins the deal, and it is rarely the one with the sharpest pitch. It is the one who stayed in touch. Commercial real estate runs on a longer clock than almost any business, and the place where money is lost is not a missed call, it is the contact you met once, meant to follow up with, and never did.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every one of those relationships in front of you and follows up on a schedule you set, with the market notes and check-ins that keep your name familiar over a cycle measured in months and years. The landlord, the tenant, and the investor hear from you at the right moments instead of forgetting you exist, and the deal comes back to you when it is finally live.</p>'},
        {"h2_html": "A pipeline you <em>cannot hold in your head</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A working commercial broker is tracking hundreds of relationships at once, and every one sits at a different stage on a different clock. A landlord with space coming available, a tenant whose lease is counting down, an investor with specific acquisition criteria, a broker you cooperate with, each needs a different touch at a different time, and none of it fits in your memory or a spreadsheet row you never open.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every contact, property, deal, note, and key date lives in one place instead of scattered across your inbox, your phone, and a stack of business cards.</li><li>Lease expirations, loan maturities, and hold periods are tracked as the follow-up dates they really are, so the opportunity surfaces before a competitor gets there first.</li><li>Deals move through stages you can actually see, from first conversation to letter of intent to close, so nothing stalls quietly in the middle.</li><li>You can pull up who you have not spoken to in too long and reach the right relationship with the right reason at the right moment.</li></ul>'},
        {"h2_html": "A lease expiration is a follow-up date <em>in disguise</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The most valuable dates in your pipeline are the ones nobody is watching. A tenant whose lease expires in eighteen months is a live opportunity today, not next year, because the search and the decision start long before the expiration. The CRM surfaces those dates for you and prompts the outreach at the moment it matters, so you are the broker who called first with a plan, not the one who found out after the tenant already renewed or moved. Between those milestones, steady and light touches, a market update, a relevant listing, a quick check-in, keep you familiar without you having to remember every name and date.</p>'},
        {"h2_html": "You own the relationships, and it works with the <em>rest of the system</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every contact and every note is yours and exportable any time, not locked inside software you rent, because your relationships are the single most valuable thing you own in this business. The CRM is one piece of the Top Shelf platform and connects to the answering service it comes together with on the Signature plan, so an inquiry that service captures lands in your pipeline and gets followed up on automatically, and to your marketing, so the investor who found your market commentary is nurtured toward a first conversation. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The investor you met at a closing, <em>two years later</em>",
        "body_html": 'You meet an investor at a closing and add them to your pipeline with a note about the kind of asset they are chasing. Normally that contact fades after a month. Instead the CRM keeps them on a light touch, a market note here, a relevant listing there, all written to sound like you, over the next two years. When they finally have capital to place and start looking, yours is the only name that stayed in front of them the whole time, so they call you before they call anyone else. You never sat down to chase it. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing contacts and deals?",
         'Yes. Your current contacts, properties, and deal history come in and live in one place, and everything stays yours and exportable. The point is to make the relationships you have already built actually work for you.'),
        ("Can it track lease expirations and other key dates?",
         'Yes. Lease expirations, loan maturities, hold periods, and follow-up dates are tracked and surfaced ahead of time, so a tenant coming up for renewal or an owner nearing the end of a hold shows up as an opportunity while there is still time to act.'),
        ("Will it follow up over a cycle this long without me?",
         'Yes, on a schedule you approve. It keeps a light, steady touch on every relationship, market notes, relevant listings, check-ins, so a contact years from transacting still knows you by name when the timing arrives. You can step in and reach anyone personally any time.'),
        ("How is this different from a spreadsheet or my contacts app?",
         'A spreadsheet does not remind you that a lease is coming due, does not follow up on its own, and does not show you which deals are stalling. The CRM does all of that on the long clock this business runs on, so the repeat and referral work actually shows up instead of depending on your memory.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your contacts and deals, build your follow-up and key-date reminders, and connect it to your calls and marketing, so it is working in days. Start with a free audit and we will find the gap where relationships are going cold today.')],
    "related": [
        ("industry-real-estate.html", "Everything Top Shelf does for commercial real estate"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-commercial-real-estate.html", "The answering service that feeds it every inquiry"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting relationships <em>go cold</em>",
    "cta_sub": "Get a free audit that finds the gap where your contacts and long-cycle opportunities are slipping through today, whether you work with us or not. No credit card, never a call center.",
},
# ====================== Marketing for Commercial Real Estate ======================
{
    "slug": "marketing-for-commercial-real-estate",
    "trade_slug": "commercial_real_estate", "trade_plural": "commercial real estate brokers",
    "hub_name": "Real Estate", "hub_slug": "industry-real-estate.html",
    "breadcrumb_leaf": "Marketing for Commercial Real Estate",
    "title": "Marketing for Commercial Real Estate | Top Shelf Business Solutions",
    "og_title": "Marketing for Commercial Real Estate",
    "meta_desc": "Commercial real estate marketing builds credibility with market-report content and local search, so investors and tenant reps find and trust you first.",
    "service_schema_name": "Marketing for Commercial Real Estate",
    "eyebrow": "For Commercial Real Estate",
    "h1_html": "Marketing <em>for Commercial Real Estate</em>",
    "answer_block": "Commercial real estate marketing keeps you visible and credible where principals and tenant reps look before they ever call, market-report content, local commercial search, and a professional presence, so the investor researching your submarket and the tenant rep hunting space find you and trust you first.",
    "sections": [
        {"h2_html": "In commercial real estate, marketing is <em>credibility</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A principal choosing who lists their building, or a tenant rep deciding who to call about space, vets the broker before the first conversation. They look for market knowledge, current listings, and a track record, and they form an opinion about whether you are a serious player long before your phone rings. That is the real job of marketing in this business: not to chase people who have no deal today, but to make sure that when a decision maker looks you up, what they find earns the call. Get that right and you are on the shortlist before you have said a word.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Marketing for commercial real estate is about being visible and credible to a specific, high-value audience, investors, tenant reps, landlords, and the brokers you cooperate with, in the exact places they look. It is a quieter, more targeted game than consumer advertising, and it is won with authority rather than volume.</p>'},
        {"h2_html": "Your market knowledge is your <em>best marketing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The content that actually moves commercial prospects is the content that proves you know the market. A read on a submarket, a note on where rents or demand seem to be heading, a plain breakdown of what a lease clause really means for a tenant, this is what investors and tenant reps search for, save, and share, and it positions you as the expert they want on their side. You supply the market view; the platform turns it into the posts, pages, and updates that carry it to the people making decisions. It is the difference between a broker who advertises and a broker who gets quoted.</p>'},
        {"h2_html": "Be found by the people looking for <em>space or representation</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a tenant rep needs space in your submarket, or an investor wants a broker who knows a particular asset class, they search, and commercial searches are lower in volume and far higher in intent than anything on the consumer side. Being present and credible for the specific terms that matter in your market, the property types you handle and the areas you cover, is what puts you in front of the handful of people whose deal is worth more than a hundred casual clicks. You do not need to be everywhere. You need to be found by the right few at the moment they are looking.</p>'},
        {"h2_html": "Stay in front of a small, <em>high-value market</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Commercial real estate is a small world, and the same principals, brokers, and investors turn up again and again over the years. A steady, professional presence, regular market content, an active and accurate profile, listings promoted where the right people see them, keeps you top of mind in that small circle so you are the name that comes up when a deal is forming. This is the public-facing side of the work, aimed at people who are not yet your clients; the private, one-to-one follow-up with the relationships already in your database is what the CRM handles.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "An investor who followed your market notes <em>before they called</em>",
        "body_html": 'An investor researching a submarket you cover starts reading the market notes and listing updates you put out, months before they are ready to buy. They do not reach out at first. They just keep seeing your name attached to a credible read on the area, so when their capital is finally ready and they need a broker who knows that market, you are the one they already trust enough to call. The first real conversation feels like a continuation, not a cold pitch, because your marketing did the introduction for you. Illustrative example, not a client.'},
    "faqs": [
        ("Do you create the market content for me?",
         'We build and run the content and the profile, but the market view is yours. You supply the read on your submarket and your deals, and we turn it into the posts, pages, and updates that carry it to investors and tenant reps. We never invent figures or market claims on your behalf.'),
        ("How is commercial real estate marketing different from residential?",
         'It is quieter, more targeted, and built on credibility rather than volume. Commercial searches are lower in number but far higher in value, and the audience is a small set of principals, tenant reps, and investors who vet you before they call, so authority matters more than reach.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with people already in your pipeline. Marketing is the public-facing side, your content, profile, and local visibility, aimed at decision makers who are not your clients yet but need to find and trust you before a deal forms.'),
        ("Will this bring me leads right away?",
         'Marketing in this business compounds rather than spikes. It builds the credibility and visibility that make you the name a principal already trusts when a deal finally comes up, which is a longer game than consumer advertising and a more durable one. The inquiries it eventually drives are handled by the answering service and the CRM.'),
        ("How long before I see it working?",
         'A neglected profile and a thin content presence can start looking credible within weeks once they are active and consistent, and authority builds from there over months. Setup is included, and a free audit will find the gap between how visible you are today and how visible the brokers you compete with are.')],
    "related": [
        ("industry-real-estate.html", "Everything Top Shelf does for commercial real estate"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-commercial-real-estate.html", "The website that showcases listings and captures the demand"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the broker they <em>already trust</em>",
    "cta_sub": "Get a free audit that finds the gap between how visible and credible you are today and where the brokers you compete with stand, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Websites & SEO for Commercial Real Estate ====================
{
    "slug": "websites-seo-for-commercial-real-estate",
    "trade_slug": "commercial_real_estate", "trade_plural": "commercial real estate brokers",
    "hub_name": "Real Estate", "hub_slug": "industry-real-estate.html",
    "breadcrumb_leaf": "Websites & SEO for Commercial Real Estate",
    "title": "Websites & SEO for Commercial Real Estate | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Commercial Real Estate",
    "meta_desc": "A commercial real estate website built for SEO showcases your listings and closed deals and ranks for local commercial searches, so principals find you first.",
    "service_schema_name": "Websites & SEO for Commercial Real Estate",
    "eyebrow": "For Commercial Real Estate",
    "h1_html": "Websites &amp; SEO <em>for Commercial Real Estate</em>",
    "answer_block": "A commercial real estate website built for SEO showcases your current listings and closed deals and ranks for the searches investors and tenant reps actually run, office space for lease, commercial broker in your city, so a serious prospect finds you, sees your track record, and calls you first.",
    "sections": [
        {"h2_html": "A principal checks your website <em>before they call you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Before an owner hands you a listing or a tenant rep brings you into a search, they look you up, and your website is where they decide whether you are a serious broker or a risk. A dated, thin site that could belong to anyone quietly loses the mandate to the broker whose site shows real listings, a genuine track record, and command of the market. In a business where a single engagement can make the year, a website that undersells you is not a cosmetic problem. It is deals going to someone who simply looked more credible online.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A website built for commercial real estate does two jobs at once. It earns the trust of the principal who is vetting you, and it ranks for the specific searches a tenant rep or investor runs when they are actually looking, so you are both found by new prospects and believed by the ones already considering you.</p>'},
        {"h2_html": "Showcase your listings and your <em>closed deals</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The fastest way to earn trust from a commercial prospect is to show them proof before the first call. A site that presents your current availabilities clearly, and a track record of the transactions you have represented and closed, tells an owner or a tenant that you have done this exact thing before and can do it for them. You supply the deals and the details; the site presents them in a way that reads as a serious brokerage rather than a template. That proof is what wins the listing pitch and the tenant-representation engagement, because it answers the only question the prospect really has: can this broker deliver.</p>'},
        {"h2_html": "Rank for the specific searches in <em>your market</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to rank for broad national terms, and you will not this year. You need to own the searches that actually produce commercial business in your market: office space for lease in your city, commercial real estate broker in your city, industrial or retail space in the submarkets you cover, tenant representation, land for sale. These searches are lower in volume than anything residential and far higher in intent, because the person typing them has a real requirement and a budget behind it. Pages built around the property types you handle and the areas you serve are what put you in front of them.</p>'},
        {"h2_html": "The site is <em>yours</em>, and it compounds",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A website you own keeps working long after it is built, ranking, showcasing your track record, and earning trust for as long as it exists, and it is registered to you, not a portal or a franchise that can drop you or bury you beneath its own brand. It is a one-time build that becomes a durable asset rather than a fee that vanishes the day you stop paying. The site plugs into the same CRM that keeps every lead it captures warm through a long sales cycle, and the answering service that fields the calls it drives, so nothing it earns you slips away between the first click and a deal that closes a year later.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A tenant rep finds your listings, and your <em>track record</em>",
        "body_html": 'A tenant rep with a client who needs space searches for available suites in a submarket you cover and lands on your site. Instead of a bare listing on a portal that treats you as interchangeable, they find your page for that area, your current availabilities, and a track record of comparable deals you have closed. They call you directly, already confident you know the market, and the search becomes your engagement. No portal sat between you and the prospect, and no lead fee came out of the deal. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site outrank the big commercial portals?",
         'Not for the broadest terms, and you do not need it to. It can realistically rank for your name, your specific submarkets, and the property-type and representation searches a national portal has no reason to target well, which is exactly where a local commercial broker can win.'),
        ("How is a website different from paying a portal for leads?",
         'A portal rents you a lead it also shows to competing brokers and treats you as interchangeable, and it stops the day you stop paying. A website you own captures prospects who come to you directly, shows your track record instead of a bare listing, and keeps working without a per-lead fee.'),
        ("Can it really show my track record and current listings?",
         'Yes. You supply your availabilities and the deals you have represented and closed, and the site presents them so a prospect sees proof before the first call. We never invent transactions or figures; the credibility on the site is your real record, presented well.'),
        ("Do I need to rank in every submarket I cover?",
         'No. We build pages for your core property types and the submarkets that matter most first, then expand, so you own the highest-intent searches rather than spreading thin across a whole metro at once.'),
        ("How long until it starts ranking?",
         'Specific, local commercial searches can start moving within weeks, and broader terms compound over months. It is a one-time build you own, not a subscription that disappears when you stop paying, and a free audit will find the gap between where your site stands today and what the market is searching for.')],
    "related": [
        ("industry-real-estate.html", "Everything Top Shelf does for commercial real estate"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-commercial-real-estate.html", "Staying visible and credible beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results in <em>your own market</em>",
    "cta_sub": "Get a free audit that finds the gap between your website and local commercial search presence and what your prospects are actually searching for, whether you work with us or not. No credit card, never a call center.",
},
]
