"""Per-page content specs for the SEO corpus (plan §5), Painters batch. Same contract as
scripts/corpus_specs.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, painter-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber or roofer content reworded.

Home Services hub, trade_slug "painters". All seven service angles are here in one file (the
ai-receptionist dict carries "demo": True and matches the SPECS[0] shape in generate_corpus.py
key-for-key). Each example body ends with the literal "Illustrative example, not a client." per
the honesty rule; if the generator also appends that line, dedupe there.

The painter reality this file is written to: painting is a considered, planned, big-ticket
purchase, not a 2am emergency. Homeowners line up three estimates and hire whoever answered or
followed up. The money slips through the gap between the walkthrough and the signature, on
interior repaints, whole-exterior jobs, and cabinet refinishing, across a long consideration
cycle and a weather-bound exterior season. The urgency is the QUOTE that goes cold, never a leak.
"""

SPECS = [
# ============================ AI Receptionist for Painters ============================
{
    "slug": "ai-receptionist-for-painters", "demo": True,
    "trade_slug": "painters", "trade_plural": "painters",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Painters",
    "title": "AI Receptionist for Painters | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Painters",
    "meta_desc": "An AI receptionist for painters answers every call while your hands are full, qualifies the repaint, and books the estimate straight onto your calendar.",
    "service_schema_name": "AI Receptionist for Painters",
    "eyebrow": "For Painters",
    "h1_html": "AI Receptionist <em>for Painters</em>",
    "answer_block": "An AI receptionist for painters answers every call the moment it rings, even when your hands are covered in paint or you are up a ladder on an exterior job, finds out what the homeowner wants painted, and books the estimate straight onto your calendar. You keep your own number, and every lead belongs to you.",
    "sections": [
        {"h2_html": "The call you miss is the estimate that goes to the painter who <em>picked up</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner planning an interior repaint or a whole-exterior job is not going to leave a voicemail and wait. They have a short list of painters and they call down it until someone answers and agrees to come look. Painting runs on that first contact more than most trades, because a homeowner cannot compare bids until someone shows up to give one, so the estimate, and the big-ticket job behind it, goes to whoever they reached. But you are up a ladder cutting in a ceiling, your hands are full and covered in paint, or you are running a crew across town, so the call rolls to voicemail.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist answers on the first ring, sounds calm and professional, finds out whether it is an interior repaint, an exterior job, cabinets, or a commercial space, gets the address and the rough scope, and books the estimate on your calendar. The lead is captured and scheduled instead of handed to the painter who happened to be standing next to a phone.</p>'},
        {"h2_html": "Built around how <em>painters actually get calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your phone does not ring while you are sitting at a desk. It rings while you are on scaffolding, taping off a room, or elbow-deep in a cabinet spray job, and because a repaint is a considered purchase, the caller is usually shopping and will book an estimate with the first painter who feels responsive. A voicemail box cannot qualify a lead, and a generic call center does not know a two-room refresh from a full repaint or a commercial bid.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers every call while your crew is on the job, so the homeowner lining up three estimates books with you instead of the painter who simply answered first.</li><li>Qualifies like you would: interior or exterior, how many rooms or the size of the exterior, cabinets or trim, residential or commercial, and the timeline they have in mind.</li><li>Gets the address and the scope, books the estimate on your real calendar, and texts you the details so you show up to the walkthrough already knowing the job.</li><li>Handles a past customer or a referral differently from a cold caller, so the people who already trust you never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one repaint</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. A single interior repaint or exterior job you would have lost to voicemail is usually worth more than the system costs for months, and a whole-exterior or a cabinet refinishing job even more. Everything it captures after that first save is on top. The point is to stop handing your best estimates to the painter who simply answered while you were on a ladder.</p>'},
        {"h2_html": "You own the number, the leads, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every address, and every job detail is yours and exportable any time, so your customer list is an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The AI receptionist is one piece of the Top Shelf platform, and it hands every lead it captures to the same CRM that follows up, so a quote you promised to work up never slips.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "Three estimates lined up, and yours is the one <em>they booked</em>",
        "body_html": 'A homeowner decides it is finally time to repaint the main floor and pulls up three painters on their phone on a Saturday morning. The first two go to voicemail because both painters are on jobs. Yours answers, learns it is four rooms plus a hallway and that the homeowner wants it done before the holidays, gets the address, and books your estimate for Tuesday evening. You are on a scaffold the whole time and never touch your phone, but you finish the day with the walkthrough already on your calendar and the scope waiting for you, while the other two painters call back Monday to a homeowner who has already booked. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every lead that comes through it belong to you and go with you if you ever leave.'),
        ("Can it qualify a repaint before it books the estimate?",
         'Yes, that is the point. It asks what you would ask, interior or exterior, how many rooms or how big the exterior, cabinets or trim, residential or commercial, and the timeline, so you walk into the estimate already knowing the job instead of finding out on the driveway.'),
        ("Will it actually book the estimate on my calendar?",
         'Yes. The walkthrough lands straight on your calendar based on your availability, and you get a text with the address and the scope right away. You set how many estimates a day you take and how much drive time to leave between them.'),
        ("Is it going to sound like a robot to my customers?",
         'It answers naturally and professionally, and it is upfront instead of pretending to be a person. A homeowner lining up painters mostly wants to know someone picked up and will come look at the job, and a steady voice that captures the details beats a voicemail box every time. You can hear it handle a live call before you decide.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We configure your qualifying questions, your calendar, and your booking rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for painters"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-painters.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing estimates to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and estimates your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ================================ CRM for Painters ================================
{
    "slug": "crm-for-painters",
    "trade_slug": "painters", "trade_plural": "painters",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Painters",
    "title": "CRM for Painters | Top Shelf Business Solutions",
    "og_title": "CRM for Painters",
    "meta_desc": "A CRM for painters follows up on every quote and past customer for you, so the bids homeowners are comparing still close with you instead of another painter.",
    "service_schema_name": "CRM for Painters",
    "eyebrow": "For Painters",
    "h1_html": "CRM <em>for Painters</em>",
    "answer_block": "A CRM for painters keeps every lead, past customer, and open quote in one place and follows up for you, so the interior repaint a homeowner is comparing against other bids and the family whose rooms you painted years ago both call you next instead of the painter who stayed in touch. Your customer list quietly becomes your pipeline.",
    "sections": [
        {"h2_html": "The quotes you already sent are the jobs you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most painters do not have a lead problem. They have a follow-up problem. You spend an hour on a walkthrough, work up a detailed quote for an interior repaint or an exterior job, and the homeowner says they are getting a couple of other bids and will think it over. Then you get busy on the jobs you already have and never circle back. They compare three quotes, and the work goes to whoever followed up, which is rarely the lowest bid and rarely the painter who went quiet. The quote was never dead. It just needed one more call or text a few days later, and that is the thing there is never time for between jobs.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open quote in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not you remember. The homeowner weighing three bids hears from you again while the other two go silent, and the job comes back to you.</p>'},
        {"h2_html": "Every home you paint is a customer <em>for years</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A repaint is not a one-time sale. The rooms you painted this year will want the next floor done, then the exterior, then the cabinets, then a color change once they tire of it, and every one of those is yours if you stay in touch. But you cannot personally remember to reach back out to hundreds of past customers, so most of that repeat and referral work goes to whoever they happen to find when they forget your name.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, address, job history, and the colors, brands, and sheens you used live in one place instead of a truck full of paperwork and your memory.</li><li>The exact paint used on each room is on file, so a touch-up call or a matching repaint is easy to quote and easy to win.</li><li>Seasonal nudges go out on schedule, exteriors as the weather warms, cabinets and interiors through the winter, so the next job comes back around without you tracking dates.</li><li>You can see who has not called in a while and reach the right customer with the right reason at the right time.</li></ul>'},
        {"h2_html": "The customers who forgot your name are still <em>yours to keep</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner you painted for two years ago is not disloyal when they call another painter. They just lost your card and never saved your number. A steady, light touch, a note when exterior season comes around, a reminder that you have their colors on file, a quick check that the last job still looks right, keeps your name in their phone so the next repaint comes to you. It costs almost nothing, and it is the difference between a one-time job and a customer for the life of the house.</p>'},
        {"h2_html": "You own the list, and it works with the rest of the system",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the AI receptionist, so a call it answers lands in your database and gets followed up on automatically, and to online booking, so a scheduled estimate is logged against the right customer with their full history and their colors already attached. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The exterior quote that <em>closes itself</em>",
        "body_html": 'You quote a homeowner on a full exterior repaint in March, and they tell you they want two more prices and might wait until early summer. Normally that is the last you hear of it. Instead the CRM sends a friendly check-in a few days later, answers the question everyone asks about prep and paint, and sends a light nudge as the weather warms up, all written to sound like you. The other two painters never followed up, so when the homeowner is ready in June, yours is the only name still in front of them, and they book without shopping any further. You never sat down to chase it. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing customers and past jobs?",
         'Yes. Your current customers, leads, and job history come in and live in one place, including the colors and products you used on each job, and everything stays yours and exportable. The point is to make the customer list you already have actually work for you.'),
        ("Will it really follow up on quotes automatically?",
         'Yes, on the schedule you approve. An open quote gets a check-in a few days later and another after that, all sent for you, so a homeowner comparing bids keeps hearing from you while the other painters go quiet. You can jump in and message anyone directly any time.'),
        ("Can it keep track of the colors and paint I used?",
         'Yes, and that is one of the most useful parts. The brand, color, and sheen for each room or surface stay on the customer record, so a touch-up, a warranty visit, or a matching repaint years later is easy to quote and easy to win.'),
        ("How is this different from just having their number in my phone?",
         'A phone full of contacts does not follow up, does not remember who is due for the next room or the exterior, and does not tell you which quote is going cold. The CRM does all of that on a schedule, so the repeat work actually shows up instead of depending on you to remember.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your customers, build your follow-up and seasonal sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will find the gap where jobs are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for painters"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-painters.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting quotes and customers <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your quotes and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================== Online Booking for Painters ==========================
{
    "slug": "online-booking-for-painters",
    "trade_slug": "painters", "trade_plural": "painters",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for Painters",
    "title": "Online Booking for Painters | Top Shelf Business Solutions",
    "og_title": "Online Booking for Painters",
    "meta_desc": "Online booking for painters lets homeowners self-schedule an in-home estimate on your real availability, so routine walkthroughs stop dying in phone tag.",
    "service_schema_name": "Online Booking for Painters",
    "eyebrow": "For Painters",
    "h1_html": "Online Booking <em>for Painters</em>",
    "answer_block": "Online booking for painters lets a homeowner schedule the in-home estimate straight from your website or a text link, on your real availability, whether it is an interior repaint, a whole-exterior job, or cabinet refinishing, so you stop playing phone tag and the walkthrough lands on your calendar with the scope you need to show up ready to quote.",
    "sections": [
        {"h2_html": "Phone tag is quietly costing you <em>estimates</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner decides to repaint and wants someone to come look and give them a price. Your crew is on a job, so you call back that evening, they are putting kids to bed, you trade voicemails, a day passes, and the estimate gets booked by the painter who could lock in a time on the spot. The homeowner was ready to schedule the moment they thought of it. The back and forth was the problem, not the interest, and a repaint is a big enough job that losing the estimate means losing real money.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets them grab an open estimate slot the moment they decide, at night or on a lunch break, without reaching you first. You wake up to the walkthrough already on the calendar instead of a missed call you now have to chase between jobs.</p>'},
        {"h2_html": "It sorts the job <em>before</em> it books",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Self-scheduling does not mean sending you across town to quote a single accent wall. The booking form asks what matters first: interior or exterior, how many rooms or the size of the exterior, cabinets, trim, or a deck, residential or commercial, and the timeline. A real repaint books an estimate, and a tiny job or a vague inquiry can be routed to a quick call instead, so your evenings are spent on walkthroughs worth driving to. You set the rules: which jobs are bookable online, how long an estimate takes, and how much notice and drive time you need.</p>'},
        {"h2_html": "A booking link everywhere a homeowner <em>finds you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The link goes anywhere someone already meets you: your website, your Google Business Profile, your email signature, your project photos on social, and the text you send after a call. Every one of those turns from a dead end that needs a callback into a place a homeowner can book an estimate in one tap. Someone scrolling your before-and-after photos on a Sunday night, finally sold on repainting the kitchen, can put the walkthrough on your calendar before they close the tab, instead of leaving a voicemail they will second-guess by Monday.</p>'},
        {"h2_html": "On your real calendar, and the homeowner actually shows",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar you already use so it can never double-book you or a crew lead against a job you already have, and it sends the homeowner a confirmation and a reminder, which is what actually cuts no-shows. A painter driving across town to an empty house for an estimate is a wasted evening you never get back. Every booking is logged against the right customer in your CRM, and it works alongside the AI receptionist, which can also book the caller who would rather talk than tap.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Sunday-night repaint, booked <em>before Monday</em>",
        "body_html": 'It is 9pm on a Sunday and a homeowner has finally decided to repaint the living room and hallway before family comes for the holidays. They land on your site, scroll through photos of real jobs you have done, and instead of leaving a voicemail they will talk themselves out of by morning, they book an estimate for Wednesday evening from the calendar right there on the page. You wake up Monday to the walkthrough already set, with their name, address, and a note that it is two rooms in a repaint they want done within the month. No phone tag, no lost job. Illustrative example, not a client.'},
    "faqs": [
        ("Does it sync to my Google or Outlook calendar?",
         'Yes. It reads your real calendar so it only ever offers times you are actually free, and new estimates drop straight onto it. It cannot double-book you against a job or another walkthrough you already have scheduled.'),
        ("Will it send me out to quote tiny jobs that are not worth the drive?",
         'Only if you let it. The form asks about the scope first, interior or exterior, how many rooms, cabinets, residential or commercial, so a real repaint books an estimate and a one-wall touch-up or a vague inquiry can be routed to a quick call. Your time goes to walkthroughs worth driving to.'),
        ("Can I control which jobs are bookable and how long an estimate takes?",
         'Yes. You decide which job types are available online, how long to block for each estimate, how much notice you need, and how much buffer to leave for drive time, so you are never booked with no way to get there.'),
        ("Will it cut down on no-shows?",
         'It helps. Automatic confirmations and reminders by text and email are the single biggest lever on no-shows, and every booking includes them. A homeowner who booked themselves and got a reminder is far more likely to be home than a loosely agreed callback.'),
        ("How fast can it be live?",
         'Setup is included, no separate fee. We connect your calendar, set up your job types and rules, and put the link on your site, profile, and photos, so it is taking bookings in days. Start with a free audit and we will find the gap where routine estimates are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for painters"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-painters.html", "The AI receptionist that can book callers too"),
        ("crm-for-painters.html", "The CRM every booking is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let homeowners book you <em>while you work</em>",
    "cta_sub": "Get a free audit of how many estimates your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Review Software for Painters =========================
{
    "slug": "review-software-for-painters",
    "trade_slug": "painters", "trade_plural": "painters",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for Painters",
    "title": "Review Software for Painters | Top Shelf Business Solutions",
    "og_title": "Review Software for Painters",
    "meta_desc": "Review software for painters turns finished jobs into before-and-after Google reviews, asked the moment the room looks new, so your work wins the next estimate.",
    "service_schema_name": "Review Software for Painters",
    "eyebrow": "For Painters",
    "h1_html": "Review Software <em>for Painters</em>",
    "answer_block": "Review software for painters turns every finished job into a public before-and-after, prompting the homeowner for a Google review the moment they walk into the transformed room, and making it a one-tap post they can add a photo to. A visual trade lives or dies on what those reviews show, and this keeps them fresh, honest, and easy to leave.",
    "sections": [
        {"h2_html": "Homeowners read a painter's reviews for <em>how you treat the house</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A painting job is not a quick visit. Your crew works inside the home for days, moving furniture, covering floors, taping off rooms, and living alongside the family while the work gets done. So when a homeowner reads your reviews, they are not scanning for speed. They are looking for the things that decide whether they can stand having a crew in the house: did the painters arrive when they promised, keep the site tidy, protect the furniture, mask the floors, and leave the place spotless at the end. Those are the lines in a review that turn a nervous homeowner into a booked estimate, and they are exactly the things your best crews already do without being told.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The trouble is that a homeowner who is thrilled on the last day rarely thinks to write any of it down, and it feels strange to stand in a freshly finished room and ask for a favor. Review software carries that ask for you, at the one moment it feels natural, so the care your crews put into a home gets captured while it is fresh instead of fading by the weekend.</p>'},
        {"h2_html": "The ask goes out the second the <em>reveal</em> lands",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every repaint has a reveal. The last coat dries, the tape peels off, the furniture slides back, and the homeowner steps into a room that looks like a different house. Those few minutes of walking around, running a hand along the trim and taking it in, are the emotional high of the whole job, and they are when a request to share the result feels welcome rather than pushy. The software fires the ask right then, over text and email, dropping the homeowner onto your Google listing in a single tap while the paint still smells fresh and the before is still vivid in their memory. Wait a few weeks and the new color is just the color; catch them at the reveal and you reach them at the exact moment they want to tell someone.</p>'},
        {"h2_html": "Every painting review comes with a <em>picture, and the picture sells</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Painting is one of the only trades where the proof fits in a photo, and a review with a before-and-after attached does two things at once. It convinces the next homeowner in a way no star rating can, and it quietly builds a portfolio on your Google listing that you never had to stage or shoot. The software nudges customers to add a picture when they post, so your listing fills with real rooms and real exteriors instead of stock images. An exterior job pays off twice over: the fresh curb appeal is on show to the entire street, and a neighbor who has been eyeing their own faded siding reads a review from three doors down and starts picturing their house next. Reviews that name the color, the finish, or how crisp the cut lines came out work the same way, letting a shopper imagine the result on their own walls before they ever pick up the phone.</p>'},
        {"h2_html": "Reply to every review, then let it <em>compound through the seasons</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Answering reviews is half the value, and most painters skip it. A short, specific reply, thanking a homeowner by the color they chose or mentioning the crew enjoyed the project, shows a shopper you are present and proud of the work, and Google treats that engagement as a reason to place you higher in local results. When a rare unhappy review lands, maybe a job that ran a day past the estimate, you hear about it at once and can answer with a calm, professional note rather than leaving it to sit unanswered. Across a season it snowballs: fresh reviews raise you in the map pack, a stronger listing draws more estimate requests, and every finished job feeds the next batch of reviews. The reputation is yours, attached to your own listing rather than a rented directory, and the loop runs on its own because each request goes out the moment a job is closed in your CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A fresh exterior, and the review the <em>whole street reads</em>",
        "body_html": 'You finish repainting the outside of a house on a Friday, and the jump from the tired, chalky siding it replaced is the kind of thing neighbors slow down to look at. That evening the software texts the homeowner a thank-you and a one-tap link, and they leave a five-star review with a before-and-after photo of the front of the house. A week later the couple two doors down, who watched your crew work all week and have been meaning to deal with their own peeling trim, look you up, find that photo sitting at the top of your listing, and recognize their own block. They book an estimate before they finish reading it. You never asked a second time, and you were already onto the next job when it landed. Illustrative example, not a client.'},
    "faqs": [
        ("Can homeowners attach before-and-after photos to their reviews?",
         'Yes, and for a painting company that is the most valuable part. The request nudges customers to include a photo when they post, so your Google listing steadily fills with real transformations, interiors and exteriors alike, that work as proof and as a portfolio for every future shopper who reads them.'),
        ("When does the review request actually go out?",
         'At the reveal, right after the final coat dries and the homeowner sees the finished room or exterior for the first time. That is the high point of the whole job, so the ask feels natural, and it reaches them by text and by email, each carrying a one-tap link. You control the exact timing and the wording so it reads like you wrote it.'),
        ("Does automating the asks break Google's rules?",
         'No. Inviting an honest review from every real customer is allowed and encouraged. What crosses the line is screening out the unhappy ones or paying for reviews, and the software does neither. It simply reaches everyone you painted for, when the moment is right, and makes posting effortless.'),
        ("What if a homeowner regrets the color they chose?",
         'You will see it the moment the review posts instead of hearing it secondhand, and the software helps you answer with a calm, professional reply that offers to make it right. A thoughtful response sitting under a wall of glowing reviews often does more to win a cautious shopper than a flawless record ever could, because it shows how you handle the rare job that slips.'),
        ("How does this help me book more estimates?",
         'A listing full of recent, photo-backed reviews raises you in the local map pack and gives a shopper the confidence to pick you over a cheaper unknown. Getting started costs nothing extra: we hook up your Google listing, dial in the timing, and trigger each ask off a closed job, then a free audit shows where your online reputation stands next to the painters you bid against.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for painters"),
        ("solution-reviews.html", "How the review system works"),
        ("crm-for-painters.html", "The CRM that triggers the ask when a job is done"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let your finished work <em>book the next job</em>",
    "cta_sub": "Get a free audit of where your reviews and Google listing stand next to the painters bidding against you, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Websites & SEO for Painters =========================
{
    "slug": "websites-seo-for-painters",
    "trade_slug": "painters", "trade_plural": "painters",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Painters",
    "title": "Websites & SEO for Painters | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Painters",
    "meta_desc": "A painting company website built for SEO ranks for house painters near me and your city, and captures the estimate directly instead of a lead-seller.",
    "service_schema_name": "Websites & SEO for Painters",
    "eyebrow": "For Painters",
    "h1_html": "Websites &amp; SEO <em>for Painters</em>",
    "answer_block": "A painting company website built for SEO ranks for the searches a homeowner types, house painters near me, interior painting, exterior painters in your city, shows up in the map pack for the towns you cover, and captures the estimate the moment they land, so the job belongs to you instead of a directory or a lead-seller renting your own leads back to you.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own leads</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a painter in your town and the top of the page is often a directory, a national booking middleman, or a pay-per-lead service, not the local shop. Those sites publish thousands of pages and have years of authority behind them, so when a homeowner searches, they land there first, fill out a form, and that lead gets sold, often to three or four painters at once who then race to underbid each other. Your site not ranking is not a vanity problem. It is the reason a homeowner you could have had for free turns into a lead you pay for and split with your competitors.</p>'},
        {"h2_html": "Rank for what a homeowner types when they are <em>ready to repaint</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for a broad term, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you cover, and for the exact searches a homeowner makes when they are planning a job: house painters near me, interior painters in your city, cabinet refinishing, exterior painting, deck staining, commercial painting company. Pages built around the services you actually offer and the areas you actually serve are what search engines, and homeowners deciding who to call, reward with the click.</p>'},
        {"h2_html": "Show the work, because painting <em>sells on the eyes</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Painting is one of the few trades where the work sells itself on sight, and most painter websites waste that. A homeowner deciding between painters wants to see real before-and-after photos of homes like theirs, straight lines, clean edges, a color they can picture on their own walls, not stock images. A site that shows your actual projects, organized by interior, exterior, and cabinets, does two jobs at once: it earns the homeowner\'s trust, and it gives search engines real, specific content about the work you do in the places you do it. A pretty template with no real work on it does neither.</p>'},
        {"h2_html": "The leads are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a pay-per-lead service disappears the day you stop paying, and the lead was never really yours anyway. A website you own keeps ranking, keeps capturing estimate requests, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you. The site plugs into the same CRM that follows up on every lead it captures and the AI receptionist that answers the calls it drives, so nothing it earns you slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A homeowner skips the directory and books <em>you</em>",
        "body_html": 'A homeowner two towns over decides to repaint the exterior and searches exterior painters near me on their phone. Instead of a national directory that would sell the lead to four painters, they find your site ranking for that town, with a gallery of real exterior jobs you have finished nearby and a page about how you handle prep and weather. They scroll the before-and-after photos, trust what they see, and book an estimate right there. You paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big directories?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the interior, exterior, and cabinet searches a national directory has no reason to target well, which is exactly where a local painter can win.'),
        ("How is this different from paying for leads?",
         'A pay-per-lead service rents you a lead that it also sells to your competitors, who then race to underbid you, and it stops the day you stop paying. A website you own captures leads that are yours alone and keeps working long after it is built, without a per-lead fee coming out of every job.'),
        ("Does showing my past work really matter that much?",
         'For painting, yes. It is a visual trade, and a homeowner choosing between bids is reassured most by real before-and-after photos of homes like theirs. Those photos also give search engines specific, genuine content about the work you do and where, which a stock-photo template never will.'),
        ("Do I need to rank for every town I serve?",
         'You rank for the ones that matter most first. We build pages for your core service areas and the highest-intent searches, then expand, rather than spreading thin across a whole metro at once.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will find the gap between where your current site, or lack of one, stands and where the searches actually are.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for painters"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-painters.html", "Staying visible in your service area beyond your site"),
        ("crm-for-painters.html", "Where every captured lead lands and gets followed up"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your leads, whether you work with us or not. No credit card, never a call center.",
},
# =========================== Marketing for Painters ===========================
{
    "slug": "marketing-for-painters",
    "trade_slug": "painters", "trade_plural": "painters",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Painters",
    "title": "Marketing for Painters | Top Shelf Business Solutions",
    "og_title": "Marketing for Painters",
    "meta_desc": "Marketing for painters keeps your Google profile active and full of project photos, so you are the painter homeowners already know when they plan a repaint.",
    "service_schema_name": "Marketing for Painters",
    "eyebrow": "For Painters",
    "h1_html": "Marketing <em>for Painters</em>",
    "answer_block": "Marketing for painters keeps you visible where homeowners look when they plan a repaint, your Google Business Profile and the map pack, and full of the before-and-after photos that sell painting on sight, so when someone nearby decides it is time, your name is the active, well-reviewed one they call instead of the shop that let its profile go stale.",
    "sections": [
        {"h2_html": "Painting demand is <em>planned, not sudden</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody calls a painter in a panic. A repaint is planned, sometimes for months; the homeowner stares at a tired room or a fading exterior all winter and decides in the spring that this is the year. By the time they start calling for estimates, they have usually already formed an impression of who looks established and trustworthy. That means the game is being visible and familiar in your service area before the homeowner is ready, not running a clever ad the week they finally search.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The painter who was invisible until the homeowner started shopping is competing on price against two other bids. The one who was already familiar, whose finished jobs the homeowner had been seeing around the neighborhood, walks into the estimate half-sold. Marketing is how you become that painter before the call.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>portfolio</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for a painter near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and above the ads. For a visual trade, a profile full of recent before-and-after photos of real jobs is a portfolio and an advertisement at once, and it looks alive next to a competitor\'s profile that has sat untouched for months. Keeping it active, complete, and stocked with your actual work is a quiet pitch running in the exact spot a homeowner looks when they decide to repaint.</p>'},
        {"h2_html": "Show up in the <em>towns you actually cover</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and it sends you calls from an hour outside your range. Focusing on the specific towns and neighborhoods you serve, with a profile, project photos, and content built around those areas, is what puts you in the map pack where you can actually take the work. It matters even more where whole subdivisions and HOA neighborhoods repaint on a cycle: be the familiar name that already painted three houses on the street, and the fourth is a short drive and an easy yes.</p>'},
        {"h2_html": "Stay ready for the season, and stay in front of past customers",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Painting demand swings with the calendar, exteriors in the warm, dry months, interiors and cabinets through the winter, and being visible right before each wave beats scrambling once it hits. A steady local presence, seasonal posts, finished-job photos, the occasional straight answer about prep or timing, keeps you top of mind for the homeowner about to decide and reminds past customers you are still the one to call for the next room. This is the public-facing side of the business; the private follow-up to people already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The neighbor who calls <em>the painter they already knew</em>",
        "body_html": 'You spend a few months showing up in one set of neighborhoods: before-and-after photos on your Google profile, a post after a big exterior job, a straight answer about how long a repaint takes. A homeowner three streets over is not ready yet, but keeps seeing your finished work and your name. Then spring comes and they finally decide to repaint the outside of the house. Instead of searching and calling three strangers to compare, they call the painter whose jobs they had been admiring all season, and yours is the first estimate booked and the one they trust. You never spoke to them once before that call. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with before-and-after photos, project updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current and shows off your work whenever someone searches for a painter near them.'),
        ("What does focusing on my service area actually mean?",
         'It means building your profile and content around the specific towns and neighborhoods you can serve well, instead of spreading a budget across a whole metro. That is what gets you into the map pack where the local estimates are, and it compounds fastest in areas where you have already painted.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with people already in your database, your open quotes and past customers. Marketing is the public-facing side, your Google profile, reviews, project photos, and local visibility, aimed at homeowners who are not your customer yet but need to find and trust you when they plan a repaint.'),
        ("Can you help me get ahead of the exterior season?",
         'Yes. We time your visibility to the waves that matter, exteriors as the weather warms, interiors and cabinets through the winter, so you are already in front of people before the season instead of scrambling for work once your competitors book up.'),
        ("How long before I see it working?",
         'A neglected profile can climb in the map pack within weeks once it is active and full of real photos, and it compounds from there as reviews and content build. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for painters"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-painters.html", "The reviews that feed the same Google profile"),
        ("websites-seo-for-painters.html", "The website that captures the demand this drives"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the painter they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# =========================== Automation for Painters ===========================
{
    "slug": "automation-for-painters",
    "trade_slug": "painters", "trade_plural": "painters",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for Painters",
    "title": "Automation for Painters | Top Shelf Business Solutions",
    "og_title": "Automation for Painters",
    "meta_desc": "Automation for painters sends estimate reminders, on-my-way texts, job updates, and follow-ups for you, so dispatch runs smooth and nothing gets missed.",
    "service_schema_name": "Automation for Painters",
    "eyebrow": "For Painters",
    "h1_html": "Automation <em>for Painters</em>",
    "answer_block": "Automation for painters handles the texts and reminders around every job for you, the reminder before an estimate, the on-my-way text when the crew heads out, the update partway through a multi-day repaint, and the follow-up and review request when the job is done, so everything runs smooth and nothing depends on you remembering between jobs.",
    "sections": [
        {"h2_html": "A homeowner living in a half-painted house wants to know <em>when you are coming back</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A repaint takes over a home for days. Furniture is moved, rooms are taped off, the family is living around drop cloths, and the worst part for the homeowner is not knowing what happens next: is the crew coming at eight or ten, are they back tomorrow to do the second coat, is the exterior job pushed because of the rain. A customer left wondering is the one who starts to worry they hired the wrong painter, even when the work is flawless. Keeping everyone updated is exactly the kind of thing that slips when you are running a brush and a crew at the same time.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Automation handles those messages for you. A confirmation before the estimate, an on-my-way text when the crew heads out, an update partway through a multi-day job, and a heads-up if weather pushes an exterior day, all sent automatically, so the homeowner feels looked after and you are not the one stopping to type it.</p>'},
        {"h2_html": "Reminders that keep your <em>schedule full and on time</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A painter driving to a no-show estimate is an evening and a tank of gas you never get back, and an empty slot a real walkthrough could have filled. Automatic confirmations and reminders by text before every estimate and every job start keep no-shows down and give a customer an easy way to reschedule instead of just not being home. For an owner running a couple of crews, that is a fuller, tighter schedule without anyone working the phones to confirm each stop.</p>'},
        {"h2_html": "Deposits, progress payments, and the follow-up <em>run themselves</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Painting jobs get paid in stages, a deposit to book, a progress payment as the work moves, the balance at the end, and chasing each one by hand is awkward and easy to put off. Automatic, polite reminders go out when a payment is due, so the money keeps pace with the work without an uncomfortable phone call. When the job wraps, the same system sends a thank-you, an automatic review request while the fresh paint still looks its best, and a note that you have their colors on file for touch-ups, all on time, so a finished job turns into a review and a future customer without you keeping a mental list.</p>'},
        {"h2_html": "Cold quotes and lapsed customers <em>come back on schedule</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A quote that went quiet and a customer you painted for two years ago are not dead, they are just waiting for a reason to call. A scheduled check-in on an open estimate, a seasonal nudge when exterior weather returns, and a reminder to a customer who is due for the next room bring that work back around automatically instead of falling out of your memory. It runs against the same database as your CRM, so nothing here duplicates a customer or a note, and every automated touch is logged where you can see it.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A customer who never has to <em>wonder what happens next</em>",
        "body_html": 'A homeowner books a three-day interior repaint. The day before it starts, they get an automatic confirmation. Each morning the crew heads out, they get an on-my-way text with an arrival window, and at the end of day two, a quick note that the crew will be back to finish the trim in the morning. When the deposit and the progress payment come due, polite reminders go out on their own. The afternoon the job wraps, they get a thank-you with a one-tap review link while the rooms still look their best, and the system quietly files the colors for a touch-up down the road. You never sat down to send any of it. Illustrative example, not a client.'},
    "faqs": [
        ("What messages does it actually send?",
         'The routine ones around a job: an estimate confirmation, an on-my-way text when the crew heads out, an update partway through a multi-day job, a heads-up if weather pushes an exterior day, payment reminders, and a follow-up with a review request when the work is done. You approve the wording so it all sounds like you.'),
        ("Does this replace me or my crew leads talking to customers?",
         'No. It handles the predictable, repetitive texts so nobody has to stop and type them, while you and your team still make every real call and step in personally for anything that needs a conversation.'),
        ("Can it help with no-shows and wasted trips?",
         'Yes. Automatic confirmations and reminders before each estimate and job start keep no-shows down and give the customer an easy way to reschedule, so you spend less time driving to empty houses.'),
        ("Can it handle deposits and progress payments?",
         'Yes. Painting gets paid in stages, and the system sends polite, automatic reminders when a deposit, a progress payment, or the balance is due, so the money keeps pace with the work without an awkward call. You set the amounts and the timing.'),
        ("How long does setup take?",
         'Setup is included with no separate fee. We build the reminder, on-my-way, payment, and follow-up sequences around how you already run your day, so it is working within days. Start with a free audit and we will find the gap where things are slipping between your calls, your crews, and your calendar.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for painters"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-painters.html", "The database every workflow runs against"),
        ("online-booking-for-painters.html", "How the visits these remind about get booked"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a customer <em>wonder what happens next</em>",
    "cta_sub": "Get a free audit of what is currently slipping between your calls, your crews, and your follow-ups, whether you work with us or not. No credit card, never a call center.",
},
]
