"""Per-page content specs for the SEO corpus (plan §5), locksmiths batch. Same contract as
scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, locksmith-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber content reworded.

Home Services hub. Four service angles here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client."
per the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ========================= AI Receptionist for Locksmiths =========================
{
    "slug": "ai-receptionist-for-locksmiths", "demo": True,
    "trade_slug": "locksmiths", "trade_plural": "locksmiths",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Locksmiths",
    "title": "AI Receptionist for Locksmiths | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Locksmiths",
    "meta_desc": "A locksmith answering service answers every lockout call while your tech is on a job, gives an ETA, and books it before the caller tries the next locksmith.",
    "service_schema_name": "AI Receptionist for Locksmiths",
    "eyebrow": "For Locksmiths",
    "h1_html": "AI Receptionist <em>for Locksmiths</em>",
    "answer_block": "A locksmith answering service answers every lockout call the moment it rings, day or night, tells a car lockout apart from a commercial rekey, and books the job with a realistic ETA while your tech has their hands full at another lock. You keep your own number, and every call stays yours.",
    "sections": [
        {"h2_html": "The call you miss is the lockout that <em>calls the next locksmith</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A person locked out of their car in a parking lot, out of their house after dark, or a shop owner stuck on the sidewalk before opening is not going to leave a voicemail. They are stranded, and they call down the list until someone picks up, quotes them, and gives them a time. Locksmithing runs on that urgency more than almost any trade, because the customer cannot get into their car, their home, or their business until you arrive, and every minute they wait is a minute they are stuck outside. But your tech is halfway through picking a lock across town, cutting a key, or programming a fob with both hands busy, so the call rolls to voicemail and the job, along with the after-hours premium that comes with it, goes to whoever answered and named an arrival time.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A locksmith answering service picks up on the first ring, stays calm with a stranded caller, finds out whether it is a car, a house, or a business, gets the location, gives a realistic arrival window, and either books it or flags a true emergency straight to your phone. The job is captured and scheduled instead of lost to the shop that simply answered.</p>'},
        {"h2_html": "Built around how <em>locksmiths actually get calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your calls do not keep office hours. Someone locks their keys in the car at eleven at night, a tenant is stuck outside an apartment on a weekend, a business owner snaps a key off in the lock before opening, and the calls that pay the most tend to come when every other shop is closed. A voicemail box cannot calm a stranded caller or gather what a job needs, and a generic call center reading a script does not know a car lockout from a mortise rekey, or a single deadbolt from a commercial master-key system.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24/7, including the late-night car lockout and the weekend house lockout that are your best-paying emergency jobs.</li><li>Triages like you would: car, home, or business, locked out or a broken key, one lock or a whole building, and how fast someone needs you there.</li><li>Gets the location and the details, gives a sensible arrival window, books routine work on your calendar, and texts you a true emergency at once so you decide whether to roll out now.</li><li>Handles a repeat commercial account or a property manager differently from a first-time caller, so the people who already trust you never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one lockout, or one commercial account</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. One late-night car lockout or one commercial rekey you would have lost while your hands were full is often worth more than the service costs for months, and after-hours emergency work is usually your highest-margin ticket of all. Better still, a first call answered well is how a property manager or a business becomes a repeat account instead of a one-time job. Everything it captures after that first save is on top. The point is to stop handing your best calls to the locksmith who simply picked up faster.</p>'},
        {"h2_html": "You own the number, the calls, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every address, and every job detail is yours and exportable any time, so your customer list, including the commercial accounts worth the most to you, is an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The locksmith answering service is one piece of the Top Shelf platform, and it hands every call it captures to the same CRM that follows up, so a quote or a repeat commercial account never slips.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "An 11pm car lockout, booked with an <em>ETA</em>",
        "body_html": 'It is eleven at night and someone is locked out of their car in a dark store parking lot, alone and rattled. They search for a locksmith and call the first three they see. Two go to voicemail. Yours answers, stays calm, confirms the car and the location, gives a twenty-minute arrival window, and books it while pinging your phone that it is urgent. Your tech was finishing a rekey across town and never had to break off to grab the phone. You roll up with the job already logged, the location and the vehicle attached, instead of hearing later that they gave up and called someone else. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever leave.'),
        ("Can it tell an emergency lockout from routine work?",
         'Yes, that is the point. It asks what you would ask, car, home, or business, locked out or a broken key, one lock or a whole building, and treats a stranded lockout as urgent while booking a rekey or a lock install as routine. You set what counts as a drop-everything call.'),
        ("Will it actually book the job and give an ETA?",
         'Yes. Routine work lands straight on your calendar based on your availability, and the caller gets a realistic arrival window instead of a vague callback. For a true emergency it can book the first opening and alert you at once so you decide whether to head out right now.'),
        ("Is it going to sound like a robot to a stranded caller?",
         'It answers naturally and calmly, and it is upfront instead of pretending to be a person. Someone locked out in a parking lot at night mostly needs to know a real locksmith is on the way and roughly when, and a steady voice that gives an ETA beats a voicemail box every time. You can hear it handle a live call before you decide.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We configure your triage questions, your calendar, and your emergency rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for locksmiths"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-locksmiths.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing lockouts to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and after-hours jobs your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ============================== CRM for Locksmiths ==============================
{
    "slug": "crm-for-locksmiths",
    "trade_slug": "locksmiths", "trade_plural": "locksmiths",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Locksmiths",
    "title": "CRM for Locksmiths | Top Shelf Business Solutions",
    "og_title": "CRM for Locksmiths",
    "meta_desc": "A CRM for locksmiths follows up on every rekey and lock-install quote and keeps your commercial and property-manager accounts coming back for repeat work.",
    "service_schema_name": "CRM for Locksmiths",
    "eyebrow": "For Locksmiths",
    "h1_html": "CRM <em>for Locksmiths</em>",
    "answer_block": "A CRM for locksmiths keeps every lead, past customer, and open quote in one place and follows up for you, so the lock-install bid a homeowner is sitting on and the property manager you rekeyed one unit for both come back to you instead of the shop that stayed in touch. Your customer list quietly becomes repeat work.",
    "sections": [
        {"h2_html": "The quotes you already sent are the jobs you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most locksmiths do not have a lead problem. They have a follow-up problem. You quote a homeowner on rekeying the whole house, a business on new commercial locks, or a landlord on a master-key setup, they say they need to think it over or check with a partner, and then the next lockout call pulls you away and you never circle back. They collect another price, and the job goes to whoever followed up, not always the lowest bid. The quote was never dead. It just needed one more call or text a few days later, and that is the thing there is never time for between service calls.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open quote in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not you remember. The customer weighing two or three locksmiths hears from you again while the others go quiet, and the job comes back to you.</p>'},
        {"h2_html": "The commercial and property-manager account is the <em>goldmine you already own</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">An emergency lockout might be a one-time customer, but the accounts that pay a locksmith for years are commercial. A property manager rekeys on every unit turnover, an office changes locks when someone leaves, a landlord runs dozens of doors, a growing business keeps adding access control, and all of it is repeat work that goes to the locksmith who stayed in touch and made it easy. The trouble is you meet these accounts on a single call and then lose track of them between the emergencies that fill your day.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every account, contact, address, and the hardware you installed lives in one place, so when a property manager calls about a turnover you already know the building and the keyway.</li><li>Follow-ups go out on a schedule you set, a check-in after a big install, a note to a manager as a leasing season comes around, so the repeat work returns without you tracking it.</li><li>You can see which commercial accounts have gone quiet and reach the right contact before they try another locksmith.</li></ul>'},
        {"h2_html": "The homeowner you rekeyed once is still <em>your security relationship</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner you helped after a move or a break-in is not disloyal when they call another locksmith. They just lost your card and never saved your number. A light, steady touch, a reminder that you also handle safes and smart locks, a quick check that the new deadbolts are working fine, keeps your name in their phone for the next lost key, the next rekey, the next upgrade. It costs almost nothing, and because you were the one trusted with their security once, you are the natural call the next time it matters.</p>'},
        {"h2_html": "You own the list, and it works with the rest of the system",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the answering service, so a call it answers lands in your database and gets followed up on automatically, and to online booking, so a scheduled job is logged against the right customer or account with its full history already attached. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "One lockout becomes a <em>standing rekey account</em>",
        "body_html": 'A property manager calls you late on a Friday to let a tenant back into a unit. You handle it, and normally that is the end of it. Instead the job goes into your CRM against that manager and their building, and a couple of weeks later it sends a friendly check-in offering to be their go-to for unit-turnover rekeys. They had been calling whoever was free, but yours is the name in front of them now, so they start sending you every turnover. One after-hours lockout quietly turned into a standing account you never had to chase from memory. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing customers and accounts?",
         'Yes. Your current customers, commercial accounts, leads, and job history come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already have actually work for you.'),
        ("Will it really follow up on quotes automatically?",
         'Yes, on the schedule you approve. An open rekey or install quote gets a check-in a few days later and another after that, all sent for you, so a customer comparing locksmiths keeps hearing from you while the others go quiet. You can jump in and message anyone directly any time.'),
        ("Can it help me build repeat commercial and property-manager work?",
         'Yes. It keeps every commercial contact, building, and keyway in one place and sends check-ins on a cadence you set, so the property managers and businesses you meet on a single call turn into standing accounts instead of one-time jobs.'),
        ("How is this different from just having their number in my phone?",
         'A phone full of contacts does not follow up, does not remember which account is due for a turnover rekey, and does not tell you which quote is going cold. The CRM does all of that on a schedule, so the repeat work actually shows up instead of depending on you to remember.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your customers and accounts, build your follow-up sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where jobs are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for locksmiths"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-locksmiths.html", "The answering service that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting quotes and accounts <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your quotes and repeat accounts are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ============================ Marketing for Locksmiths ============================
{
    "slug": "marketing-for-locksmiths",
    "trade_slug": "locksmiths", "trade_plural": "locksmiths",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Locksmiths",
    "title": "Marketing for Locksmiths | Top Shelf Business Solutions",
    "og_title": "Marketing for Locksmiths",
    "meta_desc": "Locksmith marketing keeps your Google Business Profile active and first in the map pack, so the caller searching locksmith near me trusts and calls you.",
    "service_schema_name": "Marketing for Locksmiths",
    "eyebrow": "For Locksmiths",
    "h1_html": "Marketing <em>for Locksmiths</em>",
    "answer_block": "Locksmith marketing keeps you visible where local demand shows up, your Google Business Profile and the map pack, so when someone nearby is locked out and searches for a locksmith, your name is the active, well-reviewed, real local one they trust and call instead of a stale listing or a national dispatcher.",
    "sections": [
        {"h2_html": "Locksmith demand is <em>local and sudden</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody shops around for a locksmith for weeks. Demand appears the instant someone is locked out of a car, a house, or a business, and it is intensely local, because a stranded person wants someone who can be at their door in minutes, not across the metro. That means the whole game is being visible and trusted in your service area at the exact moment someone nearby needs you, not running clever ads at people who are not locked out yet. There is no comparison-shopping window to win back later; you either turn up in that search, look trustworthy, and get the call now, or you do not exist for that job at all. Get found first in that moment, look real and close, and the job is usually yours.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for a locksmith near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and above the ads. A profile that sits untouched for months looks abandoned next to one with a real address, current hours, photos of actual work, and a steady stream of reviews. It matters even more in this trade, because the locksmith category is crowded with listings that are not the real local shop, and a stranded caller in a hurry cannot always tell them apart. A verified, active, honest profile is how a searcher spots the genuine local locksmith at a glance.</p>'},
        {"h2_html": "Reviews are how a <em>scam-wary caller</em> decides to trust you",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Locksmithing has a trust problem that is not your fault, and a nervous customer knows it. They have heard the stories of a low phone quote that balloons once the tech is on site, so before they call they scan for a locksmith with recent reviews that say the price was honest, the work was fast, and nothing got damaged. Those reviews do more to win the call than any slogan, because they answer the only real question a stranded person has: can I trust whoever shows up. Recent, genuine reviews are also one of the signals that lift you in the map pack, so the more real jobs you turn into reviews, the higher and more trusted you sit the next time someone nearby searches.</p>'},
        {"h2_html": "Show up in the towns you cover, and win the <em>commercial accounts too</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and it sends you calls from thirty minutes outside your range. Focusing on the specific towns and neighborhoods you serve, with a profile, photos, and content built around those areas, is what puts you in the map pack where you can actually take the work. The same visibility does double duty for commercial work, because the property manager or business owner choosing who to rekey a building looks you up and reads before they ever call, and a complete, well-reviewed presence is what tells them you are established enough to trust with their keys. This is the public-facing side of the business; the private follow-up to accounts already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A midnight lockout, and you are <em>already at the top</em>",
        "body_html": 'Someone gets home at midnight and realizes they are locked out, standing on the porch in the cold with a dead phone charging in the car. They search for a locksmith near them. Because your Google profile has been kept active all year, with a real local address, current hours, photos of real work, and a steady flow of reviews that mention fair pricing and a fast, careful tech, you sit at the top of the map pack and look unmistakably like the real local shop. They call the name they can see and trust first, and yours is right there. The stale listing two spots down never gets the call. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with photos of real work, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current and real whenever someone searches for a locksmith near them.'),
        ("What does focusing on my service area actually mean?",
         'It means building your profile and content around the specific towns and neighborhoods you can reach quickly, instead of spreading a budget across a whole metro. That is what gets you into the map pack where the local, high-intent calls are.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with customers and accounts already in your database. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at people who are not your customer yet but need to find and trust you the moment they are locked out.'),
        ("Can reviews really help against the listings that are not real local shops?",
         'Yes. A stranded caller cannot always tell the real local locksmith from a lead-generating listing, so a verified profile with a real address and a wall of recent, honest reviews is exactly what marks you as the genuine, trustworthy one to call.'),
        ("How long before I see it working?",
         'A neglected profile can climb in the map pack within weeks once it is active and complete, and it compounds from there as reviews and content build. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for locksmiths"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-locksmiths.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the locksmith they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Websites & SEO for Locksmiths =========================
{
    "slug": "websites-seo-for-locksmiths",
    "trade_slug": "locksmiths", "trade_plural": "locksmiths",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Locksmiths",
    "title": "Websites & SEO for Locksmiths | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Locksmiths",
    "meta_desc": "A locksmith website built for SEO ranks for locksmith near me and car lockout, and captures the caller instead of a national dispatcher or lead-seller.",
    "service_schema_name": "Websites & SEO for Locksmiths",
    "eyebrow": "For Locksmiths",
    "h1_html": "Websites &amp; SEO <em>for Locksmiths</em>",
    "answer_block": "A locksmith website built for SEO ranks for the searches a stranded person types, locksmith near me, car lockout, emergency locksmith, rekey, shows up in the map pack for the towns you cover, and captures the caller directly, so the job is yours instead of a national dispatcher or a lead-seller renting back your own calls.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a locksmith in your town and the top of the page is often a national call center, a directory, or a pay-per-lead service, not the local shop. Those operations publish thousands of pages and carry years of authority, so when someone searches, they land there first, call a number, and that lead gets sold, sometimes to three locksmiths at once, sometimes back to you for a fee out of your own margin, and sometimes dispatched to whatever unvetted tech is nearest, which is where the price-gouging horror stories come from. Your site not ranking is not a vanity problem. It is the reason a call you should have gotten for free gets sold to you, or handed to a stranger working under a name that is not yours.</p>'},
        {"h2_html": "Rank for what someone types when they are <em>locked out</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national operation this year for the broadest term, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you cover, and for the exact things people search when they need you: locksmith near me, car lockout, emergency locksmith, house lockout, rekey, a locksmith in your city. And the higher-value work has its own searches a national dispatcher never bothers to answer well, commercial locksmith, master-key systems, access control, safe opening, so each of those is a page you can own outright while the middlemen chase the generic term. Pages built around the services you actually run and the areas you actually serve are what search engines, and a stranded caller, reward with the click.</p>'},
        {"h2_html": "A stranded visitor on a phone should reach you in <em>one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone locked out is on a phone in a parking lot or on a porch, not at a desktop, and they are not going to read three paragraphs. The site has to load fast, put a tap-to-call button and your service area in front of them immediately, and make it obvious you are a real, local, licensed locksmith and not a call center that dispatches a stranger. A visitor should never have to hunt for the number.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The same trust signals that calm a scam-wary customer, a real local address, your license stated plainly, upfront and honest pricing, and real reviews, are exactly what turn a nervous visitor into a booked job. A slick site that hides who you are and buries the phone number loses the very caller it should have caught.</p>'},
        {"h2_html": "The calls are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a pay-per-lead service disappears the day you stop paying, and the lead was never really yours anyway. A website you own keeps ranking, keeps capturing calls, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you. The reviews you gather and the local and commercial pages you build stack up over time, so a site that ranks this year ranks stronger next year rather than resetting to zero when a budget runs out. The site plugs into the same CRM that follows up on every lead it captures and the answering service that picks up the calls it drives, so nothing it earns you slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A car lockout finds <em>you</em>, not a call center",
        "body_html": 'Someone is locked out of their car outside a grocery store after dark and searches car lockout locksmith near me on their phone. Instead of a national call center that would sell the lead on or dispatch whatever stranger is closest, they find your site ranking for that town, with a page about car lockouts, your license and local address stated plainly, real reviews about fair pricing, and a tap-to-call button right at the top. They call you directly, you give them an ETA, and the job is yours. You paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big directories and call centers?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the emergency, rekey, and commercial searches a national operation has no reason to target well, which is exactly where a real local locksmith can win.'),
        ("How is this different from paying for leads?",
         'A pay-per-lead service rents you a call that it also sells to your competitors or dispatches to a stranger, and it stops the day you stop paying. A website you own captures calls that are yours alone and keeps working long after it is built, without a per-lead fee coming out of every job.'),
        ("Do I need to rank for every town I serve?",
         'You rank for the ones that matter most first. We build pages for your core service areas and the highest-intent searches, then expand, rather than spreading thin across a whole metro at once.'),
        ("Most of my calls are emergency lockouts. Does a website even help?",
         'Especially then. A lockout search happens on a phone the moment someone is stranded, and the locksmith who shows up in the map pack with a tap-to-call button, a real address, and honest reviews gets the call. A site built for that moment is exactly what captures it, and it wins the commercial research jobs too.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for locksmiths"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-locksmiths.html", "Staying visible in your service area beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and call centers taking your calls, whether you work with us or not. No credit card, never a call center.",
},
]
