"""Per-page content specs for the SEO corpus (plan §5), med spas batch. Same contract as
scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, med-spa-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber or chiropractor content reworded.

Medical & Dental hub. Four service angles are here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client." per
the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ============================ AI Receptionist for Med Spas ============================
{
    "slug": "ai-receptionist-for-med-spas", "demo": True,
    "trade_slug": "med_spas", "trade_plural": "med spas",
    "hub_name": "Medical & Dental", "hub_slug": "industry-medical-dental.html",
    "breadcrumb_leaf": "AI Receptionist for Med Spas",
    "title": "AI Receptionist for Med Spas | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Med Spas",
    "meta_desc": "A med spa answering service answers every consult call and text the moment it comes in, books the consult, and turns late-night interest into appointments.",
    "service_schema_name": "AI Receptionist for Med Spas",
    "eyebrow": "For Med Spas",
    "h1_html": "AI Receptionist <em>for Med Spas</em>",
    "answer_block": "A med spa answering service answers every consult call and text the moment it comes in, day, night, or mid-treatment, tells a first-time filler inquiry apart from a rescheduling regular, and books the consultation while your injector is busy. You keep your own number, and every lead belongs to you.",
    "sections": [
        {"h2_html": "The consult you miss books with the spa that <em>picked up</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A woman who has been thinking about Botox or filler for months finally works up the nerve to call. If she gets voicemail, she does not leave one, she calls the next spa on the list, and the one after that, until someone picks up. Aesthetic work runs on trust and timing: the treatments are high-ticket and consultation-driven, and a first-time caller is nervous and comparison-shopping. Meanwhile your front desk is walking a client back to a room and your injector is mid-treatment with both hands busy, so the call rolls to voicemail and the lead, worth far more than one visit once she becomes a regular, goes to whoever answered.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist answers on the first ring, warm and calm with someone who is a little anxious, finds out what she is interested in, a tox appointment, a first-time filler consult, laser, a facial, answers the questions that decide whether she books, and puts the consultation on your calendar right then or texts her a booking link. The lead is captured and scheduled instead of lost to the spa that simply picked up.</p>'},
        {"h2_html": "Built around how med spas <em>actually get inquiries</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A lot of your interest never arrives as a tidy phone call during business hours. Someone sees a before-and-after on Instagram at eleven at night and wants to book while the nerve holds. Someone fills out the form on your site over the weekend. Someone calls on a lunch break and cannot leave a voicemail from an open-plan office. A voicemail box cannot answer a nervous first-timer, and a generic call center reading a script does not know a lip flip from a filler dissolve or which one needs your nurse.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers around the clock, including the late-night scroller who just found you on Instagram and wants to book before the feeling passes.</li><li>Replies by text and website chat, not only by phone, because many aesthetic clients would rather type than talk.</li><li>Knows your menu well enough to tell a quick tox touch-up from a first-time consult and route each one the right way.</li><li>Treats a loyal member or package client differently from a brand-new lead, so the people who already trust you never reach a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one consultation that books</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many inquiries for this to pay for itself. Aesthetic treatments are high-ticket and they repeat, so a single first-time consult you would otherwise have lost, one person who comes in for tox and stays for filler, a package, and a membership, is worth far more than the system costs across the months she keeps coming back. Everything it captures after that first save is on top. The point is to stop handing your most valuable inquiries to the spa that simply answered faster.</p>'},
        {"h2_html": "You own the number, the leads, and the <em>client list</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every inquiry, and every booked consult is yours and exportable any time, so the client list you build is an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The AI receptionist is one piece of the Top Shelf platform, and it hands every lead it captures to the same CRM that follows up, so a consult that does not book on the first call still gets nurtured toward one.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "An 11pm text, booked <em>by morning</em>",
        "body_html": 'A woman has been following your before-and-afters for weeks without ever reaching out. One night she finally texts the number from your Instagram bio at eleven at night, asking what a lip filler consult would run and whether you have anything open this week. Your front desk closed hours ago. Instead of the message sitting unread until Tuesday, the AI receptionist replies within a minute, warm and clear, answers her questions, and books her for a consult on Thursday, with a confirmation sent before she puts her phone down. You wake up to a new consult on the calendar, her name and what she asked about already attached, instead of a cold message she talked herself out of by morning. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every call and text that come through it belong to you and go with you if you ever leave.'),
        ("Can it answer texts and website chat, not just phone calls?",
         'Yes. Many aesthetic clients would rather type than talk, and a lot of your interest comes from people who found you on Instagram or TikTok after hours. It answers by phone, by text, and through the chat on your website, so a late-night inquiry gets a real reply while the interest is still warm instead of a voicemail box.'),
        ("Will it actually book the consult on my calendar?",
         'Yes. Routine consults and appointments land straight on your calendar based on your availability and the consult types you set, with a confirmation to the client and a note to you. For anything it cannot fully book, it captures the details and hands them to your team so no one is left chasing a phone tag trail.'),
        ("Will it sound like a robot to a nervous first-time client?",
         'It answers naturally and warmly, and it is upfront rather than pretending to be a person. Someone anxious about a first treatment mostly needs to feel that a real, professional spa has them, and a calm reply that answers the question beats a voicemail box every time. You can hear it handle a live call before you decide.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We configure your treatment menu, your consult types, your calendar, and how it greets a caller, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.')],
    "related": [
        ("industry-medical-dental.html", "Everything Top Shelf does for med spas"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-med-spas.html", "The CRM that follows up on every consult you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing consults to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls, texts, and after-hours inquiries your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ================================ CRM for Med Spas ================================
{
    "slug": "crm-for-med-spas",
    "trade_slug": "med_spas", "trade_plural": "med spas",
    "hub_name": "Medical & Dental", "hub_slug": "industry-medical-dental.html",
    "breadcrumb_leaf": "CRM for Med Spas",
    "title": "CRM for Med Spas | Top Shelf Business Solutions",
    "og_title": "CRM for Med Spas",
    "meta_desc": "A med spa CRM keeps every client, package, and membership in one place and reminds clients when they are due, so tox and filler cycles rebook on time.",
    "service_schema_name": "CRM for Med Spas",
    "eyebrow": "For Med Spas",
    "h1_html": "CRM <em>for Med Spas</em>",
    "answer_block": "A med spa CRM keeps every client, treatment history, package, and membership in one place and reaches out when someone is due for their next cycle, so the client whose Botox is wearing off and the one with three laser sessions left both rebook with you instead of drifting away. Your client list quietly becomes recurring revenue.",
    "sections": [
        {"h2_html": "Your happy clients rebook <em>only if you reach them</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most med spas do not have a new-client problem so much as a rebooking problem. Botox wears off in a few months. Filler softens over the year. Laser and body contouring are sold as packages of several sessions. A client walks out thrilled and fully meaning to come back, then life gets busy, no reminder ever comes, and she resurfaces months later at whatever spa ran a promo that week, if she comes back at all. The treatment was always going to repeat. It just needed a well-timed nudge, and that is the thing a full front desk never gets around to.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every client and their full treatment history and cycle in front of you and sends the reminder for you, on the schedule you set, whether or not anyone at the desk remembers. The client whose tox is about to fade hears from you right on time and rebooks, instead of forgetting you until some other spa runs the ad that reminds her she is overdue.</p>'},
        {"h2_html": "Every treatment runs on a <em>cycle you can plan around</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Aesthetic clients are the most predictable repeat business there is, if someone is tracking it. You know roughly when tox needs a touch-up, when a filler client is due for a refresh, when a package still has sessions on it, and when a membership is about to renew. But no one can hold the schedules of a few thousand clients in their head, so most of that built-in repeat revenue slips away unless something is watching the dates for you.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every client, their treatments, products, notes, and consent history live in one place instead of scattered across paper charts, a booking app, and what the front desk happens to remember.</li><li>Reminders fire on the cycle each treatment runs on, a tox touch-up, a filler refresh, the next session in a package, so the rebooking happens without anyone tracking dates.</li><li>Memberships and packages are tracked, so you can see who still has sessions to use and who is due to renew, and reach them before the benefit lapses.</li><li>You can see who has not been in for a while and send the right client the right reason to come back at the right moment.</li></ul>'},
        {"h2_html": "The client who drifted off is still <em>yours to win back</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A client who has not been in for eight months is not being disloyal. She got busy, no reminder came, and your name slipped her mind. A light, well-timed touch, a note that she is due, a quick check-in, a reason to come back this month, puts you back in front of her before some other spa promo does. It costs almost nothing, and it is the difference between a client who came in twice and one who stays with you for years of treatments. Reactivating the clients you already earned is the cheapest growth a med spa has.</p>'},
        {"h2_html": "Fewer no-shows, and a client list <em>you actually keep</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A no-show on a booked treatment is a room and an hour you cannot get back, so the CRM sends confirmations and reminders that keep your chairs full and give clients an easy way to reschedule instead of simply vanishing. Every client, note, and treatment record is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform: it connects to the AI receptionist, so a consult it answers lands in your database and gets followed up on, and to online booking, so every visit is logged against the right client with their full history already attached.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The Botox client who <em>rebooks on time</em>",
        "body_html": 'A client comes in for Botox in March, loves the result, and fully means to come back before it fades. Normally that is where it ends, until she notices in July that it has worn off and books wherever she happens to see an ad. Instead, the CRM knows her cycle and sends a friendly note in early June that she is coming due, written to sound like your spa, with a link to book. She rebooks for the second week of June without ever letting the result fully fade, and she is back on your calendar before she would have thought to look elsewhere. No one at the desk had to remember. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing clients and treatment history?",
         'Yes. Your current clients, their treatment history, packages, and notes come in and live in one place, and everything stays yours and exportable. The point is to make the client list you already have actually work for you.'),
        ("Will it really remind clients when their next treatment is due?",
         'Yes, on the cycle each treatment runs on and the schedule you approve. A tox client hears from you as she comes due, a package client gets nudged to use the sessions she paid for, and a member is reminded before benefits reset, all sent for you. You can step in and message anyone yourself any time.'),
        ("Can it track memberships and packages?",
         'Yes. It tracks who still has sessions to use, who is due to renew, and who has quietly fallen behind on a membership they are paying for, so you can reach them before the value goes unused and a member cancels.'),
        ("How is this different from the booking tool I already use?",
         'A booking calendar records appointments. It does not watch treatment cycles, follow up on a client who drifted off, flag a package that is going unused, or reactivate someone you have not seen in a year. The CRM does all of that on a schedule, so the repeat revenue actually shows up instead of depending on memory.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your clients, build your reminder and reactivation sequences around your real treatment cycles, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where rebookings are slipping today.')],
    "related": [
        ("industry-medical-dental.html", "Everything Top Shelf does for med spas"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-med-spas.html", "The AI receptionist that feeds it every consult"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting clients and cycles <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your past clients and treatment cycles are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ============================== Marketing for Med Spas ==============================
{
    "slug": "marketing-for-med-spas",
    "trade_slug": "med_spas", "trade_plural": "med spas",
    "hub_name": "Medical & Dental", "hub_slug": "industry-medical-dental.html",
    "breadcrumb_leaf": "Marketing for Med Spas",
    "title": "Marketing for Med Spas | Top Shelf Business Solutions",
    "og_title": "Marketing for Med Spas",
    "meta_desc": "Med spa marketing keeps you visible where new clients actually look, on Instagram and TikTok and in the Google map pack, so late-night scrollers book with you.",
    "service_schema_name": "Marketing for Med Spas",
    "eyebrow": "For Med Spas",
    "h1_html": "Marketing <em>for Med Spas</em>",
    "answer_block": "Med spa marketing keeps you visible where new clients actually decide, on Instagram and TikTok where they scroll before-and-afters at night, and in the Google map pack when they search for a spa nearby, so the person weighing a first treatment finds you, trusts you, and books a consult instead of a competitor.",
    "sections": [
        {"h2_html": "Aesthetic demand is created on a <em>screen, after hours</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">People do not decide to get Botox or filler at a desk during business hours. The idea forms late at night, scrolling Instagram and TikTok, watching before-and-afters and someone walk honestly through what a treatment was actually like. By the time they search for a spa nearby, they have half-decided already, and they are choosing among the few names they recognize and trust. If you are not part of that scroll, and not visible when they finally search, you are not in the running, no matter how skilled your injector is.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Marketing for a med spa is about being present and trusted in those two places, the feed where the interest starts and the search where the decision lands, so yours is the name that already feels familiar the moment someone is ready to book.</p>'},
        {"h2_html": "Your feed is the storefront, and your <em>results are the proof</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">No one books an aesthetic treatment on words alone. They want to see real results on real faces, and a steady feed of before-and-afters you have consent to post, treatment clips, and the people behind the spa is what turns a curious scroller into a booked consult. A page that has gone quiet for two months reads as a spa that closed or stopped caring, sitting right next to one posting current work. Keeping your presence active, consistent, and honest, built around the treatments you actually want more of, is a quiet advertisement running exactly where new clients are looking.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The content that actually converts is not a glossy ad. It is a nurse answering the questions that keep a first-timer on the fence, does it hurt, how long does it last, will it look overdone, next to real results and the faces behind the treatments. That is what eases the nerves standing between someone and a first appointment, and it is the kind of thing a busy front desk never finds time to post on a schedule.</p>'},
        {"h2_html": "When they finally search, the <em>map pack decides</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Once someone is ready, they search for a med spa near them or a treatment and their town, and the first thing they see is the map pack, the three local listings with the star ratings, sitting above the websites and the ads. A Google Business Profile with recent photos, current hours, your real menu, and a steady flow of reviews wins that glance over a thin, neglected listing every time. Reviews carry more weight here than in almost any business, because a new client is trusting you with her face and looking for proof that other people did the same and were glad. Keeping that profile active and those reviews fresh is what puts you in front of the ready-to-book search.</p>'},
        {"h2_html": "Stay in front, and let good visits <em>feed the next client</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Aesthetic demand keeps its own calendar, wedding and event season, the run-up to holidays and vacations, the new-year reset, and being visible right before each wave beats scrambling once it arrives. A steady presence, current posts, fresh reviews, a profile that looks tended, keeps you top of mind for the next new client and reminds past ones that you are still the place to come back to. This is the public-facing side of the business; the private follow-up to the clients already in your database is the CRM, and the reviews all of this leans on are gathered automatically by the same Top Shelf platform each time a visit is marked complete.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A late-night scroll that becomes a <em>morning consult</em>",
        "body_html": 'A woman is up late scrolling and lands on a lip-filler before-and-after from your spa, then a short clip of your injector walking through how the appointment goes. She follows you, and over the next week a couple more posts and a run of recent five-star reviews cross her feed. When she finally searches for a med spa in her town, yours is right there in the map pack with a full, active profile and the same reviews she already saw. She books a consult with the one name that already felt familiar and safe, not the listing she had never heard of. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my social and Google profile for me?",
         'Yes. We keep your Instagram, TikTok, and Google Business Profile active with content built around the treatments you want more of, on a regular schedule, and we keep your hours, menu, and photos current so you look present whenever someone looks you up.'),
        ("I am a small spa. Is social really worth it?",
         'For aesthetics, it is where the demand actually starts. People make up their minds while scrolling before-and-afters at night, so a steady, honest feed of real results you have consent to show is often your single best source of new consults, and it costs far less than running paid ads.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with clients already in your database. Marketing is the public-facing side, your social feed, your Google profile, your reviews, and your local visibility, aimed at people who are not your client yet and need to find and trust you before they will book a first treatment.'),
        ("Can you help me get ahead of the busy seasons?",
         'Yes. We time your visibility to the waves that matter for aesthetics, wedding and event season, the holidays, the new-year reset, so you are already in front of people before the rush instead of scrambling once it starts.'),
        ("How long before I see it working?",
         'A quiet feed and a neglected profile can start gaining ground within weeks once they are active and consistent, and it compounds as reviews and content build. Setup is included, and a free audit will show you what your current presence looks like to someone deciding between spas today.')],
    "related": [
        ("industry-medical-dental.html", "Everything Top Shelf does for med spas"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-med-spas.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the spa they <em>already trust</em>",
    "cta_sub": "Get a free audit of how visible you actually are on social and in local search right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Websites & SEO for Med Spas =========================
{
    "slug": "websites-seo-for-med-spas",
    "trade_slug": "med_spas", "trade_plural": "med spas",
    "hub_name": "Medical & Dental", "hub_slug": "industry-medical-dental.html",
    "breadcrumb_leaf": "Websites & SEO for Med Spas",
    "title": "Websites & SEO for Med Spas | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Med Spas",
    "meta_desc": "A med spa website built for SEO ranks for botox and med spa near me, looks premium enough to trust with your face, and books the consult before they leave.",
    "service_schema_name": "Websites & SEO for Med Spas",
    "eyebrow": "For Med Spas",
    "h1_html": "Websites &amp; SEO <em>for Med Spas</em>",
    "answer_block": "A med spa website built for SEO ranks for what a new client searches, botox near me, med spa and your city, laser hair removal, looks polished enough that someone trusts you with their face, and makes booking a consult effortless the moment they land, so the client is yours instead of a booking marketplace taking a cut.",
    "sections": [
        {"h2_html": "They are trusting you with their face, and your <em>site is the proof</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Choosing a med spa is a more personal decision than almost any local purchase. A new client is about to let someone inject her face or run a laser across her skin, and long before she calls, she is judging whether you are safe and worth it by how your website looks and feels. A slow, dated, template site quietly tells her you might be careless with the things that matter most, so she closes the tab and books with the spa whose site looked as polished as the results she is hoping for. A clean, fast, professional site is not vanity here. It is the first proof that you are the safe choice.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">So the site has to load fast, look as premium as the treatments you sell, show real results and real reviews, and make it obvious how to book a consult, all of it on a phone, because that is where she is looking.</p>'},
        {"h2_html": "Rank for what a new client <em>actually types</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national booking marketplace this year for the broadest term, and you do not need to. You can rank for your own name, for the specific town and neighborhoods you serve, and for the exact searches someone makes once she is ready: botox near me, lip filler and your city, med spa, laser hair removal, a named treatment plus your area. Pages built around the treatments you actually offer and the places you actually serve are what search engines, and a ready-to-book client, reward with the click, rather than handing it to a directory that has never met you.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A lot of aesthetic search is treatment-specific, someone types the exact procedure they saw on their feed, so a site that gives each signature treatment its own real page, what it is, who it is for, what to expect, ranks for those searches and answers the question before the client even calls. That is depth a single thin services page cannot match, and it is exactly what a national marketplace has no reason to write for your town.</p>'},
        {"h2_html": "A ready client should book in a <em>tap, not a callback</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone who has decided is on her phone, often late at night, and if booking means calling during business hours or filling out a form and waiting for a callback, the moment cools and she moves on. The site should put a clear way to book a consult right in front of her, so she can lock in a time while the nerve holds, and give the ones who would rather ask a question first an easy way to reach you. A beautiful site that buries the booking button wastes the exact visitor you worked to earn; someone ready to commit should never have to hunt for how.</p>'},
        {"h2_html": "The client belongs to <em>you</em>, not a marketplace",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The booking marketplaces and directories that outrank you are not really competing on care. They are renting you back your own clients and taking a fee out of every booking they send, and the client was never truly yours to keep. A website you own keeps ranking, keeps booking consults, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can change its terms or drop you overnight. The site plugs into the same CRM that follows up on every lead it captures and the AI receptionist that answers the inquiries it drives, so nothing it earns you slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A first-timer searches, and finds <em>you, not a marketplace</em>",
        "body_html": 'A woman in the next town over has finally decided to book her first Botox, and she searches for it on her phone late at night. Instead of a national booking marketplace that would route her to whoever pays it the most and skim a fee off the top, she finds your site ranking for her area, and it looks as polished and careful as she is hoping the treatment will be. There are real results, real reviews, and one clear button to book a consult. She books a time on the spot, and the client is yours, with no marketplace fee and no middleman in between. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big booking sites?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific town and neighborhoods, and the treatment-plus-area searches a national marketplace has no real reason to target well, which is exactly where a local spa can win.'),
        ("How is this different from listing on a booking marketplace?",
         'A marketplace rents you a client it can also route elsewhere and takes a fee out of every booking, and that client was never really yours. A website you own books consults that are yours alone and keeps working long after it is built, with no cut coming out of each appointment.'),
        ("Does the design really matter that much?",
         'For aesthetics, more than almost anywhere. A client is deciding whether to trust you with her face, and a slow or dated site tells her the wrong thing before she reads a word. A fast, premium site that shows real results is often the thing that earns the call.'),
        ("Can clients book right from the site?",
         'Yes. The site puts a clear way to book a consult front and center, so a ready client locks in a time in a tap instead of leaving a voicemail she second-guesses by morning, and every booking lands in your CRM against the right client.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-medical-dental.html", "Everything Top Shelf does for med spas"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-med-spas.html", "Staying visible in your area beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the marketplaces and directories taking your clients, whether you work with us or not. No credit card, never a call center.",
},
]
