"""Per-page content specs for the SEO corpus (plan §5), plumbers batch. Same contract as
scripts/corpus_specs.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, plumber-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the realtor content reworded.

Home Services hub. All seven service angles are here in one file (the ai-receptionist dict
carries "demo": True). Each example body ends with the literal "Illustrative example, not a
client." per the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ============================ AI Receptionist for Plumbers ============================
{
    "slug": "ai-receptionist-for-plumbers", "demo": True,
    "trade_slug": "plumbers", "trade_plural": "plumbers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Plumbers",
    "title": "AI Receptionist for Plumbers | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Plumbers",
    "meta_desc": "An AI receptionist for plumbers answers every emergency and after-hours call, triages the job, and books it on your calendar while your hands are full.",
    "service_schema_name": "AI Receptionist for Plumbers",
    "eyebrow": "For Plumbers",
    "h1_html": "AI Receptionist <em>for Plumbers</em>",
    "answer_block": "An AI receptionist for plumbers answers every call the moment it rings, day or night, tells a burst pipe apart from a dripping faucet, and books the job straight onto your calendar while you are under a sink or in a crawlspace. You keep your own number, and every call belongs to you.",
    "sections": [
        {"h2_html": "The call you miss is the emergency that <em>calls the next plumber</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner with water spreading across the kitchen floor is not going to leave a voicemail. They hang up and call the next plumber on the list, and the one after that, until someone picks up. Plumbing runs on that kind of urgency more than almost any trade, because every minute the water runs is more damage to the floor, the ceiling below it, and the drywall. But you are under a sink with a wrench in your hand, in a crawlspace with no signal, or driving to the last job, so the call rolls to voicemail and the emergency, along with the premium after-hours ticket that comes with it, goes to whoever answered.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist answers on the first ring, stays calm with a panicked caller, finds out whether it is an active leak, a sewage backup, or no hot water, gets the address, and either books the visit or flags it to you as a true emergency on the spot. The job is captured and scheduled instead of lost to the shop down the road.</p>'},
        {"h2_html": "Built around how <em>plumbers actually get calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your calls do not keep office hours. A water heater fails on a Sunday, a pipe bursts at 2am in a cold snap, a toilet overflows during dinner, and the calls that pay the most are the ones that come when every other shop is closed. A voicemail box cannot triage an emergency, and a generic call center reading a script does not know a slab leak from a running toilet, or which of the two can wait until morning.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24/7, including the 2am burst pipe and the holiday-weekend sewage backup that are your best-paying jobs.</li><li>Triages like you would: active leak or dry, water shut off or not, sewage or clean, no hot water or a slow drain, and how fast someone needs to be there.</li><li>Gets the address and the details, books routine work on your calendar, and texts you the true emergencies at once so you decide whether to roll a truck.</li><li>Handles a repeat customer or a maintenance-plan member differently from a first-time caller, so the people who already trust you never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one emergency job</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. One burst pipe or one water heater replacement you would have lost on a weekend is often worth more than the system costs for months, and after-hours emergency work is usually your highest-margin ticket of all. Everything it captures after that first save is on top. The point is to stop handing your best-paying calls to the plumber who simply answered faster.</p>'},
        {"h2_html": "You own the number, the calls, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every address, and every job detail is yours and exportable any time, so your customer list is an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The AI receptionist is one piece of the Top Shelf platform, and it hands every call it captures to the same CRM that follows up, so a quote or a maintenance reminder never slips.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A 2am burst pipe, booked while you <em>sleep</em>",
        "body_html": 'It is 2am in the first hard freeze of the year and a homeowner wakes up to water coming through the ceiling. They search for a plumber and call the first three they see. Two go to voicemail. Yours answers, stays calm, confirms the water is now shut off at the main, gets the address, and books you for first thing in the morning while flagging it to your phone as urgent. You wake up to the job already on your calendar with the address, the problem, and the customer\'s number attached, instead of hearing about it after they hired someone else. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever leave.'),
        ("Can it tell a real emergency from a routine call?",
         'Yes, that is the point. It asks the questions you would, is the water shut off, is it sewage or clean, is there hot water, and treats an active leak or a backed-up main as urgent while booking a dripping faucet or a quote as routine. You set what counts as a drop-everything emergency.'),
        ("Will it actually book the job on my calendar?",
         'Yes. Routine and scheduled work lands straight on your calendar based on your availability, and you get a text with the details right away. For a true emergency it can book the first open slot and alert you at once so you decide whether to roll a truck tonight.'),
        ("Is it going to sound like a robot to a panicked customer?",
         'It answers naturally and calmly, and it is upfront instead of pretending to be a person. Someone standing in a flooding kitchen mostly needs to know that a real plumber is handling it, and a steady voice that captures the details beats a voicemail box every time. You can hear it handle a live call before you decide.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We configure your triage questions, your calendar, and your emergency rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for plumbers"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-plumbers.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing emergencies to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and after-hours jobs your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ================================ CRM for Plumbers ================================
{
    "slug": "crm-for-plumbers",
    "trade_slug": "plumbers", "trade_plural": "plumbers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Plumbers",
    "title": "CRM for Plumbers | Top Shelf Business Solutions",
    "og_title": "CRM for Plumbers",
    "meta_desc": "A CRM for plumbers follows up on every quote and past customer for you and fires maintenance reminders, so a home you serviced once keeps calling you.",
    "service_schema_name": "CRM for Plumbers",
    "eyebrow": "For Plumbers",
    "h1_html": "CRM <em>for Plumbers</em>",
    "answer_block": "A CRM for plumbers keeps every lead, past customer, and open quote in one place and follows up for you, so the water heater bid a homeowner is sitting on and the family whose faucet you fixed two years ago both call you next instead of the shop that stayed in touch. Your customer list quietly becomes your pipeline.",
    "sections": [
        {"h2_html": "The quotes you already sent are the jobs you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most plumbers do not have a lead problem. They have a follow-up problem. You quote a water heater replacement or a repipe, the homeowner says they need to think about it, and then you get busy and never circle back. They collect two other bids, and the job goes to whoever followed up, not necessarily the lowest price. The quote was never dead. It just needed one more call or text a few days later, and that is the thing there is never time for between service calls.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open quote in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not you remember. The homeowner deciding between three bids hears from you again while the other two go quiet, and the job comes back to you.</p>'},
        {"h2_html": "Every home you service is a customer <em>for decades</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Past customers are the cheapest work a plumber can get. You have already been in the house, they already trust you with a key and a crawlspace, and the next water heater, the next drain, the next remodel is yours if you stay in touch. But you cannot personally remember to reach back out to a few thousand past customers, so most of that repeat work goes to whoever they find on Google when they forget your name.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, address, job history, and note lives in one place instead of a truck full of paper invoices and your memory.</li><li>Maintenance reminders go out on schedule, a water heater flush, a drain cleaning, a sump pump check before storm season, so the work comes back around without you tracking dates.</li><li>You can see who has not called in a while and reach the right customer with the right reminder at the right time.</li></ul>'},
        {"h2_html": "The customers who forgot your name are still <em>yours to keep</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner you helped two years ago is not disloyal when they call another plumber. They just lost your card and never saved your number. A steady, light touch, a seasonal tip, a maintenance reminder, a quick check that the last repair is still holding, keeps your name in their phone so the next emergency comes to you. It costs almost nothing, and it is the difference between a one-time job and a customer for the life of the house.</p>'},
        {"h2_html": "You own the list, and it works with the rest of the system",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the AI receptionist, so a call it answers lands in your database and gets followed up on automatically, and to online booking, so a scheduled visit is logged against the right customer with their full history already attached. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The water heater quote that <em>closes itself</em>",
        "body_html": 'You quote a homeowner on a new water heater on a Monday and they tell you they want to get another price. Normally that is the last you hear of it. Instead the CRM sends a friendly check-in two days later and a short note a few days after that, both written to sound like you. The other two plumbers never followed up, so when the homeowner is ready on Friday, yours is the only name still in front of them, and they book with you without shopping any further. You never sat down to chase it. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing customers and past jobs?",
         'Yes. Your current customers, leads, and job history come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already have actually work for you.'),
        ("Will it really follow up on quotes automatically?",
         'Yes, on the schedule you approve. An open estimate gets a check-in a few days later and another after that, all sent for you, so a homeowner comparing bids keeps hearing from you while the other plumbers go quiet. You can jump in and message anyone directly any time.'),
        ("Can it send maintenance reminders?",
         'Yes. You set the cadence, a water heater flush each year, a drain cleaning, a sump pump check before the rainy season, and the reminders go out automatically so recurring work comes back around without you tracking every date.'),
        ("How is this different from just having their number in my phone?",
         'A phone full of contacts does not follow up, does not remember who is due for maintenance, and does not tell you which quote is going cold. The CRM does all of that on a schedule, so the repeat work actually shows up instead of depending on you to remember.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your customers, build your follow-up and reminder sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where jobs are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for plumbers"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-plumbers.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting quotes and customers <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your quotes and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================== Online Booking for Plumbers ==========================
{
    "slug": "online-booking-for-plumbers",
    "trade_slug": "plumbers", "trade_plural": "plumbers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for Plumbers",
    "title": "Online Booking for Plumbers | Top Shelf Business Solutions",
    "og_title": "Online Booking for Plumbers",
    "meta_desc": "Online booking for plumbers lets customers self-schedule a water heater quote, drain cleaning, or service visit on your real availability, no phone tag.",
    "service_schema_name": "Online Booking for Plumbers",
    "eyebrow": "For Plumbers",
    "h1_html": "Online Booking <em>for Plumbers</em>",
    "answer_block": "Online booking for plumbers lets a customer pick a time for the work that is not a 2am emergency, a water heater quote, a drain cleaning, a faucet install, a yearly inspection, straight from your website or a text link on your real availability, so you stop playing phone tag and the visit lands on your calendar with the details you need to show up ready.",
    "sections": [
        {"h2_html": "Not every plumbing call is a <em>2am emergency</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A burst pipe needs a phone and a fast truck. But a lot of plumbing work is not urgent at all: a homeowner wants a quote on a new water heater, a drain snaked, a faucet swapped, or an annual inspection, and they would happily book it themselves if you let them. Making those customers call during business hours, wait on hold, and trade voicemails is how routine jobs quietly slip to the shop that made booking easier.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets them grab an open slot the moment they think of it, at night or on a lunch break, without reaching you first. You wake up to the visit already on the calendar instead of a missed call you now have to chase between service stops.</p>'},
        {"h2_html": "It sorts the emergency from the <em>routine</em> before it books",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Self-scheduling does not mean sending a flooding kitchen to a slot three days out. The booking form asks what is going on first, and a true emergency, active leak, sewage, no water, gets pointed straight to your emergency line to call right now, while genuinely routine work, a quote, a drain, an install, books itself onto your calendar. You set the rules: which jobs are bookable online, how long each type takes, how much notice you need, and which hours are open at all.</p>'},
        {"h2_html": "A booking link everywhere a customer <em>finds you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The link goes anywhere someone already meets you: your website, your Google Business Profile, your email signature, and the text you send after a call. Every one of those turns from a dead end that needs a callback into a place someone can book you in one tap. A homeowner comparing plumbers on a Sunday night for a water heater they have been putting off can put the visit on your calendar before they close the tab, instead of leaving a voicemail they will forget by Monday.</p>'},
        {"h2_html": "On your real calendar, and the customer actually shows",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar you already use so it can never double-book a tech against a job you already have, and it sends the customer a confirmation and a reminder, which is what actually cuts no-shows. A plumber driving across town to an empty house is a wasted hour you never get back. Every booking is logged against the right customer in your CRM, and it works alongside the AI receptionist, which can also book the caller who would rather talk than tap.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Sunday-night water heater, booked <em>before Monday</em>",
        "body_html": 'It is 9pm on a Sunday and a homeowner has finally had enough of a water heater that runs cold halfway through a shower. They land on your site, see real reviews, and instead of leaving a voicemail they will second-guess in the morning, they book a replacement quote for Wednesday at 10 from the calendar right there on the page. You wake up Monday to the visit already set, with their name, address, and the make of the old unit attached. No phone tag, no lost job. Illustrative example, not a client.'},
    "faqs": [
        ("Does it sync to my Google or Outlook calendar?",
         'Yes. It reads your real calendar so it only ever offers times you are actually free, and new bookings drop straight onto it. It cannot double-book a tech against a job you already have scheduled.'),
        ("Will emergencies try to book a slot three days out?",
         'No. The form asks what is going on first, and a true emergency, active leak, sewage, no water, is pointed to your emergency line to call right now instead of booking a future slot. Only the work you mark as routine can self-schedule.'),
        ("Can I control which jobs are bookable and how long they take?",
         'Yes. You decide which job types are available online, how long each one runs, how much notice you need, and how much buffer to leave for drive time, so you are never booked with no way to get there.'),
        ("Will it cut down on no-shows?",
         'It helps. Automatic confirmations and reminders by text and email are the single biggest lever on no-shows, and every booking includes them. A customer who booked themselves and got a reminder is far more likely to be home than a loosely agreed callback.'),
        ("How fast can it be live?",
         'Setup is included, no separate fee. We connect your calendar, set up your job types and rules, and put the link on your site and profile, so it is taking bookings in days. Start with a free audit and we will show you where you are losing routine jobs today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for plumbers"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-plumbers.html", "The AI receptionist that can book callers too"),
        ("crm-for-plumbers.html", "The CRM every booking is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let customers book you <em>while you work</em>",
    "cta_sub": "Get a free audit of how many routine jobs your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Review Software for Plumbers =========================
{
    "slug": "review-software-for-plumbers",
    "trade_slug": "plumbers", "trade_plural": "plumbers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for Plumbers",
    "title": "Review Software for Plumbers | Top Shelf Business Solutions",
    "og_title": "Review Software for Plumbers",
    "meta_desc": "Review software for plumbers asks every happy customer for a Google review at the right moment, so the next person with a burst pipe calls you first.",
    "service_schema_name": "Review Software for Plumbers",
    "eyebrow": "For Plumbers",
    "h1_html": "Review Software <em>for Plumbers</em>",
    "answer_block": "Review software for plumbers asks every happy customer for a review the moment the job is done and the water is running again, makes leaving one a single tap, and helps you reply to each, so the next homeowner searching in a panic finds a wall of recent five-star reviews and calls you first.",
    "sections": [
        {"h2_html": "A panicked homeowner hires the plumber with the <em>most recent reviews</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a pipe bursts, nobody asks around for a referral. They search for a plumber, glance at the map, and call the one with the most recent five-star reviews near them, because they are about to let a stranger into their home during a stressful moment and reviews are the fastest trust they can get. A thin profile with a handful of old reviews quietly loses those calls to the shop with a fresh wall of them, and you never even hear the phone that did not ring.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The problem is not that your customers are unhappy. It is that happy customers forget to post, and asking feels awkward when you are packing up the truck. Review software fixes the timing and the awkwardness so the reputation you have already earned actually shows up where people are looking.</p>'},
        {"h2_html": "Ask at the moment they are <em>most relieved</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The best time to ask is right after the water is running again and the customer is standing there grateful that the crisis is over. The software sends the ask automatically at that moment, by text and email, with a link that drops them straight onto your Google profile in one tap. No cornering people at the door, no business card that asks them to go find you later, and no reminder three weeks on when the relief has worn off and they have moved on.</p>'},
        {"h2_html": "Respond to every review, good or <em>bad</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A thoughtful reply to each review tells the next homeowner reading it that you stand behind your work, and responding is one of the signals that helps you show up higher in local search. The software flags every new review the moment it lands and helps you reply fast, so a rare critical one, the callback that went sideways, gets a calm, professional response instead of silence, and every good one gets a genuine thank you.</p>'},
        {"h2_html": "More reviews, more calls, compounding",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Recent reviews feed your Google Business Profile, which lifts you in the map pack a homeowner sees when they search for a plumber near them, which brings more calls, which brings more reviews. It builds on itself. Your reputation is yours, tied to your own profile, not a directory or a lead-seller. Review requests are part of the Top Shelf platform and fire automatically off a job marked complete in your CRM, so you collect reviews without lifting a finger.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "One drain cleaning becomes <em>next week's emergency call</em>",
        "body_html": 'You clear a stubborn kitchen drain on a Thursday afternoon. An hour after you leave, the software texts your relieved customer a thank-you with a one-tap link, and they post a warm review before dinner. The next week a neighbor two streets over has a water heater start leaking, searches for a plumber, and reads that exact review sitting at the top of your profile. They call you instead of the name below you on the map. You never asked twice, and you were on another job when it happened. Illustrative example, not a client.'},
    "faqs": [
        ("Which review sites does it work with?",
         'It focuses on Google, which is where a homeowner in a hurry looks first and what feeds your local search ranking. It can also point past customers to your other profiles. We follow each platform\'s own rules, including that a review should come from someone you actually did work for.'),
        ("When does it ask for the review?",
         'Right after the job is done and the customer is relieved, sent automatically by text and email with a one-tap link. You can adjust the timing and the wording so it sounds like you and not a form letter.'),
        ("Is automating review requests allowed?",
         'Asking every customer for an honest review is fine and encouraged. What is not allowed is filtering out unhappy customers or paying for reviews, and this does not do that. It simply asks everyone at the right moment and makes saying yes easy.'),
        ("What happens if I get a bad review?",
         'You find out immediately instead of weeks later, and the software helps you post a calm, professional reply. One measured response to a critical review, sitting under a wall of genuine positive ones, often reassures the next reader more than a spotless record would.'),
        ("How long until it is running?",
         'Setup is included with no separate fee. We connect your Google profile, set the timing and the message, and tie it to your completed jobs, so requests start going out in days. Start with a free audit and we will show you how your reputation stacks up against the plumbers you compete with.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for plumbers"),
        ("solution-reviews.html", "How the review system works"),
        ("crm-for-plumbers.html", "The CRM that triggers the ask when a job is done"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Turn finished jobs into <em>your next call</em>",
    "cta_sub": "Get a free audit of how your online reputation compares to the plumbers you compete with, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Websites & SEO for Plumbers =========================
{
    "slug": "websites-seo-for-plumbers",
    "trade_slug": "plumbers", "trade_plural": "plumbers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Plumbers",
    "title": "Websites & SEO for Plumbers | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Plumbers",
    "meta_desc": "A plumber website built for SEO ranks for emergency plumber near me and your city, and captures the caller directly instead of a lead-seller.",
    "service_schema_name": "Websites & SEO for Plumbers",
    "eyebrow": "For Plumbers",
    "h1_html": "Websites &amp; SEO <em>for Plumbers</em>",
    "answer_block": "A plumber website built for SEO ranks for the searches a homeowner types in a hurry, emergency plumber near me, water heater repair, 24 hour plumber, shows up in the map pack for the towns you cover, and captures the caller the moment they land, so the job belongs to you instead of a directory or a lead-seller renting your own calls back to you.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a plumber in your town and the top of the page is often a directory, a national booking middleman, or a pay-per-lead service, not the local shop. Those sites publish thousands of pages and have years of authority behind them, so when a homeowner searches, they land there first, fill out a form, and that lead gets sold, sometimes to three plumbers at once, sometimes back to you for a fee out of your own margin. Your site not ranking is not a vanity problem. It is the reason a call you should have gotten for free gets sold to you, or handed to whoever is on rotation that week.</p>'},
        {"h2_html": "Rank for what a homeowner types <em>in an emergency</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for a broad term, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you cover, and for the exact searches a homeowner makes when something breaks: emergency plumber near me, water heater repair in your city, burst pipe, sewer line, slab leak, 24 hour plumber. Pages built around the services you actually run and the areas you actually serve are what search engines, and panicked homeowners, reward with the click.</p>'},
        {"h2_html": "A visitor in a hurry should reach you in <em>one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone with water on the floor is on a phone, not a desktop, and they are not going to read three paragraphs. The site has to load fast, put a tap-to-call button and your service area in front of them immediately, and make an emergency obvious to act on, while still giving the routine visitor a simple way to request a quote or book a visit. A pretty site that buries the phone number is a wasted opportunity; a visitor should never leave without an easy way to reach you.</p>'},
        {"h2_html": "The calls are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a pay-per-lead service disappears the day you stop paying, and the lead was never really yours anyway. A website you own keeps ranking, keeps capturing calls, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you. The site plugs into the same CRM that follows up on every lead it captures and the AI receptionist that answers the calls it drives, so nothing it earns you slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A burst pipe finds <em>you</em>, not a directory",
        "body_html": 'A homeowner two towns over wakes up to a burst pipe and searches emergency plumber near me on their phone. Instead of a national directory that would sell the lead to three shops, they find your site ranking for that town, with a page about emergency and burst-pipe work and a tap-to-call button right at the top. They call you directly, you answer, and the job is yours. You paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big directories?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the emergency and service searches a national directory has no reason to target well, which is exactly where a local plumber can win.'),
        ("How is this different from paying for leads?",
         'A pay-per-lead service rents you a call that it also sells to your competitors, and it stops the day you stop paying. A website you own captures calls that are yours alone and keeps working long after it is built, without a per-lead fee coming out of every job.'),
        ("Do I need to rank for every town I serve?",
         'You rank for the ones that matter most first. We build pages for your core service areas and the highest-intent searches, then expand, rather than spreading thin across a whole metro at once.'),
        ("Most of my calls are emergencies. Does a website even help?",
         'Especially then. An emergency search happens on a phone in the moment something breaks, and the plumber who shows up in the map pack with a tap-to-call button and real reviews gets the call. A site built for that moment is exactly what captures it.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for plumbers"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-plumbers.html", "Staying visible in your service area beyond your site"),
        ("crm-for-plumbers.html", "Where every captured lead lands and gets followed up"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your calls, whether you work with us or not. No credit card, never a call center.",
},
# =========================== Marketing for Plumbers ===========================
{
    "slug": "marketing-for-plumbers",
    "trade_slug": "plumbers", "trade_plural": "plumbers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Plumbers",
    "title": "Marketing for Plumbers | Top Shelf Business Solutions",
    "og_title": "Marketing for Plumbers",
    "meta_desc": "Marketing for plumbers keeps your Google Business Profile active and your name first in the map pack, so you catch local demand the moment a pipe breaks.",
    "service_schema_name": "Marketing for Plumbers",
    "eyebrow": "For Plumbers",
    "h1_html": "Marketing <em>for Plumbers</em>",
    "answer_block": "Marketing for plumbers keeps you visible where local demand actually shows up, your Google Business Profile and the map pack, so when a homeowner nearby searches for a plumber the moment something breaks, your name is the active, well-reviewed one they call instead of the shop that let its profile go stale.",
    "sections": [
        {"h2_html": "Plumbing demand is <em>local and sudden</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody shops around for a plumber for weeks. Demand appears the instant a water heater dies or a drain backs up, and it is intensely local, because a homeowner wants someone who can be at their door today, not across the metro. That means the whole game is being visible and trusted in your service area at the exact moment someone nearby needs you, not running clever ads to people who do not have a plumbing problem yet. Get found first in that moment and the job is usually yours.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for a plumber near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and above the ads. A profile that sits untouched for months looks abandoned next to one with recent photos of real jobs, current hours, and a steady stream of reviews. Keeping it active, complete, and honest is a quiet advertisement running in the exact spot a homeowner looks when a pipe breaks.</p>'},
        {"h2_html": "Show up in the <em>towns you actually cover</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and it sends you calls from thirty minutes outside your range. Focusing on the specific towns and neighborhoods you serve, with a profile, photos, and content built around those areas, is what puts you in the map pack where you can actually take the work. It is a tighter, cheaper target than a citywide spend, and it is the one that turns into jobs you can reach in time.</p>'},
        {"h2_html": "Stay ready for the season, and stay in front of past customers",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Plumbing demand swings with the calendar, frozen and burst pipes in the first freeze, water heaters worn out by winter, sump pumps before the spring rain, and being visible right before each wave beats scrambling once it hits. A steady local presence, seasonal posts, job photos, the occasional tip, keeps you top of mind for the emergency and reminds past customers you are still the one to call. This is the public-facing side of the business; the private follow-up to people already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The first freeze, and you are <em>already at the top</em>",
        "body_html": 'A cold snap hits and half the town wakes up to frozen or burst pipes on the same morning. Because your Google profile has been kept active all year, with recent job photos, current hours, and a steady flow of reviews, you sit at the top of the map pack when everyone searches at once. The homeowners who need a plumber that hour call the names they can see and trust first, and yours is right there. The shop that let its profile go quiet is nowhere on the map. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with job photos, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current whenever someone searches for a plumber near them.'),
        ("What does focusing on my service area actually mean?",
         'It means building your profile and content around the specific towns and neighborhoods you can reach quickly, instead of spreading a budget across a whole metro. That is what gets you into the map pack where the local, high-intent calls are.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with people already in your database. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at homeowners who are not your customer yet but need to find and trust you the moment something breaks.'),
        ("Can you help me get ahead of seasonal demand?",
         'Yes. We time your visibility to the waves that matter, the first freeze, water heater season, sump pumps before spring rain, so you are already in front of people before the rush instead of scrambling once the calls start.'),
        ("How long before I see it working?",
         'A neglected profile can climb in the map pack within weeks once it is active and complete, and it compounds from there as reviews and content build. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for plumbers"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-plumbers.html", "The reviews that feed the same Google profile"),
        ("websites-seo-for-plumbers.html", "The website that captures the demand this drives"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the plumber they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# =========================== Automation for Plumbers ===========================
{
    "slug": "automation-for-plumbers",
    "trade_slug": "plumbers", "trade_plural": "plumbers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for Plumbers",
    "title": "Automation for Plumbers | Top Shelf Business Solutions",
    "og_title": "Automation for Plumbers",
    "meta_desc": "Automation for plumbers sends on-my-way texts, appointment reminders, and job follow-ups for you, so dispatch runs smooth and nothing gets missed.",
    "service_schema_name": "Automation for Plumbers",
    "eyebrow": "For Plumbers",
    "h1_html": "Automation <em>for Plumbers</em>",
    "answer_block": "Automation for plumbers handles the texts and reminders around every job for you, the on-my-way message to a customer waiting on a leak, the appointment reminder that prevents a wasted trip, the follow-up and review request after the work is done, so dispatch runs smooth and nothing depends on you remembering between service calls.",
    "sections": [
        {"h2_html": "A customer waiting on water wants to know <em>when you will get there</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone has a leak or no water, the wait for the plumber is the worst part, and a customer left wondering whether anyone is actually coming is the one who calls another shop to be safe or leaves a frustrated review afterward. Keeping every customer updated, confirmed for tomorrow, on the way now, running twenty minutes behind, is exactly the kind of thing that slips when you are elbow-deep in a job and the schedule is moving. The work can be perfect and the customer still unhappy simply because nobody told them what was happening.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Automation handles those messages for you. A confirmation the day before, an on-my-way text with a realistic arrival window when the tech heads out, and a note if the schedule slips, all sent automatically, so the customer feels looked after and you are not the one stopping to type it.</p>'},
        {"h2_html": "Reminders that keep your <em>schedule full and on time</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A plumber driving to a no-show is an hour and a tank of gas you never get back, and an empty slot a real job could have filled. Automatic confirmations and reminders by text before every scheduled visit keep no-shows down and give a customer an easy way to reschedule instead of just not being home. For an owner running a couple of trucks, that is a fuller, tighter schedule without anyone working the phones to confirm each stop.</p>'},
        {"h2_html": "The follow-up after the job <em>runs itself</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The job is not really done when you drive away. A quick check that everything is holding, an automatic review request while the customer is still relieved, and a maintenance reminder scheduled for the right number of months out all matter, and all are easy to forget once you are onto the next call. Automation fires each one on time, so a finished job turns into a review, a repeat customer, and the next visit without you keeping a mental list.</p>'},
        {"h2_html": "Cold quotes and lapsed customers <em>come back on schedule</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A quote that went quiet and a customer you have not seen in two years are not dead, they are just waiting for a reason to call. A scheduled check-in on an open estimate, and a seasonal nudge to a customer who is overdue, bring that work back around automatically instead of falling out of your memory. It runs against the same database as your CRM, so nothing here duplicates a customer or a note, and every automated touch is logged where you can see it.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A customer who never has to <em>wonder if you are coming</em>",
        "body_html": 'A homeowner books a water heater replacement for Tuesday morning. The day before, they get an automatic confirmation. Tuesday morning, when your tech leaves the shop, they get an on-my-way text with an arrival window. That afternoon, once the job is done, they get a thank-you with a one-tap review link, and the system quietly schedules a reminder to check the unit in a year. You never sat down to send any of it, and the customer felt taken care of from booking to follow-up. Illustrative example, not a client.'},
    "faqs": [
        ("What messages does it actually send?",
         'The routine ones around a job: an appointment confirmation, an on-my-way text with an arrival window when the tech heads out, a note if the schedule slips, and a follow-up with a review request after the work is done. You approve the wording so it all sounds like you.'),
        ("Does this replace me or my dispatcher talking to customers?",
         'No. It handles the predictable, repetitive texts so nobody has to stop and type them, while you and your team still make every real call and step in personally for anything that needs a conversation.'),
        ("Can it help with no-shows and wasted trips?",
         'Yes. Automatic confirmations and reminders before each visit keep no-shows down and give the customer an easy way to reschedule, so your techs spend less time driving to empty houses.'),
        ("Will it send maintenance and follow-up reminders on its own?",
         'Yes. After a job it can schedule a check that everything is holding and a maintenance reminder for the right number of months out, and it can nudge cold quotes and lapsed customers on a schedule you set, all logged against the customer in your CRM.'),
        ("How long does setup take?",
         'Setup is included with no separate fee. We build the reminder, on-my-way, and follow-up sequences around how you already run your day, so it is working within days. Start with a free audit and we will show you what is currently slipping between your calls, your trucks, and your calendar.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for plumbers"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-plumbers.html", "The database every workflow runs against"),
        ("online-booking-for-plumbers.html", "How the visits these remind about get booked"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a customer <em>wonder if you are coming</em>",
    "cta_sub": "Get a free audit of what is currently slipping between your calls, your trucks, and your follow-ups, whether you work with us or not. No credit card, never a call center.",
},
]
