"""Per-page content specs for the SEO corpus (plan §5), mortgage brokers batch. Same contract
as scripts/corpus_specs.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, mortgage-broker-specific substance that clears the uniqueness gate.
Never templated find-and-replace, never the plumber content reworded.

Real Estate hub. Four service angles are here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client."
per the honesty rule; if the generator also appends that line, dedupe there. Compliance: this
copy never promises a rate, an APR, an approval, or a savings figure, because the tools capture,
qualify, and follow up while the broker makes every licensed decision.
"""

SPECS = [
# ======================= AI Receptionist for Mortgage Brokers =======================
{
    "slug": "ai-receptionist-for-mortgage-brokers", "demo": True,
    "trade_slug": "mortgage_brokers", "trade_plural": "mortgage brokers",
    "hub_name": "Real Estate", "hub_slug": "industry-real-estate.html",
    "breadcrumb_leaf": "AI Receptionist for Mortgage Brokers",
    "title": "AI Receptionist for Mortgage Brokers | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Mortgage Brokers",
    "meta_desc": "A mortgage broker answering service answers every call day or night, qualifies the lead, and books the consultation, so a missed call stops being a lost loan.",
    "service_schema_name": "AI Receptionist for Mortgage Brokers",
    "eyebrow": "For Mortgage Brokers",
    "h1_html": "AI Receptionist <em>for Mortgage Brokers</em>",
    "answer_block": "A mortgage broker answering service answers every call the moment it rings, day or night, finds out whether it is a purchase, a refinance, or a rate shopper, qualifies the lead, and books the consultation on your calendar. It never quotes a rate or promises an approval, and every lead belongs to you.",
    "sections": [
        {"h2_html": "The call you miss is the loan that closes with another <em>broker</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Rate shoppers and pre-approval seekers rarely call just one broker. They grab a few numbers or fill out a form, call two or three, and go with whoever picks up first and sounds like they know the process. A mortgage is one of the largest decisions a person ever makes, but the first move is often impulsive: a buyer who just got outbid, a homeowner who saw a headline about rates and wants to know what it means for them. If that call rolls to voicemail, they do not sit and wait. They call the next broker on the list, and the loan, along with the commission on it, closes with someone else.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">You cannot pick up every time. You are in an application with a client, on the phone with an underwriter, sitting at a closing, or home with your family when a portal lead comes in at night. An answering service that actually understands mortgages picks up on the first ring, stays professional, finds out what the caller needs, and captures the lead instead of letting it ring out to nobody.</p>'},
        {"h2_html": "Built around how mortgage leads <em>actually arrive</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your leads do not keep banker\'s hours. Someone browsing homes fills out a rate form at 10pm. A buyer who just went under contract needs a pre-approval letter over the weekend. A past client reads something about rates and calls after dinner to ask about a refinance. The highest-intent leads often land exactly when your office is closed, and a voicemail box cannot tell a serious buyer from someone idly curious or route an urgent letter to you.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24/7, including the nights and weekends when online rate forms and portal leads actually come in.</li><li>Qualifies the way you would: purchase or refinance, buying now or just looking, the timeline to close, and whether they already have a pre-approval or an agent.</li><li>Captures the details and books the consultation on your calendar, then texts you the leads that cannot wait so you decide whether to call back tonight.</li><li>Treats a referral from one of your agents or a returning past client differently from a cold rate shopper, so the people who already trust you never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is one <em>funded loan</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. The commission on a single funded loan you would otherwise have lost to voicemail is worth far more than the service costs for a long stretch, and unlike a small repair call, one missed mortgage lead can be a whole loan gone. Everything it captures after that first save is on top. The point is simple: stop handing your best leads to the broker who just happened to answer faster.</p>'},
        {"h2_html": "You own the number, the leads, and the <em>pipeline</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every detail, and every lead is yours and exportable any time, so the pipeline you build is an asset you keep instead of something you rent back month to month. It is careful where it has to be: it captures and qualifies, but it never quotes a rate, never states terms, and never suggests anyone is approved. It hands each lead to the same CRM that works the long stretch from first call to closing, so nothing goes cold while a loan makes its way through.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A 10pm rate-form lead, qualified while you <em>sleep</em>",
        "body_html": 'It is 10pm and someone browsing homes online fills out a rate form on a listing. Two brokers get the lead. One lets it go to voicemail. Yours answers, stays professional, learns the buyer is pre-approved elsewhere but frustrated with the service, gets the price range and the timeline, and books a consultation for the next morning without ever quoting a rate. You wake up to the appointment already on your calendar, with the borrower\'s situation and number attached, instead of hearing they went with whoever called back first. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every lead that comes through it belong to you and go with you if you ever switch providers.'),
        ("Can it qualify a lead the way I would?",
         'Yes. It asks what you would ask: purchase or refinance, actively shopping or just looking, the timeline, the price range, and whether they already have a pre-approval or an agent. You set the questions, and the qualified lead lands on your calendar or in your inbox.'),
        ("Will it actually book the consultation on my calendar?",
         'Yes. It books consultations on your real availability and sends you the details right away. For a lead that needs you now, a buyer under contract who needs a letter this weekend, it can flag it to your phone at once so you decide whether to call back tonight.'),
        ("Will it quote rates or promise an approval?",
         'No, and that is by design. It captures the lead, qualifies it, and books the meeting, but it never quotes a rate, states terms, or suggests anyone is approved. Anything that needs a licensed conversation waits for you.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We configure your qualifying questions, your calendar, and your rules for what needs you right away, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.')],
    "related": [
        ("industry-real-estate.html", "Everything Top Shelf does for mortgage brokers"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-mortgage-brokers.html", "The CRM that nurtures every lead you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing loans to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and after-hours leads your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ============================= CRM for Mortgage Brokers =============================
{
    "slug": "crm-for-mortgage-brokers",
    "trade_slug": "mortgage_brokers", "trade_plural": "mortgage brokers",
    "hub_name": "Real Estate", "hub_slug": "industry-real-estate.html",
    "breadcrumb_leaf": "CRM for Mortgage Brokers",
    "title": "CRM for Mortgage Brokers | Top Shelf Business Solutions",
    "og_title": "CRM for Mortgage Brokers",
    "meta_desc": "A mortgage CRM works your long loan pipeline, nurtures past clients for their next refinance, and keeps referral agents warm and sending you buyers.",
    "service_schema_name": "CRM for Mortgage Brokers",
    "eyebrow": "For Mortgage Brokers",
    "h1_html": "CRM <em>for Mortgage Brokers</em>",
    "answer_block": "A mortgage CRM keeps every lead, past client, and open loan in one place and works the long pipeline for you, from first call to closing and beyond, so the pre-approved buyer still house hunting, the client due for a refinance, and the agents who refer you all stay warm instead of drifting to the broker who kept in touch.",
    "sections": [
        {"h2_html": "A loan is a long pipeline, not a single <em>call</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A mortgage is rarely won or lost in one conversation. Weeks pass between the first call and the closing table, and more time still while a pre-approved buyer keeps getting outbid on houses. Somewhere in that stretch a lead goes quiet, forgets which broker they spoke to, or gets courted by someone who followed up more often. Most brokers do not have a lead problem so much as a follow-up problem: the leads are there, but there is no time between applications and closings to work every one of them by hand.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every lead and every open loan in front of you and moving. It reminds you who is waiting on a letter, who went quiet after the first conversation, and who has been pre-approved for months without an accepted offer, and it sends the check-ins on a schedule you set so nobody drifts off while you are heads-down on a file.</p>'},
        {"h2_html": "Your past clients are your next <em>refinances</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The client whose loan you just closed is the cheapest business you will ever earn again. They already trusted you with their pay stubs and their Social Security number, and over the years they will refinance, buy again, and send family your way, if they still have your name when the time comes. Most people lose the card and call whoever comes up first. A CRM makes sure the broker they remember is you.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every lead, client, and note lives in one place instead of a spreadsheet, a crowded inbox, and your memory.</li><li>Past clients get a light, steady touch, so you are the name they think of when a refinance or a move finally makes sense for them.</li><li>You can see who has gone quiet and reach the right person with the right message at the right time, without ever promising a rate or a result.</li></ul>'},
        {"h2_html": "Referral agents are the <em>engine</em>, if you stay in front of them",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The steadiest pipeline a broker can build is a handful of real estate agents who send every buyer who needs financing. Those relationships are worth protecting, and they fade fast when you go quiet, because an agent sends clients to the broker who is top of mind and easy to work with this month, not the one who did a good job a year ago. A CRM keeps your referral partners warm: a note when their client clears a milestone, a check-in between deals, the steady contact that keeps their next buyer coming to you instead of the broker who took them to lunch last week.</p>'},
        {"h2_html": "You own the database, and it works with the rest of the <em>system</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every lead, client, and note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the answering service, so a lead it captures at 10pm lands in your database and starts getting followed up on, and to online booking, so a consultation is logged against the right person with their history already attached. It tracks the relationship and the pipeline, not the loan file itself, so it sits alongside the loan origination software you already use without getting in the way.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The refinance that comes back to <em>you</em>",
        "body_html": 'You closed a purchase loan for a client a couple of years ago and never really spoke again. Left alone, when a refinance finally makes sense for them they would call whoever they saw first. Instead the CRM has kept a light touch going the whole time, a check-in here, a useful note there, all sounding like you, so your name is the one still in their phone. When they are ready they call you back without shopping around, and the loan you earned once becomes the loan you earn again. You never sat down to chase it. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing clients and past loans?",
         'Yes. Your current leads, past clients, and contact history come in and live in one place, and everything stays yours and exportable. The point is to make the book of business you already have actually work for you.'),
        ("Will it really follow up through a long loan pipeline?",
         'Yes, on the schedule you approve. It keeps leads moving from the first call toward closing, reminds you who is waiting on you, and nudges the pre-approved buyer who has not found a house yet, all sent for you so nobody goes cold while you are on another file.'),
        ("Can it keep me in front of past clients for their next refinance?",
         'Yes. It keeps a light, steady touch on past clients so you are the one they think of when the time is right for them, without you tracking a single date. It stays on the right side of compliance and never promises a rate or a result.'),
        ("Can it help me manage my referral agents?",
         'Yes. You can keep your real estate partners in their own track, with reminders to check in between deals and updates as their clients\' loans move toward closing, so the relationships that drive your pipeline stay warm.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your contacts, build your follow-up tracks for leads, past clients, and referral partners, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where business is slipping away today.')],
    "related": [
        ("industry-real-estate.html", "Everything Top Shelf does for mortgage brokers"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-mortgage-brokers.html", "The answering service that feeds it every lead"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting past clients and referral agents <em>go cold</em>",
    "cta_sub": "Get a free audit of how much repeat and referral business is going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================== Marketing for Mortgage Brokers ==========================
{
    "slug": "marketing-for-mortgage-brokers",
    "trade_slug": "mortgage_brokers", "trade_plural": "mortgage brokers",
    "hub_name": "Real Estate", "hub_slug": "industry-real-estate.html",
    "breadcrumb_leaf": "Marketing for Mortgage Brokers",
    "title": "Marketing for Mortgage Brokers | Top Shelf Business Solutions",
    "og_title": "Marketing for Mortgage Brokers",
    "meta_desc": "Mortgage broker marketing keeps your Google profile active and your reviews strong, so borrowers and referral agents find and trust you before they ever call.",
    "service_schema_name": "Marketing for Mortgage Brokers",
    "eyebrow": "For Mortgage Brokers",
    "h1_html": "Marketing <em>for Mortgage Brokers</em>",
    "answer_block": "Mortgage broker marketing keeps you visible and trusted where borrowers and referral agents look before they ever call, your Google profile, your reviews, and a steady public presence, so when someone is ready to hand over their financial life or an agent needs a broker to recommend, your name is the one they already know.",
    "sections": [
        {"h2_html": "A mortgage is a trust decision, made before they <em>call</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody hands their pay stubs, tax returns, and Social Security number to a stranger on a whim. By the time a borrower picks up the phone, they have usually already decided who they trust, and they made that call from what they could see: your reviews, your presence online, whether you look established or invisible. Marketing here is not clever ads aimed at people with no reason to move. It is being the visible, credible broker in your market, so that when someone is finally ready, and when an agent needs a name to give a buyer, you are the obvious choice.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">That is also why someone choosing a broker rarely calls just one. They reach out to the two or three who look most established and best reviewed, and the one who already reads as trustworthy in that moment tends to win before a real conversation starts. Marketing is simply making sure yours is one of those names, in the places a borrower and a referring agent actually look, at the moment they look.</p>'},
        {"h2_html": "Reviews are the trust a borrower needs to <em>hand over their financial life</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">For most people a mortgage is the biggest financial decision of their life, and they are about to share their most private numbers to get it done. Recent, genuine reviews are the fastest way for a nervous first-time buyer or a busy homeowner to believe you will treat them fairly and get them to the closing table. A broker with a wall of current reviews wins that person over a thin or stale profile every time. Reviews matter to your referral agents too, because an agent\'s own reputation rides on who they recommend, so they send buyers to the broker whose reviews back up the introduction.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Recent reviews with genuine replies, so your profile reads as attended to rather than abandoned.</li><li>Accurate contact information, service area, and the loan types you handle, so a borrower in a hurry never hits something wrong or missing.</li><li>Current posts and information, so you read as a working broker who pays attention, not a listing set up once and forgotten.</li><li>The questions first-time buyers ask, answered where they can see them, so a searcher gets what they need without leaving to look elsewhere.</li></ul>'},
        {"h2_html": "Stay in front of the agents and clients who <em>send you business</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The public side of staying top of mind is different from the private follow-up your CRM handles. A steady presence, market updates a borrower can actually use, plain answers to the questions first-time buyers ask, the occasional post that shows you are active and paying attention, keeps you visible to referral agents and past clients out in the open, where their friends and colleagues see it too. An agent scrolling for a broker to recommend, or a past client whose coworker just asked who to call, finds you already there. All of it stays compliant: helpful and visible, never a promise about rates or approvals.</p>'},
        {"h2_html": "Show up where borrowers in your market <em>search</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for a mortgage broker near them, or an agent looks you up before sending a client, your Google Business Profile is often the first thing they find, above your website. A profile that sits untouched for months looks abandoned next to one with current information, real reviews, and signs of life. Keeping it active, complete, and accurate, with your service area and the loan types you handle clear, is a quiet advertisement running in the exact spot people look when they are deciding who to trust with the largest loan they will ever take.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The agent picks the broker they can <em>see</em>",
        "body_html": 'A real estate agent has a first-time buyer who needs financing and two brokers in mind. One has a few old reviews and a profile that has not changed in a year. The other, you, has a steady stream of recent reviews, current information, and an active presence that shows you are engaged and easy to work with. The agent sends the buyer to you, because their own reputation rides on the referral and you are the safer bet. You were not in the room, but your visibility made the introduction for you. Illustrative example, not a client.'},
    "faqs": [
        ("Do you manage my Google Business Profile and reviews for me?",
         'Yes. We keep your profile active and accurate, with your service area, the loan types you handle, and current information, and we help you gather and reply to reviews on a regular basis, so you look current and trustworthy whenever someone looks you up.'),
        ("How does this help me with referral agents?",
         'Agents recommend the broker who makes them look good and is easy to find. A strong public presence and a wall of recent reviews reassure an agent that you will take care of their client, so you become the name they hand out.'),
        ("How is this different from the CRM follow-up?",
         'The CRM works privately with people already in your database, your leads, past clients, and partners. Marketing is the public-facing side, your profile, reviews, and visibility, aimed at borrowers and agents who do not know you yet but need to find and trust you.'),
        ("Will everything stay compliant?",
         'Yes. We keep your public presence helpful and honest, information, reviews, and visibility, and we never post promises about specific rates, terms, or approvals. The goal is trust and reach, kept inside the lines your licensing requires.'),
        ("How long before I see it working?",
         'A neglected profile can climb once it is active and complete, and reviews compound from there. Setup is included, and a free audit will show you what your current presence looks like to a borrower or an agent searching for you today.')],
    "related": [
        ("industry-real-estate.html", "Everything Top Shelf does for mortgage brokers"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-mortgage-brokers.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the broker they <em>already trust</em>",
    "cta_sub": "Get a free audit of how visible and well-reviewed you are compared to the brokers you compete with, whether you work with us or not. No credit card, never a call center.",
},
# ======================== Websites & SEO for Mortgage Brokers ========================
{
    "slug": "websites-seo-for-mortgage-brokers",
    "trade_slug": "mortgage_brokers", "trade_plural": "mortgage brokers",
    "hub_name": "Real Estate", "hub_slug": "industry-real-estate.html",
    "breadcrumb_leaf": "Websites & SEO for Mortgage Brokers",
    "title": "Websites & SEO for Mortgage Brokers | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Mortgage Brokers",
    "meta_desc": "A mortgage broker website built for SEO ranks for a broker in your city, refinance, and first-time buyer help and captures the lead instead of lead-sellers.",
    "service_schema_name": "Websites & SEO for Mortgage Brokers",
    "eyebrow": "For Mortgage Brokers",
    "h1_html": "Websites &amp; SEO <em>for Mortgage Brokers</em>",
    "answer_block": "A mortgage broker website built for SEO ranks for the searches borrowers actually make, a mortgage broker in your city, first-time buyer and refinance help, and captures the lead directly instead of the national lenders and lead-sellers renting your own borrowers back to you. It loads fast and earns the trust a financial decision needs.",
    "sections": [
        {"h2_html": "The lead-sellers are renting you back your own <em>borrowers</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a mortgage broker in your city and the top of the page is usually a national lender, a rate-comparison portal, or a pay-per-lead site, not the local broker down the road. Those sites publish thousands of pages and carry years of authority, so a borrower lands there first, fills out a form, and that lead gets sold, sometimes to several brokers at once, sometimes back to you for a fee out of your own commission. Your site not ranking is not a vanity problem. It is the reason a borrower who should have found you directly turns into a lead you have to buy.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">It compounds, too. Every month you are not ranking, that portal earns more authority on the searches in your own city, collects more reviews, and the gap gets harder to close. The brokers who own their search presence started building it before they needed it, which is why a site of your own is worth starting now rather than after the next slow stretch.</p>'},
        {"h2_html": "Rank for what a borrower actually <em>types</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national lender this year for the broadest, most expensive terms, and you do not need to. You can rank for your own name, for the specific city and metro you serve, and for the searches real borrowers make when they are getting started: a mortgage broker near me, first-time home buyer help in your area, refinance questions, and the FHA, VA, and jumbo loans you handle where you lend. Pages built around the loan types you actually offer and the places you actually work are what search engines, and borrowers who are ready to move, reward with the click.</p>'},
        {"h2_html": "A fast, credible site earns the <em>financial-life handoff</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone about to share their income, their debts, and their Social Security number judges you by your website before they ever call. A slow, dated, or thrown-together site quietly tells them to be careful, and they move on to one that looks like a real business. A site that loads fast on a phone, says clearly who you are and where you are licensed, makes your reviews easy to find, and gives one obvious way to reach you is what turns a curious visitor into a booked consultation. It has to work for the referred borrower too, because the first thing most people do after an agent gives them your name is look you up.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Loads fast on a phone, because a borrower checking you out on mobile will not wait for a heavy page.</li><li>One obvious way to reach you visible the second the page opens, with no scrolling to find it.</li><li>Your NMLS ID, licensing, and real reviews easy to find, so a stranger can decide in seconds that you are legitimate.</li><li>A short, simple way to request a consultation for the borrower who would rather type than call.</li></ul>'},
        {"h2_html": "The leads are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a pay-per-lead service disappears the day you stop paying, and the lead was shared with your competitors anyway. A website you own keeps ranking, keeps capturing borrowers, and keeps compounding in value for as long as it exists, registered to you, not a platform that can drop you or raise the price. The site plugs into the same CRM that nurtures every lead it captures and the answering service that picks up the calls it drives, so nothing it earns you slips away while a loan works its way to closing.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A refinance search finds <em>you</em>, not a portal",
        "body_html": 'A homeowner in your city starts wondering whether a refinance makes sense and searches for help online. Instead of a national portal that would sell that lead to three brokers at once, they find your site ranking for your city, with a clear page about refinancing and one obvious way to reach you. They contact you directly, you have the conversation, and the loan is yours to earn. You paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big lenders and portals?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific city and metro, and the loan-type and getting-started searches a national portal has no reason to target well, which is exactly where a local broker can win.'),
        ("How is this different from paying for portal leads?",
         'A pay-per-lead service rents you a borrower it also sells to your competitors, and it stops the day you stop paying. A website you own captures leads that are yours alone and keeps working long after it is built, with no per-lead fee coming out of every loan.'),
        ("Do I need to rank for every loan type?",
         'No. You start with the ones that matter most, your core market and the highest-intent searches, then expand, rather than spreading thin across every product and every town at once.'),
        ("Most of my business is referrals. Does a website even help?",
         'Yes, maybe more than you would think. A referred borrower almost always looks you up before they call, and a fast, credible site with real reviews is what closes the gap between the introduction and the booked appointment. A weak site can lose a referral an agent already handed you.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks, while broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-real-estate.html", "Everything Top Shelf does for mortgage brokers"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-mortgage-brokers.html", "Staying visible to borrowers and agents beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results, don't <em>rent your leads back</em>",
    "cta_sub": "Get a free audit of how your website and local search compare to the lenders and lead-sellers taking your borrowers, whether you work with us or not. No credit card, never a call center.",
},
]
