"""Per-page content specs for the SEO corpus (plan §5), House Cleaning Companies batch.
generate_corpus.py imports SPECS from a specs module; each dict is one page's UNIQUE,
hand-written, trade-specific content. The generator owns the mechanics (shell, schema,
events, interlinks, keyword placement); the spec owns the substance that clears the
uniqueness gate. Never templated find-and-replace, never the plumber or garage-door
content reworded.

House cleaning runs on RECURRING revenue: a weekly, biweekly, or monthly client kept for
a year or two is worth far more than any single clean, so the whole business turns on
winning the first booking, converting a one-time deep clean or move-out into a recurring
plan, and keeping recurring clients from quietly churning. The urgency here is not a
middle-of-the-night emergency; it is the quote inquiry that goes unanswered while crews
are inside homes, the last-minute cancellation that strands a paid crew with an empty
slot, and the recurring client who stops rebooking without a word. Every dict below is
written to that world.

Home Services hub. All seven service angles are in one file (the ai-receptionist dict
carries "demo": True). Each example body ends with the literal "Illustrative example, not
a client." per the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ================== AI Receptionist for House Cleaning Companies ==================
{
    "slug": "ai-receptionist-for-house-cleaning-companies", "demo": True,
    "trade_slug": "house-cleaning-companies", "trade_plural": "house cleaning companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for House Cleaning Companies",
    "title": "AI Receptionist for House Cleaning Companies | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for House Cleaning Companies",
    "meta_desc": "An AI receptionist for house cleaning companies answers every quote call while your crews are inside homes, gathers the details, and books the clean on your calendar.",
    "service_schema_name": "AI Receptionist for House Cleaning Companies",
    "eyebrow": "For House Cleaning Companies",
    "h1_html": "AI Receptionist <em>for House Cleaning Companies</em>",
    "answer_block": "An AI receptionist for house cleaning companies answers every call the moment it comes in, even while your crews are inside homes with their hands full, gathers what a quote needs, and books the first clean or the recurring slot on your calendar. You keep your own number, and every caller stays yours.",
    "sections": [
        {"h2_html": "The quote call you miss is the recurring client the <em>next maid service signs</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner who wants a cleaner is not going to leave a voicemail and wait. They found three maid services on Google and they are calling down the list until someone picks up and gives them a real answer. But your day is spent inside homes, running a crew, hands on a vacuum or a mop, so the phone rings through to voicemail and the caller is already dialing the next company before yours even finishes ringing. And in cleaning, the call you just lost is rarely a single job. A new client who wanted weekly or biweekly service is weeks, months, sometimes years of cleans, and all of it just went to the company that answered.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist answers on the first ring, whether you are mid-clean or the call comes in on a weekend evening while someone is finally sitting down to book a cleaner. It gathers what you need to quote, the size of the home, how often they want it, and what kind of clean, and either books the visit or hands you a ready-to-price lead. The recurring client is captured instead of lost to the maid service down the road.</p>'},
        {"h2_html": "Built around how <em>cleaning calls actually come in</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your phone does not ring while you are sitting at a desk. It rings while you are inside a home you are cleaning, driving between stops, or off the clock in the evening when a busy family finally has a minute to line up a cleaner. A voicemail box cannot gather a quote, and a generic call center reading a script does not know a standard clean from a deep clean or a move-out.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers during the day while your crews are inside homes, and in the evenings and weekends when people actually sit down to book a cleaner.</li><li>Gathers what a real quote needs: home size, number of bedrooms and bathrooms, one-time or recurring, and whether it is a standard clean, a deep clean, a move-in or move-out, or post-construction.</li><li>Books the recurring slot or the first clean straight onto your calendar and texts you the details on the spot.</li><li>Handles a current client calling to reschedule, skip a week, or add the inside of the fridge differently from a brand-new prospect, so the people who already trust you never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one recurring client</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. A single weekly or biweekly client you would have lost to voicemail is not one clean, it is a standing spot on your schedule that pays week after week for as long as they stay with you, which is often years. One of those kept is usually worth more than the system costs for a long stretch, and everything it captures after that is on top. The point is to stop handing your best recurring clients to whichever company simply answered first.</p>'},
        {"h2_html": "You own the number, the calls, and the client list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on the number you already advertise, or a new one registered in your name, not ours. Every caller, every address, and every note about the home is yours and exportable any time, so the client list you are building is an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The AI receptionist is one piece of the Top Shelf platform, and it hands every call it captures to the same CRM that follows up, so a quote or a first-clean offer never slips.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A move-out clean with a Friday deadline, booked while you <em>work</em>",
        "body_html": 'A renter finds out on Monday that their lease ends Friday and they need a move-out clean to get the deposit back. They search for a cleaner and call the first few they find. Two go to voicemail. Yours answers, confirms the size of the place and the move-out deadline, quotes the deep clean it will take, and books your crew for Thursday morning while your team is inside another home and never touches a phone. You come off the job to the clean already on your calendar with the address, the square footage, and the deadline attached, instead of hearing about it after they hired someone else. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         "Yes. It can answer on the number you already advertise, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever switch providers."),
        ("Can it actually gather a quote and tell a one-time clean from recurring?",
         "Yes, that is the point. It asks what you would ask, the size of the home, how many bedrooms and bathrooms, how often they want service, and whether it is a standard clean, a deep clean, or a move-out, so a recurring client and a one-time job each come to you ready to schedule and price."),
        ("Will it book the clean on my calendar?",
         "Yes. It books the first clean or the recurring slot straight onto your real calendar based on the availability and service area you set, and texts you the details right away. You decide the rules, like how much notice you need and which days a crew is open in each area."),
        ("Is it going to sound like a robot to my clients?",
         "It answers naturally and professionally, and it is upfront instead of pretending to be a person. Someone deciding who to let into their home mostly wants to know a real company is handling it and a time is set, which beats a voicemail box every time. You can hear it handle a live call before you decide."),
        ("How fast can it be running?",
         "Setup is included with no separate onboarding fee. We configure your quote questions, your calendar, and your service area for you, so it is answering in days, not weeks. Start with a free audit and we will show you how many calls your current setup is missing.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for house cleaning companies"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-house-cleaning-companies.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing new clients to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many quote calls and recurring clients your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ========================= CRM for House Cleaning Companies =========================
{
    "slug": "crm-for-house-cleaning-companies",
    "trade_slug": "house-cleaning-companies", "trade_plural": "house cleaning companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for House Cleaning Companies",
    "title": "CRM for House Cleaning Companies | Top Shelf Business Solutions",
    "og_title": "CRM for House Cleaning Companies",
    "meta_desc": "A CRM for house cleaning companies follows up to turn one-time cleans into recurring plans and catches recurring clients before they quietly churn.",
    "service_schema_name": "CRM for House Cleaning Companies",
    "eyebrow": "For House Cleaning Companies",
    "h1_html": "CRM <em>for House Cleaning Companies</em>",
    "answer_block": "A CRM for house cleaning companies keeps every client, quote, and one-time clean in one place and follows up for you, so the move-out clean you did once becomes a recurring plan and the weekly client who went quiet gets caught before they churn. Your client list quietly becomes recurring revenue.",
    "sections": [
        {"h2_html": "The one-time cleans you already did are the recurring clients you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most cleaning companies do not have a lead problem. They have a follow-up problem. You do a great deep clean or a move-out, the client is thrilled, and then nobody ever asks them to go on a schedule. A one-time clean is a one-time payment unless someone follows up and offers weekly or biweekly service while the memory of a spotless house is still fresh. That is the single most valuable conversation in the business, and it is the one there is never time for between crews and quotes.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every one-time clean and open quote in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not anyone at the office remembers. The client who loved the deep clean gets asked to make it regular, the quote someone is sitting on gets a nudge, and the recurring plan closes instead of the job ending at one visit.</p>'},
        {"h2_html": "Every recurring client is worth more the <em>longer they stay</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The money in cleaning is not in any single job, it is in the client who stays on the schedule for years. That client already trusts your crew with a key and an alarm code, already has a card on file, and is the cheapest revenue you will ever have. But you cannot hold every home, every preference, and every recurring date in your head, so details get lost and clients drift when the service stops feeling personal.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every client, address, gate or alarm code, product preference, pet note, and recurring schedule lives in one place instead of scattered across memory and a stack of paper.</li><li>Recurring cleans stay on schedule, and clients who are due, or overdue, surface automatically instead of slipping off the calendar.</li><li>You can see who has not booked in a while and reach the right client with the right offer before they drift to another service.</li></ul>'},
        {"h2_html": "The recurring clients slipping away are still <em>yours to keep</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A recurring client rarely calls to quit. They just skip a week, then another, and quietly stop rebooking, and you do not notice until the route has a hole in it. That silent churn is the most expensive thing in a cleaning business, because replacing a long-standing client costs far more than keeping one. A CRM flags the client who has gone quiet or pushed off two cleans in a row, so you can reach out with a check-in or a small win-back offer while there is still a client to keep, instead of finding the gap after they are gone.</p>'},
        {"h2_html": "You own the list, and it works with the rest of the system",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every client and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the AI receptionist, so a call it answers lands in your database and gets followed up on automatically, and to online booking, so a recurring slot or a one-time clean is logged against the right client with their full history and preferences already attached. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The deep clean that <em>becomes a standing Thursday</em>",
        "body_html": 'A new client books a one-time deep clean before hosting family for the holidays, and your crew leaves the house spotless. Normally that is the end of it. Instead the CRM sends a warm check-in two days later, while the house still feels perfect, asking if they would like to keep it that way every other week, and it sounds like you wrote it. The client says yes, and a one-time job turns into a standing biweekly Thursday slot that pays for years. You never sat down to make the ask. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing clients and past cleans?",
         "Yes. Your current clients, one-time cleans, recurring schedules, and notes come in and live in one place, and everything stays yours and exportable. The point is to make the client list you already have actually work for you."),
        ("Will it really follow up to turn one-time cleans into recurring?",
         "Yes, on the schedule you approve. A client who booked a deep clean or a move-out gets a friendly ask to go weekly or biweekly while the house still feels spotless, and an open quote gets a nudge, all sent for you. You can jump in and message anyone directly any time."),
        ("Can it catch recurring clients before they cancel?",
         "Yes. It flags a client who has gone quiet or pushed off two cleans in a row so you can reach out with a check-in or a win-back offer before they drift, instead of finding the hole in your route after they are already gone."),
        ("How is this different from a spreadsheet of clients?",
         "A spreadsheet does not follow up, does not remember who is due, and does not tell you which recurring client is about to churn. The CRM does all of that on a schedule, so the recurring revenue actually holds instead of depending on you to remember every home."),
        ("How long until it is set up?",
         "Setup is included with no separate onboarding fee. We bring in your clients, build your follow-up and win-back sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will find the gaps where clients and quotes are slipping through today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for house cleaning companies"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-house-cleaning-companies.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting clients and quotes <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your one-time cleans and recurring clients are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Online Booking for House Cleaning Companies ====================
{
    "slug": "online-booking-for-house-cleaning-companies",
    "trade_slug": "house-cleaning-companies", "trade_plural": "house cleaning companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for House Cleaning Companies",
    "title": "Online Booking for House Cleaning Companies | Top Shelf Business Solutions",
    "og_title": "Online Booking for House Cleaning Companies",
    "meta_desc": "Online booking for house cleaning companies lets clients get a quote and claim a recurring slot or a one-time clean on your real availability, with no phone tag.",
    "service_schema_name": "Online Booking for House Cleaning Companies",
    "eyebrow": "For House Cleaning Companies",
    "h1_html": "Online Booking <em>for House Cleaning Companies</em>",
    "answer_block": "Online booking for house cleaning companies lets a client pick a one-time clean or lock in a recurring weekly or biweekly slot straight from your website, your Google listing, or a text link, on your real availability, so you stop trading voicemails and the clean lands on your calendar with the details your crew needs to show up ready.",
    "sections": [
        {"h2_html": "A quote and a booking should not take <em>three days of phone tag</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A lot of cleaning is not urgent, and that is exactly why it slips. Someone decides they finally want a regular cleaner or a one-time deep clean, they call during the day, you are inside a home and cannot pick up, and now it is voicemail, a callback tomorrow, another missed call, and two days of tag for a job they were ready to book on the spot. Make people work that hard and the recurring client you should have signed books the company that let them do it themselves.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets them see your availability and claim a time the moment they decide, at night or on a lunch break, without reaching you first. Even better for a cleaning business, they can lock in a recurring slot, every other Thursday, the first Monday of the month, so you are not booking one visit, you are filling a standing spot on the route. You come off a job to the clean already on the calendar instead of a missed call to chase.</p>'},
        {"h2_html": "It gathers what a clean needs <em>before it books</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Self-scheduling does not mean letting anyone drop anything onto your calendar. The booking form asks what matters for a cleaning visit first, the size of the home, the number of bedrooms and bathrooms, one-time or recurring and how often, the type of clean, and any add-ons like inside the oven or interior windows, so a standard job books itself and an unusual one, a large home or a post-construction clean, gets a quick call to price first. You set the rules: which visit types are bookable, how long each one takes, how much notice you need, and which days each area is open.</p>'},
        {"h2_html": "A booking link everywhere a client <em>finds you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The link goes anywhere someone already meets you: your website, your Google Business Profile, your email signature, and the text you send after a quote. Every one of those turns from a dead end that needs a callback into a place someone can book you in one tap. A busy parent comparing cleaners at 10 p.m. can put a recurring clean on your calendar before they close the tab, instead of leaving a voicemail they will forget by morning.</p>'},
        {"h2_html": "On your real calendar and route, and the client actually shows",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar you already use so it can never double-book a crew or stack two jobs across town with no time to drive between them, and it sends the client a confirmation and a reminder, which is what actually cuts the last-minute cancellations that leave a paid crew standing idle. An empty slot a crew cannot fill on short notice is labor you pay for with nothing coming in. Every booking is logged against the right client in your CRM, and it works alongside the AI receptionist, which can book the client who would rather talk than tap.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A recurring clean claimed <em>on a Sunday night</em>",
        "body_html": 'It is 10 p.m. on a Sunday and a parent who has been meaning to hire a cleaner for months finally has a minute. They land on your site, see real reviews and that your crews are background-checked, and instead of leaving a voicemail they will second-guess by morning, they book a first deep clean for that Wednesday and set it to repeat every other week, right from the calendar on the page. You wake up Monday to a new recurring client already on the route, with the address, the home size, and their preferences attached. No phone tag, no lost client. Illustrative example, not a client.'},
    "faqs": [
        ("Does it sync to my Google or Outlook calendar?",
         "Yes. It reads your real calendar so it only ever offers times a crew is actually free, and new bookings drop straight onto it. It cannot double-book a crew against a job you already have scheduled."),
        ("Can clients book a recurring clean, not just a one-time?",
         "Yes, and that is the point for a cleaning business. A client can lock in a weekly, biweekly, or monthly slot, so a single booking fills a standing spot on your route instead of just one visit, and it repeats on the schedule they chose."),
        ("Can I control the visit types, add-ons, and how long each takes?",
         "Yes. You decide which visit types are bookable online, standard, deep, move-out, and which add-ons are offered, how long each one runs, how much notice you need, and how much drive-time buffer to leave, so a crew is never booked with no way to get there."),
        ("Will it cut down on last-minute cancellations?",
         "It helps. Automatic confirmations and reminders by text and email are the single biggest lever on cancellations and no-shows, and every booking includes them. A client who booked themselves and got a reminder is far more likely to be home and ready than a loosely agreed callback, so your crew is not left with an idle slot."),
        ("How fast can it be live?",
         "Setup is included, no separate fee. We connect your calendar, set up your visit types, add-ons, and service-area rules, and put the link on your site and Google profile, so it is taking bookings in days. Start with a free audit and we will show you where you are losing bookings today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for house cleaning companies"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-house-cleaning-companies.html", "The AI receptionist that can book callers too"),
        ("crm-for-house-cleaning-companies.html", "The CRM every booking is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let clients book you <em>while you clean</em>",
    "cta_sub": "Get a free audit of how many bookings your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Review Software for House Cleaning Companies ====================
{
    "slug": "review-software-for-house-cleaning-companies",
    "trade_slug": "house-cleaning-companies", "trade_plural": "house cleaning companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for House Cleaning Companies",
    "title": "Review Software for House Cleaning Companies | Top Shelf Business Solutions",
    "og_title": "Review Software for House Cleaning Companies",
    "meta_desc": "Review software for house cleaning companies asks every happy client for a Google review at the right moment, so the next homeowner trusts your crew with a key first.",
    "service_schema_name": "Review Software for House Cleaning Companies",
    "eyebrow": "For House Cleaning Companies",
    "h1_html": "Review Software <em>for House Cleaning Companies</em>",
    "answer_block": "Review software for house cleaning companies asks every happy client for a review right after a clean, makes leaving one a single tap, and helps you reply to each, so the next homeowner deciding who to trust with a key to their home finds a wall of recent five-star reviews and calls you first.",
    "sections": [
        {"h2_html": "Nobody hands a house key to the cleaner with <em>three old reviews</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Choosing a cleaning company is an unusually personal decision. You are letting strangers into your home, often when you are not there, sometimes with a key, an alarm code, or a garage code. So a homeowner comparing cleaners does not just glance at the star rating, they read the recent reviews to decide whether they trust these people in their house at all. A company with a handful of old reviews quietly loses those clients to the one with a fresh, steady wall of them, and you never hear the phone that did not ring.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The problem is almost never that your clients are unhappy. It is that a thrilled client walks into a spotless home, feels great for an hour, and never thinks to post about it, while asking in person feels awkward. Review software fixes the timing and the awkwardness, so the reputation your crews have already earned actually shows up where new clients are deciding.</p>'},
        {"h2_html": "Ask at the moment they walk into a <em>clean home</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The best time to ask is right after a clean, when the client walks in to fresh floors and the smell of a house that is finally spotless and is happiest with the work. The software sends the ask automatically at that moment, by text and email, with a link that drops them straight onto your Google profile in one tap. No cornering anyone in their doorway, no card that asks them to go find you later, and for recurring clients it paces the ask so a weekly customer is invited once when they are new and again now and then, never nagged after every single visit.</p>'},
        {"h2_html": "Respond to every review, good or <em>bad</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A thoughtful reply to each review tells the next homeowner reading it that you stand behind your crews, and responding is one of the signals that helps you show up higher in local search. The software flags every new review the moment it lands and helps you reply fast, so a rare critical one, the day a crew missed a room or ran late, gets a calm, professional response instead of silence, and every good one gets a genuine thank you.</p>'},
        {"h2_html": "More reviews, more clients, compounding",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Recent reviews feed your Google Business Profile, which lifts you in the map pack a homeowner sees when they search for a cleaner near them, which brings more clients, which brings more reviews. It builds on itself. Your reputation is yours, tied to your own profile, not a directory or a lead-seller. Review requests are part of the Top Shelf platform and fire automatically off a clean marked complete in your CRM, so you collect reviews without lifting a finger.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "One deep clean becomes <em>next week's new client</em>",
        "body_html": 'Your crew finishes a first deep clean on a Thursday afternoon and leaves the house spotless. An hour later, the software texts your delighted client a thank-you with a one-tap link, and they post a warm review that mentions how careful and trustworthy the crew was, before dinner. The next week a neighbor down the street decides to hire a cleaner, searches, and reads that exact review sitting at the top of your profile. They call you instead of the company below you on the map, because yours is the one someone they almost know just trusted in their home. You never asked twice. Illustrative example, not a client.'},
    "faqs": [
        ("Which review sites does it work with?",
         "It focuses on Google, which is where a homeowner choosing a cleaner looks first and what feeds your local search ranking. It can also point past clients to your other profiles. We follow each platform's own rules, including that a review should come from someone you actually cleaned for."),
        ("When does it ask for the review?",
         "Right after a clean, when the client is happiest with the work, sent automatically by text and email with a one-tap link. For recurring clients it paces the ask so they are invited when they are new and occasionally after that, never after every visit."),
        ("Is automating review requests allowed?",
         "Asking every client for an honest review is fine and encouraged. What is not allowed is filtering out unhappy clients or paying for reviews, and this does not do that. It simply asks everyone at the right moment and makes saying yes easy."),
        ("What happens if I get a bad review?",
         "You find out immediately instead of weeks later, and the software helps you post a calm, professional reply. One measured response to a critical review, sitting under a wall of genuine positive ones, often reassures the next reader more than a spotless record would."),
        ("How long until it is running?",
         "Setup is included with no separate fee. We connect your Google profile, set the timing and the message, and tie it to your completed cleans, so requests start going out in days. Start with a free audit and we will show you how your reputation stacks up against the cleaners you compete with.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for house cleaning companies"),
        ("solution-reviews.html", "How the review system works"),
        ("crm-for-house-cleaning-companies.html", "The CRM that triggers the ask when a clean is done"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Turn finished cleans into <em>your next client</em>",
    "cta_sub": "Get a free audit of how your online reputation compares to the cleaners you compete with, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Websites & SEO for House Cleaning Companies ====================
{
    "slug": "websites-seo-for-house-cleaning-companies",
    "trade_slug": "house-cleaning-companies", "trade_plural": "house cleaning companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for House Cleaning Companies",
    "title": "Websites & SEO for House Cleaning Companies | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for House Cleaning Companies",
    "meta_desc": "A house cleaning company website built for SEO ranks for house cleaning near me and move out cleaning in your city, and captures the client directly, not a lead-seller.",
    "service_schema_name": "Websites & SEO for House Cleaning Companies",
    "eyebrow": "For House Cleaning Companies",
    "h1_html": "Websites &amp; SEO <em>for House Cleaning Companies</em>",
    "answer_block": "A house cleaning company website built for SEO ranks for the searches homeowners actually make, house cleaning near me, maid service in your city, move out cleaning, shows up in the map pack for the areas you cover, and captures the client the moment they land, so the booking belongs to you instead of a directory renting your own leads back to you.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own leads</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a cleaner in your town and the top of the page is often a directory or a pay-per-lead app, not a local company. Those sites publish thousands of pages and have years of authority behind them, so a homeowner searching for a cleaner lands there first, fills out a form, and that lead gets sold, sometimes to three cleaning companies at once, sometimes back to you for a fee out of your own margin. Your site not ranking is not a vanity problem. It is the reason a client who should have found you for free gets sold to you, or handed to whoever pays the most that week.</p>'},
        {"h2_html": "Rank for the searches a homeowner <em>actually makes</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for every broad term, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you serve, and for the exact searches homeowners make when they are ready to book: house cleaning near me, maid service in your city, move out cleaning, deep cleaning, recurring house cleaning. Pages built around the services you actually offer, standard cleans, deep cleans, move-in and move-out, and the areas you actually cover are what search engines, and homeowners, reward with the click.</p>'},
        {"h2_html": "A visitor should reach you in <em>one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most of these searches happen on a phone, and a homeowner is deciding fast whether they trust you in their house. The site has to load quickly, put a tap-to-call button, an instant quote or a booking link, and your trust signals, insured, bonded, background-checked crews, in front of them right away, while still giving the browser a simple way to see pricing and areas served. A pretty site that buries the phone number and hides who you are is a wasted opportunity; a visitor should never leave without an easy way to book or reach you.</p>'},
        {"h2_html": "The clients are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a pay-per-lead app disappears the day you stop paying, and the lead was never really yours anyway. A website you own keeps ranking, keeps capturing bookings, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you. The site plugs into the same CRM that follows up on every lead it captures and the AI receptionist that answers the calls it drives, so nothing it earns you slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A move-out search finds <em>you</em>, not a directory",
        "body_html": 'A renter two towns over needs a move-out clean before a Friday walkthrough and searches move out cleaning near me on their phone. Instead of a national directory that would sell the lead to three companies, they find your site ranking for that town, with a page about move-out cleans and a tap-to-call button and a booking link right at the top. They book you directly, your CRM logs it, and your crew is scheduled for Thursday. You paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big directories?",
         "Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and searches like move out cleaning or deep cleaning in your city that a national directory has no reason to target well, which is exactly where a local cleaning company can win."),
        ("How is this different from paying for leads on an app?",
         "A pay-per-lead app rents you a lead that it also sells to your competitors, and it stops the day you stop paying. A website you own captures clients who are yours alone and keeps working long after it is built, without a per-lead fee coming out of every job."),
        ("Do I need to rank for every town I serve?",
         "You rank for the ones that matter most first, ideally the areas where your routes are densest so new clients sit near the ones you already clean. We build pages for your core service areas and highest-intent searches, then expand, rather than spreading thin across a whole metro at once."),
        ("My current site never brings me bookings. Why would this?",
         "Usually because the current site does not rank for local searches and hides both the phone number and what makes you trustworthy. This one is built to rank for the areas you serve and to turn a visitor into a call or a booked clean, with your reviews and insured, background-checked crews front and center."),
        ("How long until it starts ranking?",
         "Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for house cleaning companies"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-house-cleaning-companies.html", "Staying visible in your service area beyond your site"),
        ("crm-for-house-cleaning-companies.html", "Where every captured lead lands and gets followed up"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your clients, whether you work with us or not. No credit card, never a call center.",
},
# ======================= Marketing for House Cleaning Companies =======================
{
    "slug": "marketing-for-house-cleaning-companies",
    "trade_slug": "house-cleaning-companies", "trade_plural": "house cleaning companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for House Cleaning Companies",
    "title": "Marketing for House Cleaning Companies | Top Shelf Business Solutions",
    "og_title": "Marketing for House Cleaning Companies",
    "meta_desc": "Marketing for house cleaning companies keeps your Google Business Profile active and your name first in the map pack, so you win the client the moment they decide to hire a cleaner.",
    "service_schema_name": "Marketing for House Cleaning Companies",
    "eyebrow": "For House Cleaning Companies",
    "h1_html": "Marketing <em>for House Cleaning Companies</em>",
    "answer_block": "Marketing for house cleaning companies keeps you visible where local demand shows up, your Google Business Profile and the map pack, so when a homeowner nearby decides it is finally time to hire a cleaner, your name is the active, well-reviewed, trustworthy one they call instead of the company that let its profile go stale.",
    "sections": [
        {"h2_html": "Cleaning demand is <em>local and trust-driven</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">People do not shop for a cleaner for weeks, and when they finally decide, it is usually triggered by something, a new baby, a move, a return to the office, a holiday about to fill the house with guests, or just a spring where enough is enough. In that moment the search is intensely local, because they want a company that already serves their neighborhood, and it is intensely about trust, because they are about to let strangers into their home. Get found first, and found trustworthy, in that moment and the client is usually yours.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for a cleaner near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and the ads. A profile that sits untouched for months looks abandoned next to one with recent photos of spotless results, current hours and service area, and a steady stream of reviews. Keeping it active, complete, and honest is a quiet advertisement running in the exact spot a homeowner looks the day they decide to hire someone.</p>'},
        {"h2_html": "Show up in the <em>neighborhoods you actually cover</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and it sends you clients thirty minutes outside your range that wreck your routing. Focusing on the specific towns and neighborhoods you serve, with a profile, photos, and content built around those areas, is what puts you in the map pack where you can actually take the work, and it pulls new clients toward the streets you already clean, so your routes get denser and your crews spend less of the day driving. It is a tighter, cheaper target than a citywide spend, and it is the one that turns into profitable, reachable clients.</p>'},
        {"h2_html": "Stay ready for the season, and stay in front of past clients",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Cleaning demand swings with the calendar, spring cleaning, the run-up to the holidays, the summer move season, the new-year reset, and being visible right before each wave beats scrambling once it hits. A steady local presence, seasonal posts, before-and-after photos of real cleans, the occasional tip, keeps you top of mind for the moment someone decides and reminds past clients you are still the ones to call. This is the public-facing side of the business; the private follow-up to people already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "Spring hits, and you are <em>already at the top</em>",
        "body_html": 'The first warm week of spring arrives and half the neighborhood decides at once that it is time for a deep clean. Because your Google profile has been kept active all year, with recent before-and-after photos, current hours, and a steady flow of reviews, you sit at the top of the map pack when everyone searches. The homeowners ready to book that week call the names they can see and trust first, and yours is right there, close to home and clearly reviewed. The company that let its profile go quiet is nowhere on the map. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         "Yes. We keep it active with before-and-after photos, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current whenever someone searches for a cleaner near them."),
        ("What does focusing on my service area actually mean?",
         "It means building your profile and content around the specific towns and neighborhoods you can reach easily, instead of spreading a budget across a whole metro. That is what gets you into the map pack and pulls new clients toward the streets you already clean, so your routes stay dense and profitable."),
        ("How is this different from the CRM follow-up?",
         "The CRM follows up privately with people already in your database. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at homeowners who are not your client yet but need to find and trust you the day they decide to hire a cleaner."),
        ("Can you help me get ahead of seasonal demand?",
         "Yes. We time your visibility to the waves that matter, spring cleaning, the holidays, the summer move season, so you are already in front of people before the rush instead of scrambling once the calls start."),
        ("How long before I see it working?",
         "A neglected profile can climb in the map pack within weeks once it is active and complete, and it compounds from there as reviews and content build. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for house cleaning companies"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-house-cleaning-companies.html", "The reviews that feed the same Google profile"),
        ("websites-seo-for-house-cleaning-companies.html", "The website that captures the demand this drives"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the cleaner they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ======================= Automation for House Cleaning Companies =======================
{
    "slug": "automation-for-house-cleaning-companies",
    "trade_slug": "house-cleaning-companies", "trade_plural": "house cleaning companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for House Cleaning Companies",
    "title": "Automation for House Cleaning Companies | Top Shelf Business Solutions",
    "og_title": "Automation for House Cleaning Companies",
    "meta_desc": "Automation for house cleaning companies sends clean reminders, on-the-way texts, and after-clean follow-ups for you, so crews are not locked out and recurring clients rebook.",
    "service_schema_name": "Automation for House Cleaning Companies",
    "eyebrow": "For House Cleaning Companies",
    "h1_html": "Automation <em>for House Cleaning Companies</em>",
    "answer_block": "Automation for house cleaning companies handles the texts and reminders around every clean for you, the reminder the night before so a crew is never locked out, the on-the-way text, the after-clean follow-up and review request, and the nudge that turns a one-time clean into a recurring plan, so nothing depends on someone at the office remembering between jobs.",
    "sections": [
        {"h2_html": "A crew that arrives to a <em>locked, empty house</em> is money gone",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a client forgets a cleaning day, the cost is not just an awkward call. Your crew drives out, and the door is locked, the gate code changed, or the alarm is armed and nobody is home, and now two or three people you pay by the hour are standing in a driveway with nowhere to go and a hole in the route no one can fill on short notice. Keeping every client reminded and confirmed, the night before and the morning of, is exactly the kind of thing that slips when you are running crews and answering quotes all day.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Automation handles those messages for you. A confirmation and a reminder the night before, an on-the-way text with a realistic arrival window when the crew heads out, and a note if the schedule shifts, all sent automatically, so the client is ready, the door is open, and your crew walks straight into a clean instead of a wasted trip.</p>'},
        {"h2_html": "Reminders that keep your <em>route full and your crews working</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A last-minute cancellation is the most expensive thing on a cleaning schedule, because a slot dropped the morning of is almost impossible to refill and the crew still gets paid. Automatic confirmations and reminders by text before every clean keep cancellations down and give a client an easy way to reschedule in advance instead of bailing at the door. For an owner running a couple of crews, that is a fuller, tighter route without anyone working the phones to confirm each stop.</p>'},
        {"h2_html": "The follow-up after the clean <em>runs itself</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The job is not really done when the crew drives away. A quick check that the client was happy, an automatic review request while the house still feels spotless, and, most valuable of all, a nudge asking a one-time client to make it recurring while the memory is fresh, all matter, and all are easy to forget once you are onto the next home. Automation fires each one on time, so a finished clean turns into a review, a recurring client, and repeat work without you keeping a mental list.</p>'},
        {"h2_html": "Cold quotes and paused clients <em>come back on schedule</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A quote that went quiet and a recurring client who paused over the holidays and never restarted are not dead, they are just waiting for a reason to book again. A scheduled check-in on an open quote, and a seasonal nudge to a client who said they would call after the new year, bring that work back around automatically instead of falling out of your memory. It runs against the same database as your CRM, so nothing here duplicates a client or a note, and every automated touch is logged where you can see it.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A clean that <em>never leaves a crew locked out</em>",
        "body_html": 'A client is booked for a recurring clean on Tuesday morning. The night before, they get an automatic confirmation with an easy way to reschedule if plans changed. Tuesday morning, when the crew leaves for the route, they get an on-the-way text with an arrival window, so the door is unlocked and the alarm is off when the crew pulls up. That afternoon, once the clean is done, they get a thank-you with a one-tap review link, and a client from a one-time deep clean last week gets a friendly nudge to go biweekly. You never sat down to send any of it. Illustrative example, not a client.'},
    "faqs": [
        ("What messages does it actually send?",
         "The routine ones around a clean: a confirmation and reminder the night before, an on-the-way text with an arrival window when the crew heads out, a note if the schedule shifts, and a follow-up with a review request and a recurring-plan offer after the clean is done. You approve the wording so it all sounds like you."),
        ("Does this replace me or my office talking to clients?",
         "No. It handles the predictable, repetitive texts so nobody has to stop and type them, while you and your team still make every real call and step in personally for anything that needs a conversation."),
        ("Can it really cut down on lockouts and last-minute cancellations?",
         "Yes. Confirmations and reminders the night before and the morning of are the single biggest lever on cancellations and locked-out crews, and they give a client an easy way to reschedule in advance instead of bailing at the door, so your crews spend less time driving to houses they cannot get into."),
        ("Will it help turn one-time cleans into recurring clients?",
         "Yes. After a one-time clean it can automatically ask the client to go weekly or biweekly while the house still feels spotless, and it can nudge cold quotes and paused clients back on a schedule you set, all logged against the client in your CRM."),
        ("How long does setup take?",
         "Setup is included with no separate fee. We build the reminder, on-the-way, and follow-up sequences around how you already run your day, so it is working within days. Start with a free audit and we will show you what is currently slipping between your quotes, your crews, and your calendar.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for house cleaning companies"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-house-cleaning-companies.html", "The database every workflow runs against"),
        ("online-booking-for-house-cleaning-companies.html", "How the cleans these remind about get booked"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a crew <em>arrive to a locked door</em>",
    "cta_sub": "Get a free audit of what is currently slipping between your quotes, your crews, and your follow-ups, whether you work with us or not. No credit card, never a call center.",
},
]
