"""Per-page content specs for the SEO corpus (plan §5), Roofers batch. Same shape as
scripts/corpus_specs.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword placement); each dict owns the UNIQUE, hand-written,
roofer-specific substance that clears the uniqueness gate. Never templated find-and-replace.

Unlike the Realtor batch, this file carries all seven pages including the AI-receptionist
page (slug ai-receptionist-for-roofers, "demo": True), which matches the SPECS[0] dict in
generate_corpus.py key-for-key. Home Services hub, trade_slug "roofers".
"""

SPECS = [
# ======================== AI Receptionist for Roofers ========================
{
    "slug": "ai-receptionist-for-roofers", "demo": True,
    "trade_slug": "roofers", "trade_plural": "roofers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Roofers",
    "title": "AI Receptionist for Roofers | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Roofers",
    "meta_desc": "An AI receptionist for roofers answers every call after a storm hits, qualifies the homeowner, and books the free inspection while your crews work.",
    "service_schema_name": "AI Receptionist for Roofers",
    "eyebrow": "For Roofers",
    "h1_html": "AI Receptionist <em>for Roofers</em>",
    "answer_block": "An AI receptionist for roofers answers every call the moment it comes in, day or night, qualifies the homeowner, and books a free inspection straight onto your calendar while your crews are on a roof and the phone is ringing nonstop after a storm. You keep your own number, and every lead is yours.",
    "sections": [
        {"h2_html": "The call you miss after a storm is the roof your <em>competitor signs</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Roofing runs on speed, and never more than in the days after a hail or wind event. A homeowner with a damaged roof does not call one roofer, they call three, and they hire whoever picks up and gets someone out to look. But your crews are already on roofs, your estimators are already booked, and the calls stack up faster than anyone can answer them. Every one that rolls to voicemail is a homeowner who has already dialed the next company on the list.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist closes that gap. It answers on the first ring, day or night, sounds calm and professional, finds out whether the caller has storm damage, an active leak, or an aging roof, then books a free inspection on your calendar and texts you the details before your estimator is off the current job. The lead is captured and scheduled instead of lost to whoever answered faster.</p>'},
        {"h2_html": "Built around how <em>roofing actually books work</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your phones do not ring at a steady pace. They are quiet for weeks, then a storm rolls through and you get a season of calls in two days, most of them after hours, most of them from people who will hire the first roofer to show up. A voicemail box cannot triage that, and a generic call center does not know an insurance claim from a cash repair.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24/7, including the midnight-after-the-storm call and the Sunday inquiry off your yard sign.</li><li>Handles a surge, so a rush of calls all get answered at once instead of stacking up in voicemail.</li><li>Asks the questions you would ask: storm damage or wear, is it actively leaking, insurance claim or paying out of pocket, roof age, and the address.</li><li>Books the free inspection on your real calendar and sends you the lead by text on the spot.</li></ul>'},
        {"h2_html": "The math is <em>one signed roof</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to recover many calls for this to pay for itself. A roof replacement is a big-ticket job, so one homeowner you would have lost to voicemail after a storm, or one inspection you would have missed on a weekend, is worth far more than the whole system costs for a long time. Everything it catches after that is margin. The point is to stop handing a storm\'s worth of leads to the roofer who happened to answer while you were on a roof.</p>'},
        {"h2_html": "You own the number, the leads, and the list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing phone number, or a new one registered in your name, not ours. Every caller, every lead, and every detail is yours and exportable any time, with no long contract and no holding your data hostage. The AI receptionist is one piece of the Top Shelf platform, and it plugs into the same CRM that follows up on every estimate, so a lead it captures at 11 p.m. after a storm still gets worked instead of going cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A hail storm Saturday, while your crews are <em>already on roofs</em>",
        "body_html": 'Hail moves through on a Saturday afternoon and your phone starts ringing before the sky clears. Your two crews are already on roofs and your estimator is mid-inspection, so the calls would normally pile up in voicemail until Monday. Instead the AI receptionist answers every one, confirms who has active leaks and visible damage, and books free inspections across your open slots for the coming week. By the time your estimator checks the phone, there is a full week of inspections booked, each with a name, an address, and whether the homeowner plans to file a claim. You did not miss the surge, and none of those roofs went to the company down the road.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing number, or set up a new one registered in your name. Either way the number and every lead that comes through it belong to you and go with you if you ever leave.'),
        ("Can it handle a flood of calls after a storm?",
         'That is exactly what it is for. It answers every call at once, so a storm that would send a dozen homeowners to voicemail instead gets a dozen inspections booked. It does not get overwhelmed, put people on hold, or clock out at 5 p.m.'),
        ("Can it tell an insurance claim from a cash repair?",
         'Yes. It asks whether the homeowner has storm damage, whether the roof is actively leaking, and whether they plan to file a claim or pay out of pocket, so an adjuster-driven job and a quick repair are flagged differently before your estimator ever calls back.'),
        ("Will it actually book the free inspection?",
         'Yes. It books straight onto your calendar based on your availability, sends you the details by text right away, and can send the homeowner a confirmation. You set the rules, like how many inspections a day each estimator can take and how much drive time to leave between them.'),
        ("Is this going to sound like a robot to my customers?",
         'It answers naturally and professionally, and it is upfront rather than pretending to be a person. A homeowner with water coming through the ceiling cares about one thing, that someone picked up and is sending help, which beats a voicemail box every time. You can hear how it handles a live call before you decide.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for roofers"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("solution-crm.html", "The CRM that follows up on every lead you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing storm leads to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and leads your current setup misses when the phones surge, whether you work with us or not. No credit card, never a call center.",
},
# ============================ CRM for Roofers ============================
{
    "slug": "crm-for-roofers",
    "trade_slug": "roofers", "trade_plural": "roofers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Roofers",
    "title": "CRM for Roofers | Top Shelf Business Solutions",
    "og_title": "CRM for Roofers",
    "meta_desc": "A CRM for roofers follows up on every estimate and storm lead for you, so the bids that go quiet still close with you instead of the next roofer.",
    "service_schema_name": "CRM for Roofers",
    "eyebrow": "For Roofers",
    "h1_html": "CRM <em>for Roofers</em>",
    "answer_block": "A CRM for roofers keeps every lead, inspection, and signed estimate in one place and follows up for you, so the homeowner who got a bid in April and the storm lead who went quiet in July still come back to you instead of going cold. Your pipeline stops living on sticky notes and in your estimators' heads.",
    "sections": [
        {"h2_html": "The estimates you already gave are the ones you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most roofers do not have a lead problem. They have a follow-up problem. You inspect a roof, hand over a bid, and the homeowner says they need to think about it, talk to a spouse, or wait on the insurance check. That is normal in roofing, where a replacement is a big decision people sit on for weeks. But most bids never get a second touch, so the homeowner signs with whoever followed up, and it usually is not the roofer who inspected first.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM catches every inspection and every estimate and works it on a schedule you set, with texts and emails that go out on time whether or not anyone remembers. The homeowner who is thirty days into deciding still hears from you, still has your number handy, and still calls you when the claim clears instead of the company that stayed in touch.</p>'},
        {"h2_html": "A storm fills your pipeline, then <em>empties it if nobody follows up</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">After a storm you can take more leads in a week than you normally see in a month, and no estimator can personally remember to circle back to all of them. The ones waiting on an adjuster, the ones getting a second opinion, the ones who called scared and then calmed down, all of them slip unless something keeps track.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every lead, inspection, note, and bid lives in one place instead of a truck console and three phones.</li><li>Follow-ups fire on the cadence you set, so a homeowner waiting on an insurance decision gets a check-in at the right time without anyone setting a reminder.</li><li>You see which bids are heating up, so the estimator\'s limited callback time goes to the roof about to sign.</li></ul>'},
        {"h2_html": "Answer first, without living on your <em>phone</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A new lead that hears back in the first few minutes is far more likely to book than one that waits an hour, and after a storm the first roofer to respond usually gets the inspection. The CRM replies instantly with a text-back the moment a lead comes in and hands it to your team with the details, so you are first even when every estimator is up a ladder.</p>'},
        {"h2_html": "You own the database, and it runs the whole platform",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every homeowner, every note, and every bid is yours and exportable any time, not locked in a system you rent. The CRM is the hub of the Top Shelf platform: it plugs into the AI receptionist, so a storm call it catches lands in your pipeline and gets followed up automatically, and into online booking, so a scheduled inspection is logged against the right homeowner. Nothing you spend to generate a lead gets wasted because someone forgot to call back.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The bid you <em>forgot about</em> signs three weeks later",
        "body_html": 'You inspect a roof in the spring, leave a bid, and the homeowner says they are waiting on their insurance company. You would normally lose track of them within a week. Instead the CRM keeps a light touch going, a check-in here, an answer to a common question there, all sent for you. Three weeks later the claim is approved, and the homeowner texts you to schedule, because yours is the name that stayed in front of them the whole time. You did not lift a finger to keep that bid alive.'},
    "faqs": [
        ("Does it import my existing leads and past customers?",
         'Yes. Your current leads, open bids, and past customers come in and live in one place, and everything stays yours and exportable. The point is to make the pipeline you already have actually get worked.'),
        ("Will it really follow up on estimates automatically?",
         'Yes, on the schedule you approve. New leads get an instant response, and open bids get check-ins on a cadence you set, all sent for you. Your estimators can always jump in and message a homeowner directly when a bid needs a personal push.'),
        ("Does it help with the leads that are waiting on insurance?",
         'Yes, and those are the ones most often lost. A homeowner waiting on an adjuster or a claim decision can wait weeks, and the CRM keeps a light, well-timed touch going so you are still the roofer they call when the check comes, instead of whoever followed up last.'),
        ("What happens to the flood of leads after a storm?",
         'They all land in one place and get worked on a schedule instead of piling up in someone\'s memory. The ones ready now get booked, and the ones waiting get nurtured, so a busy storm week does not turn into a pile of forgotten bids a month later.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your leads and bids, build the follow-up sequences around how you sell, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will find the gap where bids are going cold today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for roofers"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-roofers.html", "The AI receptionist that feeds it every storm call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting good bids <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your open estimates and storm leads are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ======================= Online Booking for Roofers =======================
{
    "slug": "online-booking-for-roofers",
    "trade_slug": "roofers", "trade_plural": "roofers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for Roofers",
    "title": "Online Booking for Roofers | Top Shelf Business Solutions",
    "og_title": "Online Booking for Roofers",
    "meta_desc": "Online booking for roofers lets homeowners self-schedule a free roof inspection on your real availability, straight onto your estimator's calendar.",
    "service_schema_name": "Online Booking for Roofers",
    "eyebrow": "For Roofers",
    "h1_html": "Online Booking <em>for Roofers</em>",
    "answer_block": "Online booking for roofers lets a homeowner schedule a free inspection straight from your website, a storm-response ad, or a text link, on your real availability, so you stop playing phone tag and the inspection lands on your calendar with the address and the damage details your estimator needs to show up ready.",
    "sections": [
        {"h2_html": "Phone tag is quietly costing you <em>inspections</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner notices a missing shingle or a water stain and wants someone to look at it. Your estimator is on a roof, so they call back two hours later, the homeowner is at work, they trade voicemails, a day passes, and the roof gets looked at by the company that could lock in a time on the spot. The inspection was never the problem. The back and forth was. When someone is worried enough about their roof to call, the worst thing you can do is make them wait for a callback.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets them grab an open inspection slot the moment they feel it, day or night, without reaching anyone first. Your estimator wakes up to the inspection already set instead of a missed call they now have to chase between jobs.</p>'},
        {"h2_html": "It qualifies the roof <em>before</em> it books",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Self-scheduling does not mean sending an estimator across town for nothing. The booking form asks what matters first: storm damage or normal wear, whether the roof is actively leaking, insurance claim or paying directly, the age of the roof, and the address. A clear storm-damage claim books an inspection, and a vague question gets routed for a quick call, so your estimator\'s day is spent on roofs worth driving to. You set the rules: how many inspections a day, how long each takes, and how much drive time to leave between them.</p>'},
        {"h2_html": "A booking link everywhere a homeowner <em>finds you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The link goes anywhere a lead already meets you: your website, your Google Business Profile, your storm-season ads, your email signature, and the text you send after a missed call. Every one of those turns from a dead end that needs a callback into a place a homeowner can book an inspection in one tap. After a storm, when everyone is calling every roofer at once, letting people book themselves is the difference between catching the surge and drowning in it.</p>'},
        {"h2_html": "On your real calendar, and the inspection shows up",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar your estimators already use so it can never double-book a slot, and it sends the homeowner a confirmation and a reminder, which is what actually cuts no-shows on free inspections. Every booking is logged against the right homeowner in your CRM, and it works alongside the AI receptionist, which can book a caller who would rather talk than tap. The leads and the calendar stay yours.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A storm-night homeowner books an inspection <em>while you sleep</em>",
        "body_html": 'It is 10 p.m. after a wind storm and a homeowner sees shingles in the yard. They are deciding which roofer to call in the morning. They land on your site, see your real reviews, and instead of leaving a voicemail they will forget by breakfast, they book a free inspection for Thursday at 9 from the calendar right there on the page. Your estimator wakes up to the inspection already set, with the address, the roof age, and a note that the homeowner plans to file a claim. No phone tag, and the roof did not go to the first company that answered.'},
    "faqs": [
        ("Does it sync to my estimators' calendars?",
         'Yes. It reads their real calendars so it only offers times someone is actually free, and new inspections drop straight on. It cannot double-book an estimator against a job or another inspection already scheduled.'),
        ("Can homeowners book, or does it send someone out for junk leads?",
         'You control that. The form asks about damage, leaks, roof age, and whether it is an insurance claim, so a real prospect books an inspection and a vague inquiry gets routed to a quick call first. Your estimator\'s time goes to roofs worth the drive.'),
        ("Can it respect drive time and stop back-to-back inspections across town?",
         'Yes. You set how many inspections a day each estimator takes, how long each runs, and how much buffer to leave between them, so nobody is booked with no time to cross the city.'),
        ("Will it cut down on no-shows for free inspections?",
         'It helps. Automatic confirmations and reminders by text and email are the single biggest lever on no-shows, and every booking includes them. A homeowner who booked themselves and got a reminder is far more likely to be home than a loosely agreed callback.'),
        ("How fast can it be live?",
         'Setup is included, no separate fee. We connect your calendars, set up your inspection types and rules, and put the link on your site, ads, and Google profile, so it is taking bookings in days. Start with a free audit and we will find the gap where inspections are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for roofers"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-roofers.html", "The AI receptionist that can book callers too"),
        ("crm-for-roofers.html", "The CRM every inspection is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let homeowners book you <em>while you work</em>",
    "cta_sub": "Get a free audit of how many inspections your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Review Software for Roofers ====================
{
    "slug": "review-software-for-roofers",
    "trade_slug": "roofers", "trade_plural": "roofers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for Roofers",
    "title": "Review Software for Roofers | Top Shelf Business Solutions",
    "og_title": "Review Software for Roofers",
    "meta_desc": "Review software for roofers asks every happy homeowner for a Google review at the right moment and makes it one tap, so your reputation wins bigger jobs.",
    "service_schema_name": "Review Software for Roofers",
    "eyebrow": "For Roofers",
    "h1_html": "Review Software <em>for Roofers</em>",
    "answer_block": "Review software for roofers asks every satisfied homeowner for a review at the right moment, makes leaving one a single tap, and helps you respond to each, so your reputation keeps winning big-ticket roofs instead of depending on the few customers who remember to post on their own.",
    "sections": [
        {"h2_html": "A roof is a big check, so homeowners <em>check you first</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Before a homeowner hands a roofer thousands of dollars, they Google you and read what your past customers said. A roof is not a purchase people take lightly, and there are enough storm-chasing outfits and fly-by-night crews out there that homeowners are wary by default. A thin profile with a handful of old reviews quietly costs you jobs you never hear about, because the homeowner just called the roofer with the wall of recent five-star reviews instead.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The problem is not that your customers are unhappy. It is that happy customers forget to post, and asking feels awkward when you are wrapping up a job. Review software solves the timing and the awkwardness so the reputation you have actually earned on roofs shows up online where the next homeowner is looking.</p>'},
        {"h2_html": "Ask at the moment they are <em>happiest</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The best time to ask is right after the job is finished and the homeowner is standing in the driveway looking at a roof that no longer leaks. The software sends the ask automatically at that moment, by text and email, with a link that takes them straight to your Google profile in one tap. No cornering people, no business cards nobody acts on, and no asking three weeks later when the relief has worn off and the roof is just a roof again.</p>'},
        {"h2_html": "Respond to every review, good or <em>bad</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A thoughtful reply to each review tells the next homeowner that you stand behind your work, and responding is one of the signals that helps you show up in local search. The software flags every new review the moment it lands and helps you reply quickly, so a rare critical one, the storm job that ran long or the mix-up about a start date, gets a calm, professional response instead of silence, and every good one gets a thank you.</p>'},
        {"h2_html": "More reviews, more roofs, compounding",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Recent reviews feed your Google Business Profile, which lifts you in the local results a homeowner sees when they search for a roofer, which brings more jobs, which brings more reviews. It builds on itself, and it matters most right after a storm when a flood of homeowners are all searching at once and comparing whoever shows up. Review requests are part of the Top Shelf platform and fire automatically off a job marked complete in your CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "One finished roof becomes <em>the next job on the block</em>",
        "body_html": 'You finish a roof replacement on a Friday. That afternoon, the software texts your happy homeowner a thank-you with a one-tap link, and they post a warm review before dinner. A week later a neighbor two doors down, who watched your crew work all week and has been meaning to get their own aging roof looked at, Googles roofers in the area and reads that exact review at the top of your profile. They call you instead of a number off a storm-chaser\'s flyer. You never asked twice, and you were already on another job when it happened.'},
    "faqs": [
        ("Which review sites does it work with?",
         'It focuses on Google, which is where most homeowners look first and what feeds your local search ranking. It can also point past customers to your other profiles. We follow each platform\'s own rules, including that a review should come from a real customer whose roof you actually worked on.'),
        ("When does it ask for the review?",
         'Right after the job is marked complete, when the homeowner is happiest, sent automatically by text and email with a one-tap link. You can adjust the timing and the wording so it sounds like you.'),
        ("Is automating review requests allowed?",
         'Asking every customer for an honest review is fine and encouraged. What is not allowed is filtering out unhappy customers or paying for reviews, and this does not do that. It simply asks everyone at the right moment and makes it easy to say yes.'),
        ("What happens if I get a bad review?",
         'You find out immediately instead of weeks later, and the software helps you post a calm, professional response. One thoughtful reply to a critical review, sitting under a wall of genuine positive ones, often reassures a wary homeowner more than a perfect record would.'),
        ("How long until it is running?",
         'Setup is included with no separate fee. We connect your Google profile, set the timing and the message, and tie it to your completed jobs, so requests start going out in days. Start with a free audit and we will show you how your reputation stacks up against the roofers you compete with.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for roofers"),
        ("solution-reviews.html", "How the review system works"),
        ("crm-for-roofers.html", "The CRM that triggers the ask when a job is done"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Turn finished roofs into <em>your next job</em>",
    "cta_sub": "Get a free audit of how your online reputation compares to the roofers you compete with, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Websites & SEO for Roofers ====================
{
    "slug": "websites-seo-for-roofers",
    "trade_slug": "roofers", "trade_plural": "roofers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Roofers",
    "title": "Websites & SEO for Roofers | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Roofers",
    "meta_desc": "A roofing company website built for SEO ranks for roof repair near me and storm-season searches, and captures leads directly instead of the lead sellers.",
    "service_schema_name": "Websites & SEO for Roofers",
    "eyebrow": "For Roofers",
    "h1_html": "Websites &amp; SEO <em>for Roofers</em>",
    "answer_block": "A roofing company website built for SEO ranks for the searches homeowners actually type, like roof repair near me and storm damage roof inspection, shows up in local results before the lead-selling directories, and captures a homeowner's details the moment they land, so the traffic and the leads belong to you instead of a service that sells the same lead to several roofers.",
    "sections": [
        {"h2_html": "The lead sellers are not competing with you, they are <em>selling you your own homeowners</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The big directories and lead services outrank most individual roofer sites because they publish thousands of pages and have years of authority behind them. A homeowner searching for a roofer, or for roof repair near me, often lands on one of those first, fills out a form, and that one lead gets sold to several roofers who then race to call it and undercut each other. Your site not ranking is not just a vanity problem. It is the reason a lead you could have had for free gets sold back to you, at a price, alongside your competitors.</p>'},
        {"h2_html": "Rank for the searches only a <em>local roofer can win</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for a broad term, and you do not need to. You can rank for your company name, for the towns and neighborhoods you actually work, and for the specific searches homeowners run, like "roof repair near me," "storm damage roof inspection," and "metal roof installer near me," where a national lead service has nothing local to say and your site can. Real pages about the areas you serve, the roof types you install, and the storms your area actually gets are what search engines, and homeowners, reward.</p>'},
        {"h2_html": "A visitor should not be able to leave your site <em>anonymous</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner who lands on your site after a storm, reads a page about hail damage, and leaves without a way for you to reach them is a wasted opportunity. The site should offer something real, a free inspection booking, a straight answer about the claims process, a roof-age guide, in exchange for a name and a number, so a visitor becomes a lead in your CRM instead of a number in your traffic report.</p>'},
        {"h2_html": "The traffic is <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you hand a lead service disappears the moment you stop paying, and the lead was never only yours to begin with. A website you own keeps ranking, keeps capturing leads, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform account that vanishes. The site plugs into the same CRM that follows up on every lead it captures, so a homeowner who books an inspection at midnight after a storm gets worked instead of forgotten.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A homeowner skips the directory and calls <em>you</em> instead",
        "body_html": 'A hail storm hits your town and a homeowner searches for a storm damage roof inspection near them. Instead of a lead-service form that sells their information to several roofers, they find your site ranking with a page about hail damage in that exact area, written from roofs you have actually worked. They book a free inspection out of the how-bad-is-it worry everyone feels after a storm, leave their name and number, and your CRM follows up before they finish reading. You paid nothing per lead, and no directory ever touched it.'},
    "faqs": [
        ("Do I still need the lead services if I have my own site?",
         'Maybe, for now, while your own rankings build. The point is not to depend on them. It is to own a channel where the leads are entirely yours instead of sold to you and several competitors at the same time.'),
        ("Will my site actually outrank the big directories?",
         'Not for the broadest searches. It can realistically rank for your name, your specific towns and neighborhoods, and long-tail local searches like roof repair in a named suburb, which is exactly where a local roofer can beat a national directory.'),
        ("How does this help during storm season?",
         'Storm season is when local searches spike, roof repair, hail damage, and emergency roof tarp, all at once. A site built to rank for those terms and to book an inspection on the spot catches that surge of homeowners directly, instead of you buying the same demand back through a lead service.'),
        ("I already have a website. Why do I need another?",
         'A lot of roofer sites are online brochures that never rank and never capture a lead. This one is built to rank for the towns and roof types you actually work and to turn visitors into booked inspections in your own CRM, not just to exist.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks, and broader terms compound over months. Setup is included with no separate fee, and a free audit will find the gap between where your current site ranks and where the searches actually are.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for roofers"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("crm-for-roofers.html", "Where every captured lead lands and gets followed up"),
        ("marketing-for-roofers.html", "Staying visible beyond your site"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>roofing in your town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories selling your homeowners to everyone, whether you work with us or not. No credit card, never a call center.",
},
# ======================== Marketing for Roofers ========================
{
    "slug": "marketing-for-roofers",
    "trade_slug": "roofers", "trade_plural": "roofers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Roofers",
    "title": "Marketing for Roofers | Top Shelf Business Solutions",
    "og_title": "Marketing for Roofers",
    "meta_desc": "Marketing for roofers keeps your Google Business Profile and local presence active, so you are the roofer homeowners already know when a storm hits.",
    "service_schema_name": "Marketing for Roofers",
    "eyebrow": "For Roofers",
    "h1_html": "Marketing <em>for Roofers</em>",
    "answer_block": "Marketing for roofers keeps you visible in the towns you serve and ready for the moment demand spikes, through your Google Business Profile and consistent local content, so when a storm hits or a neighbor finally decides to replace an aging roof, your name is the one they already know and the profile they find looks active and trusted.",
    "sections": [
        {"h2_html": "Roofing demand comes in <em>waves</em>, and the ready roofer wins",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Roofing is not a steady drip of work. It is quiet stretches broken by storms that send a whole town looking for a roofer in the same week. When that wave hits, homeowners do not calmly research. They call the name they already recognize, or they search and call whoever looks most established at the top of the results. The roofer who was invisible until the storm is starting from behind against the one who was already familiar.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Winning that recognition before the storm is worth more than any single ad, because by the time roofs are damaged and everyone is calling, the homeowner has usually already decided who feels trustworthy. Marketing is how you become that roofer before the wave comes.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>yard sign</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a homeowner searches for a roofer near them after a storm, your Google Business Profile is often the first thing they see, before your website and before a directory. A profile that sits untouched for months looks abandoned next to one with recent job photos, before-and-after shots, and posts about the last storm you responded to. Keeping it active is a quiet, constant advertisement running in the exact moment a worried homeowner is looking, and it is what puts you in the map results they call first.</p>'},
        {"h2_html": "Own the towns you actually <em>drive to</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable. Picking the towns and neighborhoods your crews already work and showing up there consistently, a finished-roof photo here, a note about storm response there, a straight answer about the claims process, builds the specific recognition that turns into a call when a roof fails down the street. It is slower than a big ad blast, and it is the approach that actually compounds inside the area you can profitably serve.</p>'},
        {"h2_html": "Stay known between storms, not just <em>during them</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The roofers who only market when it is storming are competing with everyone else doing the same thing, at the most expensive moment. A steady, low-effort presence between storms, a job photo, a seasonal roof-maintenance tip, a real answer to a common question, keeps you familiar so you are already the known name when the next wave hits. This is the public-facing side of your business; the private follow-up to homeowners already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The neighbor who calls <em>the roofer they already knew</em>",
        "body_html": 'You spend a few months showing up in one set of neighborhoods: job photos on Google, before-and-after shots, a post after the last hail storm about how you handle claims. A homeowner three streets over is not thinking about their roof yet, but keeps seeing your work and your name. Then a storm rolls through and their roof takes damage. Instead of searching and calling five strangers, they call the roofer whose finished jobs they had already been seeing all season. You never spoke to them once before that call.'},
    "faqs": [
        ("What does owning a town actually mean?",
         'It means consistently showing up in the specific towns and neighborhoods your crews work, with local content, job photos, and updates, instead of spreading a budget thin across a whole metro. Over months, that repetition is what makes homeowners in that area recognize your name before they need you.'),
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with job photos, before-and-after shots, and local posts on a regular schedule, so it looks current and established whenever a homeowner searches for a roofer near them.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with homeowners already in your database, your open bids and past customers. Marketing is the public-facing side, your Google profile, local content, and neighborhood visibility, aimed at homeowners who are not your contact yet but will recognize your name when a storm hits.'),
        ("Should I only market when there is a storm?",
         'That is the trap most roofers fall into, and it means competing with everyone at the most expensive moment. Staying visible between storms is cheaper and builds the familiarity that makes homeowners choose you when the wave comes, instead of you bidding against ten other companies for the same panicked search.'),
        ("How long before I see it working?",
         'Recognition builds over months, not days, which is exactly why most roofers never stick with it long enough to see it pay off, then scramble when a storm hits. Setup is included, and a free audit will show you what your current online presence looks like to a homeowner searching near you today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for roofers"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-roofers.html", "The reviews that feed the same Google profile"),
        ("crm-for-roofers.html", "The private follow-up system behind the scenes"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the roofer they <em>already know</em>",
    "cta_sub": "Get a free audit of how visible you actually are in the towns you serve and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ======================== Automation for Roofers ========================
{
    "slug": "automation-for-roofers",
    "trade_slug": "roofers", "trade_plural": "roofers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for Roofers",
    "title": "Automation for Roofers | Top Shelf Business Solutions",
    "og_title": "Automation for Roofers",
    "meta_desc": "Automation for roofers runs estimate follow-ups, inspection reminders, and review requests for you, so no lead or job slips while your crews are on roofs.",
    "service_schema_name": "Automation for Roofers",
    "eyebrow": "For Roofers",
    "h1_html": "Automation <em>for Roofers</em>",
    "answer_block": "Automation for roofers keeps every lead, inspection, and job on track without anyone remembering to send a text, sending estimate follow-ups while a bid is still warm, reminding homeowners about a scheduled inspection, and requesting a review the moment a roof is finished, so nothing about the process depends on an estimator finding a free minute between roofs.",
    "sections": [
        {"h2_html": "The follow-through slips when everyone is <em>on a roof</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The work that wins roofing jobs is not glamorous. It is the second text on a bid, the reminder the day before an inspection, the review ask the afternoon a roof is done. Each one is small, and each one gets skipped during a busy week because the person who should send it is up a ladder. After a storm, when the volume triples, the follow-through is the first thing to fall, and it is exactly the thing that turns inspections into signed roofs.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Automation handles the routine steps so they happen on every lead and every job, whether you have one inspection this week or forty after a storm. You still make every real call and every real decision. The predictable texts and reminders are simply sent for you, on time, every time.</p>'},
        {"h2_html": "Estimate follow-up that <em>runs itself</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A roofing bid rarely closes on the first visit, and it goes cold fast without a nudge. Once you leave an estimate, the homeowner gets a well-timed sequence, a thank-you, an answer to the questions people always ask, a check-in while the decision is fresh, all sent automatically until they book or clearly say no. The bids waiting on an insurance decision get a longer, gentler cadence, so a homeowner still deciding weeks later is still hearing from you instead of the roofer who happened to call last.</p>'},
        {"h2_html": "Inspection reminders that cut <em>the drive to nowhere</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A free inspection a homeowner forgot about is a wasted trip and a wasted slot your estimator could have given someone else. Automatic confirmations and reminders go out by text and email before every inspection, so the homeowner is actually home when your estimator pulls up, and a slot that opens because someone cancels gets freed instead of sitting empty. Fewer dead trips means more roofs looked at with the same crew.</p>'},
        {"h2_html": "The review ask, sent the moment a <em>roof is done</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The best time to ask for a review is the afternoon the job wraps, and it is the ask most likely to be forgotten when the crew is already loading up for the next roof. When a job is marked complete, the review request fires automatically, by text and email with a one-tap link, while the homeowner is still looking up at a roof that no longer leaks. It runs against the same database as your CRM, so nothing here duplicates a contact or double-texts a homeowner.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A bid that never <em>goes quiet</em>",
        "body_html": 'Your estimator inspects a roof on a Monday and leaves a bid for a homeowner who is waiting on their insurance company. Over the next few weeks the homeowner gets an automatic thank-you the same day, a text answering the claims question everyone asks, and a gentle check-in timed to when claims usually clear, none of which your estimator sat down to write. When the check comes, yours is the roofer still in front of them, so they text to schedule instead of calling around. The day the roof is finished, a review request goes out on its own, and a five-star review is posted before the crew reaches the next job.'},
    "faqs": [
        ("What does it actually automate?",
         'The routine steps that win and finish jobs: estimate follow-ups after an inspection, reminders before a scheduled inspection, and a review request the moment a job is marked complete. Each runs on a schedule you approve, on every lead and every job.'),
        ("Does this replace my estimators calling homeowners?",
         'No. It handles the predictable texts and reminders so nobody has to remember them, and it frees your estimators to make the calls that actually need a person, like walking a homeowner through a claim or closing a bid that is on the fence.'),
        ("How does it handle bids waiting on insurance?",
         'Those get a longer, gentler follow-up cadence, because a claim can take weeks. A homeowner still waiting on an adjuster keeps hearing from you at the right intervals, so you are the roofer they call when the decision comes instead of whoever followed up most recently.'),
        ("Can it stop double-texting a homeowner?",
         'Yes. It runs against the same CRM database, so it knows where each homeowner is in the process and does not send an estimate follow-up to someone who already booked or a review ask to someone whose job is not done.'),
        ("How long does setup take?",
         'Setup is included with no separate fee. We build the follow-up, reminder, and review sequences around how you already work, so it is running within days. Start with a free audit and we will find the gap where jobs are slipping between inspection and signature today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for roofers"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-roofers.html", "The database every workflow runs against"),
        ("online-booking-for-roofers.html", "How the inspections these remind about get booked"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a <em>bid go quiet</em>",
    "cta_sub": "Get a free audit of what is currently slipping between your inspections, your bids, and your finished jobs, whether you work with us or not. No credit card, never a call center.",
},
]
