"""Per-page content specs for the SEO corpus (plan §5), Landscapers batch. Same contract as
scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, landscaper-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber or roofer content reworded.

Home Services hub, trade_slug "landscapers". All seven service angles are here in one file (the
ai-receptionist dict carries "demo": True and matches the SPECS[0] shape in generate_corpus.py
key-for-key). Each example body ends with the literal "Illustrative example, not a client." per
the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ========================= AI Receptionist for Landscapers =========================
{
    "slug": "ai-receptionist-for-landscapers", "demo": True,
    "trade_slug": "landscapers", "trade_plural": "landscapers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Landscapers",
    "title": "AI Receptionist for Landscapers | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Landscapers",
    "meta_desc": "An AI receptionist for landscapers answers every call while your crews are out on the route, sorts the quote from the cleanup, and books the estimate before the caller tries the next company.",
    "service_schema_name": "AI Receptionist for Landscapers",
    "eyebrow": "For Landscapers",
    "h1_html": "AI Receptionist <em>for Landscapers</em>",
    "answer_block": "An AI receptionist for landscapers answers every call the moment it rings, even when your whole crew is out on the route with mowers running, finds out whether it is a weekly maintenance quote, a design job, or a storm cleanup, and books the estimate on your calendar. You keep your own number, and every call belongs to you.",
    "sections": [
        {"h2_html": "The call you miss in spring is a whole season you <em>hand to the next company</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner who has decided to hire a lawn service does not leave one voicemail and wait. They call two or three companies and sign with whoever picks up, gets them a quote, and can start soon, because the yard is on their mind right now and they want it handled. That decision is worth far more than a single job, because a weekly mowing customer is recurring revenue across the whole season and often for years. But your crews are out on the route with mowers running, you are mid-quote in someone\'s backyard, or you are driving between stops, so the call rolls to voicemail and a season of work goes to whoever answered.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist answers on the first ring, day or night, stays friendly and professional, finds out whether it is a weekly maintenance quote, a one-off cleanup, a design or install job, or a commercial account shopping around, gets the address, and either books the estimate or flags it to you as a lead worth calling back yourself. The work is captured and scheduled instead of lost to the company down the road.</p>'},
        {"h2_html": "Built around how <em>landscapers actually get calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your phone does not ring at a steady pace. It is quiet through the winter, then spring arrives and a season of quote calls lands in a few weeks, most of them while your crews are out on the route and nobody can hear a phone over the mowers. A voicemail box cannot triage that, and a generic call center reading a script does not know a weekly mowing signup from a full landscape install or a commercial bid worth chasing.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers every call, including the spring signup rush and the Saturday quote request off your truck sign, so a season of recurring work does not pile up in voicemail.</li><li>Triages like you would: weekly or biweekly maintenance, a one-off cleanup, a design or hardscape install, an irrigation issue, and how soon they need a quote.</li><li>Gets the address and the property details, books the estimate on your calendar, and texts you a commercial or HOA lead at once so you can call that high-value account back yourself.</li><li>Handles a current maintenance customer differently from a first-time caller, so the accounts you already have never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one maintenance contract</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. One weekly maintenance customer you would have lost in the spring rush is recurring revenue for the whole season, and often the next one too, so it is usually worth more than the system costs for a long time. A single commercial or HOA account is worth far more still. Everything it captures after that first save is on top. The point is to stop handing a season\'s worth of signups to the landscaper who simply answered faster.</p>'},
        {"h2_html": "You own the number, the calls, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every address, and every property detail is yours and exportable any time, so your customer list is an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The AI receptionist is one piece of the Top Shelf platform, and it hands every call it captures to the same CRM that follows up, so a quote or a seasonal reminder never slips.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A spring-rush Saturday, booked while you are <em>on the route</em>",
        "body_html": 'It is a Saturday in April, the first real warm weekend of the year, and homeowners all over town are deciding at the same time to finally hire out the yard. Your two crews are on the route and the phone is ringing all day. Normally those calls stack up in voicemail and half of them never call back. Instead the AI receptionist answers every one, sorts the weekly-mowing signups from the one-off cleanups, books estimates across your open slots for the week, and texts you the single call from a property manager whose HOA landscaping contract is up for renewal so you can call that account back yourself. You did not miss the rush, and none of that recurring work went to the company down the road. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever leave.'),
        ("Can it tell a weekly maintenance customer from a one-off install?",
         'Yes, that is the point. It asks the questions you would, weekly or biweekly mowing, a one-time cleanup, a design or hardscape install, an irrigation issue, and how soon they need a quote, so a season-long maintenance signup and a big install estimate are flagged differently before you ever call back. You set what counts as a drop-everything lead, like a commercial or HOA bid.'),
        ("Will it actually book the estimate on my calendar?",
         'Yes. It books the on-site estimate straight onto your calendar based on your availability, and you get a text with the details right away. For a high-value commercial or HOA lead it can flag you at once so you decide whether to call that account back yourself.'),
        ("Can it keep up with the spring rush when every call comes at once?",
         'That is exactly what it is for. It answers every call at the same time, so the week the whole town decides to hire a lawn service does not send half your callers to voicemail. It does not get overwhelmed, put people on hold, or clock out at five.'),
        ("Is it going to sound like a robot to my customers?",
         'It answers naturally and calmly, and it is upfront instead of pretending to be a person. Someone who just wants a quote on their yard mostly needs to know a real company picked up and is handling it, and that beats a voicemail box every time. You can hear it handle a live call before you decide.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for landscapers"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-landscapers.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing spring signups to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many quote calls and new maintenance customers your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ================================ CRM for Landscapers ================================
{
    "slug": "crm-for-landscapers",
    "trade_slug": "landscapers", "trade_plural": "landscapers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Landscapers",
    "title": "CRM for Landscapers | Top Shelf Business Solutions",
    "og_title": "CRM for Landscapers",
    "meta_desc": "A CRM for landscapers follows up on every design quote and keeps every maintenance customer on the books, firing seasonal upsell and re-up reminders so a yard you mow once keeps paying all season.",
    "service_schema_name": "CRM for Landscapers",
    "eyebrow": "For Landscapers",
    "h1_html": "CRM <em>for Landscapers</em>",
    "answer_block": "A CRM for landscapers keeps every lead, maintenance customer, and open install quote in one place and follows up for you, so the patio bid a homeowner is sitting on and the family whose lawn you mowed last summer both come back to you instead of the company that stayed in touch. Your route quietly becomes recurring revenue.",
    "sections": [
        {"h2_html": "The quotes you already sent are the installs you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most landscapers do not have a lead problem. They have a follow-up problem. You walk a yard, hand over a bid for a patio, a full landscape install, or a new irrigation system, and the homeowner says they need to think about it. A big install is a decision people sit on for weeks and compare bids on. Then you get busy on the route and never circle back, so they collect two other prices and sign with whoever followed up, not necessarily the lowest bid. The quote was never dead. It just needed one more call or text a few days later, and that is the thing there is never time for during a mowing week.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open quote in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not you remember. The homeowner deciding between three landscapers hears from you again while the other two go quiet, and the install comes back to you.</p>'},
        {"h2_html": "Every yard you maintain is recurring revenue <em>you can keep for years</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Past customers and standing maintenance accounts are the cheapest, steadiest work a landscaper can get. You already know the property, they already trust your crew on it, and the mulch refresh, the aeration, the next season of mowing are yours if you stay in touch. But you cannot personally remember to re-sign a few hundred customers every spring or prompt every upsell at the right time of year.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, property, service history, gate code, and note lives in one place instead of a truck full of clipboards and your memory.</li><li>Seasonal reminders go out on schedule, spring cleanup and mulch, summer mowing, fall aeration and leaf cleanup, so the upsells come back around without you tracking dates.</li><li>You can see which customers paused over winter and reach the right ones to re-sign before the route fills up for the season.</li></ul>'},
        {"h2_html": "The customers who dropped off over winter are still <em>yours to win back</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A lot of maintenance customers pause or cancel in the winter slow season and fully mean to restart in spring, then drift to whoever markets to them first when the grass starts growing. A steady, light touch, a late-winter check-in, a spring re-up note, a reminder of what their yard looked like when you kept it, keeps your name in front of them so the new season comes back to you. It costs almost nothing, and it is the difference between rebuilding your route from scratch every spring and keeping the customers you already earned.</p>'},
        {"h2_html": "You own the list, and it works with the rest of the system",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the AI receptionist, so a call it answers lands in your database and gets followed up on automatically, and to online booking, so a scheduled estimate is logged against the right customer with their full property history already attached. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The patio quote that <em>closes itself</em>",
        "body_html": 'You bid a backyard patio and planting job on a Monday and the homeowner tells you they want to get another price. Normally that is the last you hear of it. Instead the CRM sends a friendly check-in two days later and a short note a few days after that, both written to sound like you. The other two companies never followed up, so when the homeowner is ready on Friday, yours is the only name still in front of them, and they book with you without shopping any further. You never sat down to chase it. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing customers and properties?",
         'Yes. Your current customers, leads, and job history come in and live in one place, with the property details and notes attached, and everything stays yours and exportable. The point is to make the route and customer list you already have actually work for you.'),
        ("Will it really follow up on my install and design quotes automatically?",
         'Yes, on the schedule you approve. An open estimate for a patio, a landscape install, or an irrigation job gets a check-in a few days later and another after that, all sent for you, so a homeowner comparing bids keeps hearing from you while the other companies go quiet. You can jump in and message anyone directly any time.'),
        ("Can it send seasonal and upsell reminders?",
         'Yes. You set the cadence, spring mulch and cleanup, fall aeration and overseeding, a fertilization round at the right time of year, and the reminders go out automatically so the recurring add-on work comes back around without you tracking every date.'),
        ("Can it help me re-sign customers who cancelled over the winter?",
         'Yes, and that is where a lot of a landscaper\'s spring goes. It can flag every customer who paused or dropped off in the off-season and send a well-timed re-up nudge before the route fills, so you rebuild the season with the customers you already earned instead of starting from scratch.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your customers, build your follow-up and reminder sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will find the gap where jobs are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for landscapers"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-landscapers.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting quotes and customers <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your quotes and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================== Online Booking for Landscapers ==========================
{
    "slug": "online-booking-for-landscapers",
    "trade_slug": "landscapers", "trade_plural": "landscapers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for Landscapers",
    "title": "Online Booking for Landscapers | Top Shelf Business Solutions",
    "og_title": "Online Booking for Landscapers",
    "meta_desc": "Online booking for landscapers lets a homeowner self-schedule an on-site estimate for mowing, a cleanup, or a design job on your real availability, so you stop playing phone tag in the spring rush.",
    "service_schema_name": "Online Booking for Landscapers",
    "eyebrow": "For Landscapers",
    "h1_html": "Online Booking <em>for Landscapers</em>",
    "answer_block": "Online booking for landscapers lets a homeowner schedule an on-site estimate for the work that is not urgent, weekly mowing, a spring cleanup, a mulch refresh, a design consult, straight from your website or a text link on your real availability, so you stop playing phone tag in the spring rush and the visit lands on your calendar with the address and details you need.",
    "sections": [
        {"h2_html": "Phone tag is quietly costing you <em>estimates</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">An overgrown yard before a party, a spring cleanup, a homeowner who has finally decided to hire out the mowing, none of these are urgent, and every one of them would happily book an estimate without talking to anyone. In the spring rush, though, your estimator is out walking yards all day, so they call back two hours later, the homeowner is at work, they trade voicemails, a day passes, and the yard gets quoted by the company that could lock in a time on the spot. The estimate was never the problem. The back and forth was.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets a customer grab an open estimate slot the moment they decide, at night or on a lunch break, without reaching anyone first. You wake up to the visit already on the calendar instead of a missed call you now have to chase between stops on the route.</p>'},
        {"h2_html": "It sorts the quick job from the <em>big install</em> before it books",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Self-scheduling does not mean sending a crew across town for nothing. The booking form asks what the job is first, weekly or biweekly maintenance, a one-off cleanup, mulch or sod, a design or hardscape install, an irrigation issue, and a straightforward request books an estimate while a big install gets routed for a quick call. You set the rules: which job types are bookable online, how long each estimate takes, how much notice you need, and which areas you are working on which days.</p>'},
        {"h2_html": "A booking link everywhere a customer <em>finds you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The link goes anywhere someone already meets you: your website, your Google Business Profile, your email signature, your spring-season posts, and the text you send after a call. Every one of those turns from a dead end that needs a callback into a place someone can book you in one tap. A homeowner comparing lawn services on a Sunday night can put an estimate on your calendar before they close the tab, instead of leaving a voicemail they will forget by Monday.</p>'},
        {"h2_html": "On your real calendar, drive-time aware, and the customer shows",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar you already use so it can never double-book a crew against a job you already have, it respects the drive time between stops so your route stays tight, and it sends the customer a confirmation and a reminder, which is what actually cuts no-shows. A crew driving across town to an empty driveway is a wasted slot you never get back. Every booking is logged against the right customer in your CRM, and it works alongside the AI receptionist, which can also book the caller who would rather talk than tap.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Sunday-night lawn-service search, booked <em>before Monday</em>",
        "body_html": 'It is eight on a Sunday night in April and a homeowner has finally had enough of spending every weekend behind a mower. They land on your site, see real reviews, and instead of leaving a voicemail they will second-guess in the morning, they book a weekly-maintenance estimate for Wednesday from the calendar right there on the page. You wake up Monday to the visit already set, with their name, address, and the size of the lot attached. No phone tag, and no season-long customer lost to the company that answered first. Illustrative example, not a client.'},
    "faqs": [
        ("Does it sync to my Google or Outlook calendar?",
         'Yes. It reads your real calendar so it only ever offers times you are actually free, and new estimates drop straight onto it. It cannot double-book a crew or an estimator against a job you already have scheduled.'),
        ("Can it respect drive time so I am not booked across town?",
         'Yes. You set how much buffer to leave between stops and which areas you are working on which days, so it books estimates in a way that keeps your route tight instead of sending you back and forth across the service area.'),
        ("Can I control which jobs are bookable and how long an estimate takes?",
         'Yes. You decide which job types can self-schedule, how long each estimate runs, and how much notice you need, so a quick mowing quote can book itself while a full design or hardscape job is routed to a call first.'),
        ("Will it cut down on no-shows for free estimates?",
         'It helps. Automatic confirmations and reminders by text and email are the single biggest lever on no-shows, and every booking includes them. A homeowner who booked themselves and got a reminder is far more likely to be there than a loosely agreed callback.'),
        ("How fast can it be live?",
         'Setup is included, no separate fee. We connect your calendar, set up your job types and rules, and put the link on your site and profile, so it is taking bookings in days. Start with a free audit and we will find the gap where estimates are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for landscapers"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-landscapers.html", "The AI receptionist that can book callers too"),
        ("crm-for-landscapers.html", "The CRM every booking is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let customers book you <em>while you work</em>",
    "cta_sub": "Get a free audit of how many estimates your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Review Software for Landscapers =========================
{
    "slug": "review-software-for-landscapers",
    "trade_slug": "landscapers", "trade_plural": "landscapers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for Landscapers",
    "title": "Review Software for Landscapers | Top Shelf Business Solutions",
    "og_title": "Review Software for Landscapers",
    "meta_desc": "Review software for landscapers turns every finished yard into a fresh, photo-backed Google review, so your before-and-after work wins the next season of homeowners and the HOA boards comparing crews.",
    "service_schema_name": "Review Software for Landscapers",
    "eyebrow": "For Landscapers",
    "h1_html": "Review Software <em>for Landscapers</em>",
    "answer_block": "Review software for landscapers turns each finished install and clean cut into a fresh, photo-backed Google review, asking at the reveal when the customer loves the yard and making it a single tap. A steady stream of recent reviews, some with before-and-after shots, is what wins the next homeowner and the HOA board comparing crews.",
    "sections": [
        {"h2_html": "Homeowners choose a landscaper by <em>looking at the work</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone wants their yard handled, they do not just skim star ratings, they look. Landscaping is one of the few trades where a customer can judge the quality of your work from a photo before they ever call, so a review with a picture of a lush, finished lawn or a fresh paver walkway does more to win the job than any description could. A profile carrying a few old, text-only reviews sits flat next to a competitor whose recent ones are full of yards that look like the one this homeowner is picturing.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The catch is that thrilled customers rarely think to post, and pulling out your phone to ask while the crew is loading up feels awkward. Review software closes that gap for you, so the standard of work already sitting in your customers\' yards finally lands where the next homeowner is deciding.</p>'},
        {"h2_html": "Ask at the reveal, and let the <em>before-and-after do the talking</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The moment to ask is when the crew pulls back and the homeowner sees the finished yard for the first time, or when a season of tidy cuts has plainly earned it. The request goes out on its own right then, and it points the customer to your Google profile and prompts them to attach a photo. A before shot of a patchy, overgrown lot beside the after is the single most persuasive review a landscaper can gather, because the next visitor sees the exact transformation they are hoping to buy. No cornering anyone at the truck, no card they will lose, and no ask three weeks later once the yard is just the yard.</p>'},
        {"h2_html": "The accounts worth the most <em>read your reviews before they call</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner will hire off a good feeling and a few strong reviews. An HOA board or a commercial property manager is far more cautious, because they are signing a contract that runs all year and answering to other people for the pick. They open your profile, check how recent the reviews are, and watch whether you reply like a professional. A current review history, with a calm and courteous response on each one, tells a decision-maker you will still be dependable in August, and that is what wins the accounts that are worth a whole season on their own.</p>'},
        {"h2_html": "Fresh reviews each season beat a <em>wall built years ago</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Reviews age. A homeowner searching this spring trusts one from last month far more than a glowing note from three years back, and Google leans the same way when it decides who to show. Landscaping hands you a natural rhythm for this, because every spring and summer you finish a run of jobs, and each one is a chance to add a current review right before the next wave of people starts hiring. Left to chance that window slips by and the profile goes stale; worked automatically off each completed job, a fresh layer of proof keeps landing all season. Your reputation stays attached to your own Google profile, never a directory you are renting.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The photo review that <em>won the whole community</em>",
        "body_html": 'A property manager needs a new crew to maintain a neighborhood of common areas and puts the work out to a few companies. Before any of them present, she does what everyone does now and reads their Google profiles. Yours is stacked with reviews from the last few months, several carrying before-and-after photos of entrances and lawns that look a lot like hers, each with a short, gracious reply underneath. The other bidders show a thin page of older reviews and no pictures. She has mostly decided before the walk-through even begins, and the year-long contract goes to the crew whose recent work she could already see. Illustrative example, not a client.'},
    "faqs": [
        ("Can a review include before-and-after photos of the yard?",
         'Yes, and for a landscaper those are the ones that win work. The request nudges a happy customer to attach a picture, so your profile fills with real before-and-after shots of yards you have transformed, which sell the next job far better than words on their own.'),
        ("When does the review request go out?",
         'At the point a customer is most impressed, the day an install is revealed or after a cleanup that changed how the place looks, sent by text and email with a link that opens your Google profile in a tap. You control the timing and wording so it reads like you, not a template.'),
        ("Will good reviews actually help me land HOA and commercial accounts?",
         'They carry real weight there. A board or a property manager is choosing a vendor for a full year and vets you by how recent your reviews are and how you answer them, so a current, well-tended profile is often working on that decision before you ever meet in person.'),
        ("Most of my reviews are a couple of seasons old. Is that a problem?",
         'It can be, since homeowners and Google both favor recent ones. The whole idea here is to keep a new review landing off every finished job through the busy months, so you always have fresh proof up when the next round of people starts choosing a landscaper.'),
        ("Is it against the rules to ask every customer?",
         'No. Inviting every real customer to leave an honest review is encouraged; what is off-limits is hiding the unhappy ones or paying for stars, and this does neither. It just invites everyone at the right time, and saying yes takes a single tap.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for landscapers"),
        ("solution-reviews.html", "How the review system works"),
        ("crm-for-landscapers.html", "The CRM that triggers the ask when a job is done"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Turn finished yards into <em>your next call</em>",
    "cta_sub": "Get a free audit of how your online reputation compares to the landscapers you compete with, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Websites & SEO for Landscapers =========================
{
    "slug": "websites-seo-for-landscapers",
    "trade_slug": "landscapers", "trade_plural": "landscapers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Landscapers",
    "title": "Websites & SEO for Landscapers | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Landscapers",
    "meta_desc": "A landscaper website built for SEO ranks for landscaper near me, lawn care, and landscape design, catches the spring search spike, and puts a gallery of finished yards in front of every visitor.",
    "service_schema_name": "Websites & SEO for Landscapers",
    "eyebrow": "For Landscapers",
    "h1_html": "Websites &amp; SEO <em>for Landscapers</em>",
    "answer_block": "A landscaper website built for SEO turns the spring search rush into booked estimates, ranking for the terms homeowners type when they want a yard done, landscaper near me, lawn care, landscape design, and backing it with a gallery of finished work and a page for every town you mow, so the customer belongs to you, not to a lead broker.",
    "sections": [
        {"h2_html": "Landscaping is a <em>seasonal search</em>, and spring rewards whoever ranks first",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search volume for lawn care and landscaping does not hold steady. It climbs hard in the first warm weeks of the year, when homeowners decide all at once to hire out the yard, and it swells again before fall cleanup. Whoever ranks during those spikes catches a customer who is usually signing on for a whole season, not a single job. Miss the spike and you are invisible during the few weeks when a large share of your year actually gets decided. A site tuned for those searches is how you show up while people are typing landscaper near me, rather than turning up once the rush is already over.</p>'},
        {"h2_html": "Your gallery is the page that <em>sells the job</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most trades cannot show off their work, but you finish yards that people want to look at, which hands your website an asset the others will never have. A gallery of real patios, planting beds, and lawns you have built does two jobs at once: it keeps a visitor scrolling and gives search engines fresh, image-rich pages to rank, and it closes the sale by letting a homeowner picture their own place finished. Grouping the photos by type of work, weekly maintenance, a full design, a paver patio, a new lawn, means a visitor after one specific thing lands on proof you do exactly that.</p>'},
        {"h2_html": "A page for <em>every town on your route</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not work a whole metro, you work the towns and neighborhoods your crews can reach without blowing up the route. One home page cannot rank for all of them, so the site gets its own page for each area you cover, written about that town and the work you do there, so someone searching for lawn care in their particular suburb finds a page that is genuinely about their suburb. That also keeps new customers clustered where you already drive, which protects the route density your margins live on. You begin with the towns that matter most and add more as you grow.</p>'},
        {"h2_html": "Rank for the <em>whole menu, and keep the asset</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Homeowners do not only look for mowing. They search for landscape design, a paver patio, sod installation, sprinkler repair, and fall leaf cleanup, and each one is a separate high-intent search you can own with a page built around it. The larger point is that the site, the gallery, and the town pages all belong to you. They keep ranking through the slow months and cost nothing per call, unlike a pay-per-lead service that vanishes the moment you stop paying and was selling that same homeowner to two or three of your competitors anyway. An audit will lay out every search your area is running that your site does not turn up for yet.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A spring search in <em>one suburb</em>, booked before the season fills",
        "body_html": 'It is early April and a homeowner in a specific suburb searches for landscape design in that town on their phone. Instead of a lead-broker form that would pass the inquiry around, they land on your page for exactly that suburb, scroll a gallery of patios and planting beds you built a few streets over, and book an on-site estimate before they close the tab. You follow up the same day, and because they found you at the very start of the rush, you win the design job and the maintenance that comes after it. You paid nothing for the lead, and no middleman ever sat between you and the customer. Illustrative example, not a client.'},
    "faqs": [
        ("What can a landscaper realistically rank for?",
         'Your own name, the specific towns you cover, and the searches homeowners actually make, landscaper near me, lawn care, landscape design, a paver patio, sprinkler repair. You will not top a national directory for the broadest term overnight, but those local and service-specific searches are the ones a directory has no real answer for.'),
        ("Do I really need a separate page for each town I cover?",
         'For the ones that matter, yes. A single page cannot rank well for a dozen towns at once, so a real page written about each area you work lets you show up when someone searches for lawn care in their own town, and it keeps fresh work clustered where your crews already drive.'),
        ("Does the photo gallery actually help my SEO, or is it just for looks?",
         'Both. A gallery of real, finished yards gives search engines fresh, image-rich content and keeps visitors on the page longer, which supports your ranking, and at the same time it does the selling, since a homeowner who can see work like the yard they want is much more likely to book.'),
        ("My work slows down in winter. Does the website still earn its keep off-season?",
         'Yes, and that is one edge it has over paid leads. The site keeps ranking and gathering inquiries through the quiet months, so homeowners planning spring projects reach you early, instead of your visibility going dark the moment you stop paying for leads.'),
        ("How long before I start showing up?",
         'Local and service-specific searches can begin moving within weeks, while broader terms build over months, so the smart play is to be ranking before the spring spike rather than scrambling during it. Setup is included, and a free audit finds the gap between the searches in your area and what your site ranks for today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for landscapers"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-landscapers.html", "Staying visible in your service area beyond your site"),
        ("crm-for-landscapers.html", "Where every captured lead lands and gets followed up"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your calls, whether you work with us or not. No credit card, never a call center.",
},
# =========================== Marketing for Landscapers ===========================
{
    "slug": "marketing-for-landscapers",
    "trade_slug": "landscapers", "trade_plural": "landscapers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Landscapers",
    "title": "Marketing for Landscapers | Top Shelf Business Solutions",
    "og_title": "Marketing for Landscapers",
    "meta_desc": "Marketing for landscapers keeps your Google Business Profile active and your name first in the map pack, so you catch the spring signup rush the moment a homeowner nearby decides to hire a lawn service.",
    "service_schema_name": "Marketing for Landscapers",
    "eyebrow": "For Landscapers",
    "h1_html": "Marketing <em>for Landscapers</em>",
    "answer_block": "Marketing for landscapers keeps you visible where local demand shows up, your Google Business Profile and the map pack, so when a homeowner nearby decides to hire a lawn service in spring or finally wants a patio built, your name is the active, well-reviewed one they call instead of the company that let its profile go stale.",
    "sections": [
        {"h2_html": "Landscaping demand is <em>local and seasonal</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody shops around for a landscaper for months. Demand is local, because a homeowner wants a crew that already runs their neighborhood and can fit their yard into the route, and it comes in waves. The biggest wave is spring, when homeowners all decide within a few weeks to hire out the lawn for the year, followed by cleanup season in the fall. Being found and trusted in your service area at the moment those waves hit is the whole game, not running clever ads to people who are not thinking about their yard yet.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Get found first in that spring window and you do not win one job, you win a customer for the whole season and often for years. The landscaper who is invisible until the grass is already tall is starting from behind against the one who was already familiar.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for a landscaper near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and above the ads. A profile that sits untouched for months looks abandoned next to one with recent photos of finished yards and installs, current services, and a steady stream of reviews. Keeping it active, complete, and honest is a quiet advertisement running in the exact spot a homeowner looks when they decide it is time to hire.</p>'},
        {"h2_html": "Show up in the <em>towns you actually cover</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and it sends you calls from thirty minutes outside your range that wreck the route density your margins depend on. Focusing on the specific towns and neighborhoods you serve, with a profile, photos, and content built around those areas, is what puts you in the map pack where you can actually take the work and keep your crews driving less between stops. It is a tighter, cheaper target than a citywide spend, and it is the one that turns into a profitable route.</p>'},
        {"h2_html": "Be ready for the season, and stay in front of past customers",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Landscaping demand swings hard with the calendar, the spring signup rush, mulch and cleanup, summer mowing, fall aeration and leaf removal, and being visible right before each wave beats scrambling once it hits. A steady local presence, seasonal posts, photos of finished work, the occasional tip, keeps you top of mind for the season and reminds past customers you are still the crew to call. This is the public-facing side of the business; the private follow-up to people already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The spring rush, and you are <em>already at the top</em>",
        "body_html": 'The first warm week of spring arrives and half the town decides on the same weekend that it is time to hire out the yard. Because your Google profile has been kept active all year, with recent photos of finished lawns and installs, current services, and a steady flow of reviews, you sit at the top of the map pack when everyone searches at once. The homeowners deciding who to hire for the season call the names they can see and trust first, and yours is right there. The company that let its profile go quiet over the winter is nowhere on the map. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with photos of finished yards and installs, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current whenever someone searches for a landscaper near them.'),
        ("What does focusing on my service area actually mean?",
         'It means building your profile and content around the specific towns and neighborhoods you can reach quickly, instead of spreading a budget across a whole metro. That is what gets you into the map pack where the local signups are, and it keeps new customers clustered so your route stays tight.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with people already in your database, your past customers and standing accounts. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at homeowners who are not your customer yet but need to find and trust you when they decide to hire.'),
        ("Can you help me get ahead of the spring rush?",
         'Yes. We time your visibility to the waves that matter, the spring signup rush, mulch and cleanup season, fall aeration and leaf removal, so you are already in front of people before the wave instead of scrambling once the calls start.'),
        ("How long before I see it working?",
         'A neglected profile can climb in the map pack within weeks once it is active and complete, and it compounds from there as reviews and content build. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for landscapers"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-landscapers.html", "The reviews that feed the same Google profile"),
        ("websites-seo-for-landscapers.html", "The website that captures the demand this drives"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the landscaper they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# =========================== Automation for Landscapers ===========================
{
    "slug": "automation-for-landscapers",
    "trade_slug": "landscapers", "trade_plural": "landscapers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for Landscapers",
    "title": "Automation for Landscapers | Top Shelf Business Solutions",
    "og_title": "Automation for Landscapers",
    "meta_desc": "Automation for landscapers sends route reminders, rain-delay reschedule texts, and job follow-ups for you, so a rained-out week does not turn into a day on the phone and nobody wonders when the crew is coming.",
    "service_schema_name": "Automation for Landscapers",
    "eyebrow": "For Landscapers",
    "h1_html": "Automation <em>for Landscapers</em>",
    "answer_block": "Automation for landscapers handles the texts around your route and jobs for you, the heads-up before the crew arrives, the rain-delay reschedule sent to the whole route at once, the estimate follow-up and review request after a job, so a washed-out week does not become a day on the phone and nothing depends on you remembering between stops.",
    "sections": [
        {"h2_html": "When it rains, the whole route shifts, and everyone wants to know <em>when you are coming</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Weather runs a landscaper\'s calendar more than anything else. A rained-out morning bumps every stop on the route, and within an hour the phone is full of customers asking when you will be there, or worse, a commercial account assuming the crew skipped them. Texting each one back is exactly the kind of thing that slips when you are busy reshuffling a whole day of stops on the fly. The work can be perfect and the customer still unhappy simply because nobody told them the schedule moved.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Automation handles those messages for you. A heads-up before the crew arrives, a rain-delay text sent to the whole affected route at once, and a note when a stop moves, all sent automatically, so nobody is left wondering and no account thinks you no-showed while you are out running the rest of the day.</p>'},
        {"h2_html": "Reminders that keep your <em>route full and on time</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A crew that pulls up to a locked gate, a dog loose in the yard, or a car parked over the beds loses the stop and throws off the rest of the route. A confirmation the day before and a heads-up the morning of keep the property ready and the crew moving, and give a customer an easy way to say if today does not work. For an owner running a couple of crews, that is a fuller, tighter route without anyone working the phones to confirm every stop.</p>'},
        {"h2_html": "The follow-up after the job <em>runs itself</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The job is not really done when the trailer pulls away. A quick check that the customer is happy, an automatic review request while the yard is looking its best, and a seasonal reminder, aeration in the fall, mulch in the spring, a fertilization round scheduled for the right month, all matter, and all are easy to forget once you are onto the next stop. Automation fires each one on time, so a finished job turns into a review, an upsell, and the next visit without you keeping a mental list.</p>'},
        {"h2_html": "Cold quotes and lapsed customers <em>come back on schedule</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">An install quote that went quiet and a maintenance customer who dropped off over the winter are not dead, they are just waiting for a reason to call. A scheduled check-in on an open bid, and a spring re-up nudge to a customer who has not been on the route in a while, bring that work back around automatically instead of falling out of your memory. It runs against the same database as your CRM, so nothing here duplicates a customer or a note, and every automated touch is logged where you can see it.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A rained-out Tuesday that does not become <em>a day on the phone</em>",
        "body_html": 'Rain rolls in on a Tuesday morning and the whole day\'s route has to move to Thursday. Instead of your office fielding a stack of calls one by one, the system texts every affected customer at once that the crew will be there Thursday, with a simple line for anyone who needs a different day. The commercial account that would have assumed you skipped them knows exactly when you are coming. By that afternoon the route is reset, nobody is annoyed, and you never picked up the phone to explain the weather. Illustrative example, not a client.'},
    "faqs": [
        ("What messages does it actually send?",
         'The routine ones around your route and your jobs: a confirmation and a heads-up before the crew arrives, a rain-delay text to the whole affected route when the weather moves the day, and a follow-up with a review request after the work is done. You approve the wording so it all sounds like you.'),
        ("Does this replace me or my office talking to customers?",
         'No. It handles the predictable, repetitive texts so nobody has to stop and type them, while you and your team still make every real call and step in personally for anything that needs a conversation, like a commercial account with a special request.'),
        ("Can it reschedule my whole route when it rains?",
         'Yes, and this is where it earns its keep for a landscaper. When the weather moves your day, it can notify every affected stop at once with the new day, so a rained-out morning does not turn into an afternoon on the phone or a customer who thinks you forgot them.'),
        ("Will it send seasonal and follow-up reminders on its own?",
         'Yes. After a job it can schedule a review request and a seasonal reminder, aeration, mulch, or a fertilization round, for the right month, and it can nudge cold quotes and customers who lapsed over the winter, all logged against the customer in your CRM.'),
        ("How long does setup take?",
         'Setup is included with no separate fee. We build the reminder, rain-delay, and follow-up sequences around how you already run your route, so it is working within days. Start with a free audit and we will find the gap where jobs are slipping between your crews, your calendar, and your follow-ups today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for landscapers"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-landscapers.html", "The database every workflow runs against"),
        ("online-booking-for-landscapers.html", "How the visits these remind about get booked"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a customer <em>wonder if you are coming</em>",
    "cta_sub": "Get a free audit of what is currently slipping between your route, your crews, and your follow-ups, whether you work with us or not. No credit card, never a call center.",
},
]
