"""Per-page content specs for the SEO corpus (plan §5), HVAC Companies batch.
generate_corpus.py imports SPECS from a specs module; each dict is one page's UNIQUE,
hand-written, trade-specific content. The generator owns the mechanics (shell, schema,
events, interlinks, keyword placement); the spec owns the substance that clears the
uniqueness gate. Never templated find-and-replace off another trade.

HVAC lives and dies by the seasons. The phones are quiet in the shoulder months and then
flood on the first 100-degree afternoon and the first hard freeze, when half the town loses
cooling or heat on the same day. No cooling in August and no heat in January are emergencies
that come in after hours. The recurring revenue is in maintenance agreements and seasonal
tune-ups; the big tickets are system replacements that get financed and take weeks to decide;
and every system ever installed has an age, which makes an aging unit a replacement lead with
a date on it. SPECS[0] is the AI receptionist and carries "demo": True, so the generator drops
in the live-call demo (same as every batch). Honesty rules: no invented stats, prices, or
clients; benefits are hedged ("often", "typically"); the generator appends the
"Illustrative example, not a client." disclaimer to every example block, so the spec does not
repeat it. Payments is deliberately omitted: HVAC is a card/financing-at-close trade already
covered by the platform's payments page, so a trade-specific payments page would be thin.
"""

SPECS = [
# ==================== AI Receptionist for HVAC Companies ====================
{
    "slug": "ai-receptionist-for-hvac-companies", "demo": True,
    "trade_slug": "hvac-companies", "trade_plural": "HVAC companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for HVAC Companies",
    "title": "AI Receptionist for HVAC Companies | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for HVAC Companies",
    "meta_desc": "An AI receptionist for HVAC companies answers every service call, triages the no-cooling emergency, and books the visit while your techs are out in the field.",
    "service_schema_name": "AI Receptionist for HVAC Companies",
    "eyebrow": "For HVAC Companies",
    "h1_html": "AI Receptionist <em>for HVAC Companies</em>",
    "answer_block": "An AI receptionist for HVAC companies answers every call the moment it comes in, day or night, sorts a no-cooling or no-heat emergency from a routine tune-up, and books the visit onto your dispatch calendar while your techs are up in an attic and the office is slammed. You keep your own number, and every call and customer stays yours.",
    "sections": [
        {"h2_html": "The call you miss on the <em>first 100-degree day</em> is the job your competitor books",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">HVAC demand does not arrive evenly. It shows up all at once on the first real heat wave and the first hard freeze, when half the town loses cooling or heat on the same afternoon and every one of them starts dialing. Your techs are already booked solid and out on calls, the office has three lines ringing at once, and the ones you cannot pick up roll to voicemail. Most people never leave a message. They just call the next HVAC company on the list, and that company books the job that should have been yours.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist answers on the first ring even when every line is busy. It stays calm, finds out whether the caller has no cooling, no heat, or just wants a tune-up, gets the address and the type of system, and books the visit or flags a true emergency, then texts the office the details. The call gets captured and scheduled instead of lost in the flood.</p>'},
        {"h2_html": "Built around how an <em>HVAC company actually runs</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your business does not stop at five o\'clock. The furnace that quits at eleven on a January night and the AC that dies over a holiday weekend are exactly the calls that turn into your biggest tickets, and they never come in during office hours. A voicemail box cannot triage an emergency, and a generic call center reading a script does not know a heat pump from a package unit, or a real emergency from a dirty filter.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24/7, including the after-hours no-heat and no-cooling calls that become same-night service.</li><li>Triages the way a good dispatcher would: no cooling, no heat, water where it should not be, or a routine tune-up, and treats each with the right urgency.</li><li>Books the visit on your real dispatch calendar and texts the office the caller, the address, the system, and the problem on the spot.</li><li>Handles a replacement inquiry differently from a repair, so a homeowner pricing a whole new system is treated as the install lead it is.</li></ul>'},
        {"h2_html": "The math is <em>one emergency call</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to recover many calls for this to pay for itself. One after-hours no-heat emergency you would have missed, or one homeowner pricing a replacement system, which often runs well into the thousands, is worth more than the whole service costs to run for months. Everything it catches after that is margin. The point is to stop losing your peak-season days, the ones when every line is ringing and nobody can pick up, to whoever answers faster.</p>'},
        {"h2_html": "You own the number, the calls, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every booked job, and every customer detail is yours and exportable any time, with no long contract and no holding your data hostage to keep you paying. The AI receptionist is one piece of the Top Shelf platform, and it hands each call straight to the same CRM that follows up on replacement quotes and maintenance renewals, so a lead it captures does not go cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A 10 p.m. no-heat call, while you are <em>off the clock</em>",
        "body_html": "It is 10 p.m. in January and a homeowner wakes up to a cold house and a furnace that will not fire. You are asleep and your techs are done for the day. Instead of voicemail, your AI receptionist answers, confirms there is no heat and no gas smell, gets the address and the type of system, books the first slot in the morning, and flags it as a priority for dispatch. Before your alarm goes off, the office already has the job on the calendar with the address, the system, and the problem. You never missed the call, and the homeowner never dialed anyone else."},
    "faqs": [
        ("Does it work with my current business number?",
         "Yes. It can answer on your existing number, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever leave."),
        ("Can it tell an emergency from a routine call?",
         "Yes. It asks the questions a good dispatcher would, no cooling, no heat, water where it should not be, or a routine tune-up, and treats each with the right urgency. A true no-heat or no-cooling emergency gets flagged for dispatch, and a filter change gets booked into a normal slot."),
        ("Can it actually book onto our dispatch calendar?",
         "Yes. It books straight onto the calendar your office already runs on, based on the availability and service windows you set, and texts the details right away so dispatch can react. You decide how much lead time you need and which slots stay open."),
        ("Will it sound like a robot to my customers?",
         "It answers naturally and professionally, and it is upfront rather than pretending to be a person. Most callers care about one thing, that someone picked up and is handling it, which beats a voicemail box on a 100-degree day every time. You can hear how it handles a live call before you decide."),
        ("How fast can it be answering our calls?",
         "Setup is included with no separate onboarding fee. We configure the triage questions, your dispatch calendar, and the repair and replacement flows for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-hvac-companies.html", "The CRM that follows up on every lead you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing peak-season jobs to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and jobs your current setup is missing on your busiest days, whether you work with us or not. No credit card, never a call center.",
},
# ======================== CRM for HVAC Companies ========================
{
    "slug": "crm-for-hvac-companies",
    "trade_slug": "hvac-companies", "trade_plural": "HVAC companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for HVAC Companies",
    "title": "CRM for HVAC Companies | Top Shelf Business Solutions",
    "og_title": "CRM for HVAC Companies",
    "meta_desc": "A CRM for HVAC companies follows up on every replacement quote and maintenance renewal for you, so recurring revenue and big-ticket jobs do not slip away.",
    "service_schema_name": "CRM for HVAC Companies",
    "eyebrow": "For HVAC Companies",
    "h1_html": "CRM <em>for HVAC Companies</em>",
    "answer_block": "A CRM for HVAC companies keeps every customer, past job, open quote, and maintenance agreement in one place and follows up for you, so a replacement quote from last week and a tune-up plan due to renew stay yours instead of going quiet. The customer list you already have quietly becomes recurring revenue.",
    "sections": [
        {"h2_html": "Your maintenance agreements are <em>recurring revenue you keep losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A maintenance agreement is the best revenue in HVAC. It is predictable, it comes back every year, and a plan member calls you first when something breaks instead of shopping around. But agreements only pay off if they renew, and a renewal depends on someone remembering to reach out before the plan lapses. With hundreds of members and a season that never slows down, that reminder is exactly the task that slips, and a lapsed member quietly becomes someone else\'s customer the next time their system acts up.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM tracks every agreement and its renewal date and reaches out on schedule, by text and email, whether or not anyone in the office remembers. The members you already earned keep renewing, and the recurring revenue you built up does not walk out the door one forgotten renewal at a time.</p>'},
        {"h2_html": "The <em>replacement quote</em> you gave last week is still worth chasing",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A new system is a big decision, and most homeowners do not say yes the day you hand them the quote. They think it over, they compare, they wait on a paycheck or a spouse, and a quote that gets one follow-up call and then silence usually turns into a lost job, not because the price was wrong but because nobody stayed in touch. Most quotes that close need more than one touch, and the second and third touch are the ones that never happen on a busy week.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every open quote is tracked with a follow-up cadence, so a homeowner deciding on a replacement hears from you again instead of forgetting your name.</li><li>Financing reminders go out on the big-ticket jobs, so cost stays a conversation instead of a dead end.</li><li>You can see which quotes are still live, so the one call you have time to make goes to the homeowner closest to saying yes.</li></ul>'},
        {"h2_html": "Aging equipment is a <em>replacement lead with a date on it</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every system you have ever serviced has an age, and a furnace or AC that went in twelve or fifteen years ago is a replacement waiting to happen. That history sits in your files doing nothing. A CRM keeps the install date and the equipment on record for every customer, so you can reach the homeowner whose unit is near the end of its life with a planned-replacement conversation before it dies on the hottest day of the year and they call whoever answers. You are not cold-calling anyone. You are reaching people you already served, about equipment you already know.</p>'},
        {"h2_html": "You own the customer history, not a filing cabinet",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer, every system you installed, every service call, and every note lives in one place instead of a tech\'s memory and a stack of paper invoices, and it stays yours and exportable any time. The CRM is one piece of the Top Shelf platform and plugs into the AI receptionist, so a call it captures lands on the right customer record and gets followed up automatically, and into online booking, so a scheduled tune-up is logged against the system it belongs to.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The replacement quote you <em>almost wrote off</em> closes",
        "body_html": "You quote a homeowner on a new system in the spring. They say they need to think about it, and on a normal week that quote would sit until you forgot it existed. Instead the CRM keeps a light follow-up going, a check-in, a note about financing, a reminder as the heat builds. In July, with their old unit struggling through a heat wave, they call you back, because yours is the name that stayed in front of them, and the quote was still right there in your system. You did not chase it by hand once."},
    "faqs": [
        ("Does it import my existing customers and their equipment history?",
         "Yes. Your current customers, past jobs, open quotes, and maintenance agreements come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already built actually work for you."),
        ("Can it track maintenance agreement renewals for me?",
         "Yes. It keeps every agreement and its renewal date and reaches out automatically before the plan lapses, by text and email, so members renew instead of quietly falling off. You can step in and talk to anyone directly whenever you want."),
        ("How does it help me follow up on replacement quotes?",
         "Every open quote gets a follow-up cadence instead of one call and silence. The homeowner deciding on a new system hears from you again, financing reminders go out on the big jobs, and you can see which quotes are still live so your time goes to the ones closest to closing."),
        ("Can it really tell me whose equipment is getting old?",
         "Yes, because it keeps the install date and the system on record for every customer you have serviced. You can reach the homeowners whose units are near the end of their life about a planned replacement, before it fails on the hottest or coldest day and they call whoever answers first."),
        ("How long until it is set up?",
         "Setup is included with no separate onboarding fee. We bring in your customers and equipment history, build the renewal and quote follow-ups, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will find the gaps where revenue is slipping through today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-hvac-companies.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting renewals and quotes <em>go quiet</em>",
    "cta_sub": "Get a free audit of how many maintenance renewals and open quotes are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Online Booking for HVAC Companies ====================
{
    "slug": "online-booking-for-hvac-companies",
    "trade_slug": "hvac-companies", "trade_plural": "HVAC companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for HVAC Companies",
    "title": "Online Booking for HVAC Companies | Top Shelf Business Solutions",
    "og_title": "Online Booking for HVAC Companies",
    "meta_desc": "Online booking for HVAC companies lets homeowners self-schedule a tune-up or service call on your real dispatch calendar, so you stop playing phone tag on it.",
    "service_schema_name": "Online Booking for HVAC Companies",
    "eyebrow": "For HVAC Companies",
    "h1_html": "Online Booking <em>for HVAC Companies</em>",
    "answer_block": "Online booking for HVAC companies lets a homeowner pick a tune-up or a service visit straight from your website, your Google listing, or a text link, on your real dispatch availability, so you stop playing phone tag and the appointment lands on your calendar with the address and the problem already attached.",
    "sections": [
        {"h2_html": "Phone tag is quietly costing you <em>service calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner\'s AC is making a noise and they want someone to look at it. Your office is closed, or the line is busy, so they leave a message. You call back the next morning, they are at work and cannot talk, you trade voicemails, and two days later they have already booked the company that let them grab a time online at nine the night before. The work was there. The back and forth is what lost it. When someone is ready enough to book, making them wait for a callback is where the job slips away.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets them lock in an open slot the moment they feel the problem, day or night, without reaching the office first. You come off a call to a visit already scheduled instead of a missed call you now have to chase between jobs.</p>'},
        {"h2_html": "It qualifies the job <em>before</em> it books",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Letting homeowners self-schedule does not mean letting anything onto your calendar. The booking form asks what matters first: is it no cooling, no heat, a routine tune-up, or a quote for a new system, what kind of system they have, and whether the address is in your service area, so a real service call books a real slot and an emergency gets routed the right way. You set the rules: how much lead time you need, how long each visit type runs, and which hours and zones are open at all.</p>'},
        {"h2_html": "A booking link everywhere a homeowner <em>finds you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The link goes anywhere a customer already meets you: your website, your Google Business Profile, your email signature, the tune-up reminder you text every spring and fall, and the follow-up after a repair. Every one of those turns from a dead end that needs a phone call into a place someone can book you in one tap. A homeowner deciding on a Sunday night to finally get that pre-season tune-up can put it on your calendar before they close the tab, instead of meaning to call on Monday and never getting to it.</p>'},
        {"h2_html": "On your real dispatch calendar, and the visit shows up",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar your office already runs on, so it can never double-book a tech or hand out a slot you do not have, and it sends the homeowner a confirmation and a reminder, which is what actually cuts down no-shows. Every booking is logged against the right customer in your CRM, and it works alongside the AI receptionist, which can book the caller who would rather talk than tap. The jobs and the calendar stay yours.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Sunday-night homeowner books the <em>tune-up they kept putting off</em>",
        "body_html": "It is 9 p.m. on a Sunday in early spring and a homeowner finally remembers they never had the AC checked before summer. Your office is closed. Instead of a note on the fridge they will ignore, they land on your site, see your real reviews, and book a tune-up for Thursday morning straight from the calendar on the page. You wake up Monday to the visit already scheduled, with their address, their system, and the reason for the visit attached. No phone tag, no slot left empty."},
    "faqs": [
        ("Does it sync to the calendar my office already uses?",
         "Yes. It reads your real dispatch calendar so it only offers times a tech is actually free, and new bookings drop straight onto it. It cannot double-book a crew or hand out a slot you do not have."),
        ("Can it keep emergencies and routine visits separate?",
         "Yes. You can offer different visit types, no cooling, no heat, a tune-up, or a replacement quote, each with its own questions and length, so an emergency is routed the right way and a routine tune-up books a normal slot."),
        ("Will it stop people booking outside my service area?",
         "Yes. The form can check the address or zip against the zones you cover before it confirms, so you are not driving an hour to a job you never should have taken. You set which areas and hours are open."),
        ("Will it cut down on no-shows?",
         "It helps. Automatic confirmations and reminders by text and email are the single biggest lever on no-shows, and every booking includes them. A homeowner who booked themselves and got a reminder is far more likely to be home than a loosely agreed callback."),
        ("How fast can it be live?",
         "Setup is included with no separate fee. We connect your calendar, set up your visit types, service area, and rules, and put the link on your site and Google listing, so it is taking bookings in days. Start with a free audit and we will show you where you are losing appointments today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-hvac-companies.html", "The AI receptionist that can book callers too"),
        ("crm-for-hvac-companies.html", "The CRM every booking is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let homeowners book you <em>while your office is closed</em>",
    "cta_sub": "Get a free audit of how many service calls your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Review Software for HVAC Companies ====================
{
    "slug": "review-software-for-hvac-companies",
    "trade_slug": "hvac-companies", "trade_plural": "HVAC companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for HVAC Companies",
    "title": "Review Software for HVAC Companies | Top Shelf Business Solutions",
    "og_title": "Review Software for HVAC Companies",
    "meta_desc": "Review software for HVAC companies asks every happy customer for a Google review at the right moment and makes it one tap, so your reputation earns the next install.",
    "service_schema_name": "Review Software for HVAC Companies",
    "eyebrow": "For HVAC Companies",
    "h1_html": "Review Software <em>for HVAC Companies</em>",
    "answer_block": "Review software for HVAC companies asks every happy customer for a review right after the tech finishes the job, makes leaving one a single tap, and helps you respond to each, so your reputation keeps bringing in repairs and installs instead of depending on the few customers who remember to post on their own.",
    "sections": [
        {"h2_html": "Before a homeowner spends on a new system, they <em>read your reviews</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A new HVAC system is one of the larger purchases a homeowner makes, and almost nobody hands over that kind of money to a company they have not checked. Before they call, they search, and they read what your past customers said. A thin profile with a handful of old reviews quietly costs you installs you never even hear about, because the homeowner just called the company with the wall of recent five-star reviews instead. Your reputation is doing the selling on the biggest jobs whether you manage it or not.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The problem is rarely that your customers are unhappy. It is that a satisfied homeowner forgets to post once the house is comfortable again, and asking in the moment feels awkward. Review software solves the timing and the awkwardness so the reputation you already earned shows up online, where the buying decision actually happens.</p>'},
        {"h2_html": "Ask at the moment the house is <em>comfortable again</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The best time to ask is the moment the repair is done or the new system fires up and the house finally cools down or warms back up, when the customer is relieved and grateful and the tech is still in the driveway. The software sends the ask automatically right then, by text and email, with a link that takes them straight to your Google profile in one tap. No cornering people, no sticky notes for the crew to remember, and no asking three weeks later once the relief has worn off and the review never gets written.</p>'},
        {"h2_html": "Respond to every review, good or <em>bad</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Answering reviews is not just manners. A calm, specific reply under each one shows the next homeowner you stand behind big-ticket work, and it is one of the signals Google uses to rank you locally. The software alerts you the moment a review posts and helps you answer fast, so the occasional rough one, a missed arrival window or a part that was back-ordered, gets a professional reply in public instead of sitting there in silence, and every good one gets a genuine thank you. On a purchase the size of a new system, how you handle a single complaint often reassures a reader more than a wall of perfect scores.</p>'},
        {"h2_html": "More reviews, more installs, compounding",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Recent reviews feed your Google Business Profile, which lifts you in the map pack a homeowner sees when they search for HVAC repair near them, which brings more calls, which brings more reviews. It builds on itself, and it matters most in the seasons when everyone in town is searching at once. Your reputation is tied to your own profile, and review requests are part of the Top Shelf platform, firing automatically when a job is marked complete in your system.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "One finished install becomes <em>your next one</em>",
        "body_html": "Your crew replaces a system on a Friday and the house is cool again by early afternoon. Right then, the software texts the relieved homeowner a thank-you with a one-tap link, and they post a warm review before dinner. A few weeks later a neighbor whose own AC is on its last summer searches for HVAC companies nearby and reads that exact review at the top of your profile. They call you instead of the name on a truck they saw once. You never asked twice, and your crew was already on the next job when it happened."},
    "faqs": [
        ("Which review sites does it work with?",
         "It focuses on Google, which is where most homeowners look first and what feeds your local search and map pack ranking. It can also point past customers to your other profiles. We follow each platform's own rules, including that a review should come from a customer you actually served."),
        ("When does it ask for the review?",
         "Right after the job is done, when the house is comfortable again and the customer is happiest, sent automatically by text and email with a one-tap link. You can adjust the timing and the wording so it sounds like your company."),
        ("Is automating review requests allowed?",
         "Asking every customer for an honest review is fine and encouraged. What is not allowed is filtering out unhappy customers or paying for reviews, and this does not do that. It simply asks everyone at the right moment and makes it easy to say yes."),
        ("What happens if we get a bad review?",
         "You find out immediately instead of weeks later, and the software helps you post a calm, professional response. On a big purchase like a new system, one thoughtful reply to a critical review, sitting under a wall of genuine positive ones, often reassures the next reader more than a perfect record would."),
        ("How long until it is running?",
         "Setup is included with no separate fee. We connect your Google profile, set the timing and the message, and tie it to your completed jobs, so requests start going out in days. Start with a free audit and we will show you how your reputation stacks up against the HVAC companies you compete with.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-reviews.html", "How the review system works"),
        ("marketing-for-hvac-companies.html", "How those reviews lift you in the map pack"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Turn finished jobs into <em>your next install</em>",
    "cta_sub": "Get a free audit of how your online reputation compares to the HVAC companies you compete with, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Websites & SEO for HVAC Companies ====================
{
    "slug": "websites-seo-for-hvac-companies",
    "trade_slug": "hvac-companies", "trade_plural": "HVAC companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for HVAC Companies",
    "title": "Websites & SEO for HVAC Companies | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for HVAC Companies",
    "meta_desc": "An HVAC company website built for SEO ranks for AC repair near me and captures the no-cooling call, instead of losing it to a shared-lead directory.",
    "service_schema_name": "Websites & SEO for HVAC Companies",
    "eyebrow": "For HVAC Companies",
    "h1_html": "Websites &amp; SEO <em>for HVAC Companies</em>",
    "answer_block": "An HVAC company website built for SEO gets you found when a homeowner in a hot house searches AC repair near me, puts your business in the local map results ahead of the shared-lead directories, and turns that visit into a call before they bounce, so the no-cooling and no-heat jobs in your area are yours instead of a lead sold to three contractors at once.",
    "sections": [
        {"h2_html": "When the AC dies, homeowners search and call the <em>top of the map</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone loses cooling in July, they do not reach for a phone book or think hard about which company to call. They pull out their phone, type AC repair near me, and call one of the first names that comes up, usually a business sitting in the map pack at the top. If your company is not there, you do not exist for that job, no matter how good your work is or how long you have been in town. The homeowner in a hot house is not scrolling to the second page.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Ranking for those searches is not vanity. It is the difference between the emergency landing on your phone or your competitor\'s, on the exact day demand spikes and half your town is typing the same three words at once.</p>'},
        {"h2_html": "Rank for the searches your <em>customers actually type</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Homeowners do not search for heating, ventilation, and air conditioning. They search for AC repair, furnace repair, AC not cooling, no heat, and HVAC installation, each tied to their city or neighborhood and often with an emergency edge. A site built to rank pairs those real searches with the areas you actually serve, so you show up for the specific city-and-service and neighborhood terms a local company can win. A page about AC repair in your town, written for your town, is something a national directory has no reason to build and you can own outright.</p>'},
        {"h2_html": "A homeowner in a hot house should reach you in <em>one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone with no cooling on a 100-degree day has no patience for a slow page or a buried phone number. The site has to load fast, put click-to-call and a booking button in front of them the second they land, and make it obvious you handle emergencies and cover their area, so a visitor in a hurry becomes a booked job instead of a bounce back to the search results. A good-looking site that hides the phone number loses the very customer it just attracted.</p>'},
        {"h2_html": "The traffic is <em>yours</em>, not rented from a lead site",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you send to a shared-lead site buys a call that was often sold to two or three other contractors at the same time, and it stops the day you stop paying. A website you own keeps ranking, keeps capturing calls, and keeps compounding for as long as it exists, and the leads are yours alone, not split with whoever else bought the same name. The site plugs into the same CRM that follows up on every call and quote it brings in, so nothing it earns you goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A no-cooling homeowner skips the directory and <em>calls you</em>",
        "body_html": "It is the first real heat wave and a homeowner two neighborhoods over loses their AC. They grab their phone and search AC repair near them. Instead of a shared-lead directory, they find your site ranking for that exact city-and-service, see that you handle emergencies and cover their area, and tap to call from the top of the page. Your phone rings with a job you paid nothing per lead for, and no directory sold that same homeowner to two of your competitors."},
    "faqs": [
        ("Will my site actually outrank the big directories and lead sites?",
         "For broad national terms, not overnight. For the searches that matter to you, city-and-service terms like AC repair in your town, your neighborhoods, and emergency HVAC, a local company can realistically rank and win, because that is exactly where a national directory has nothing local to offer."),
        ("Do I still need Angi, Thumbtack, or HomeAdvisor if I have my own site?",
         "That is your call, but the point is to own a channel where the leads are entirely yours instead of shared or sold. Many companies keep a lead site running while their own site grows, then lean on it less as their ranking and calls come up."),
        ("How long until it starts ranking?",
         "Local, specific searches can start moving within weeks, and broader terms compound over months. It is worth starting before your busy season, not during it, so you are already ranking when demand spikes and everyone is searching at once."),
        ("Is the site built to get people to call, not just look nice?",
         "Yes. It loads fast, puts click-to-call and a booking button in front of a visitor immediately, and makes your service area and emergency availability obvious, because a homeowner with no cooling calls the company that is easiest to reach, not the prettiest page."),
        ("Do I own the website, or am I renting it?",
         "You own it. The site and domain are registered to you, the content is yours, and every lead it captures lands in your own CRM. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("crm-for-hvac-companies.html", "Where every captured lead lands and gets followed up"),
        ("marketing-for-hvac-companies.html", "Staying visible in the map pack beyond your site"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>AC repair near you</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the companies and lead sites taking your calls, whether you work with us or not. No credit card, never a call center.",
},
# ======================== Marketing for HVAC Companies ========================
{
    "slug": "marketing-for-hvac-companies",
    "trade_slug": "hvac-companies", "trade_plural": "HVAC companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for HVAC Companies",
    "title": "Marketing for HVAC Companies | Top Shelf Business Solutions",
    "og_title": "Marketing for HVAC Companies",
    "meta_desc": "Marketing for HVAC companies keeps you visible before the first heat wave and hard freeze, through your Google Business Profile and steady seasonal content.",
    "service_schema_name": "Marketing for HVAC Companies",
    "eyebrow": "For HVAC Companies",
    "h1_html": "Marketing <em>for HVAC Companies</em>",
    "answer_block": "Marketing for HVAC companies keeps you visible in your service area before demand spikes, not scrambling once it does, through your Google Business Profile, the map pack, and steady seasonal content, so when the first heat wave or hard freeze hits and everyone searches at once, your company is the one already showing up.",
    "sections": [
        {"h2_html": "HVAC demand is <em>seasonal and spiky</em>, and visibility has to come first",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your phone does not ring evenly all year. It is quiet in the shoulder seasons and then explodes on the first 100-degree afternoon and the first hard freeze, when everyone who ignored a struggling system suddenly needs you on the same day. The trouble is that visibility is not a switch you flip when the heat wave hits. The company that shows up first in that moment is the one that was already ranking, already posting, already in front of people for weeks before demand arrived. Waiting until you are slow to start marketing means you are invisible exactly when it counts most.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a homeowner searches for HVAC repair near them, your Google Business Profile and the map pack are often the first thing they see, before your website and before a directory. A profile that sits untouched for months looks abandoned next to one with recent photos, seasonal posts, and a steady stream of fresh reviews. Keeping it active, with real posts about tune-up season, financing on replacements, and the work you are doing, is a quiet advertisement running in the exact moment someone is looking for a company like yours.</p>'},
        {"h2_html": "Fill the <em>slow seasons</em> instead of only surviving the busy ones",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The money in HVAC is not only in the summer emergencies. It is in the tune-ups booked in spring and fall, the shoulder seasons most companies leave on the table. Marketing that pushes pre-season maintenance before the heat and before the cold smooths out the valleys, keeps your techs busy when they would otherwise be idle, and turns a one-time repair customer into a maintenance-plan member who calls you first for years. It is steadier, cheaper business than fighting for the same emergency calls everyone else is chasing in July.</p>'},
        {"h2_html": "Your past customers are your <em>cheapest demand</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The homeowners you have already served are the easiest business you will ever get and the easiest to lose touch with. A steady, low-effort presence, a seasonal tune-up reminder, a note about a financing offer on replacements, a helpful tip before the cold sets in, keeps you top of mind so the repeat call and the referral come to you instead of whoever they saw most recently. This is the public-facing side of your business. The private follow-up to the customers already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The pre-season post that <em>fills your spring</em>",
        "body_html": "Before summer, your Google profile runs steady posts about getting an AC tune-up done before the heat arrives. A homeowner who has been meaning to deal with their aging system sees one while searching, books a tune-up in April instead of waiting for a July breakdown, and signs up for a maintenance plan on the visit. Months later, when their system finally needs replacing, they call you without shopping around, because you are the company that has been in front of them all along. You filled a slow month and earned a plan member and a future install from one post."},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         "Yes. We keep it active with seasonal posts, photos, and updates on a regular schedule, so it looks current whenever a homeowner searches for HVAC near them, especially heading into the busy seasons."),
        ("Why market in the slow season if the phone rings itself in summer?",
         "Because visibility takes weeks to build and the busy-season calls go to whoever was already showing up. Marketing in spring and fall also fills your tune-up schedule, keeps techs busy when they would be idle, and turns one-time repairs into maintenance-plan members who call you first."),
        ("How is this different from the CRM follow-up?",
         "The CRM follows up privately with customers already in your database. Marketing is the public-facing side, your Google profile, the map pack, and seasonal content, aimed at homeowners who are not your customer yet but will recognize your name when their system quits."),
        ("Can you focus on the specific areas I serve?",
         "Yes. The content and posting center on the cities and neighborhoods you actually cover, instead of a generic message spread across a whole metro, so you build recognition where your trucks already go."),
        ("How long before I see it working?",
         "Recognition and ranking build over weeks and months, which is why the companies that win the busy season started marketing during the slow one. Setup is included, and a free audit will show you what your current online presence looks like to a homeowner searching near you today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-hvac-companies.html", "The reviews that feed the same Google profile"),
        ("crm-for-hvac-companies.html", "The private follow-up system behind the scenes"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the company already <em>showing up</em> when the heat hits",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ======================== Automation for HVAC Companies ========================
{
    "slug": "automation-for-hvac-companies",
    "trade_slug": "hvac-companies", "trade_plural": "HVAC companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for HVAC Companies",
    "title": "Automation for HVAC Companies | Top Shelf Business Solutions",
    "og_title": "Automation for HVAC Companies",
    "meta_desc": "Automation for HVAC companies fires seasonal maintenance reminders, sends on-the-way updates, and follows up on quotes, so no visit or lead gets missed.",
    "service_schema_name": "Automation for HVAC Companies",
    "eyebrow": "For HVAC Companies",
    "h1_html": "Automation <em>for HVAC Companies</em>",
    "answer_block": "Automation for HVAC companies handles the routine sequences that keep the work moving, seasonal maintenance reminders that fire themselves, on-the-way updates to the customer, and quote and job follow-ups, so nothing depends on the office remembering to send a text on the busiest week of the year.",
    "sections": [
        {"h2_html": "Seasonal maintenance reminders that <em>fire themselves</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A maintenance plan is only worth what it delivers, and every spring AC tune-up and fall furnace check has to actually get scheduled for the plan to renew and the customer to stay yours. Doing that by hand, calling hundreds of members twice a year to remind them, is exactly the job that slips when the office is buried. Automation sends each member their tune-up reminder on schedule, at the right time of year, with a link to book, so the visits fill in on their own and the plan proves its worth without anyone in the office chasing a list.</p>'},
        {"h2_html": "Every customer knows the tech is <em>on the way</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nothing generates more where-are-they phone calls than a customer sitting home in a hot or cold house waiting on a tech with no idea when he will arrive. Those calls tie up the office on the exact days it is slammed. Automation sends the confirmation when the visit is booked, a reminder the day before, and an on-the-way text when the tech heads out, so the customer stays informed and calm and the office is not the bottleneck fielding status calls all afternoon. The homeowner feels looked after, and dispatch gets its time back.</p>'},
        {"h2_html": "The quote and the job <em>follow up on themselves</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">After a repair, the right next step is often a nudge toward a maintenance plan, and after a replacement quote, it is a follow-up while the homeowner is still deciding. Both are easy to intend and easy to forget. Automation handles the routine version: a plan offer that goes out after a completed repair, and a follow-up sequence on an open quote so a big-ticket install does not go silent after one call. You still make every real call and every real decision. The predictable touches that never happen on a busy week simply happen.</p>'},
        {"h2_html": "A cold lead or an aging system does not have to <em>stay quiet</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Not every homeowner is ready this season. A replacement quote that got a maybe next year, or a lead that went cold, can resurface automatically on a schedule with a light check-in instead of falling out of memory entirely. The same goes for the customer whose system is nearing the end of its life: a planned-replacement nudge before it dies on the worst day. It runs against the same database as your CRM, so nothing here duplicates a customer or a note, it just makes sure the follow-up you meant to do actually happens.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A plan member who books their <em>fall check without a phone call</em>",
        "body_html": "A maintenance-plan member had their AC tuned up in the spring. When the weather starts to turn, the automation sends them a fall furnace-check reminder with a link to book, timed to the season, without anyone in the office pulling a list or making a call. The member books a slot, a tech goes out, the furnace is ready before the first cold snap, and the plan renews on the strength of actually getting used. Nobody in the office remembered to make it happen, and it happened anyway."},
    "faqs": [
        ("What does it actually send automatically?",
         "The routine, predictable touches: seasonal tune-up and furnace-check reminders to plan members, booking confirmations and reminders, on-the-way texts when a tech heads out, post-repair maintenance-plan offers, and follow-ups on open replacement quotes."),
        ("Does this replace my office staff checking in with customers?",
         "No. It handles the routine, repetitive messages so your team is not remembering to send each one by hand. Your office still makes every real call and steps in personally for anything that needs a conversation."),
        ("Can it send on-the-way and reminder texts to customers?",
         "Yes. The customer gets a confirmation when the visit is booked, a reminder the day before, and an on-the-way text when the tech leaves, which cuts down the where-are-they calls that tie up your office on busy days."),
        ("What happens to replacement quotes and leads that go quiet?",
         "They get a scheduled follow-up instead of being forgotten. A maybe-next-year quote resurfaces on a cadence you set, and a customer whose system is near the end of its life gets a planned-replacement nudge before it fails, so old opportunities keep coming back around."),
        ("How long does setup take?",
         "Setup is included with no separate fee. We build the reminder and follow-up sequences around how your company already works and the seasons you run on, so it is running within days. Start with a free audit and we will find the gaps where visits, quotes, and renewals are falling through today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-hvac-companies.html", "The database every workflow runs against"),
        ("online-booking-for-hvac-companies.html", "How the visits these reminders drive get booked"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a visit or a quote <em>go quiet</em>",
    "cta_sub": "Get a free audit of what is currently falling through the cracks between your bookings, your quotes, and your maintenance renewals, whether you work with us or not. No credit card, never a call center.",
},
]
