"""Per-page content specs for the SEO corpus (plan §5), general contractors batch. Same contract as
scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics (shell, schema,
events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns the UNIQUE,
hand-written, general-contractor-specific substance that clears the uniqueness gate. Never templated
find-and-replace, never the plumber or mover content reworded. General contractors sell large,
high-value projects (remodels, additions, whole-project builds) on a long consult-bid-decide cycle,
not same-day emergencies, so the substance leans on responsiveness, follow-up on outstanding bids
over weeks, referral and repeat-client nurture, and a portfolio that earns trust for a big purchase.

Home Services hub. Four service angles here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client." per
the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ==================== AI Receptionist for General Contractors ====================
{
    "slug": "ai-receptionist-for-general-contractors", "demo": True,
    "trade_slug": "general_contractors", "trade_plural": "general contractors",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for General Contractors",
    "title": "AI Receptionist for General Contractors | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for General Contractors",
    "meta_desc": "A general contractor answering service answers every project call, even when you are on a job site, captures the scope, and books the consult for you.",
    "service_schema_name": "AI Receptionist for General Contractors",
    "eyebrow": "For General Contractors",
    "h1_html": "AI Receptionist <em>for General Contractors</em>",
    "answer_block": "A general contractor answering service answers every call the moment it rings, even when you are on a job site and cannot reach the phone, gathers the project details, what they want built, when, and whether they have plans or a budget, and books the consult so the remodel belongs to you instead of the contractor who answered first.",
    "sections": [
        {"h2_html": "The call you miss is the remodel that <em>calls the next contractor</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner planning a kitchen remodel or a room addition is not calling one contractor. They line up three or four, send a couple of emails too, and lean toward the one who answers, sounds like a real, organized company, and gets back to them quickly. General contracting runs on that first impression more than almost any trade, because the homeowner is about to spend a large amount of money and let a crew into their home for weeks, so they are quietly deciding who to trust from the very first contact. But you are on a job site walking a framing crew through a change or meeting an inspector, nowhere near the phone, so the call rings out and the project, worth far more than any single small job, goes to whoever happened to answer.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A general contractor answering service picks up on the first ring, sounds calm and professional, asks what they want to build, gets the scope and the address, and either books the consult or hands you a qualified lead with the details already captured. The project is sitting on your calendar instead of lost to the contractor down the road who happened to be near a phone.</p>'},
        {"h2_html": "Built around how <em>contractors actually get inquiries</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your inquiries do not come in while you are sitting at a desk. They come in while you are coordinating subs, chasing a delivery that showed up short, meeting an inspector, or pricing the next job from the truck between stops, and a lot of them come in the evenings and weekends when homeowners finally sit down to research contractors. A voicemail box cannot hold a serious buyer who is working down a list, and a generic call center reading a script does not know a full gut renovation from a deck rebuild, or which caller is ready to book a consult and which is a year out. Speed matters more than most contractors realize; a homeowner who reaches a real answer while they are still holding the phone rarely keeps dialing down their list, and the one who hits a voicemail almost always does.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers every call and web inquiry, including the nights and weekends when homeowners actually look for a contractor.</li><li>Asks what you would ask: what they want built, roughly when, whether they have plans, drawings, or a budget in mind, and where the property is.</li><li>Books qualified consults straight onto your calendar and texts you the details, so you walk in already knowing the project.</li><li>Treats a referral from a past client, a designer, or an agent differently from a cold web lead, so the people most likely to sign never land in a voicemail box.</li></ul>'},
        {"h2_html": "The math is <em>one signed project</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. A general contractor lives on a small number of large projects, so one remodel or addition you would have lost while your hands were full on a job site is often worth more than the service costs for a long stretch. Missing that call is not a small service ticket you shrug off; it is a whole project, the kind that can carry a slow month, handed to whoever answered faster. Everything it captures after that first save is on top. You are not paying for a receptionist to sit and wait for the phone to ring. You are making sure the one homeowner who was finally ready to spend real money on their house reached an organized business that answered, took down the project, and put a consult on the calendar, instead of a voicemail box they never called back. For a nervous buyer, that first real answer is often what decides which contractor they trust. It also protects the reputation you have built, because a homeowner who cannot reach you does not assume you are busy with good work; they assume you are hard to pin down, and that impression follows a contractor around a small market.</p>'},
        {"h2_html": "You own the number, the calls, and the <em>customer list</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every project detail, and every address is yours and exportable any time, so the client list you are building stays an asset you own instead of something you rent back month to month. There is no long contract holding your data hostage. The answering service is one piece of the Top Shelf platform, and it hands every lead it captures to the same CRM that keeps following up over the weeks a homeowner takes to decide, so a bid or a consult never quietly slips through the gap. The list it builds is the same list your follow-up runs on, so a lead is never captured twice or re-entered by hand, and a homeowner who would rather book the consult themselves can, while the ones who want to talk reach a real, professional answer.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "An after-hours remodel call, <em>booked before morning</em>",
        "body_html": 'It is 8pm and a homeowner who has been saving for a primary suite addition finally sits down and calls the three contractors they found online. The first two ring out to voicemail. Yours answers, sounds calm and professional, asks what they want to build and roughly when, gets the address, and books a consult for Thursday while a note pings your phone. You wake up to a booked appointment with the scope, the timeline, and the homeowner\'s number already attached, instead of hearing weeks later that they hired the contractor who picked up. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every lead that comes through it belong to you and go with you if you ever leave.'),
        ("Can it handle a real project inquiry, or just take a message?",
         'It does not guess at a price. It gathers what a real consult needs, what they want built, roughly when, whether they have plans or a budget, and where the property is, then books the consult on your calendar or hands you a qualified lead. You still set the scope and the price, but the project is captured instead of lost.'),
        ("What happens to calls when I am out on a job site?",
         'That is exactly when it earns its keep. It answers every call and web inquiry the moment it comes in, no matter how buried you are on a site, so the hours you cannot reach the phone stop being the hours you lose the most work.'),
        ("Is it going to sound like a robot to a homeowner?",
         'It answers naturally and is upfront instead of pretending to be a person. Someone about to trust a crew with a major remodel mostly wants to know a real, organized company is handling it, and a steady voice that takes down the project beats a voicemail box every time. You can hear it handle a live call before you decide.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We configure your questions, your calendar, and your lead rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for general contractors"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-general-contractors.html", "The CRM that follows up on every lead you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing remodels to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many project inquiries your current setup is letting slip through the gap, whether you work with us or not. No credit card, never a call center.",
},
# ========================= CRM for General Contractors =========================
{
    "slug": "crm-for-general-contractors",
    "trade_slug": "general_contractors", "trade_plural": "general contractors",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for General Contractors",
    "title": "CRM for General Contractors | Top Shelf Business Solutions",
    "og_title": "CRM for General Contractors",
    "meta_desc": "A CRM for general contractors follows up on every open bid and keeps past clients and referral sources warm, so the next remodel comes back to you.",
    "service_schema_name": "CRM for General Contractors",
    "eyebrow": "For General Contractors",
    "h1_html": "CRM <em>for General Contractors</em>",
    "answer_block": "A CRM for general contractors keeps every lead, open bid, past client, and referral source in one place and follows up for you over the weeks a homeowner takes to decide, so the addition someone is still weighing and the client whose kitchen you built last year both come back to you instead of the contractor who stayed in touch.",
    "sections": [
        {"h2_html": "The bids you already sent are the projects you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most general contractors do not have a lead problem. They have a follow-up problem. You walk the project, put real time into a detailed bid on a remodel or an addition, and then the homeowner goes quiet. They are gathering two or three other numbers, talking it over with a spouse, waiting on financing, and a decision that big rarely lands in a day. Meanwhile you get pulled back onto the jobs you already have, and you never circle back. Weeks later they sign with another contractor, and it is usually not the cheapest one. It is the one who kept in touch and seemed the most on top of things.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open bid in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not the week got away from you. The homeowner comparing contractors hears from you again while the others go silent, and being the organized one that never drops the thread is exactly the signal that wins a nervous buyer on a big project. None of it takes you off the tools, because the follow-up runs in the background while you build, and you step in only when a homeowner actually replies.</p>'},
        {"h2_html": "Every home you build for is a client <em>for the next project</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Past clients are the cheapest work a general contractor can get. You have already earned trust inside their home, they have seen how your crew works, and the next project, the bathroom after the kitchen, the addition two years on, the basement they always meant to finish, is yours if you stay in touch. But you cannot personally remember to reach back out to everyone you have ever built for, so most of that repeat work drifts to whoever turns up when they finally search, long after they have lost your card. The work was good and the relationship was real, and it still slips away, not because anyone was unhappy but because nobody stayed in front of them.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every client, project, photo, and note lives in one place instead of a truck console full of paper and whatever you can remember.</li><li>You can see who you built for a year or two back and reach them with the right reason at the right time, before a competitor turns up in their search.</li><li>Thank-you and referral asks go out after a project wraps, so the happy client who would gladly recommend you actually gets asked while the work is still fresh.</li></ul>'},
        {"h2_html": "The referral and the repeat project are a <em>goldmine you already own</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Word of mouth is how most remodels get won, and it is the warmest lead a builder ever gets, because the trust arrives before you do. A homeowner about to hand a stranger a large check and the keys to their home for months would far rather hire the contractor a friend already vouched for. The people who send you that work, past clients, designers, architects, and real estate agents, are a referral engine you already own, and it runs on staying in touch. A light, genuine touch, a thank-you when the job wraps, a check that everything is holding, a note when the season a client mentioned rolls around, keeps your name in front of the exact people most likely to hand you the next project or pass it along. The same list quietly turns your best referral sources into partners, the designer who brings you into every renovation, the agent who recommends a builder at closing, all sitting in one place where a check-in goes out on schedule without you thinking about it. That, more than any ad, is the biggest lever a general contractor has.</p>'},
        {"h2_html": "You own the list, and it <em>works with the rest of the system</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every client, bid, and note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the answering service, so a call it captures lands in your database and gets followed up on automatically, and to your booking, so a scheduled consult is logged against the right person with their full project history already attached. The result is one place where every project you have quoted, built, or been referred is tracked, and nothing you have earned goes cold in the gap between the first call and the signed contract. You still message anyone directly whenever a project needs a real conversation; the system just makes sure the quiet ones never get forgotten. Over a few years that database becomes one of the most valuable things the business owns, a record of every homeowner who ever trusted you and every project still waiting to happen, and it stays yours no matter what.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The addition bid that <em>closes itself</em>",
        "body_html": 'You bid a rear addition for a homeowner in March and they tell you they need to talk it over and line up financing. Normally that is the last you hear of it. Instead the CRM sends a friendly check-in the next week, a short note a couple of weeks after that, and a nudge when spring arrives, all written to sound like you. The other two contractors never followed up, so when the homeowner is finally ready in May, yours is the only name still in front of them and the only one who felt organized the whole way through. They sign with you without shopping it again. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing clients and past projects?",
         'Yes. Your current clients, leads, and project history come in and live in one place, and everything stays yours and exportable. The point is to make the relationships you have already built actually book you work.'),
        ("Will it really follow up on outstanding bids automatically?",
         'Yes, on the schedule you approve. An open bid gets a check-in days later and more touches over the following weeks, all sent for you, so a homeowner weighing three contractors keeps hearing from you while the others go quiet. You can jump in and message anyone directly any time.'),
        ("Can it keep referral sources and past clients warm?",
         'Yes. It flags clients you built for a year or two back who may be ready for the next project, and it keeps a light, genuine touch going with past clients, designers, and agents who send you work, so the repeat projects and referrals come back around without you keeping track.'),
        ("How is this different from just keeping notes in my phone?",
         'A phone full of contacts does not follow up, does not remind you which bid is going cold, and does not tell you who has gone quiet. The CRM does all of that on a schedule, so the repeat work and the bids you already sent actually turn into signed projects.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your clients, build your follow-up and referral sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where projects are slipping through the gap today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for general contractors"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-general-contractors.html", "The answering service that feeds it every lead"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting bids and clients <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your bids and past clients are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ======================= Marketing for General Contractors =======================
{
    "slug": "marketing-for-general-contractors",
    "trade_slug": "general_contractors", "trade_plural": "general contractors",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for General Contractors",
    "title": "Marketing for General Contractors | Top Shelf Business Solutions",
    "og_title": "Marketing for General Contractors",
    "meta_desc": "General contractor marketing keeps your Google Business Profile active, your project photos and reviews in front of homeowners, and your name first in search.",
    "service_schema_name": "Marketing for General Contractors",
    "eyebrow": "For General Contractors",
    "h1_html": "Marketing <em>for General Contractors</em>",
    "answer_block": "General contractor marketing is less about chasing sudden demand and more about earning trust, the reviews, project photos, and local visibility that make a homeowner comfortable handing you a big remodel, so when someone nearby searches for a contractor, your name is the credible, well-reviewed one they call instead of the company that let its profile go stale.",
    "sections": [
        {"h2_html": "A remodel is a considered purchase, and <em>trust decides it</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody hires the first general contractor they stumble on the way they grab the nearest coffee. A remodel or an addition is a large sum of money and a stranger in the home for weeks, so homeowners research it. They read reviews, look at past work, ask friends and neighbors, and quietly rule out anyone who looks thin or hard to trust before they ever make contact. So marketing for a general contractor is not about shouting the loudest at people who have no project in mind. It is about being easy to find and, far more importantly, easy to believe the moment someone does start looking.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Get that right and you are on the short list before the first call. Get it wrong, a stale profile, no photos of finished work, a handful of old reviews, and you are quietly crossed off a list you never knew you were on. The work you do is good. Marketing is how a homeowner knows that before they let you in the door, and it is why two contractors doing equally solid work can end up with very different phones ringing. The good news is that credibility is buildable; the reviews, the photos, and the visible history of finished work are all things a deliberate marketing effort creates over time.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a homeowner searches for a contractor near them, the map pack, those local listings with the star ratings, is the first thing they see, and it is often their first read on whether you are worth a call. Right beside it sit your reviews and any photos of the work you have posted. A profile that has been quiet for months, with no recent projects and a thin trickle of reviews, looks like a business that is either slow or gone, no matter how good your work actually is. One that is active, complete, and full of real before and after photos of finished kitchens, additions, and renovations looks like exactly the builder a nervous homeowner is hoping to find.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Keeping it current, honest, and stocked with your actual projects is a quiet advertisement running in the precise spot people look when they are deciding who to trust with their home. A steady stream of honest reviews does double duty, it is the proof a cautious buyer wants and one of the signals that lifts you in local search, so the more real projects you turn into reviews, the higher you sit the next time someone nearby searches.</p>'},
        {"h2_html": "Show up in the <em>towns you actually build in</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive, forgettable, and drums up inquiries for projects an hour past where you actually want to work. Focusing on the specific towns and neighborhoods you build in, with a profile, photos, and content tied to those areas, is what puts you in front of the homeowners you can realistically take on. It is a tighter, cheaper target than a citywide spend, and it lines up with how people actually search when a project is on their mind: general contractor near me, home remodeling, room addition, and kitchen remodel in their own town. Being the credible local name for those searches is what turns visibility into signed projects rather than clicks that go nowhere. It is also how you win the neighboring suburbs a searcher there would never assume you cover, because your profile and local pages name those areas plainly instead of leaving people to guess how far you travel for a job. It is the difference between a homeowner three towns over scrolling past you because you look like someone else\'s contractor, and that same homeowner seeing their own town named and deciding you are local enough to call.</p>'},
        {"h2_html": "Feed the referrals, and stay in front of <em>past clients</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The strongest lead a general contractor gets is a warm referral, and a referral almost always ends with the person looking you up before they call. What they find, an active profile, real photos of finished projects, genuine reviews you replied to, is what turns a neighbor mentioning your name into a booked consult. So part of marketing is simply staying visible and current enough that the trust a referral hands you survives the search that follows it. A steady presence, the occasional post of a completed project and a thoughtful reply to a review, keeps you in the conversation and reminds past clients you are still the one to call for the next phase. This is the public-facing side of staying known. The private, one-to-one follow-up with the clients and referral sources already in your database is the CRM, and the two work best together, one bringing new people to your door and the other making sure the people who already trust you never forget you. A referral you fail to follow up on and a past client who forgets your name are the same loss, a warm relationship gone cold, and steady visibility is the cheapest insurance against both.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The neighbor who already <em>trusts your work</em>",
        "body_html": 'A homeowner spends a month working up the nerve to finish their basement. They ask around, and a neighbor mentions the contractor who did their kitchen last year. That night they search your company, and because your Google profile is active, full of real project photos, and backed by recent reviews you actually replied to, everything they find confirms what the neighbor said. They call you already leaning toward yes, instead of treating you like one of three strangers to vet. The referral opened the door, and your marketing is what made walking through it feel safe. Illustrative example, not a client.'},
    "faqs": [
        ("Do you keep my Google Business Profile updated for me?",
         'Yes. We keep it active with photos of your finished projects, updates, and local content on a regular schedule, and keep your services and service area accurate, so it looks current and trustworthy whenever a homeowner searches for a contractor near them.'),
        ("What does focusing on my service area actually mean?",
         'It means building your profile and content around the specific towns and neighborhoods you actually build in, instead of spreading a budget across a whole metro. That is what puts you in front of the local homeowners who can realistically hire you, rather than leads an hour away.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with the clients and referral sources already in your database. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at homeowners who do not know you yet and need to find and trust you before a big remodel.'),
        ("I get most of my work from referrals. Does marketing still matter?",
         'Especially then. A referral sends someone straight to look you up, and what they find, an active profile, real project photos, honest reviews, is what turns a warm mention into a call. Marketing makes your referrals close, and it brings in the homeowners who do not have a neighbor to ask.'),
        ("How long before I see it working?",
         'A neglected profile can climb in local search within weeks once it is active and complete, and it compounds as reviews and project photos build. Setup is included, and a free audit will show you what your current online presence looks like to a homeowner deciding who to trust today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for general contractors"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-general-contractors.html", "The portfolio website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the contractor they <em>already trust</em>",
    "cta_sub": "Get a free audit of how visible and credible you look to a homeowner planning a project right now, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Websites & SEO for General Contractors ====================
{
    "slug": "websites-seo-for-general-contractors",
    "trade_slug": "general_contractors", "trade_plural": "general contractors",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for General Contractors",
    "title": "Websites & SEO for General Contractors | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for General Contractors",
    "meta_desc": "A general contractor website built for SEO ranks for home remodeling and contractor near me, and shows the portfolio and reviews that win a big project.",
    "service_schema_name": "Websites & SEO for General Contractors",
    "eyebrow": "For General Contractors",
    "h1_html": "Websites &amp; SEO <em>for General Contractors</em>",
    "answer_block": "A general contractor website built for SEO ranks for the searches a homeowner makes when planning a project, general contractor near me, home remodeling, room addition, kitchen remodel in your city, and shows the portfolio, reviews, and proof that turn a big, scary purchase into a booked consult, so the lead comes straight to you instead of a directory.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own leads</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a contractor in your town and the top of the page is often a directory or a pay-per-lead marketplace, not a local builder. Those sites publish thousands of pages and carry years of authority, so a homeowner lands there first, fills out a form, and that inquiry gets sold, sometimes to several contractors at once, sometimes back to you for a fee out of your own margin. You do the work of being good, and a middleman collects the rent on your own market. For a general contractor that sting is bigger than for most trades, because the lead being auctioned is not a small repair, it is a whole remodel. Your site not ranking is not a vanity problem. It is the reason a project you should have won for free gets sold to you, or handed to three competitors right alongside you, while the homeowner never even knows the local builder they were hoping for was a click away.</p>'},
        {"h2_html": "Rank for what a homeowner types when <em>planning a project</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for the broadest terms, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you build in, and for the exact things people search when a project is taking shape: general contractor near me, home remodeling, room addition, kitchen remodel, whole house renovation in your city. Pages built around the work you actually do and the areas you actually serve are what search engines, and homeowners deep in planning, reward with the click.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">This kind of search is slower and more considered than an emergency, and that works in your favor. A homeowner researching a remodel over weeks reads more, clicks deeper, and remembers the contractor whose pages actually answered their questions and showed the relevant work. It is also where the higher-value projects live, the full addition, the whole-home renovation, the custom build, searches a national directory never bothers to answer well, and every one of them is a page you can own outright while the directories chase the generic term. Those are the pages that quietly bring in the projects worth building a business around. A single page that ranks for the right remodel search in the right town can pay for the whole site with one project, and then keep paying for years.</p>'},
        {"h2_html": "A homeowner trusting you with their home reads your site <em>before they call</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A remodel is not a low-trust purchase. The homeowner is about to hand a crew of strangers the keys to their home for weeks or months and spend a large amount of money, so before they ever call they are on your site deciding whether you look like a real, established, insured company or just a truck and a business card. That is why a portfolio matters more for a general contractor than for almost any trade. Real photos of finished kitchens, additions, and renovations, honest reviews, and your license and insurance stated plainly are what turn a nervous visitor into a booked consult.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A lot of that deciding happens late at night, when a homeowner finally sits down after the kids are asleep to think through their project, which is exactly when a site that loads fast, looks right on a phone, shows the work, and makes requesting a consult effortless captures the job, instead of a voicemail box nobody is checking or a form buried three clicks deep. The site that respects that moment is the one that gets the call. None of that requires a flashy site, it requires an honest one that loads fast, proves you are real, and puts the work and the contact button where a tired homeowner can find them at a glance.</p>'},
        {"h2_html": "The leads are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you pour into a pay-per-lead service disappears the day you stop paying, and the lead was never really yours anyway, it was sold to your competitors in the same breath. A website you own keeps ranking, keeps capturing inquiries, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you tomorrow. The site plugs into the same CRM that follows up on every inquiry it captures over the weeks a homeowner takes to decide, and the answering service that picks up the calls it drives, so a lead never lands in one place while the follow-up lives in another. The result is one site that ranks, captures, and hands every project straight into the system that closes it, instead of a pretty page that looks nice and loses the lead in the gap between the first click and the signed contract. You are building an asset, not renting attention, and every month it keeps ranking is a month of projects a lead service would have charged you for one at a time.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A kitchen remodel that finds <em>you, not a directory</em>",
        "body_html": 'A homeowner a couple of towns over decides it is finally time to redo their kitchen and searches for a general contractor near them. Instead of a national directory that would sell their details to three builders at once, they find your site ranking for that town, with a page about kitchen remodels and a gallery of finished ones you actually did. They read a few reviews, see that you are licensed and local, and request a consult right there. The inquiry comes straight to you, you paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big directories?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the remodel and project searches a national directory has no reason to target well, which is exactly where a local builder can win.'),
        ("How is this different from paying for leads?",
         'A pay-per-lead service rents you an inquiry it also sells to your competitors, and it stops the day you stop paying. A website you own captures inquiries that are yours alone and keeps working long after it is built, without a fee coming out of every project.'),
        ("Do I really need a portfolio on the site?",
         'For a general contractor, yes. A homeowner spending big on their home is buying trust as much as construction, and photos of your finished work, paired with reviews and clear proof you are licensed and insured, are often what turn a visitor into a booked consult.'),
        ("Do I need to rank for every town I serve?",
         'You rank for the ones that matter most first. We build pages for your core service areas and the highest-value project searches, then expand, rather than spreading thin across a whole metro at once.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for general contractors"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-general-contractors.html", "Staying visible in your service area beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your projects, whether you work with us or not. No credit card, never a call center.",
},
]
