"""Per-page content specs for the SEO corpus (plan §5), tree services batch. Same contract as
scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, tree-service-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber content reworded.

Home Services hub. Four service angles are here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client."
per the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ========================= AI Receptionist for Tree Services =========================
{
    "slug": "ai-receptionist-for-tree-services", "demo": True,
    "trade_slug": "tree_services", "trade_plural": "tree services",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Tree Services",
    "title": "AI Receptionist for Tree Services | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Tree Services",
    "meta_desc": "A tree service answering service answers every storm and after-hours call, tells a tree on a house from an estimate, and books it while your crew runs the saw.",
    "service_schema_name": "AI Receptionist for Tree Services",
    "eyebrow": "For Tree Services",
    "h1_html": "AI Receptionist <em>for Tree Services</em>",
    "answer_block": "An AI receptionist for tree services answers the moment the phone rings, storm night or Sunday, tells a tree through a roof apart from a routine trimming quote, and books the job while your crew is thirty feet up in a bucket truck running a saw. You keep your own number, and every call is yours.",
    "sections": [
        {"h2_html": "The call you miss after a storm is the job that <em>goes to the next crew</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a storm rolls through, the phone does not ring once, it rings all at once. Every homeowner on the block with a limb on the roof, a trunk across the driveway, or a tree leaning on the power line is calling at the same moment, and they are all calling more than one company. A tree on a house is not something anyone leaves a voicemail about and then waits on. They call down the list until a person picks up, and the crew that answers is the crew that gets the work, often the whole street of it.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">But when the storm hits, you are already out on a job with a saw running, tied off in a canopy, or feeding the chipper, and nobody near the truck can hear the phone over the noise. So the surge you waited all season for rolls to voicemail, and the emergency removals, the ones that pay the most and cannot wait, go to whoever happened to be standing next to their phone. An AI receptionist answers every one of those calls on the first ring, stays steady with a rattled homeowner, finds out whether a tree is on the house or just down in the yard, gets the address, and either books it or flags it to you as a real emergency on the spot.</p>'},
        {"h2_html": "Built around how tree services <em>actually get calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your work does not let you answer the phone. A ground crew running saws and a chipper cannot hear it, a climber forty feet up is not going to take a call, and the estimate you are walking is a conversation you cannot interrupt every time a new lead rings in. Meanwhile the calls range from a genuine emergency to a homeowner who just wants a price on taking down a dead oak someday, and a voicemail box cannot tell those two apart or tell the panicked one that help is coming.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers day and night, including the storm-night emergency and the weekend limb on a roof that are your best-paying calls.</li><li>Triages the way you would: is a tree on a structure or a vehicle, is it near a power line, is anyone in danger, or is this a routine quote for a removal, a trim, or stump grinding that can wait.</li><li>Gets the address and the details, books the estimates and routine work on your calendar, and texts you the true emergencies at once so you decide whether to pull a crew off what they are doing.</li><li>Treats a repeat customer or a referral differently from a first-time caller, so the people who already trust you never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one storm removal</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Catching even a handful of these calls pays for the whole thing. One emergency removal after a storm, the kind of job that has you there the same day with a bucket truck and a full crew, is often worth more than the system costs for months, and that storm work is usually your highest-margin ticket of the year. Every estimate and routine trim it captures after that first save is on top. The point is to stop handing the surge you count on to the outfit that simply answered while your saws were running.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">And the surge is not spread evenly across the year. It lands in a few days after each big blow, exactly when every crew in town is slammed and homeowners are anxious and ready to hire the first company that shows up prepared. Being the one that answers in that window, instead of the one calling people back two days later, is the difference between a booked week and a quiet one.</p>'},
        {"h2_html": "You own the number, the calls, and the <em>customer list</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It answers on the number your trucks already carry, or a fresh one put in your name, never ours. Every caller, every address, and every job detail is yours and exportable any time, so the customer list you build stays an asset you own instead of something you rent back month to month, and it is there for you whether you stay with us for years or leave tomorrow. No multi-year contract sits on top of your data. The AI receptionist is one piece of the Top Shelf platform, and it hands every call it captures straight to the same CRM that follows up, so an estimate you quoted or a seasonal trimming reminder never slips through the cracks between jobs. It earns its keep the first stormy weekend, and it keeps earning it on the quiet days by catching the estimate calls that used to roll to voicemail while you were up in a tree.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A midnight tree through the roof, booked while you <em>sleep</em>",
        "body_html": 'It is the middle of the night in a bad windstorm and a homeowner wakes to a branch punched through the bedroom ceiling. They search for a tree service and call the first three they find. Two go to voicemail. Yours answers, stays calm, confirms nobody is hurt and the family is out of that room, gets the address, and books your crew for first light while flagging it to your phone as urgent. You wake up to the job already on your calendar with the address, the problem, and the customer\'s number attached, instead of hearing about it after they hired someone else. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever leave.'),
        ("Can it tell a real emergency from a routine estimate?",
         'Yes, that is the point. It asks the questions you would, is a tree on a house or a vehicle, is it near a power line, is anyone in danger, and treats that as urgent while booking a someday removal, a trim, or a stump grind as routine. You set what counts as a drop-everything emergency.'),
        ("Will it actually book the job on my calendar?",
         'Yes. Estimates and routine work land straight on your calendar based on your availability, and you get a text with the details right away. For a true emergency it can book the first open slot and alert you at once so you decide whether to pull a crew off what they are on.'),
        ("Is it going to sound like a robot to a panicked homeowner?",
         'It answers naturally and calmly, and it is upfront instead of pretending to be a person. Someone staring at a tree on their roof mostly needs to know a real crew is handling it, and a steady voice that captures the details beats a voicemail box every time. You can hear it handle a live call before you decide.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We configure your triage questions, your calendar, and your emergency rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for tree services"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-tree-services.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing storm calls to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and after-hours jobs your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ================================ CRM for Tree Services ================================
{
    "slug": "crm-for-tree-services",
    "trade_slug": "tree_services", "trade_plural": "tree services",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Tree Services",
    "title": "CRM for Tree Services | Top Shelf Business Solutions",
    "og_title": "CRM for Tree Services",
    "meta_desc": "A CRM for tree service companies follows up on every estimate and past customer for you, so a removal you bid and a yard you trimmed both call you back.",
    "service_schema_name": "CRM for Tree Services",
    "eyebrow": "For Tree Services",
    "h1_html": "CRM <em>for Tree Services</em>",
    "answer_block": "A CRM for tree service companies keeps every lead, past customer, and open estimate in one place and follows up for you, so the removal a homeowner is sitting on and the property you trimmed two years ago both call you next instead of the crew that stayed in touch. Your customer list quietly becomes your pipeline.",
    "sections": [
        {"h2_html": "The estimates you already walked are the jobs you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most tree services do not have a lead problem. They have a follow-up problem. You drive out, walk the property, and give a homeowner a price on taking down a big oak or clearing a fence line, and they tell you they need to think about it or talk to a spouse. Then the next storm hits, the schedule fills, and you never circle back. They collect two or three other bids, and the job goes to whoever followed up, not always the lowest number. The estimate was never dead. It just needed one more call or text a few days later, and that is the thing there is never time for between removals.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open estimate in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not you remember. The homeowner weighing three bids on a costly removal hears from you again while the other crews go quiet, and the job comes back to you without you sitting down at a desk to chase it.</p>'},
        {"h2_html": "Every property you touch is a customer <em>for as long as the trees keep growing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Past customers are the cheapest work a tree service can get. You have already been on the property, you know the trees, and they already trust your crew around their house and their lines. The thing about trees is that they do not stop. The oak you thinned this year needs it again in a few, the hedge keeps coming back, and the storm-damaged limbs you cleaned up have neighbors that will fail next. But you cannot personally remember to reach back out to every yard you have ever worked, so most of that repeat work goes to whoever a homeowner happens to find when they forget your name.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, address, tree history, and note lives in one place instead of a truck full of paper estimates and your memory of the property.</li><li>Seasonal reminders go out on schedule, dormant-season pruning in winter, a trim before the next storm season, a check on the trees you treated, so the work comes back around without you tracking dates.</li><li>You can see who has not called in a while and reach the right property with the right reminder at the right time of year.</li><li>A homeowner who called once about one dead tree becomes a standing account for everything else on the lot.</li></ul>'},
        {"h2_html": "The yards you trimmed once are still <em>yours to keep</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner you helped two years ago is not disloyal when they call another company. They simply misplaced your card and never punched your number into their phone. A steady, light touch, a seasonal note before the wind picks up, a reminder that the tree you topped is due for another look, keeps your name in their phone so the next removal and the next cleanup come to you. Reactivating past customers for seasonal trimming is some of the easiest money a tree service leaves on the table, because the trust and the property knowledge are already there. It costs almost nothing to send, and it is the difference between a one-time job and a customer for the life of the yard.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The seasons do the selling for you. Late winter is the time to prune while trees are dormant, the weeks before storm season are when a nervous homeowner wants weak limbs gone, and a dry spell is when dead wood becomes an obvious hazard. A reminder that lands right before each of those moments reaches a customer who is already thinking about their trees, which is why reactivation works so much better than chasing strangers.</p>'},
        {"h2_html": "You own the list, and it works with <em>the rest of the system</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every property note is yours to export whenever you want, not trapped inside rented software. The CRM is one piece of the Top Shelf platform and connects to the AI receptionist, so a storm call it answers lands in your database and gets followed up on automatically, and to online booking, so a scheduled estimate is logged against the right property with its full history already attached. Nothing you have earned in the field goes cold back at the shop.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">That connection matters most right after a storm, when a flood of new calls could easily turn into names on scraps of paper that never get entered. Here they land in the same list as your regulars, tagged and ready for the follow-up that turns a one-time emergency cleanup into a customer who calls you for the pruning next spring. That is how a busy storm week becomes a fuller schedule for the rest of the year, instead of a stack of one-off jobs you never hear from again.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The removal estimate that <em>closes itself</em>",
        "body_html": 'You walk a property on a Monday and quote a homeowner on taking down two dead pines near the house. They tell you they want to get another price. Normally that is the last you hear of it. Instead the CRM sends a friendly check-in two days later and a short note a few days after that, both written to sound like you. The other two crews never followed up, so when the homeowner is ready that Friday, yours is the only name still in front of them, and they book with you without shopping any further. You never sat down to chase it. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing customers and past jobs?",
         'Yes. Your current customers, leads, and job history come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already have actually work for you instead of sitting in a drawer.'),
        ("Will it really follow up on estimates automatically?",
         'Yes, on the schedule you approve. An open estimate gets a check-in a few days later and another after that, all sent for you, so a homeowner comparing bids on a removal keeps hearing from you while the other crews go quiet. You can jump in and message anyone directly any time.'),
        ("Can it send seasonal trimming reminders?",
         'Yes. You set the cadence, dormant-season pruning, a trim before storm season, a check on trees you treated, and the reminders go out automatically so recurring work comes back around without you tracking every property and date.'),
        ("How is this different from just having their number in my phone?",
         'A phone full of contacts does not follow up, does not remember which yard is due for a trim, and does not tell you which estimate is going cold. The CRM does all of that on a schedule, so the repeat work actually shows up instead of depending on you to remember.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your customers, build your follow-up and reminder sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where jobs are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for tree services"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-tree-services.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting estimates and customers <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your estimates and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ============================= Marketing for Tree Services =============================
{
    "slug": "marketing-for-tree-services",
    "trade_slug": "tree_services", "trade_plural": "tree services",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Tree Services",
    "title": "Marketing for Tree Services | Top Shelf Business Solutions",
    "og_title": "Marketing for Tree Services",
    "meta_desc": "Tree service marketing keeps your Google Business Profile active and your name first in the map pack, so you catch local demand the moment a storm hits.",
    "service_schema_name": "Marketing for Tree Services",
    "eyebrow": "For Tree Services",
    "h1_html": "Marketing <em>for Tree Services</em>",
    "answer_block": "Marketing for tree services keeps you visible where local demand shows up, your Google Business Profile and the map pack, so when a homeowner nearby searches after a storm or for a big removal, your name is the active, well-reviewed one with photos of clean, safe work, not the crew that let its profile sit.",
    "sections": [
        {"h2_html": "Tree work demand is <em>local and sudden</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody shops around for a tree service for weeks. Demand appears the instant a storm drops a limb, a tree starts leaning toward the house, or a homeowner finally decides the dead one out back has to go, and it is intensely local, because they want a crew that can be at their property this week, not one across the metro. That means the whole game is being visible and trusted in your service area at the exact moment someone nearby needs you, not running clever ads to people who are not looking at their trees yet. Get found first in that moment, and the job is usually yours.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A storm makes that even sharper. When the wind comes through, half a neighborhood needs a crew on the same morning, everyone is searching at once, and they are anxious and ready to hire fast. The company that is already visible and already trusted when that wave hits catches it. Miss it, and you are calling a homeowner back after they have already booked the first crew that showed up in their search.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for a tree service near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and above the ads. A listing nobody has touched in months reads as abandoned beside one showing recent takedowns, current hours, and a steady run of fresh reviews. And for tree work the photos carry extra weight. A homeowner is about to let a stranger run a chainsaw over their roof and around their power lines, so pictures of clean, careful takedowns and a yard left tidy afterward do more to win trust than any slogan. Keeping the profile active, complete, and honest is a quiet advertisement running in the exact spot a homeowner looks when a tree becomes a problem.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Those photos are also your best answer to a homeowner who has heard the horror stories, the crew that dropped a limb through a fence or left ruts across the lawn. A profile full of before-and-after shots of tidy, professional work quietly settles that fear before they ever call, which is exactly why an active gallery beats a stale listing with two blurry pictures from years ago.</p>'},
        {"h2_html": "Show up in the <em>towns you actually cover</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and it sends you calls from an hour outside your range for a job you cannot reach in time. Building your profile, photos, and content around the specific towns you actually drive to is what lands you in the map pack for jobs you can really take. It is a tighter, cheaper target than a citywide spend, and it is the one that turns into removals and trims you can schedule this week instead of leads you have to turn down.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">It also keeps the calls worth taking. A profile built around your real coverage area draws homeowners who are actually inside it, so your phone rings with jobs you can reach and price well instead of tire-kickers forty-five minutes away. That focus is the quiet difference between a busy, profitable schedule and a phone that rings a lot without filling the week.</p>'},
        {"h2_html": "Stay ready for storm season, and stay in front of <em>past customers</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Tree work swings hard with the calendar and the weather, storm-damage cleanup after every big blow, dormant-season pruning in the cold months, dead and hazardous limbs that show up in a dry summer, and being visible right before each wave beats scrambling once it hits. A steady local presence, seasonal posts, job photos, the occasional tip about what to watch for on an aging tree, keeps you top of mind for the emergency and reminds past customers you are still the crew to call. This is the public-facing side of the business, the part that reaches homeowners who are not yours yet. The private follow-up to the people already in your database is the CRM.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The seasons are predictable enough to get ahead of. You know the storms are coming, you know winter is the window for structural pruning, and you know a long dry stretch turns dead wood into an obvious hazard. Timing your visibility to land just before each of those, instead of after, is what puts you at the top of the map while the demand is peaking rather than after your competitors have already booked it. The work is coming either way, and the only question is whether it comes to you or to the crew that stayed visible.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The first big storm, and you are <em>already at the top</em>",
        "body_html": 'A line of storms comes through overnight and half the town wakes up to downed limbs and split trunks on the same morning. Because your Google profile has been kept active all year, with recent photos of clean removals, current hours, and a steady flow of reviews, you sit at the top of the map pack when everyone searches at once. The homeowners who need a crew that day call the names they can see and trust first, and yours is right there with pictures of exactly the kind of work they need. The company that let its profile go quiet is nowhere on the map. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with photos of real jobs, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current whenever someone searches for a tree service near them.'),
        ("What does focusing on my service area actually mean?",
         'It means building your profile and content around the specific towns and neighborhoods you can reach quickly, instead of spreading a budget across a whole metro. That is what gets you into the map pack where the local, high-intent calls are, and it keeps you from paying to reach homeowners you cannot get to in time.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with people already in your database. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at homeowners who are not your customer yet but need to find and trust you the moment a tree becomes a problem.'),
        ("Can you help me get ahead of storm and seasonal demand?",
         'Yes. We time your visibility to the waves that matter, storm-damage cleanup, dormant-season pruning, hazard removals in a dry spell, so you are already in front of people before the rush instead of scrambling once the calls start.'),
        ("How long before I see it working?",
         'A neglected profile can climb in the map pack within weeks once it is active and complete, and it compounds from there as reviews and photos build. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for tree services"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-tree-services.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the tree service they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Websites & SEO for Tree Services =========================
{
    "slug": "websites-seo-for-tree-services",
    "trade_slug": "tree_services", "trade_plural": "tree services",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Tree Services",
    "title": "Websites & SEO for Tree Services | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Tree Services",
    "meta_desc": "A tree service website built for SEO ranks for tree removal near me and your city, and captures the caller directly instead of a lead-seller.",
    "service_schema_name": "Websites & SEO for Tree Services",
    "eyebrow": "For Tree Services",
    "h1_html": "Websites &amp; SEO <em>for Tree Services</em>",
    "answer_block": "A tree service website built for SEO ranks for the searches a homeowner makes when a tree has to come down, tree removal near me, emergency tree service, stump grinding in your city, and captures the caller the moment they land, so the job is yours instead of a lead-seller renting your calls back to you.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a tree service in your town and the top of the page is often a directory, a national booking middleman, or a pay-per-lead service, not the local crew. Those sites publish thousands of pages and have years of authority behind them, so when a homeowner searches, they land there first, fill out a form, and that lead gets sold, sometimes to three companies at once, sometimes back to you for a fee out of your own margin. A site that does not rank is not just a bruised ego. It is the reason a call you should have gotten for free gets sold to you, or handed to whichever crew is next in the rotation that week.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The worst part is that you often end up paying twice, once in the fee to a service that ranked in your place, and again in margin because the same lead went to competitors you now have to undercut. Ranking your own site is how you find the gap in that arrangement and step out of it, so the homeowner searching in your town lands on you first and the call was free.</p>'},
        {"h2_html": "Rank for what a homeowner types when a <em>tree has to come down</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You are not going to beat a national directory on a broad term this year, and you do not have to. You can rank for your own name, for the specific towns and neighborhoods you cover, and for the exact searches a homeowner makes when a tree becomes a problem: tree removal near me, emergency tree service after a storm, storm damage cleanup, stump grinding, tree trimming in your city. Those searches carry real intent, someone typing them has a tree they need dealt with now, not someday. Pages built around the services you actually run and the areas you actually serve are what search engines, and anxious homeowners, reward with the click.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">It helps that a lot of tree searches are seasonal and event-driven. A page about storm damage and emergency removals earns its ranking exactly when the weather creates a wave of that search, and a page about dormant-season pruning is ready when the cold months bring it around. A site built around the real shape of tree work captures each of those waves instead of sitting flat while the season passes.</p>'},
        {"h2_html": "A homeowner after a storm should reach you in <em>one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone staring at a limb on their roof is on a phone, not a desktop, and they are not going to read three paragraphs. The site has to load fast, put a tap-to-call button and your service area in front of them right away, and make an emergency obvious to act on, while still giving the homeowner who just wants a trimming quote a simple way to ask for one. A slow, pretty site that buries the phone number is a wasted opportunity, and after a storm, when everyone is searching at once, it is the fast, clear one that catches the call.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">It matters for the routine work too. The homeowner who has been putting off a big removal will finally look you up on a quiet evening, and a site that loads fast, shows real photos and reviews, and lets them ask for an estimate in one tap will book that job while a clumsy one sends them back to the search results. Every visitor who leaves without an easy way to reach you is a job that went to whoever made it simpler.</p>'},
        {"h2_html": "The calls are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Money poured into a pay-per-lead service vanishes the moment you stop paying, and the lead was never truly yours to begin with. A website you own keeps ranking, keeps capturing calls, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you or raise your rate. The site plugs into the same CRM that follows up on every lead it captures and the AI receptionist that answers the calls it drives, so nothing it earns you slips away between the search and the booked job.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">That ownership compounds. A lead service resets to zero the moment the invoice stops, but a site that has been ranking for a year is worth more in its second year, not less, because the authority and the reviews and the pages have all built on each other. It is the one marketing asset in this business that you actually keep, and the calls it brings in are yours to follow up, book, and turn into the repeat customers a rented lead never becomes. Build it once, keep it ranking, and it quietly does the job a lead-seller charges you for every single month.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A tree across the driveway finds <em>you</em>, not a directory",
        "body_html": 'A homeowner two towns over wakes up after a storm to a tree down across the driveway and searches emergency tree service near me on their phone. Instead of a national directory that would sell the lead to three crews, they find your site ranking for that town, with a page about storm damage and emergency removals and a tap-to-call button right at the top. They call you directly, you answer, and the job is yours. You paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big directories?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the emergency and service searches a national directory has no reason to target well, which is exactly where a local tree service can win.'),
        ("How is this different from paying for leads?",
         'A pay-per-lead service rents you a call that it also sells to your competitors, and it stops the day you stop paying. A website you own captures calls that are yours alone and keeps working long after it is built, without a per-lead fee coming out of every job.'),
        ("Do I need to rank for every town I serve?",
         'You rank for the ones that matter most first. We build pages for your core service areas and the highest-intent searches, then expand, rather than spreading thin across a whole metro at once.'),
        ("Most of my calls come from storms. Does a website even help?",
         'Especially then. A storm search happens on a phone the moment a tree comes down, and the crew that shows up in the map pack with a tap-to-call button and real photos of clean work gets the call. A site built for that moment is exactly what captures it.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks, broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for tree services"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-tree-services.html", "Staying visible in your service area beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your calls, whether you work with us or not. No credit card, never a call center.",
},
]
