"""Per-page content specs for the SEO corpus (plan §5), Garage Door Companies batch.
generate_corpus.py imports SPECS from a specs module; each dict is one page's UNIQUE,
hand-written, trade-specific content. The generator owns the mechanics (shell, schema,
events, interlinks, keyword placement); the spec owns the substance that clears the
uniqueness gate. Never templated find-and-replace.

Garage door companies live in a same-day, first-to-answer market: a snapped spring or an
off-track door is an emergency (a car trapped inside, a house that will not lock), and the
repair goes to whoever answers and quotes first. Payments is deliberately omitted for this
batch: these are cash/card-at-the-truck trades already handled by the platform's payments
page, so a trade-specific payments page would be forced and thin.
"""

SPECS = [
# ==================== AI Receptionist for Garage Door Companies ====================
{
    "slug": "ai-receptionist-for-garage-door-companies", "demo": True,
    "trade_slug": "garage-door-companies", "trade_plural": "garage door companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Garage Door Companies",
    "title": "AI Receptionist for Garage Door Companies | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Garage Door Companies",
    "meta_desc": "An AI receptionist for garage door companies answers every broken-spring or stuck-door call and books the same-day repair while your crew is on a job.",
    "service_schema_name": "AI Receptionist for Garage Door Companies",
    "eyebrow": "For Garage Door Companies",
    "h1_html": "AI Receptionist <em>for Garage Door Companies</em>",
    "answer_block": "An AI receptionist for garage door companies answers every call the moment it comes in, day or night, finds out whether it is a broken spring, a door off its track, or a dead opener, and books the same-day repair on your schedule while your tech is under a door. You keep your own number, and every call stays yours.",
    "sections": [
        {"h2_html": "The call you miss is the repair the <em>next company books</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Garage door repair is a speed business. A spring snaps at 6 a.m., the car is trapped inside, the homeowner cannot get to work, and they search "garage door repair near me" and call the first three companies that come up. Whoever answers first and can promise a tech this morning usually gets the job. You are under a door on another call, the phone rolls to voicemail, and most people in that spot do not leave one. They dial the next number.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A missed call here is not small. It is a same-day repair, and sometimes a full door replacement worth far more, walking to the competitor who answered. An AI receptionist closes that gap: it answers on the first ring, stays calm with a stressed caller, finds out what failed and how urgent it is, and books the visit on your schedule before your current job is finished.</p>'},
        {"h2_html": "Built for how <em>garage door calls actually come in</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your phone does not ring on a schedule. Springs break on cold mornings, doors come off track on weekends, and openers quit at night, exactly when a voicemail box or a generic call center is least useful. A script reader does not know a torsion spring from a cable and will not put a job on your calendar.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24/7, including the after-hours broken-spring call and the Saturday off-track door.</li><li>Triages fast: is the door stuck open and the house unsecured, is a car trapped inside, or is this a tune-up that can wait.</li><li>Captures what a tech needs to arrive ready: what failed, the door or opener brand, and repair versus replacement.</li><li>Books the visit on your real calendar and texts you the details on the spot.</li></ul>'},
        {"h2_html": "The math is <em>one job</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not have to recover many calls for this to pay for itself. One emergency repair you would have lost to voicemail, or one full door replacement, which often runs into the thousands, is usually worth more than the system costs for a long stretch. The point is simple: stop handing your same-day jobs to whichever company answered while you were busy.</p>'},
        {"h2_html": "You own the number, the calls, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on the number you already advertise, or a new one registered in your name, not ours. Every caller, every job, and every customer detail is yours and stays yours, exportable any time, with no long contract holding your data hostage. The AI receptionist is one piece of the Top Shelf platform, and it hands each call straight to the same CRM that follows up on quotes and past customers, so nothing it captures goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A broken spring at 6 a.m., while your <em>crew is still asleep</em>",
        "body_html": "A homeowner heads out for work at 6 a.m. and the garage door will not budge. The torsion spring snapped overnight, the door is too heavy to lift by hand, and the car is trapped inside. They call your shop before your crew is even awake. Instead of voicemail, your AI receptionist answers, confirms the broken spring and the stuck car, and books the first repair slot at 8 a.m. Before anyone has clocked in, your phone has a text with the address, the problem, the door size, and the appointment on the calendar. You did not lose that customer to the next company on the list."},
    "faqs": [
        ("Does it work with my current phone number?",
         "Yes. It can answer on the number you already advertise, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever switch providers."),
        ("Can it tell an emergency from a routine call?",
         "Yes. It triages every call: a broken spring with a car trapped inside, or a door stuck open and the house unsecured, is treated as same-day, while a tune-up or quote request is booked accordingly. You set what counts as an emergency and how those reach you."),
        ("Can it actually book the job on my schedule?",
         "Yes. It books straight onto your real calendar based on the availability and service area you set, sends you the details by text right away, and can text the customer a confirmation. You decide the rules, like how much lead time you need and which slots are open for same-day work."),
        ("Will it sound like a robot to a stressed homeowner?",
         "It answers naturally and professionally, and it is upfront rather than pretending to be a person. Someone standing next to a door that will not open mostly wants to know an appointment is set and help is coming, which beats a voicemail box every time. You can hear it handle a live call before you decide."),
        ("How fast can it be running?",
         "Setup is included and there is no separate onboarding fee. We configure the triage questions, your calendar, and your service area for you, so it is answering your calls in days, not weeks. Start with a free audit and we will show you how many calls your current setup is missing.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-garage-door-companies.html", "The CRM that follows up on every lead you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop sending emergencies to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and same-day jobs your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ======================== CRM for Garage Door Companies ========================
{
    "slug": "crm-for-garage-door-companies",
    "trade_slug": "garage-door-companies", "trade_plural": "garage door companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Garage Door Companies",
    "title": "CRM for Garage Door Companies | Top Shelf Business Solutions",
    "og_title": "CRM for Garage Door Companies",
    "meta_desc": "A CRM for garage door companies follows up on every replacement quote and past repair customer for you, so the jobs that take weeks to decide still close with you.",
    "service_schema_name": "CRM for Garage Door Companies",
    "eyebrow": "For Garage Door Companies",
    "h1_html": "CRM <em>for Garage Door Companies</em>",
    "answer_block": "A CRM for garage door companies keeps every repair customer, replacement quote, and lead in one place and follows up for you, so a homeowner still deciding on a new door and a past customer whose opener is aging both come back to you instead of going cold. Your customer list quietly becomes your pipeline.",
    "sections": [
        {"h2_html": "The quotes you already gave are the jobs you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most garage door companies do not have a lead problem. They have a follow-up problem. You go out, look at a sagging or dented door, and hand over a quote for a full replacement. The homeowner says they need to think about it, and they mean it, because a new door is a real decision they usually take a few weeks and two or three quotes to make. Then nobody follows up, and the job goes to whichever company checked back in.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every quote on a follow-up schedule you set, with texts and emails that go out on time whether or not anyone at the shop remembers. The homeowner comparing three companies still hears from you and books with the one that stayed in touch instead of the one they talked to last.</p>'},
        {"h2_html": "Your past customers are the <em>cheapest jobs you will ever get</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Springs wear out, openers age, rollers and cables give up, and the door you serviced three years ago is due again. A past customer already trusts you and costs nothing to win back, but nobody can remember to reach out to every home you have worked on, so most of that repeat business sits unused and slowly forgets who fixed the door last time.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, job, note, and quote lives in one place instead of a truck notebook and three apps.</li><li>Tune-up reminders and check-ins go out on schedule, so past customers hear from you without anyone setting a reminder.</li><li>You can see which quotes are still open and which customers are due, so your time goes to the jobs closest to booking.</li></ul>'},
        {"h2_html": "Answer first, without living on the phone",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A new lead that hears back in the first few minutes is far more likely to book than one that waits an hour, and in a same-day trade the first company to respond usually wins the job. The CRM replies instantly with a text-back the moment a lead comes in and hands it to you with the details, so you are first without watching your inbox from the top of a ladder.</p>'},
        {"h2_html": "You own the customer list, not a lead app",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time. Switch software, change how you run the office, and your list comes with you instead of staying locked inside someone else\'s system. The CRM is one piece of the Top Shelf platform and plugs into the AI receptionist, so a call it answers lands in your list and gets followed up on automatically, and into online booking, so an appointment is logged against the right customer.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The replacement quote you <em>almost forgot</em> turns into a job",
        "body_html": "A homeowner asks for a quote on a new double door after a panel gets crushed backing out. You give them the number, they want to think it over and get one more quote, and you would normally lose track of them within a week. Instead the CRM keeps a light follow-up going for you: a quick check-in, an answer to a warranty question, a note that install slots are filling up. Three weeks later they book the door, and they book it with you, because yours is the company that stayed in touch. You did not chase them once by hand."},
    "faqs": [
        ("Does it import my existing customers and past jobs?",
         "Yes. Your current customers, open quotes, and past jobs come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already have actually work for you."),
        ("Will it really text and email customers automatically?",
         "Yes, on the schedule you approve. New leads get an instant response, and past customers get tune-up reminders and quote follow-ups on a cadence you set, all sent for you. You can always jump in and message someone directly."),
        ("Does this help with past customers, or just new leads?",
         "Both, and past customers are where the quiet money is. A repeat repair or a due tune-up costs nothing to win and books faster than a cold lead, and the CRM keeps you in front of those homes so that work actually comes back instead of going to whoever they find next."),
        ("Do I keep my data if I change software later?",
         "Yes. Your customers and notes are in your name and exportable any time, so you are never locked in. You are not renting access to your own customer list."),
        ("How long until it is set up?",
         "Setup is included with no separate onboarding fee. We bring in your customers, build the follow-up sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will find the gaps where jobs are slipping through today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-garage-door-companies.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting quotes <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your open quotes and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Online Booking for Garage Door Companies ====================
{
    "slug": "online-booking-for-garage-door-companies",
    "trade_slug": "garage-door-companies", "trade_plural": "garage door companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for Garage Door Companies",
    "title": "Online Booking for Garage Door Companies | Top Shelf Business Solutions",
    "og_title": "Online Booking for Garage Door Companies",
    "meta_desc": "Online booking for garage door companies lets homeowners self-schedule a tune-up, a new-door consult, or a non-urgent repair on your real availability.",
    "service_schema_name": "Online Booking for Garage Door Companies",
    "eyebrow": "For Garage Door Companies",
    "h1_html": "Online Booking <em>for Garage Door Companies</em>",
    "answer_block": "Online booking for garage door companies lets a homeowner pick a tune-up, a new-door consult, or a non-urgent repair straight from your website, your Google listing, or a text link, on your real availability, so you stop playing phone tag on the jobs that are not emergencies and the appointment lands on your calendar ready to run.",
    "sections": [
        {"h2_html": "Not every job is a <em>same-day emergency</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A snapped spring is a phone call you want to answer live. But a noisy door that needs a tune-up, a homeowner shopping a new-door consult, or a keypad that stopped working is not an emergency, and those callers do not need to reach you first. They need a time. When you are on a roof of a job and cannot pick up, that homeowner either waits for a callback that trades voicemails for two days or books the next company that let them grab a slot on the spot.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets them pick an open time the moment they think of it, day or night, without reaching you at all. You come off a job to an appointment already set instead of a missed call you now have to chase between other jobs.</p>'},
        {"h2_html": "It asks the right questions <em>before</em> it books",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Self-scheduling does not mean letting anyone drop anything onto your calendar. The booking form asks what matters for a garage door visit, repair or replacement, single or double door, the opener brand, and the address so you know it is in your service area, so a real job books itself and anything unusual gets a quick call first. You set the rules: how much notice you need, how long a tune-up versus a consult runs, drive-time buffers between stops, and which hours are open at all.</p>'},
        {"h2_html": "A booking link everywhere a homeowner <em>finds you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The link goes anywhere a homeowner already meets you: your website, your Google Business Profile, your email signature, and the text you send after a first call. Every one of those turns from a dead end that needs a callback into a place someone can book you in one tap. A homeowner comparing companies on a Sunday night can put a new-door consult on your calendar before they close the tab.</p>'},
        {"h2_html": "On your real calendar, and the tech shows up ready",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar you already use so it can never double-book a crew, and it sends the customer a confirmation and a reminder, which is what actually cuts down no-shows and wasted drive-outs. Every booking is logged against the right customer in your CRM, and it works alongside the AI receptionist, which can book a caller who would rather talk than tap. The jobs and the calendar stay yours.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Sunday-night tune-up booked <em>while you sleep</em>",
        "body_html": "It is 9 p.m. on Sunday and a homeowner finally decides to deal with the door that has been grinding and shaking for a month. It is not an emergency, so they would normally leave a voicemail and forget about it by Monday. Instead they land on your site, see you have real reviews, and book a tune-up for Wednesday morning from the calendar right there on the page. You wake up Monday to the appointment already set, with the address, the door type, and what they said was wrong. No phone tag, no lost job."},
    "faqs": [
        ("Does it sync to my Google or Outlook calendar?",
         "Yes. It reads your real calendar so it only ever offers times a crew is actually free, and new bookings drop straight onto it. It cannot double-book you against a job you already have scheduled."),
        ("Can it respect drive time and stop back-to-back bookings?",
         "Yes. You set how much notice you need, how long each visit type runs, and how much buffer to leave between stops, so a crew is never booked across town with no time to get there."),
        ("Can homeowners book a tune-up and a consult differently?",
         "Yes. You can offer different visit types with their own questions and lengths, so a tune-up, a non-urgent repair, and a new-door consult each capture the details you need for that kind of visit."),
        ("Will it cut down on no-shows and wasted trips?",
         "It helps. Automatic confirmations and reminders by text and email are the single biggest lever on no-shows, and every booking includes them. A homeowner who booked themselves and got a reminder is far more likely to be home than a loosely agreed callback."),
        ("How fast can it be live?",
         "Setup is included, no separate fee. We connect your calendar, set up your visit types and service-area rules, and put the link on your site and Google profile, so it is taking bookings in days. Start with a free audit and we will show you where you are losing non-urgent jobs today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-garage-door-companies.html", "The AI receptionist that can book callers too"),
        ("crm-for-garage-door-companies.html", "The CRM every booking is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let homeowners book you <em>while you work</em>",
    "cta_sub": "Get a free audit of how many non-urgent jobs your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Review Software for Garage Door Companies ====================
{
    "slug": "review-software-for-garage-door-companies",
    "trade_slug": "garage-door-companies", "trade_plural": "garage door companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for Garage Door Companies",
    "title": "Review Software for Garage Door Companies | Top Shelf Business Solutions",
    "og_title": "Review Software for Garage Door Companies",
    "meta_desc": "Review software for garage door companies asks every happy customer for a Google review at the right moment, so your rating wins the same-day comparison.",
    "service_schema_name": "Review Software for Garage Door Companies",
    "eyebrow": "For Garage Door Companies",
    "h1_html": "Review Software <em>for Garage Door Companies</em>",
    "answer_block": "Review software for garage door companies asks every happy customer for a review the moment the door is working again, makes leaving one a single tap, and helps you respond to each, so your rating is the one that wins when a homeowner is comparing three companies at once instead of depending on the few customers who post on their own.",
    "sections": [
        {"h2_html": "The same-day search is a <em>side-by-side comparison</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a spring breaks or a door will not close, a homeowner does not research for a week. They search "garage door repair near me," see a short list of companies with a star rating and a review count next to each, and call the ones that look most trusted, often within a few minutes. That rating and that count are doing the comparing for you, in the exact moment someone is ready to book.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A thin profile with a handful of old reviews quietly loses those calls to the company with a wall of recent ones, and you never hear about the job you did not get. The problem is usually not unhappy customers. It is that happy ones forget to post, and asking in the moment feels awkward. Review software solves the timing and the awkwardness so the reputation you have earned actually shows up where the comparison happens.</p>'},
        {"h2_html": "Ask at the moment they are <em>happiest</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The best time to ask is the minute the repair is done, when the door glides shut again and the tech is still in the driveway. The software sends the ask automatically at that moment, by text and email, with a link that takes the customer straight to your Google profile in one tap. No cornering anyone, no cards that get lost, and no asking three weeks later when the relief has worn off.</p>'},
        {"h2_html": "Respond to every review, good or <em>bad</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A thoughtful reply to each review tells the next homeowner reading it that you are engaged and professional, and responding is one of the signals that helps you show up in local search. The software flags every new review the moment it lands and helps you reply quickly, so a rare critical one gets a calm, professional response instead of silence, and every good one gets a thank you.</p>'},
        {"h2_html": "More reviews, more calls, compounding",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Recent reviews feed your Google Business Profile, which lifts you in the local map results a homeowner sees when they search for repair, which brings more calls, which brings more reviews. It builds on itself. Your reputation is yours, tied to your own profile. Review requests are part of the Top Shelf platform and fire automatically off a job marked done in your CRM, so the ask goes out every time without anyone remembering.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "One repair becomes the review that <em>wins the next call</em>",
        "body_html": "Your tech replaces a broken spring on a Friday afternoon and the door runs like new. Before he pulls away, the software texts the customer a thank-you with a one-tap link, and they post a warm review before dinner. The next week a homeowner a few streets over has a spring go, searches for repair, and sees your company at the top with that fresh five-star review right under it. They call you instead of the shop with three old reviews. You never asked twice, and you were on another job when it happened."},
    "faqs": [
        ("Which review sites does it work with?",
         "It focuses on Google, which is where most homeowners look first and what feeds your local map ranking. It can also point past customers to your other profiles. We follow each platform's own rules, including that a review should come from someone you actually did work for."),
        ("When does it ask for the review?",
         "Right after the job is done, when the customer is happiest, sent automatically by text and email with a one-tap link. You can adjust the timing and the wording so it sounds like your company."),
        ("Is automating review requests allowed?",
         "Asking every customer for an honest review is fine and encouraged. What is not allowed is filtering out unhappy customers or paying for reviews, and this does not do that. It simply asks everyone at the right moment and makes it easy to say yes."),
        ("What happens if I get a bad review?",
         "You find out immediately instead of weeks later, and the software helps you post a calm, professional response. One thoughtful reply to a critical review, sitting under a wall of genuine positive ones, often reassures the next reader more than a perfect record would."),
        ("How long until it is running?",
         "Setup is included with no separate fee. We connect your Google profile, set the timing and the message, and tie it to your completed jobs, so requests start going out in days. Start with a free audit and we will show you how your rating stacks up against the companies you compete with.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-reviews.html", "How the review system works"),
        ("crm-for-garage-door-companies.html", "The CRM that triggers the ask when a job is done"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Win the <em>side-by-side comparison</em>",
    "cta_sub": "Get a free audit of how your online rating compares to the garage door companies you compete with, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Websites & SEO for Garage Door Companies ====================
{
    "slug": "websites-seo-for-garage-door-companies",
    "trade_slug": "garage-door-companies", "trade_plural": "garage door companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Garage Door Companies",
    "title": "Websites & SEO for Garage Door Companies | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Garage Door Companies",
    "meta_desc": "A garage door company website built for SEO ranks for garage door repair near me and captures the emergency call, instead of handing it to a pay-per-lead middleman.",
    "service_schema_name": "Websites & SEO for Garage Door Companies",
    "eyebrow": "For Garage Door Companies",
    "h1_html": "Websites &amp; SEO <em>for Garage Door Companies</em>",
    "answer_block": "A garage door company website built for SEO ranks for the searches homeowners actually make, like garage door repair near me, shows up in local results before the pay-per-lead sites, and captures the call the moment someone lands, so the traffic and the jobs belong to you instead of a lead middleman selling the same call to three companies.",
    "sections": [
        {"h2_html": "The lead sites are not competing with you, they are <em>selling you your own calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The big pay-per-lead sites and directories outrank most individual garage door companies because they publish thousands of pages and have years of authority behind them. A homeowner searching for repair often lands on one of those first, fills out a form, and the lead gets sold to two or three companies at once, sometimes including you, at a price per lead. Your site not ranking is not just a vanity problem. It is the reason a call you should have gotten for free gets sold back to you, and shared with the competitors you are bidding against.</p>'},
        {"h2_html": "Rank for the searches you can <em>actually win</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for every broad term, and you do not need to. You can rank for the towns and neighborhoods you actually serve, and for searches like "garage door repair [city]," "broken spring repair [city]," or "[city] garage door installation," where a national lead site has nothing local to say and your site can. Pages built around the doors and opener brands you service, the areas you cover, and the specific problems you fix are what search engines, and homeowners, reward.</p>'},
        {"h2_html": "A visitor should not be able to leave your site <em>without becoming a call</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most of these searches happen on a phone, next to a door that will not open, so the site has to load fast and put a tap-to-call button and a quote request in front of the visitor before they scroll. A pretty site that buries the phone number is a wasted opportunity. The point is to turn a stressed homeowner into a call or a booked job in your CRM, not a number in a traffic report.</p>'},
        {"h2_html": "The traffic is <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you spend per lead disappears the moment you stop paying, and the lead was never only yours to begin with. A website you own keeps ranking, keeps capturing calls, and keeps compounding in value for as long as it exists, and it is registered to you, not a lead platform you rent. The site plugs into the same CRM that follows up on every call it captures, so nothing it earns you goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A homeowner skips the lead site and calls <em>you</em> instead",
        "body_html": "Someone in a suburb you cover has a door come off track and searches for garage door repair on their phone. Instead of a shared lead form, they find your site ranking with a page for that exact town and the repair they need, and a tap-to-call button right at the top. They call you directly, your CRM logs it, and a tech is scheduled that morning. You paid nothing per lead, and no middleman sold that same call to two of your competitors."},
    "faqs": [
        ("Do I still need the pay-per-lead sites if I have my own site?",
         "Maybe, for now. Some companies keep them running while their own site gains ground. The point is not to replace them overnight, it is to also own a channel where the calls are entirely yours instead of shared or sold."),
        ("Will my site actually outrank the big directories?",
         "Not for every broad national term. It can realistically rank for the specific towns you serve and long-tail local searches a national lead site has no reason to target, which is exactly where a local garage door company can win."),
        ("Is it built to work on a phone?",
         "Yes, that is the priority. Most repair searches happen on a phone in an emergency, so the site is built to load fast and put tap-to-call and a quote request in front of the visitor first."),
        ("My current site never brings me calls. Why would this?",
         "Usually because the current site does not rank for local searches and hides the phone number. This one is built to rank for the areas you serve and to turn a visitor into a call or a booked job in your CRM, not just to look nice."),
        ("How long until it starts ranking?",
         "Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("crm-for-garage-door-companies.html", "Where every captured call lands and gets followed up"),
        ("marketing-for-garage-door-companies.html", "Staying visible in your service area beyond your site"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search for <em>garage door repair near you</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the lead sites sending your calls somewhere else, whether you work with us or not. No credit card, never a call center.",
},
# ======================== Marketing for Garage Door Companies ========================
{
    "slug": "marketing-for-garage-door-companies",
    "trade_slug": "garage-door-companies", "trade_plural": "garage door companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Garage Door Companies",
    "title": "Marketing for Garage Door Companies | Top Shelf Business Solutions",
    "og_title": "Marketing for Garage Door Companies",
    "meta_desc": "Marketing for garage door companies keeps your Google Business Profile and local presence in front of homeowners the moment a spring breaks or a door will not close.",
    "service_schema_name": "Marketing for Garage Door Companies",
    "eyebrow": "For Garage Door Companies",
    "h1_html": "Marketing <em>for Garage Door Companies</em>",
    "answer_block": "Marketing for garage door companies keeps you visible in the local map results and across the towns you serve, through an active Google Business Profile and steady local content, so the moment a spring breaks or a door will not close, yours is the company a homeowner sees first and calls.",
    "sections": [
        {"h2_html": "Garage door demand is <em>sudden, local, and urgent</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody wakes up planning to spend money on their garage door. They plan nothing until the morning the spring snaps or the opener quits, and then they need someone today. That is the whole game. An ad they scrolled past last week does very little; being the company that shows up, trusted and nearby, in the minute they search is worth more than almost any other spend, because by the time they are looking they are ready to book.</p>'},
        {"h2_html": "Your Google Business Profile is your <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for garage door repair near them, the map results are often the first thing they see, above the websites and the lead sites. A profile that sits untouched for months looks abandoned next to one with recent photos of finished doors, current hours, and fresh reviews. Keeping it active, accurate, and full of real work is a quiet advertisement running in the exact moment a homeowner is deciding who to call.</p>'},
        {"h2_html": "Own your service area instead of the whole metro",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to an entire metro is expensive and forgettable, and it sends you jobs an hour outside your route. Focusing on the towns and zip codes you actually serve, and showing up there consistently, builds the local visibility that turns into calls you can reach quickly and profitably. It is a tighter, cheaper target than blanketing a city, and it is the approach that compounds inside the area you can actually cover.</p>'},
        {"h2_html": "Stay visible between emergencies too",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Not all garage door work is an emergency. A steady, low-effort local presence, a note about tune-ups before winter, a photo of a new door install, a reminder that worn springs are cheaper to replace before they snap, keeps your name familiar so the emergency call comes to you when it finally happens. This is the public-facing side of your business; the private follow-up to customers already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The company a homeowner <em>already recognizes</em>",
        "body_html": "A homeowner's door will not close one evening, leaving the garage open to the street, and they need it fixed now. They search on their phone and your Google Business Profile is right at the top of the map, with recent photos, current hours, and fresh reviews, and the name looks familiar from a neighborhood post they scrolled past a while back. They tap to call you first, before the two companies below you. You never spoke to them until that call."},
    "faqs": [
        ("What does managing my Google Business Profile actually mean?",
         "Keeping it accurate and active: correct hours and service area, recent photos of real work, regular posts, and staying on top of reviews, so it looks current and trustworthy whenever a homeowner searches near them."),
        ("Do you post to my profile for me?",
         "Yes. We keep it active with photos, updates, and local content on a regular schedule, so it looks current and worked-on instead of abandoned when someone is choosing who to call."),
        ("How is this different from the CRM follow-up?",
         "The CRM follows up privately with customers already in your database. Marketing is the public-facing side, your Google profile, local content, and map visibility, aimed at homeowners who are not your customer yet but will find and recognize you the day their door fails."),
        ("Can I focus on specific towns or zip codes?",
         "Yes. You pick the service area you want to be known in, and the profile and content center on those towns instead of a generic citywide message that sends you jobs too far to reach."),
        ("How long before I see it working?",
         "Local visibility builds over weeks and months, not days, and an active profile can start helping in the map results sooner than that. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-garage-door-companies.html", "The reviews that feed the same Google profile"),
        ("crm-for-garage-door-companies.html", "The private follow-up system behind the scenes"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the company they <em>see first</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ======================== Automation for Garage Door Companies ========================
{
    "slug": "automation-for-garage-door-companies",
    "trade_slug": "garage-door-companies", "trade_plural": "garage door companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for Garage Door Companies",
    "title": "Automation for Garage Door Companies | Top Shelf Business Solutions",
    "og_title": "Automation for Garage Door Companies",
    "meta_desc": "Automation for garage door companies sends appointment reminders, quote follow-ups, and review requests for you, so no job or customer slips through the cracks.",
    "service_schema_name": "Automation for Garage Door Companies",
    "eyebrow": "For Garage Door Companies",
    "h1_html": "Automation <em>for Garage Door Companies</em>",
    "answer_block": "Automation for garage door companies runs the routine follow-up around every job for you, sending appointment reminders so techs are not driving to no-shows, chasing replacement quotes on a schedule, and asking for a review the moment a repair is done, so nothing depends on someone at the shop remembering to send a text between jobs.",
    "sections": [
        {"h2_html": "The follow-up is real work nobody has <em>time to do</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every job has a tail of small tasks after the truck leaves: confirm tomorrow\'s appointments, remind the customer, check back on the quote they were thinking over, ask the happy ones for a review. None of it is hard, and all of it slips during a busy week when the phone will not stop. Each one that slips is a wasted drive to an empty house, a replacement quote that quietly dies, or a five-star review you earned and never got.</p>'},
        {"h2_html": "Reminders that <em>cut the no-shows</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Before every scheduled visit, the customer gets an automatic confirmation and a reminder by text, with a simple way to confirm or reschedule. That is the single biggest lever on no-shows, and it keeps a tech from driving across your service area to a house where nobody is home. You stop losing a slot and the fuel to an appointment that was never going to happen, without anyone at the shop making reminder calls.</p>'},
        {"h2_html": "Quote follow-ups that <em>chase themselves</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A new door is a decision, and most homeowners take a few weeks and a couple of quotes to make it. Once you send a replacement quote, a scheduled sequence of light check-ins goes out for you until the customer decides, so the one who went quiet gets a nudge instead of being forgotten. The quote was rarely a no, it was a not yet, and this makes sure someone follows up at the right time. It runs against the same database as your CRM, so nothing here duplicates a customer or a note.</p>'},
        {"h2_html": "Review requests and tune-up reminders on <em>autopilot</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The moment a job is marked done, a review request goes out automatically while the customer is happiest, so your rating keeps climbing without anyone remembering to ask. Further out, past customers get a light tune-up reminder when their door is due, worn springs and dry rollers are cheaper to service than to fix after they fail, which brings back work you would otherwise never hear about. It is a steady, low-key touch, not a stream of spam.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A job that <em>follows up on itself</em>",
        "body_html": "Your tech finishes a spring repair on a Tuesday and marks the job done in the app. That afternoon the customer gets a review request with a one-tap link. A homeowner who got a new-door quote the week before gets an automatic check-in asking if they have any questions. A customer from last fall gets a reminder that their door is due for a tune-up before winter. All three go out on time, and nobody at the shop sat down to send a single one of them."},
    "faqs": [
        ("What does it actually send?",
         "The routine follow-up around a job: appointment confirmations and reminders, replacement-quote check-ins, review requests when a job is done, and tune-up reminders to past customers when their door is due. You approve the messages and the timing up front."),
        ("Does this replace me personally following up with customers?",
         "No. It handles the routine, predictable messages so nobody has to remember them. You still make every real call and step in personally for anything that needs a conversation, like a big replacement decision."),
        ("Can it really chase my replacement quotes for me?",
         "Yes. Once a quote goes out, a scheduled set of check-ins goes to that customer until they decide, so the ones who went quiet keep hearing from you instead of quietly dropping off your list."),
        ("Are automatic review requests allowed?",
         "Yes. Asking every customer for an honest review is fine and encouraged. The request simply goes out at the right moment with a one-tap link; it never filters out unhappy customers or pays for reviews."),
        ("How long does setup take?",
         "Setup is included with no separate fee. We build the reminder, follow-up, and review sequences around how you already work, so it is running within days. Start with a free audit and we will find the gaps where jobs and quotes are falling through today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for home services"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-garage-door-companies.html", "The database every workflow runs against"),
        ("online-booking-for-garage-door-companies.html", "How the visits these reminders cover get booked"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a job <em>go quiet</em>",
    "cta_sub": "Get a free audit of what is currently falling through the cracks between your jobs, your quotes, and your calendar, whether you work with us or not. No credit card, never a call center.",
},
]
