"""Per-page content specs for the HANDYMAN SERVICES batch (Home Services hub). Same contract as
corpus_specs.py: generate_corpus.py imports SPECS and owns the mechanics (shell, schema, GA4
events, interlinks, keyword-first title/slug/H1/first-sentence); each dict owns the unique,
hand-written, handyman-specific substance that clears the uniqueness gate, never a reworded
plumber or electrician page. Seven pages: AI receptionist (with live demo), CRM, online booking,
review software, websites and SEO, marketing, and automation. Each example body ends with the
literal "Illustrative example, not a client."; the generator strips a trailing copy and appends
its own, so it renders once.
"""

SPECS = [
# ======================= AI Receptionist for Handyman Services =======================
{
    "slug": "ai-receptionist-for-handyman-services", "demo": True,
    "trade_slug": "handyman-services", "trade_plural": "handyman businesses",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Handyman Services",
    "title": "AI Receptionist for Handyman Services | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Handyman Services",
    "meta_desc": "An AI receptionist for handyman services answers every small-job call, captures the whole to-do list, and books it on your calendar while your hands are full.",
    "service_schema_name": "AI Receptionist for Handyman Services",
    "eyebrow": "For Handyman Services",
    "h1_html": "AI Receptionist <em>for Handyman Services</em>",
    "answer_block": "An AI receptionist for handyman services answers every call the moment it rings while you are on a ladder or holding a drill, tells a quick TV mount apart from a full honey-do list, roughs out the work, and books it on your calendar. You keep your own number, and every small job belongs to you.",
    "sections": [
        {"h2_html": "The small job you miss just <em>calls the next handyman</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A person with one small thing, a TV to hang, a gate that will not latch, a hole in the drywall where a shelf came down, is not going to leave a voicemail and wait a day for a callback. They call the next handyman on the list, and the one after that, until someone picks up, or they give up and live with it. And you are the one person doing the work, up a ladder or under a sink with a drill running, so the call rolls to voicemail. It is not one big emergency you are missing. It is a steady stream of small jobs that never even reach you.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist answers on the first ring, every time, while you keep working. It finds out what they need, whether it is one quick job or a list of ten, gets the address, and books a visit or a time window on your calendar. The work is captured instead of lost to the next name in their search.</p>'},
        {"h2_html": "Built around how <em>handymen actually get work</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your callers rarely have one tidy job. Someone reads off a list, mount a TV, fix a sticking door, patch where a shelf used to be, swap two light fixtures, and a voicemail box cannot capture any of it, let alone rough out how long it will take or which day it fits into. A generic call center does not know a ten-minute job from a half-day of work, or a regular from a first-timer.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers all day while you are heads-down on a job, so the calls that come in while you work never pile up in a voicemail box you check at night.</li><li>Captures the whole list, not just the first thing, so you show up with the right tools and enough time booked instead of a surprise punch-list at the door.</li><li>Books routine small jobs onto your calendar and texts you the details, and can steer new work toward a day you are already in that neighborhood.</li><li>Knows a repeat customer, the regulars who call you their handyman, from a first-time caller, so the people who keep you busy never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is a <em>half-day you would have missed</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. A full day for a handyman is a stack of small tickets, and even one afternoon of little jobs booked from calls you would otherwise have missed on a busy day is usually worth more than the system costs for the month. Everything it captures after that is on top. The point is to stop handing a steady stream of easy, close-together work to whoever happened to pick up the phone.</p>'},
        {"h2_html": "You own the number, the calls, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every address, and every job on their list is yours and exportable any time, so the customer list you are building stays an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The AI receptionist is one piece of the Top Shelf platform, and it hands every call it captures to the same CRM that follows up, so a quote or the rest of a list never slips.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A honey-do list of six things, booked while you <em>finish a deck</em>",
        "body_html": "A homeowner has been staring at the same list for a month, a TV to mount, a sticking bedroom door, a hole where a shelf came down, a wobbly stair railing, and two light fixtures to swap. They call three handymen on their lunch break. Two go to voicemail. Yours answers, takes down all six items, roughs out a half-day, and books it for Thursday while you are across town finishing a deck repair. You come off that job to find the whole visit already on your calendar, with the address and the full list attached, instead of hearing about it after they gave up and called someone else. Illustrative example, not a client."},
    "faqs": [
        ("Does it work with my current phone number?",
         "Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever leave."),
        ("Can it capture a whole list, not just one job?",
         "Yes, and that is the point. Most callers have several small things at once, so it takes down every item, roughs out how long the visit will run, and books the right amount of time, so you are not surprised by a punch-list at the door."),
        ("Will it actually book the job on my calendar?",
         "Yes. It books onto your real calendar based on your availability, sends you the address and the list by text right away, and can group new work toward a day you are already working nearby. You set the rules for how much notice you need and which hours are open."),
        ("Is it going to sound like a robot to my customers?",
         "It answers naturally and is upfront instead of pretending to be a person. For most callers with a small job, what matters is that a real person is going to show up and handle their list, and a friendly voice that takes down the details beats a voicemail box every time. You can hear it handle a live call before you decide."),
        ("How fast can it be running?",
         "Setup is included with no separate onboarding fee. We configure your job types, your calendar, and how you like work grouped and booked, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for handyman businesses"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-handyman-services.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing small jobs to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and small jobs your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ============================== CRM for Handyman Services ==============================
{
    "slug": "crm-for-handyman-services",
    "trade_slug": "handyman-services", "trade_plural": "handyman businesses",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Handyman Services",
    "title": "CRM for Handyman Services | Top Shelf Business Solutions",
    "og_title": "CRM for Handyman Services",
    "meta_desc": "A CRM for handyman services keeps every past customer and unfinished list in one place and follows up for you, so a home you helped once keeps calling you back.",
    "service_schema_name": "CRM for Handyman Services",
    "eyebrow": "For Handyman Services",
    "h1_html": "CRM <em>for Handyman Services</em>",
    "answer_block": "A CRM for handyman services keeps every past customer, lead, and unfinished to-do list in one place and follows up for you, so the family whose shelves you hung last spring and the neighbor who asked for a quote both call you next instead of whoever they happen to find. Your customer list quietly becomes your pipeline.",
    "sections": [
        {"h2_html": "You are not short on work, you are short on <em>staying in touch</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most handymen do not have a demand problem. Every home has a rolling list of small stuff, so the work is always out there. The problem is that you did four of the six things a customer asked for, said you would come back for the other two, and then a busy month buried it. Or a customer loved the job, meant to call you again, and lost your number. The work was never gone. It just needed a nudge a few days or a few months later, and that is the thing there is never time for between jobs.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every past customer and every unfinished list in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not you remember. The customer with two things left over hears from you again, and the next batch of work comes back to you instead of the handyman a neighbor happens to mention.</p>'},
        {"h2_html": "Every home you help is a customer <em>for years</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A good handyman becomes the person a household calls their handyman, the name they save for every small thing that comes up. You have already been inside, they already trust you, and the next list, the next repair, the next small ask is yours if you stay in touch. But you cannot personally remember to reach back out to hundreds of homes, so most of that repeat work goes to whoever they think of first when the list piles up again.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, address, past job, and note lives in one place instead of a truck full of receipts and your memory.</li><li>Seasonal nudges go out on schedule, a spring to-do list, a round of fixes before the holidays, fall weatherproofing, so the work comes back around without you tracking a single date.</li><li>You can see who has not called in a while and reach the right customer with the right reminder at the right time.</li></ul>'},
        {"h2_html": "The list is never <em>finished</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner you helped a year ago is not disloyal when they call someone else. They just lost your number and their list kept growing. A steady, light touch, a seasonal check-in, a note that you can knock out the two things you did not get to last time, keeps your name in their phone so the next round of work comes to you. It costs almost nothing, and it is the difference between a one-time visit and a customer for the life of the house.</p>'},
        {"h2_html": "You own the list, and it works with the rest of the system",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the AI receptionist, so a call it answers lands in your database and gets followed up on automatically, and to online booking, so a scheduled visit is logged against the right customer with their full history and past lists already attached. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The two things you did not get to, <em>booked six months later</em>",
        "body_html": "You spend a morning at a house knocking out most of a list, but the customer runs out of budget before you get to the fence gate and the closet shelving, and you tell them to call when they are ready. Normally that is the last you hear of it. Instead the CRM keeps a light touch going, a friendly check-in a few weeks later and a seasonal nudge after that, both written to sound like you. In the fall the homeowner has a fresh list plus those two leftovers, and they text you, because yours is the name still in their phone. You never sat down to chase it. Illustrative example, not a client."},
    "faqs": [
        ("Does it import my existing customers and past jobs?",
         "Yes. Your current customers, leads, and job history come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already have actually work for you."),
        ("Will it follow up on leftover list items and quotes automatically?",
         "Yes, on the schedule you approve. The two things you did not get to, and the bigger project you quoted, get a check-in a few days later and a nudge after that, all sent for you, so work you already earned does not just sit there. You can jump in and message anyone directly any time."),
        ("Can it send seasonal reminders to past customers?",
         "Yes. You set the cadence, a spring to-do list, a round of fixes before the holidays, fall weatherproofing, and the reminders go out automatically so repeat work comes back around without you tracking every date."),
        ("How is this different from just having their number in my phone?",
         "A phone full of contacts does not follow up, does not remember who has a list waiting, and does not tell you who has not called in a year. The CRM does all of that on a schedule, so the repeat work actually shows up instead of depending on you to remember hundreds of homes."),
        ("How long until it is set up?",
         "Setup is included with no separate onboarding fee. We bring in your customers, build your follow-up and reminder sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where jobs are slipping through today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for handyman businesses"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-handyman-services.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting past customers <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your past customers and unfinished lists are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Online Booking for Handyman Services =========================
{
    "slug": "online-booking-for-handyman-services",
    "trade_slug": "handyman-services", "trade_plural": "handyman businesses",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for Handyman Services",
    "title": "Online Booking for Handyman Services | Top Shelf Business Solutions",
    "og_title": "Online Booking for Handyman Services",
    "meta_desc": "Online booking for handyman services lets customers self-schedule a couple hours of help, a TV mount, or furniture assembly on your real availability, no phone tag.",
    "service_schema_name": "Online Booking for Handyman Services",
    "eyebrow": "For Handyman Services",
    "h1_html": "Online Booking <em>for Handyman Services</em>",
    "answer_block": "Online booking for handyman services lets a customer pick a time for the work they need done, a couple hours of help, a TV mount, furniture assembly, a short punch-list, straight from your website or a text link on your real availability, so you stop trading voicemails and the visit lands on your calendar with the list already attached.",
    "sections": [
        {"h2_html": "A small job is not worth a <em>week of phone tag</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When the job is small, the effort to book it has to be small too. A homeowner wants a couple hours of help with a list, or just a TV hung before the weekend, and they are happy to schedule it, but if they have to call during the day, wait for a callback, and trade voicemails, the reward is not worth the hassle. So they put it off, or they book the handyman who let them lock in a time on the spot. The job was never the problem. The back and forth was.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets them grab an open slot the moment they think of it, at night or on a break, without reaching you first. You come off a job to find the visit already on your calendar instead of a missed call you now have to chase between stops.</p>'},
        {"h2_html": "It fills the <em>gaps between bigger jobs</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Small jobs are how you turn a loose day into a full one. A one-hour mount or a quick repair fits neatly into the gap between two bigger jobs, and a booking tool that knows your real availability can offer those openings instead of leaving them empty. You set the rules: a minimum visit length so a ten-minute job does not cost you a whole trip, how long each type of work runs, how much buffer to leave for drive time, and which hours are open at all. You can even steer bookings toward days you are already working an area, so the small stuff clusters instead of scattering you across town.</p>'},
        {"h2_html": "A booking link everywhere a customer <em>finds you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The link goes anywhere someone already meets you: your website, your Google Business Profile, your email signature, and the text you send after a job. Every one of those turns from a dead end that needs a callback into a place someone can book you in one tap. A homeowner scrolling for someone to assemble a crib before the baby comes, or hang a heavy mirror they do not trust themselves with, can put the visit on your calendar before they close the tab instead of leaving a voicemail they forget by morning.</p>'},
        {"h2_html": "On your real calendar, and the customer actually shows",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar you already use so it can never double-book you against a job you already have, and it sends the customer a confirmation and a reminder, which is what actually cuts no-shows. Driving across town to an empty house is an hour you never get back, and on a small job that wasted trip can wipe out the whole ticket. Every booking is logged against the right customer in your CRM, and it works alongside the AI receptionist, which can also book the caller who would rather talk than tap.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Saturday list, booked <em>Sunday night</em>",
        "body_html": "It is 9pm on a Sunday and a homeowner is finally fed up with a growing list, a curtain rod to hang, a cabinet door that will not stay shut, a smoke detector chirping somewhere. Instead of leaving a voicemail they will second-guess in the morning, they land on your site, see real reviews, and book two hours of handyman time for Saturday at 9 from the calendar right there on the page. You wake up to the visit already set, with their name, address, and the list attached. No phone tag, no lost job. Illustrative example, not a client."},
    "faqs": [
        ("Does it sync to my Google or Outlook calendar?",
         "Yes. It reads your real calendar so it only ever offers times you are actually free, and new bookings drop straight onto it. It cannot double-book you against a job you already have scheduled."),
        ("Can customers book by the hour or by the job?",
         "Both, however you want to sell it. You can offer set tasks like a TV mount or furniture assembly, or blocks of time like a two-hour or half-day visit, with a minimum length so a tiny job never costs you a whole trip for nothing."),
        ("Can I control the jobs, the length, and drive time?",
         "Yes. You decide which job types are bookable online, how long each one runs, how much notice you need, and how much buffer to leave for driving, so you are never booked with no way to get across town in time."),
        ("Will it cut down on no-shows?",
         "It helps. Automatic confirmations and reminders by text and email are the single biggest lever on no-shows, and every booking includes them. A customer who booked themselves and got a reminder is far more likely to be home than a loosely agreed callback."),
        ("How fast can it be live?",
         "Setup is included, no separate fee. We connect your calendar, set up your job types and rules, and put the link on your site and profile, so it is taking bookings in days. Start with a free audit and we will show you where you are losing easy jobs today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for handyman businesses"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-handyman-services.html", "The AI receptionist that can book callers too"),
        ("crm-for-handyman-services.html", "The CRM every booking is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let customers book you <em>while you work</em>",
    "cta_sub": "Get a free audit of how many easy jobs your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Review Software for Handyman Services =========================
{
    "slug": "review-software-for-handyman-services",
    "trade_slug": "handyman-services", "trade_plural": "handyman businesses",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for Handyman Services",
    "title": "Review Software for Handyman Services | Top Shelf Business Solutions",
    "og_title": "Review Software for Handyman Services",
    "meta_desc": "Review software for handyman services asks every happy customer for a Google review at the right moment, so the next person searching for a handyman calls you first.",
    "service_schema_name": "Review Software for Handyman Services",
    "eyebrow": "For Handyman Services",
    "h1_html": "Review Software <em>for Handyman Services</em>",
    "answer_block": "Review software for handyman services asks every happy customer for a review the moment the list is crossed off, makes leaving one a single tap, and helps you reply to each, so the next homeowner searching for a handyman they can trust finds a wall of recent five-star reviews and calls you first.",
    "sections": [
        {"h2_html": "Homeowners hire the handyman with the <em>most recent reviews</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A handyman is a stranger a homeowner lets roam the whole house, often while they are at work, touching everything from the TV wall to the nursery. So before they call, they read reviews, because reliable, honest, showed up on time, fair price, cleaned up after, is exactly what they are nervous about and exactly what a review settles. A thin profile with a few old reviews quietly loses those calls to the handyman with a fresh wall of them, and you never even hear the phone that did not ring.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The problem is not that your customers are unhappy. It is that you finish a small job, pack up, and move to the next one without ever asking, so the reputation you have earned never makes it online. Review software fixes the timing and the awkwardness so it does.</p>'},
        {"h2_html": "Every small job is a review you are <em>leaving on the table</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do more jobs in a week than most trades do, which means more chances to be reviewed, if you actually ask every time. The software sends the ask automatically the moment a job is done, by text and email, with a link that drops the customer straight onto your Google profile in one tap. No cornering people at the door, no card that asks them to go find you later, and no reminder three weeks on when the visit has slipped their mind. It turns your volume of small jobs into a steady stream of reviews.</p>'},
        {"h2_html": "The reviews that list your range are your <em>best ad</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A handyman review often reads like a menu, they hung our TV, fixed the gate, and put together a crib, all in one visit, and that is the most convincing ad you could run, because the next reader has their own mixed list and just saw proof you handle exactly that. The software flags every new review the moment it lands and helps you reply fast, so each good one gets a genuine thank you and a rare critical one gets a calm, professional response instead of silence.</p>'},
        {"h2_html": "More reviews, more calls, compounding",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Recent reviews feed your Google Business Profile, which lifts you in the map pack a homeowner sees when they search for a handyman near them, which brings more calls, which brings more reviews. It builds on itself. Your reputation is yours, tied to your own profile, not a directory or a lead-seller. Review requests are part of the Top Shelf platform and fire automatically off a job marked complete in your CRM, so you collect reviews without lifting a finger.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "One punch-list becomes <em>next week's calls</em>",
        "body_html": "You spend a Thursday afternoon knocking out a mixed list, a TV mounted, a gate rehung, a bathroom fan replaced. An hour after you leave, the software texts your happy customer a thank-you with a one-tap link, and they post a warm review that names all three jobs before dinner. The next week two neighbors are looking for someone to handle their own odd jobs, search for a handyman nearby, and read that exact review sitting at the top of your profile. They call you instead of a name below you on the map. You never asked twice, and you were already on another job. Illustrative example, not a client."},
    "faqs": [
        ("Which review sites does it work with?",
         "It focuses on Google, which is where someone looking for a handyman looks first and what feeds your local search ranking. It can also point past customers to your other profiles. We follow each platform's own rules, including that a review should come from someone you actually did work for."),
        ("When does it ask for the review?",
         "Right after the job is done and the list is crossed off, sent automatically by text and email with a one-tap link. You can adjust the timing and the wording so it sounds like you and not a form letter."),
        ("Is automating review requests allowed?",
         "Asking every customer for an honest review is fine and encouraged. What is not allowed is filtering out unhappy customers or paying for reviews, and this does not do that. It simply asks everyone at the right moment and makes saying yes easy."),
        ("What happens if I get a bad review?",
         "You find out immediately instead of weeks later, and the software helps you post a calm, professional reply. One measured response to a critical review, sitting under a wall of genuine positive ones, often reassures the next reader more than a spotless record would."),
        ("How long until it is running?",
         "Setup is included with no separate fee. We connect your Google profile, set the timing and the message, and tie it to your completed jobs, so requests start going out in days. Start with a free audit and we will show you how your reputation stacks up against the handymen you compete with.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for handyman businesses"),
        ("solution-reviews.html", "How the review system works"),
        ("crm-for-handyman-services.html", "The CRM that triggers the ask when a job is done"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Turn finished lists into <em>your next call</em>",
    "cta_sub": "Get a free audit of how your online reputation compares to the handymen you compete with, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Websites & SEO for Handyman Services =========================
{
    "slug": "websites-seo-for-handyman-services",
    "trade_slug": "handyman-services", "trade_plural": "handyman businesses",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Handyman Services",
    "title": "Websites & SEO for Handyman Services | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Handyman Services",
    "meta_desc": "A handyman website built for SEO ranks for handyman near me and the specific jobs people search, and captures the caller directly instead of a lead-seller.",
    "service_schema_name": "Websites & SEO for Handyman Services",
    "eyebrow": "For Handyman Services",
    "h1_html": "Websites &amp; SEO <em>for Handyman Services</em>",
    "answer_block": "A handyman website built for SEO ranks for what people search, handyman near me, TV mounting, furniture assembly, drywall repair in your city, shows up in the map pack for the towns you cover, and captures the caller the moment they land, so the job belongs to you instead of a directory renting your calls back to you.",
    "sections": [
        {"h2_html": "The directories are not competing with you, they are <em>renting you back your own calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a handyman in your town and the top of the page is often Thumbtack, Angi, TaskRabbit, or Nextdoor, not the local person who actually does the work. Those sites publish endlessly and have years of authority behind them, so a homeowner lands there first, fills out one form, and that lead gets sold or shared, sometimes to several handymen at once, sometimes back to you for a fee out of the price of a job that was already small. Your site not ranking is not a vanity problem. It is the reason a call you should have gotten for free gets sold to you, or handed to whoever paid for the slot that week.</p>'},
        {"h2_html": "Rank for the <em>exact small job</em> a homeowner types",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for a broad term, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you cover, and for the exact things people search when they have a job in mind: handyman near me, TV mounting service, furniture assembly, drywall patch, fence repair, gutter cleaning in your city. That long tail of specific small jobs is where a local handyman wins, because a directory has nothing local to say about mounting a TV in your town and your page does.</p>'},
        {"h2_html": "Show them the range, and let them reach you in <em>one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A visitor who wants a mixed list done needs to see, fast, that you handle exactly their kind of work, so the site puts your range and your service area in front of them right away, with a tap-to-call button and a simple way to send over a list. Most of them are on a phone, deciding in under a minute, so the page has to load fast and make reaching you effortless. A pretty site that buries the phone number and hides what you do is a wasted opportunity; a visitor should never leave without an easy way to book you or send their list.</p>'},
        {"h2_html": "The calls are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a directory profile or a shared-lead service disappears the day you stop paying, and the lead was never really yours anyway. A website you own keeps ranking, keeps capturing calls, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you. The site plugs into the same CRM that follows up on every lead it captures and the AI receptionist that answers the calls it drives, so nothing it earns you slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A TV-mount search finds <em>you</em>, not a directory",
        "body_html": "A homeowner a few streets over just bought a big TV and searches for a handyman to mount it. Instead of a directory form that gets shared with three other people, they find your site ranking for that town, with a page that lists TV mounting right alongside the rest of your work and a tap-to-call button at the top. They call you directly, mention two other things while they have you, and the small job turns into a half-day. You paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client."},
    "faqs": [
        ("Will my site actually outrank the big directories?",
         "Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the exact small-job searches a national directory has no reason to target well, which is exactly where a local handyman can win."),
        ("How is this different from Thumbtack or TaskRabbit?",
         "Those platforms rent you a lead that they also share with your competitors, and it stops the day you stop paying. A website you own captures calls that are yours alone and keeps working long after it is built, without a per-lead fee coming out of every small job."),
        ("Should my site list every service I offer?",
         "The ones worth ranking for, yes. Pages built around specific jobs people search, TV mounting, furniture assembly, drywall repair, fence work, are what capture the homeowner looking for that exact thing, and they show a visitor you handle their whole mixed list."),
        ("Most of my jobs are small. Is a website even worth it?",
         "Especially then. Small jobs come in volume and by search, and the handyman who shows up for handyman near me with a clear list of work and a tap-to-call button gets the call. A site built for that moment is exactly what turns a small search into a booked visit, often with more added on."),
        ("How long until it starts ranking?",
         "Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for handyman businesses"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-handyman-services.html", "Staying visible in your service area beyond your site"),
        ("crm-for-handyman-services.html", "Where every captured lead lands and gets followed up"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your calls, whether you work with us or not. No credit card, never a call center.",
},
# ============================ Marketing for Handyman Services ============================
{
    "slug": "marketing-for-handyman-services",
    "trade_slug": "handyman-services", "trade_plural": "handyman businesses",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Handyman Services",
    "title": "Marketing for Handyman Services | Top Shelf Business Solutions",
    "og_title": "Marketing for Handyman Services",
    "meta_desc": "Marketing for handyman services keeps your Google Business Profile active and your name first in the neighborhood, so you are the handyman people already call.",
    "service_schema_name": "Marketing for Handyman Services",
    "eyebrow": "For Handyman Services",
    "h1_html": "Marketing <em>for Handyman Services</em>",
    "answer_block": "Marketing for handyman services keeps you visible where local demand shows up, your Google Business Profile, the map pack, and the neighborhood, so when a homeowner nearby finally tackles their list, your name is the active, well-reviewed one they already know to call instead of a stranger they have to go find.",
    "sections": [
        {"h2_html": "Handyman work runs on <em>who they already know</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most homeowners do not shop hard for a handyman. When the list finally gets long enough to act on, they call the name they already recognize, the person a neighbor recommended, the truck they have seen around, the handyman who did a good job last year. This trade is referral-heavy for a reason: letting a stranger into your home for a day of odd jobs is a trust decision, and people default to a familiar name. Winning that recognition before someone has a list is worth more than any single ad, because by the time they are ready, they are calling from memory, not running a careful search.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>word of mouth</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone does search for a handyman near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and the ads. A profile that has sat untouched for months looks abandoned next to one with recent photos of real jobs, current hours, and a steady stream of reviews. Keeping it active, complete, and honest, with photos that show the range of work you do, is a quiet advertisement running in the exact spot a homeowner looks when the list finally wins.</p>'},
        {"h2_html": "Stay tight to the <em>neighborhoods you cover</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and it sends you tiny jobs thirty minutes away that are not worth the drive. Focusing on the specific towns and neighborhoods you serve, with a profile, photos, and content built around those areas, and a presence on the neighborly channels people actually ask on, is what puts you in front of the local work you can reach. It is a tighter, cheaper target, and because the jobs cluster close together, it is the one that keeps a day of small tickets profitable.</p>'},
        {"h2_html": "Ride the seasons, and stay in front of past customers",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Handyman demand swings with the calendar, spring to-do lists, a rush of fixes before the holidays when everyone wants the house ready for guests, weatherproofing in the fall, small repairs after a storm, and being visible right before each wave beats scrambling once it hits. A steady local presence, seasonal posts, job photos, the occasional tip, keeps you top of mind for the next list and reminds past customers you are still the one to call. This is the public-facing side of the business; the private follow-up to people already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The list they finally tackle, and you are <em>already the name</em>",
        "body_html": "You keep your Google profile active all year with photos of finished jobs, a mounted TV, a rebuilt gate, a patched and painted wall, and you post now and then on the neighborhood channels. A homeowner a few streets over does not need you yet, but keeps seeing your name and your work. Before the holidays their list of small fixes finally has to get done for guests, and instead of searching cold, they call the handyman whose name they already knew from around the neighborhood. You never spoke to them once before that call. Illustrative example, not a client."},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         "Yes. We keep it active with job photos, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current whenever someone searches for a handyman near them."),
        ("What does focusing on my service area actually mean?",
         "It means building your profile and content around the specific towns and neighborhoods you can reach quickly, instead of spreading a budget across a whole metro. That keeps your small jobs close together and profitable, and puts you in the map pack where the local calls are."),
        ("How is this different from the CRM follow-up?",
         "The CRM follows up privately with people already in your database. Marketing is the public-facing side, your Google profile, reviews, and neighborhood visibility, aimed at homeowners who are not your customer yet but need to recognize and trust your name when their list finally gets long enough."),
        ("Can you help me get ahead of seasonal demand?",
         "Yes. We time your visibility to the waves that matter, spring to-do lists, the pre-holiday rush to get the house ready, fall weatherproofing, so you are already in front of people before the rush instead of scrambling once the calls start."),
        ("How long before I see it working?",
         "A neglected profile can climb in the map pack within weeks once it is active and complete, and recognition in a neighborhood builds from there as reviews and content stack up. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for handyman businesses"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-handyman-services.html", "The reviews that feed the same Google profile"),
        ("websites-seo-for-handyman-services.html", "The website that captures the demand this drives"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the handyman they <em>already know</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ============================ Automation for Handyman Services ============================
{
    "slug": "automation-for-handyman-services",
    "trade_slug": "handyman-services", "trade_plural": "handyman businesses",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for Handyman Services",
    "title": "Automation for Handyman Services | Top Shelf Business Solutions",
    "og_title": "Automation for Handyman Services",
    "meta_desc": "Automation for handyman services sends on-my-way texts, reminders, and job follow-ups for you, so a one-person shop runs like it has an office and nothing slips.",
    "service_schema_name": "Automation for Handyman Services",
    "eyebrow": "For Handyman Services",
    "h1_html": "Automation <em>for Handyman Services</em>",
    "answer_block": "Automation for handyman services handles the texts and reminders around every job for you, the on-my-way message to a customer who took the morning off, the reminder that saves a wasted trip, the follow-up and review request after the list is done, so a one-person shop runs like it has an office and nothing depends on you remembering between jobs.",
    "sections": [
        {"h2_html": "A one-person shop drowns in the <em>little messages</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A customer who took the morning off work to let you in wants to know you are actually coming. A quote from last week needs a nudge before it goes cold. A booked visit needs a confirmation the day before so nobody wastes the trip. None of these is hard, but there are dozens of them across a week of small jobs, and you have no office staff to send them, so they slip while you are on a ladder with a drill running. The work can be perfect and the customer still unhappy, simply because nobody told them what was happening.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Automation handles those messages for you. A confirmation the day before, an on-my-way text with a realistic arrival window when you head out, and a note if you are running behind, all sent automatically, so every customer feels looked after and you are not the one stopping to type it. A solo shop starts running like it has a dispatcher, without paying for one.</p>'},
        {"h2_html": "Reminders that <em>save the wasted trip</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Driving to a no-show is an hour and a tank of gas you never get back, and on a small job that one wasted trip can wipe out the whole ticket. Automatic confirmations and reminders by text before every visit keep no-shows down and give a customer an easy way to reschedule instead of just not being home. For a handyman stringing together a dozen small stops, that is a tighter, fuller day and fewer holes you cannot fill on short notice.</p>'},
        {"h2_html": "The follow-up after the job <em>runs itself</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The job is not really done when you drive away. A quick thank-you, an automatic review request while the customer is still happy the list is finally handled, and a note offering to book the one or two things you did not get to all matter, and all are easy to forget once you are onto the next stop. Automation fires each one on time, so a finished list turns into a review, a repeat customer, and the rest of the work booked, without you keeping a mental note.</p>'},
        {"h2_html": "Cold quotes and lapsed customers <em>come back on schedule</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A quote for a bigger project that went quiet and a customer you have not seen in a year are not dead, they are just waiting for a reason to call. A scheduled check-in on an open estimate, and a seasonal nudge to a customer whose list is surely growing again, bring that work back around automatically instead of falling out of your memory. It runs against the same database as your CRM, so nothing here duplicates a customer or a note, and every automated touch is logged where you can see it.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A customer who never has to <em>wonder if you are coming</em>",
        "body_html": "A homeowner books a half-day for a list of small fixes on Tuesday. The day before, they get an automatic confirmation. Tuesday morning, when you leave for the job, they get an on-my-way text with an arrival window, so the person who took time off work is not left guessing. That afternoon, once the list is done, they get a thank-you with a one-tap review link and a friendly note offering to book the shelf install you ran out of time for. You never sat down to send any of it, and the customer felt taken care of from booking to follow-up. Illustrative example, not a client."},
    "faqs": [
        ("What messages does it actually send?",
         "The routine ones around a job: an appointment confirmation, an on-my-way text with an arrival window when you head out, a note if you are running behind, and a follow-up with a review request and an offer to book whatever you did not get to. You approve the wording so it all sounds like you."),
        ("Does this replace me talking to customers?",
         "No. It handles the predictable, repetitive texts so a one-person shop does not have to stop and type them all day, while you still make every real call and step in personally for anything that needs a conversation."),
        ("Can it help with no-shows and wasted trips?",
         "Yes. Automatic confirmations and reminders before each visit keep no-shows down and give the customer an easy way to reschedule, so you spend less time driving to empty houses, which matters most when the job is small."),
        ("Will it follow up on leftover list items and old quotes?",
         "Yes. After a job it can offer to book the things you did not get to, and it can nudge cold quotes and lapsed customers on a schedule you set, all logged against the customer in your CRM so nothing gets double-sent or forgotten."),
        ("How long does setup take?",
         "Setup is included with no separate fee. We build the reminder, on-my-way, and follow-up sequences around how you already run your day, so it is working within days. Start with a free audit and we will show you what is currently slipping between your calls, your trips, and your calendar.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for handyman businesses"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-handyman-services.html", "The database every workflow runs against"),
        ("online-booking-for-handyman-services.html", "How the visits these remind about get booked"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a customer <em>wonder if you are coming</em>",
    "cta_sub": "Get a free audit of what is currently slipping between your calls, your trips, and your follow-ups, whether you work with us or not. No credit card, never a call center.",
},
]
