"""Per-page content specs for the SEO corpus, hair salons batch. Same contract as
scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, hair-salon-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber content reworded.

Salon, Spa & Fitness hub. Four service angles live here in one file (the ai-receptionist dict
carries "demo": True). Each example body ends with the literal "Illustrative example, not a
client." per the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ========================= AI Receptionist for Hair Salons =========================
{
    "slug": "ai-receptionist-for-hair-salons", "demo": True,
    "trade_slug": "hair_salons", "trade_plural": "hair salons",
    "hub_name": "Salon, Spa & Fitness", "hub_slug": "industry-salon-spa-fitness.html",
    "breadcrumb_leaf": "AI Receptionist for Hair Salons",
    "title": "AI Receptionist for Hair Salons | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Hair Salons",
    "meta_desc": "A hair salon answering service answers every call and text the moment it comes in, day or night, books the appointment, and never sends a client to voicemail.",
    "service_schema_name": "AI Receptionist for Hair Salons",
    "eyebrow": "For Hair Salons",
    "h1_html": "AI Receptionist <em>for Hair Salons</em>",
    "answer_block": "A hair salon answering service answers every call and text the moment it comes in, day or night, tells a new client booking a first appointment apart from a quick question, and books it onto the right stylist's calendar while your team is behind the chair. You keep your own number, and every client belongs to you.",
    "sections": [
        {"h2_html": "The call you miss is the new client who <em>books the salon that answered</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A stylist with both hands in a client\'s hair cannot pick up the phone, and a new client calling to book a first appointment is not going to leave a voicemail and wait. They hang up and call the next salon, and the one after that, until someone answers. The work at the chair is the reason the phone rings out, and the new client, along with every visit they would have made all year, goes to whoever was free to answer.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An answering service picks up on the first ring, day or night, sounds warm instead of rushed, asks what the client wants done and roughly when, and either books the appointment or takes the details so nothing is lost. The new client is captured and scheduled instead of handed to the salon down the street that simply got to the phone first.</p>'},
        {"h2_html": "Most new clients find you at night, on <em>their phone</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A huge share of new-client interest never comes during salon hours at all. Someone sees a color transformation on Instagram at ten at night, taps through, and wants to book while the inspiration is fresh, or scrolling on a lunch break they fire off a quick message about extensions. If that message sits unanswered until tomorrow, the moment has passed and they have already booked somewhere that replied while they were still looking.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The answering service replies instantly to a text or a message, not just a call, and turns that late-night curiosity into a booked appointment on the spot. The client who messaged at eleven at night wakes up on your calendar instead of still shopping around.</p>'},
        {"h2_html": "Built around how a salon <em>actually books</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A booking is not one-size-fits-all, and a generic call center reading a script does not know a root touch-up from a full balayage, or that a first-time color client needs more chair time than a trim. The answering service handles it the way your front desk would on a good day.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers calls, texts, and messages 24/7, so the client who finds you at midnight and the one who calls on a Sunday both reach a real reply instead of a voicemail box.</li><li>Books the right service with the right stylist for the right amount of time, and knows a new color client is not a quick fifteen-minute appointment.</li><li>Treats a loyal regular differently from a first-time caller, so the clients who already trust you never feel like they are talking to a stranger.</li><li>Takes the details for anything it cannot book outright, a consultation or a color correction, and hands it straight to you to confirm.</li></ul>'},
        {"h2_html": "You own the number, the calls, and <em>the client list</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing salon number, or a new one registered in your name, not ours. Every caller, every message, and every booking is yours and exportable any time, so the client list you are building is an asset you keep instead of something you rent back month to month, with no long contract holding your clients hostage. The answering service is one piece of the Top Shelf platform, and it hands every booking it captures to the same CRM that rebooks and follows up, so a new client turns into a regular instead of a one-time visit.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A 10pm Instagram booking, captured while the <em>chairs are full</em>",
        "body_html": "A new client three neighborhoods over sees a balayage you posted and, at ten at night, taps your profile and sends a message asking if you have anything that weekend. Your stylists left hours ago, but the answering service replies in seconds, asks what she is after, checks the calendar, and books her with the colorist who does that look for Saturday morning. She wakes up with the appointment confirmed and the details in her texts, instead of scrolling to the next salon because nobody replied. You gained a client while the salon was dark. Illustrative example, not a client."},
    "faqs": [
        ("Does it work with my current salon phone number?",
         "Yes. It can answer on your existing salon number, or set up a new one registered in your name. Either way the number and every call, text, and booking that comes through it belong to you and go with you if you ever leave."),
        ("Can it answer texts and Instagram messages, not just calls?",
         "Yes, and that matters for a salon. A lot of new clients reach out by text or a message after seeing your work at night, and the answering service replies to those instantly, answers the first question, and books the appointment, so a late-night message does not sit until morning."),
        ("Will it actually book the appointment on the right stylist's calendar?",
         "Yes. It books the right service with the right stylist for the right amount of time based on your calendar and rules, and you get the details right away. For anything that needs your judgment, a big color correction or a consultation, it takes the details and hands it to you to confirm."),
        ("Will it sound like a robot to a new client?",
         "It answers naturally and warmly, and it is upfront rather than pretending to be a person. A new client mostly wants to know they can get in and that a real salon has them booked, and a friendly reply that captures the details beats a voicemail box every time. You can hear it handle a live call before you decide."),
        ("How fast can it be running?",
         "Setup is included with no separate onboarding fee. We configure your services, your stylists, your hours, and your booking rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you how many calls and messages your current setup is missing.")],
    "related": [
        ("industry-salon-spa-fitness.html", "Everything Top Shelf does for hair salons"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-hair-salons.html", "The CRM that rebooks every client you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing new clients to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls, texts, and after-hours messages your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ================================ CRM for Hair Salons ================================
{
    "slug": "crm-for-hair-salons",
    "trade_slug": "hair_salons", "trade_plural": "hair salons",
    "hub_name": "Salon, Spa & Fitness", "hub_slug": "industry-salon-spa-fitness.html",
    "breadcrumb_leaf": "CRM for Hair Salons",
    "title": "CRM for Hair Salons | Top Shelf Business Solutions",
    "og_title": "CRM for Hair Salons",
    "meta_desc": "A CRM for hair salons keeps every client, formula, and visit in one place and rebooks them for you, so a color client every six weeks keeps coming back.",
    "service_schema_name": "CRM for Hair Salons",
    "eyebrow": "For Hair Salons",
    "h1_html": "CRM <em>for Hair Salons</em>",
    "answer_block": "A CRM for hair salons keeps every client, color formula, and past visit in one place and rebooks them for you, so the color client due every six weeks and the regular who drifted away both come back to your chair instead of trying the salon down the street. Your client list quietly becomes recurring revenue.",
    "sections": [
        {"h2_html": "The client who does not rebook is the revenue you are <em>quietly losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most salons do not have a new-client problem so much as a rebooking problem. A color client is not a one-time sale, she is a standing appointment every five or six weeks for as long as she stays, and the same is true of the regular who comes in for a cut. When she leaves without her next visit booked, that chair time does not vanish, it gets filled by someone else or sits empty, and the recurring revenue she represented walks out with her.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every client and their history in front of you and prompts the rebook, by text or email, on the cadence each service needs. The color client hears from you right before her roots start to show, books her next visit, and stays on the schedule instead of drifting off.</p>'},
        {"h2_html": "Every client you have seen once is a client for <em>years</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your past clients are the easiest chair to fill. They already trust you with their hair, they know the drive and the price, and the next color, cut, or set of extensions is yours if you stay in touch. But you cannot personally remember when a few hundred clients are each due back, which formula you mixed, or who preferred which stylist, so a lot of that repeat work slips to whoever they find when they finally book.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every client, their formulas, notes, preferred stylist, and full visit history live in one place instead of a card box, a notes app, and your memory.</li><li>Rebooking reminders go out on the schedule each service needs, so color, cuts, and treatments come back around without you tracking dates.</li><li>Memberships and prepaid packages are tracked against the right client, so the people who paid ahead actually come in and use them.</li><li>You can see who is due, who is overdue, and reach the right client with the right reminder at the right time.</li></ul>'},
        {"h2_html": "The clients who drifted away are a <em>goldmine</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A client you have not seen in eight months is usually not angry, she just got busy or lost track of time, and never got a reason to come back. Reaching out to the clients who have gone quiet is some of the highest-return work a salon can do, because you are not paying to find a stranger, you are reminding someone who already liked your work that you are still here. A warm, well-timed win-back message brings a surprising number of them back into the chair. The CRM finds the clients who have lapsed and sends that message for you, so a name you had written off turns back into a standing appointment.</p>'},
        {"h2_html": "Fewer no-shows, filled cancellations, and a list <em>you own</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Two things quietly drain a fully booked day: the no-show who forgot, and the last-minute cancellation that leaves a hole nobody fills. The CRM sends automatic confirmations and reminders before every appointment, the single best way to cut no-shows and give a client an easy way to move a time instead of simply not showing. When someone does cancel, it can reach the clients who wanted an earlier slot and fill the gap before that chair time is lost. Every client and note is yours and exportable any time, not locked inside software you rent, and the CRM connects to the answering service, so a booking it captures lands in your database and gets followed up on automatically. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A color client who rebooks before her <em>roots show</em>",
        "body_html": "A client comes in for a full color on a Saturday and leaves without booking her next visit, the way most people do when the day is busy. Normally that is the last you think of it until she resurfaces months later, or not at all. Instead, five weeks on, the CRM sends her a friendly reminder that she is about due, written to sound like you, with a link to grab a time. She books that afternoon, before the regrowth even bothers her, and stays on a rhythm that keeps her in your chair all year. You never sat down to chase it. Illustrative example, not a client."},
    "faqs": [
        ("Does it import my existing clients and their history?",
         "Yes. Your current clients, their contact details, formulas, notes, and past visits come in and live in one place, and everything stays yours and exportable. The point is to make the client list you already have actually work for you."),
        ("Will it really prompt clients to rebook on its own?",
         "Yes, on the cadence you set. A color client can hear from you around the five or six week mark, a cut client on their own rhythm, all sent for you, so the standing appointments keep rebooking instead of depending on someone remembering at the desk. You can message anyone directly any time too."),
        ("Can it store color formulas and client preferences?",
         "Yes. Each client's formulas, notes, preferred stylist, allergies, and history stay attached to their profile, so whoever is behind the chair can pick up exactly where the last visit left off instead of starting from a guess."),
        ("Can it help with no-shows and last-minute cancellations?",
         "Yes. Automatic confirmations and reminders before each appointment are the biggest lever on no-shows, and when a client cancels, it can reach the people who wanted an earlier time and fill the opening before that chair time is lost."),
        ("How long until it is set up?",
         "Setup is included with no separate onboarding fee. We bring in your clients, build your rebooking and win-back sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where visits are slipping through today.")],
    "related": [
        ("industry-salon-spa-fitness.html", "Everything Top Shelf does for hair salons"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-hair-salons.html", "The answering service that feeds it every booking"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting clients <em>drift away</em>",
    "cta_sub": "Get a free audit of how many of your clients are overdue to rebook or have quietly stopped coming in, whether you work with us or not. No credit card, never a call center.",
},
# ============================= Marketing for Hair Salons =============================
{
    "slug": "marketing-for-hair-salons",
    "trade_slug": "hair_salons", "trade_plural": "hair salons",
    "hub_name": "Salon, Spa & Fitness", "hub_slug": "industry-salon-spa-fitness.html",
    "breadcrumb_leaf": "Marketing for Hair Salons",
    "title": "Marketing for Hair Salons | Top Shelf Business Solutions",
    "og_title": "Marketing for Hair Salons",
    "meta_desc": "Hair salon marketing keeps your Google profile and Instagram active and your name first in the map pack, so new clients nearby find and book you first.",
    "service_schema_name": "Marketing for Hair Salons",
    "eyebrow": "For Hair Salons",
    "h1_html": "Marketing <em>for Hair Salons</em>",
    "answer_block": "Marketing for hair salons keeps you visible where new clients actually look, your Google Business Profile, the map pack, and Instagram, so when someone nearby searches for a salon or scrolls at night, your name is the active, well-reviewed one they book instead of the salon that let its profile go stale.",
    "sections": [
        {"h2_html": "People choose a salon with their <em>eyes</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody hands a stranger their hair on faith. Before a new client ever calls, she has already looked you up, glanced at your photos, read a few reviews, and decided whether she trusts you with a color she cannot easily undo. That decision happens on a screen, in a minute or two, long before the phone rings. So the whole game for a salon is being visible, current, and clearly good at what you do in the exact places a new client looks, not running clever ads at people who are not thinking about their hair yet.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Get found, look active, and show real work in that moment, and the booking is usually yours. Look neglected or invisible, and she books the salon that showed up looking alive, no matter how good you actually are behind the chair.</p>'},
        {"h2_html": "Your Google Business Profile is your <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for a hair salon near them, or for balayage, a keratin treatment, or a men\'s cut in your area, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and the ads. A profile that has sat untouched for months, with old photos and stale hours, looks closed next to one with recent work, current details, and a steady stream of fresh reviews. Keeping it complete, active, and honest is a quiet advertisement running in the exact spot a new client looks when she decides where to book, and it is free space most salons let go to waste.</p>'},
        {"h2_html": "Instagram is where new clients <em>discover you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">For a hair salon, social media is not vanity, it is the storefront window. A huge amount of new-client interest starts with someone scrolling at night, saving a color they love, and tapping through to see who did it. A feed with real before-and-afters, the looks you specialize in, and the personalities behind the chairs does the selling for you while you sleep, and it gives a nervous first-timer the confidence that you can do exactly what she is picturing. A feed that has gone quiet for months tells her the opposite. Keeping a steady, genuine presence in front of the people near you is what turns a scroll into a saved post, and a saved post into a booking, especially when that post links straight to a way to reach you.</p>'},
        {"h2_html": "Reviews and a steady local presence, <em>working together</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Recent, genuine reviews are the other half of the trust a new client needs, and they feed the same Google profile that decides whether you show up in the map pack at all. More reviews lift you in local search, which brings more new clients, which brings more reviews, and it compounds. A steady presence, fresh photos of real work, replies to reviews, posts tied to the seasons and the looks people are asking for, keeps you top of mind for the neighborhoods you actually serve. This is the public-facing side of the business, aimed at people who are not your clients yet; the private follow-up to the clients already in your chair is the CRM. Your reputation is yours, tied to your own profile, not a directory or an app that rents you back your own name.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "New in town, and yours is the salon she <em>can already see</em>",
        "body_html": "Someone just moved to the area and needs to find a new colorist she can trust, which for a lot of people is a genuinely stressful search. She looks up hair salons near her and, on the same night, scrolls a little to see the work. Because your Google profile is active and full of recent color, with a wall of fresh five-star reviews, and your feed is full of the exact looks she wants, yours is the name that feels safe. She books with you and never finishes checking the others. The salon a mile away, with a profile last touched a year ago, never entered the running. Illustrative example, not a client."},
    "faqs": [
        ("Do you post to my Google Business Profile and Instagram for me?",
         "Yes. We keep both active with real photos of your work, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so you look current and busy whenever a new client looks you up."),
        ("How do I get more reviews?",
         "Reviews are part of the picture, asked for at the right moment and pointed at the Google profile that feeds your local ranking. We help you gather honest reviews from happy clients and reply to the ones that come in, since responding is itself a signal that lifts you in local search."),
        ("How is this different from the CRM?",
         "The CRM follows up privately with clients already in your book, rebooking and win-back. Marketing is the public-facing side, your Google profile, reviews, and social presence, aimed at people who are not your clients yet but need to find you and trust you before they will book."),
        ("Do I need to be on every social platform?",
         "No. For most salons the work is concentrated where new clients actually look and decide, your Google Business Profile and the visual platforms where people browse hair. We focus your effort there instead of spreading you thin across places that do not bring bookings."),
        ("How long before I see it working?",
         "A neglected Google profile can climb in the map pack within weeks once it is active and complete, and it compounds as reviews and photos build. Setup is included, and a free audit will show you what your online presence looks like to a new client searching near you today.")],
    "related": [
        ("industry-salon-spa-fitness.html", "Everything Top Shelf does for hair salons"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-hair-salons.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the salon they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are on Google and social in your area right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Websites & SEO for Hair Salons =========================
{
    "slug": "websites-seo-for-hair-salons",
    "trade_slug": "hair_salons", "trade_plural": "hair salons",
    "hub_name": "Salon, Spa & Fitness", "hub_slug": "industry-salon-spa-fitness.html",
    "breadcrumb_leaf": "Websites & SEO for Hair Salons",
    "title": "Websites & SEO for Hair Salons | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Hair Salons",
    "meta_desc": "A hair salon website built for SEO ranks for salon and balayage searches near you, shows your work up front, and lets a new client book in one tap.",
    "service_schema_name": "Websites & SEO for Hair Salons",
    "eyebrow": "For Hair Salons",
    "h1_html": "Websites &amp; SEO <em>for Hair Salons</em>",
    "answer_block": "A hair salon website built for SEO ranks for the searches a new client makes, hair salon near me, balayage near me, color and extensions in your area, shows your work up front, and lets her book in one tap, so the client belongs to you instead of a directory or booking app taking a cut of your own bookings.",
    "sections": [
        {"h2_html": "A new client trusts your website before she <em>trusts you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Hair is personal and hard to undo, so a new client does her homework before she books, and the website is where that trust is won or lost. She lands on it from a search or a link in your profile, and within seconds she is judging whether you do the work she wants and whether booking is easy. A site that loads slowly, hides the photos, or makes her call during business hours is a site she leaves for the next salon, no matter how talented the team is.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The site has to load fast on a phone, put your best work and a way to book right in front of her, and feel effortless. A beautiful salon with a neglected website loses clients it never even hears about.</p>'},
        {"h2_html": "Rank for what someone types when they <em>need a salon</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The results at the top for hair salon near me in your town are often a directory or a booking marketplace, not the local salons themselves. Those sites publish thousands of pages and have years of authority, so a new client lands there first, and the booking gets handed around or costs you a cut of a client who should have been yours for free. You will not outrank a national directory for the broadest term this year, and you do not need to. You can rank for your own name, for the neighborhoods you serve, and for the exact things people search: balayage near me, color correction, extensions, a keratin treatment, a men\'s cut in your area. Pages built around the services and areas you actually serve are what search engines, and new clients, reward with the click.</p>'},
        {"h2_html": "A visitor on her phone should see your work and <em>book in one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A new client is almost always on her phone, often at night, and will not read paragraphs or hunt for a phone number. The site has to load fast, show a real portfolio of your work up top, put your reviews where she can see them, and give her a book button that works in one tap, day or night. Photos matter more for a salon than almost any business, because she is buying a look, so the work has to be front and center, not buried behind a slow gallery. A pretty site that makes booking hard is a wasted opportunity; a visitor should never leave without an easy way to get in the chair.</p>'},
        {"h2_html": "The bookings are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every booking through a marketplace or a pay-per-client app costs you a cut and was never really yours to begin with, and the day you stop paying, it all disappears. A website you own keeps ranking, showing your work, and taking bookings for as long as it exists, and it is registered to you, not a platform that can change the rules or drop you. The site plugs into the same CRM that rebooks every client it captures and the answering service that replies to the ones who would rather message than tap, so nothing it earns you slips away. What you build is an asset that compounds, not rent you pay forever for your own clients.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A late-night balayage search finds <em>you</em>, not an app",
        "body_html": "A woman new to the area has been putting off finding a colorist, and at nine at night she finally searches balayage near me on her phone. Instead of a booking marketplace that would take a cut and show her ten salons at once, she finds your site ranking for that search, with a page about the color work you specialize in, a portfolio right at the top, and real reviews under it. She sees a look just like the one she wants, taps the book button, and picks Saturday, all before she closes the tab. The booking is yours, no cut taken, and no app ever stood between you and your new client. Illustrative example, not a client."},
    "faqs": [
        ("Will my site actually outrank the big directories and booking apps?",
         "Not for the broadest terms overnight. It can realistically rank for your salon name, your specific neighborhoods, and the service searches a national app has no reason to target well, balayage, color correction, extensions in your area, which is exactly where a local salon can win."),
        ("How is this different from paying a booking marketplace?",
         "A marketplace shows a new client ten salons at once and takes a cut of a booking that could have been yours directly, and it stops the day you stop paying. A website you own captures bookings that are yours alone, with no cut taken, and keeps working long after it is built."),
        ("Do I need a page for every service and neighborhood?",
         "You start with the ones that matter most: your top money services and your core areas. We build those pages first, around what people actually search and what you most want to book, then expand, rather than spreading thin across everything at once."),
        ("Most of my new clients come from Instagram. Does a website even help?",
         "Yes, because they still tap through to decide. Instagram catches the eye, but a new client checks your site and reviews before she trusts you with her hair, and that is where a fast, photo-forward page with easy booking turns a curious scroll into a booked chair."),
        ("How long until it starts ranking?",
         "Local, specific searches can start moving within weeks, while broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.")],
    "related": [
        ("industry-salon-spa-fitness.html", "Everything Top Shelf does for hair salons"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-hair-salons.html", "Staying visible in your area beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own neighborhood</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and booking apps taking your clients, whether you work with us or not. No credit card, never a call center.",
},
]
