"""Per-page content specs for the SEO corpus (plan §5), personal injury lawyers batch. Same
contract as scripts/corpus_specs.py: generate_corpus.py imports SPECS and owns the mechanics
(shell, schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict
below owns the UNIQUE, hand-written, personal-injury-firm-specific substance that clears the
uniqueness gate. Never templated find-and-replace, never the plumber content reworded.

Legal hub. Four service angles are here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client."
per the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ==================== AI Receptionist for Personal Injury Lawyers ====================
{
    "slug": "ai-receptionist-for-personal-injury-lawyers", "demo": True,
    "trade_slug": "personal_injury_lawyers", "trade_plural": "personal injury lawyers",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "AI Receptionist for Personal Injury Lawyers",
    "title": "AI Receptionist for Personal Injury Lawyers | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Personal Injury Lawyers",
    "meta_desc": "A personal injury answering service picks up every accident call day or night, runs real intake, and routes true emergencies to your on-call attorney.",
    "service_schema_name": "AI Receptionist for Personal Injury Lawyers",
    "eyebrow": "For Personal Injury Lawyers",
    "h1_html": "AI Receptionist <em>for Personal Injury Lawyers</em>",
    "answer_block": "An AI receptionist for personal injury lawyers answers every accident call the moment it rings, day or night, captures the intake a case actually needs, and routes a true emergency to your on-call attorney while you are in court or asleep. You keep your own number, and every caller belongs to your firm.",
    "sections": [
        {"h2_html": "The call you miss is the case that <em>signs with the next firm</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone who was just in a wreck, or a family member calling from a hospital waiting room, is not going to leave a voicemail and sit tight. They call the next personal injury firm on Google, and the one after that, until a real person picks up and starts helping. In this practice more than almost any other, the firm that answers first and begins the intake is usually the one that signs the case. But you are in a deposition, standing in front of a judge, meeting another client, or asleep at 1am, so the call rolls to voicemail and a case that could be worth a great deal to your firm goes to whoever answered.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist answers on the first ring, stays steady with a shaken caller, finds out what happened, when, and how badly someone is hurt, and either books the consultation or flags a true emergency to your on-call attorney on the spot. The case is captured and moving instead of lost to the firm across town.</p>'},
        {"h2_html": "Built around how <em>accident calls actually come in</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your calls do not keep office hours. A wreck happens on a Friday night, a fall on a Saturday, and the call often comes hours or days later, from a hospital bed, a body shop, or a spouse in a waiting room, whenever the person finally decides to find a lawyer. A voicemail box cannot run an intake, and a generic call center reading a script does not know which questions matter or which call cannot wait until Monday.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24/7, including the nights, weekends, and holidays when accidents happen and every other firm sends the caller to voicemail.</li><li>Runs real intake the way your staff would: what happened, when and where, the injuries, the other driver and their insurance, whether there is a police report, and whether they have already spoken to another firm or an adjuster.</li><li>Flags a true emergency, a serious injury, a caller still at the scene, a filing deadline that looks close, to your on-call attorney at once so a person can call back fast.</li><li>Handles a returning client or a referral differently from a first-time caller, so the people who already trust your firm never hit a machine.</li></ul>'},
        {"h2_html": "The math is <em>one signed case</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. A single serious injury case you would have lost on a weekend is worth far more to your firm than the system costs, and the intake captured on that first call is often what decides whether the person signs with you at all. Everything it captures after that first save is on top. The point is to stop handing your best cases to the firm that simply answered faster.</p>'},
        {"h2_html": "You <em>own</em> the number, the intake, and the client list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing firm number, or a new one registered in your name, not ours. Every caller, every intake, and every detail is yours and exportable any time, so the leads you work hard to earn are an asset your firm keeps instead of something you rent back month to month. There is no long contract holding your data. The AI receptionist is one piece of the Top Shelf platform, and it hands every intake it captures to the same CRM that follows up, so a consultation you have not signed yet never goes cold. It answers and records the facts; your attorneys make every legal decision and every call about whether to take a case.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A midnight call after a wreck, <em>captured while you sleep</em>",
        "body_html": 'It is nearly midnight when someone rear-ended on the highway gets home from the emergency room and starts searching for a personal injury lawyer. They call the first three they find. Two go to voicemail. Yours answers, stays calm, gets the date and location of the crash, the injuries, the other driver\'s insurance, and whether a police report was filed, then books a morning consultation and flags it to your on-call attorney as time-sensitive. You wake up to the intake already written up, with the caller\'s number attached, instead of hearing they signed with someone else. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current firm phone number?",
         'Yes. It can answer on your existing number, or set up a new one registered in your name. Either way the number and every intake that comes through it belong to your firm and go with you if you ever leave.'),
        ("Can it actually run intake, not just take a message?",
         'Yes, that is the point. It asks the questions your intake staff would, what happened, when and where, the injuries, the other driver and their insurance, whether there is a police report, and writes it up so an attorney can pick it up cold. You decide exactly which questions it asks.'),
        ("Will it wake up my on-call attorney for a real emergency?",
         'It flags the calls you tell it to treat as urgent, a serious injury, a caller still at the scene, a deadline that looks close, and alerts your on-call attorney right away so a person can call back fast. You set what counts as drop-everything.'),
        ("Is it going to give the caller legal advice?",
         'No. It answers, reassures, and captures the facts; it does not advise on the case or promise anything about it. Every legal question and every decision about taking a case stays with your attorneys. Someone shaken after a wreck mostly needs to know a real firm is handling it, and a steady voice that gets the details beats a voicemail box.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We build your intake questions, your booking, and your emergency rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current phone setup is missing.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for personal injury lawyers"),
        ("solution-ai-phone.html", "How the AI phone and intake system works"),
        ("crm-for-personal-injury-lawyers.html", "The CRM that follows up on every intake you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing cases to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and after-hours intakes your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ========================= CRM for Personal Injury Lawyers =========================
{
    "slug": "crm-for-personal-injury-lawyers",
    "trade_slug": "personal_injury_lawyers", "trade_plural": "personal injury lawyers",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "CRM for Personal Injury Lawyers",
    "title": "CRM for Personal Injury Lawyers | Top Shelf Business Solutions",
    "og_title": "CRM for Personal Injury Lawyers",
    "meta_desc": "A CRM for personal injury lawyers follows up on every signed and unsigned intake for you, so leads stop going cold and signed clients never feel forgotten.",
    "service_schema_name": "CRM for Personal Injury Lawyers",
    "eyebrow": "For Personal Injury Lawyers",
    "h1_html": "CRM <em>for Personal Injury Lawyers</em>",
    "answer_block": "A CRM for personal injury lawyers keeps every lead, signed client, and open intake in one place and follows up for you, so the person still deciding after a first call and the past client with a new claim both come back to your firm instead of the one that stayed in touch. Your intake list quietly becomes your caseload.",
    "sections": [
        {"h2_html": "The intakes you already took are the cases you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most personal injury firms do not have a call problem. They have a follow-up problem. Someone calls after a wreck, you run the intake, and they say they want to think it over, talk to their spouse, or wait to see what the insurance company offers. Then you get pulled back into active cases and never circle back. They talk to two other firms, and they sign with whoever followed up, not necessarily the one they called first. The lead was never dead. It just needed another call or text a few days later, and that is the thing there is never time for between hearings and client meetings.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open intake in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not anyone remembers. The person weighing two or three firms hears from you again while the others go quiet, and the case comes back to you.</p>'},
        {"h2_html": "A signed client who feels <em>ignored</em> is a bad review waiting to happen",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Signing the case is the start, not the finish. Personal injury matters run for months or years, and the fastest way to lose a client, or earn the one-star review that scares off the next caller, is to go silent while they wait and wonder what is happening with their claim. Keeping every client in the loop is exactly what slips when your desk is buried in active files.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every lead, client, intake, and note lives in one place instead of scattered across voicemails, sticky notes, and three people\'s memory.</li><li>Automatic check-ins go out on a schedule, so a client in the slow middle of a case hears from your firm before they start to worry and call around.</li><li>You can see at a glance who has not heard from you lately and reach the right person with the right update at the right time.</li></ul>'},
        {"h2_html": "Past clients and referral sources are your cheapest <em>cases</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A past client who was treated well is the least expensive case a personal injury firm can get. They already trust you, and the next fender bender, the next fall, the family member who gets hurt comes to you first, as long as you are still in their phone when it happens. The same goes for the people who send you cases, a doctor, a chiropractor, a body shop, another attorney who does not handle injury work. You cannot personally remember to stay in touch with everyone, so a steady, light touch, an occasional check-in, a quick note that you appreciated the referral, keeps your name in front of the people most likely to send you the next case. It costs almost nothing, and it is the difference between a one-time client and a lasting source of work.</p>'},
        {"h2_html": "You <em>own</em> the list, and it works with the rest of the system",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every lead and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the AI receptionist, so a call it answers and an intake it captures land in your database and get followed up on automatically, and to your consultation booking, so a scheduled meeting is logged against the right person with their intake already attached. Nothing your firm has earned goes cold. It tracks the follow-up and the facts; your attorneys make every decision about the case itself.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The unsigned lead that <em>signs a week later</em>",
        "body_html": 'Someone calls on a Monday after a car accident, you run the intake, and they tell you they want to wait and see whether the other driver\'s insurance just pays out. Normally that is the last you hear of them. Instead the CRM sends a friendly check-in two days later and a short note a few days after that, both written to sound like your firm. The insurance offer comes in low, and because yours is the only firm still in front of them, they call you back and sign, without shopping around again. Nobody on your team had to remember to chase it. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing clients and intakes?",
         'Yes. Your current clients, leads, and intake history come in and live in one place, and everything stays yours and exportable. The point is to make the list your firm already has actually work for you.'),
        ("Will it really follow up on unsigned leads automatically?",
         'Yes, on the schedule you approve. An open intake gets a check-in a few days later and another after that, all sent for you, so a person comparing firms keeps hearing from you while the others go quiet. You can step in and reach anyone directly any time.'),
        ("Can it keep signed clients from feeling ignored?",
         'Yes. You set the cadence, and the CRM sends check-ins through the quiet stretches of a case so a client hears from your firm before they start to worry. Consistent contact is one of the simplest ways to hold onto a client and earn the review instead of the complaint.'),
        ("How is this different from the case-management software I already use?",
         'It sits alongside it. Case management runs the legal file; this runs the relationship, the follow-up on leads you have not signed, the check-ins with clients, and the touchpoints with referral sources, which is exactly the part that tends to fall through when everyone is busy.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your contacts, build your follow-up and check-in sequences, and connect it to your calls and booking, so it is working in days. Start with a free audit and we will show you where leads and clients are slipping today.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for personal injury lawyers"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-personal-injury-lawyers.html", "The AI receptionist that feeds it every intake"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting leads and clients <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your intakes and past clients are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ====================== Marketing for Personal Injury Lawyers ======================
{
    "slug": "marketing-for-personal-injury-lawyers",
    "trade_slug": "personal_injury_lawyers", "trade_plural": "personal injury lawyers",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "Marketing for Personal Injury Lawyers",
    "title": "Marketing for Personal Injury Lawyers | Top Shelf Business Solutions",
    "og_title": "Marketing for Personal Injury Lawyers",
    "meta_desc": "Marketing for personal injury lawyers keeps your Google Business Profile active and reviews strong, so an injured person nearby calls your firm first.",
    "service_schema_name": "Marketing for Personal Injury Lawyers",
    "eyebrow": "For Personal Injury Lawyers",
    "h1_html": "Marketing <em>for Personal Injury Lawyers</em>",
    "answer_block": "Marketing for personal injury lawyers keeps your firm visible where accident victims actually look, your Google Business Profile, the map pack, and your reviews, so when someone nearby searches for a lawyer right after a wreck, your name is the active, well-reviewed one they trust and call instead of the firm that let its profile go stale.",
    "sections": [
        {"h2_html": "Personal injury demand is <em>sudden, local, and high-stakes</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody shops for a personal injury lawyer for weeks. The need appears the instant a wreck happens or an injury turns serious, and it is intensely local, because a hurt person wants a firm that knows their county\'s courts and can meet them near home. That means the whole game is being visible and trusted in your market at the exact moment someone nearby needs a lawyer, not running clever ads at people who have not been hurt. Get found first in that moment, as a firm that looks active and credible, and the call is usually yours.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">That is also why a hurt person rarely calls just one firm. They tap the first few names that look trustworthy, and the firm that already appears established and well reviewed in that instant tends to win the call before a real conversation even starts. Marketing is simply making sure yours is one of those names, in the places an injured person actually looks, at the moment they look.</p>'},
        {"h2_html": "Your Google Business Profile and reviews are the first <em>trust test</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for a personal injury lawyer near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and even above the ads. Choosing a lawyer is a high-trust decision made under stress, and a profile that has sat untouched for months, with a few old reviews, looks abandoned next to a firm that shows recent reviews, real replies, and current information. Keeping your profile active, complete, and honest, and steadily earning reviews, is a quiet advertisement running in the exact spot an injured person looks first.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Recent reviews with real replies, so the profile looks attended to rather than abandoned.</li><li>Accurate practice areas, hours, address, and phone number, so a person in a hurry never hits wrong or missing information.</li><li>Current photos and posts, so your firm reads as people who are actually working, not a listing someone set up once and forgot.</li><li>The common questions answered right on the profile, so a searcher gets what they need without leaving to look elsewhere.</li></ul>'},
        {"h2_html": "Show up in the cities and cases you <em>actually take</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and personal injury is one of the most competitive and costly categories there is to advertise in, so a broad spray of ads burns money fast. Focusing on the specific cities and counties you serve, and the case types you actually want, car accidents, truck wrecks, slip and falls, whatever your firm is built for, is what puts you in front of the right searches. It is a tighter, cheaper target than blanketing a region, and it brings the cases you are set up to handle instead of calls you have to turn away.</p>'},
        {"h2_html": "Stay in front, before and after the <em>injury happens</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You cannot predict when someone will be hurt, so the firms that win are the ones already visible and trusted when it happens. A steady local presence, an active profile, a stream of recent reviews, the occasional helpful post, keeps your name in front of a community so you are the one they remember when a friend or family member needs a lawyer. This is the public-facing side of the firm, aimed at people who are not your client yet; the private follow-up to the leads and clients already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A wreck this morning, and you are <em>already at the top</em>",
        "body_html": 'Someone gets rear-ended on the way to work and, once they are home and hurting, searches for a personal injury lawyer near them. Because your Google profile has been kept active all year, with recent reviews, real replies, and current information, your firm sits at the top of the map pack when they look. They read a few reviews, see a firm that clearly pays attention, and call you first. The firm two listings down, the one that let its profile go quiet, never hears the phone that did not ring for it. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with updates, real replies to reviews, and local content on a regular schedule, and keep your practice areas, hours, and service area accurate, so it looks current whenever an injured person searches for a lawyer near them.'),
        ("Is legal marketing not heavily regulated?",
         'It is, and we stay inside the lines. No promising outcomes, no fake or incentivized reviews, no misleading claims. We keep your real profile active and your genuine reviews visible, which is both what the rules allow and what actually earns trust.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with leads and clients already in your database. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at injured people who are not your client yet but need to find and trust your firm the moment something happens.'),
        ("Personal injury ads are so expensive. Is this the same thing?",
         'No. This is about owning your local, organic presence, your profile, your reviews, your visibility in the map pack, which keeps working without a cost-per-click on every accident search. It is the opposite of renting attention through the most expensive keywords in the market.'),
        ("How long before I see it working?",
         'A neglected profile can climb in the map pack within weeks once it is active and complete, and it compounds as reviews and content build. Setup is included, and a free audit will show you what your current online presence looks like to someone searching for a lawyer near you today.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for personal injury lawyers"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-personal-injury-lawyers.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the firm they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible your firm actually is in your market and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# =================== Websites & SEO for Personal Injury Lawyers ===================
{
    "slug": "websites-seo-for-personal-injury-lawyers",
    "trade_slug": "personal_injury_lawyers", "trade_plural": "personal injury lawyers",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "Websites & SEO for Personal Injury Lawyers",
    "title": "Websites & SEO for Personal Injury Lawyers | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Personal Injury Lawyers",
    "meta_desc": "A personal injury lawyer website built for SEO ranks for car accident lawyer near me and your city, and captures the caller directly instead of a lead-seller.",
    "service_schema_name": "Websites & SEO for Personal Injury Lawyers",
    "eyebrow": "For Personal Injury Lawyers",
    "h1_html": "Websites &amp; SEO <em>for Personal Injury Lawyers</em>",
    "answer_block": "A personal injury lawyer website built for SEO ranks for what an injured person types after a wreck, car accident lawyer near me, your city plus attorney, and captures the caller the moment they land, so the case belongs to your firm instead of a directory or a lead-seller renting your own calls back to you.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a personal injury lawyer in your city and the top of the page is often a directory, a find-an-attorney middleman, or a pay-per-lead service, not a local firm. Those sites publish thousands of pages and have years of authority behind them, so an injured person lands there first, fills out a form, and that lead gets sold, sometimes to several firms at once, sometimes back to you for a fee out of your own case. Your site not ranking is not a vanity problem. It is the reason a call you should have gotten for free gets sold to you, or handed to whichever firm is paying the most that week.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">It compounds, too. Every month you are not ranking, that directory earns more authority on the searches in your own city, its listings collect more reviews, and the gap gets harder to close. The firms that own their search presence started building it before they needed it, which is why a site of your own is worth starting now rather than after the next slow stretch.</p>'},
        {"h2_html": "Rank for what an injured person types <em>right after a wreck</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for the broadest term, and you do not need to. Personal injury is one of the most competitive and expensive keyword spaces there is, so you win where the giants are weak: your own firm name, the specific cities and counties you serve, and the exact searches people make after they are hurt, car accident lawyer near me, personal injury attorney in your city, truck accident, slip and fall, plus the case types you take. Pages built around the areas you actually cover and the cases you actually want are what search engines, and an anxious searcher, reward with the click.</p>'},
        {"h2_html": "A person in pain should reach you in <em>one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone who was just hurt is on a phone, stressed, and not going to read three pages of legal history. The site has to load fast, put a tap-to-call button and your practice areas in front of them immediately, and make it obvious they have reached a real local firm with real reviews and real people, while still giving the careful researcher a simple way to request a consultation. A slow, cluttered site that buries the phone number hands the case to the next result; an injured visitor should never leave without an easy way to reach you.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Loads fast on a phone, because a stressed person on mobile will not wait for a heavy page to appear.</li><li>A tap-to-call button and your practice areas visible the second the page opens, with no scrolling to find them.</li><li>Real reviews and real faces up front, so a stranger can decide in seconds that your firm is legitimate.</li><li>A short, simple way to request a consultation for the person who would rather type than call.</li></ul>'},
        {"h2_html": "The calls are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a pay-per-lead service or a directory listing disappears the day you stop paying, and the lead was shared with your competitors anyway. A website your firm owns keeps ranking, keeps capturing calls, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you or raise your rate. The site plugs into the same CRM that follows up on every lead it captures and the AI receptionist that answers the calls it drives, so nothing it earns your firm slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A wreck victim finds <em>your firm</em>, not a directory",
        "body_html": 'Someone hurt in a crash across town searches car accident lawyer near me on their phone. Instead of a national directory that would sell the lead to three firms at once, they find your site ranking for that city, with a page about car accident cases and a tap-to-call button right at the top. They see real reviews, call your firm directly, and reach a person who starts helping. You paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big legal directories?",
         'Not for the broadest terms overnight. It can realistically rank for your firm name, your specific cities and counties, and the case-type and near-me searches a national directory has no reason to target well, which is exactly where a local firm can win.'),
        ("How is this different from paying for leads?",
         'A pay-per-lead service or directory rents you a call it also sells to other firms, and it stops the day you stop paying. A website your firm owns captures calls that are yours alone and keeps working long after it is built, without a fee coming out of every case.'),
        ("Personal injury keywords are the most expensive in Google. Can I really compete?",
         'Not by outbidding the national spenders on the broadest terms, and you do not have to. Owning your organic and local presence, your city, your case types, your reviews, is how a local firm gets found without paying for every single accident click.'),
        ("Most of my best cases come from referrals. Does a website even matter?",
         'It still does. Referred clients look you up before they call, and an injured person with no referral turns to Google in the moment. A site that ranks and looks credible turns both of those into calls instead of sending them to a directory.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks; the broader, more competitive terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for personal injury lawyers"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-personal-injury-lawyers.html", "Staying visible in your market beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own city</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your calls, whether you work with us or not. No credit card, never a call center.",
},
]
