"""Per-page content specs for the SEO corpus (plan §5), junk removal batch. Same contract as
scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, junk-removal-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber content reworded.

Home Services hub. Four service angles here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client."
per the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ======================= AI Receptionist for Junk Removal =======================
{
    "slug": "ai-receptionist-for-junk-removal", "demo": True,
    "trade_slug": "junk_removal", "trade_plural": "junk removal companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Junk Removal",
    "title": "AI Receptionist for Junk Removal | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Junk Removal",
    "meta_desc": "A junk removal answering service answers every call while your crew loads a truck, gives a ballpark, and books the haul before the caller tries a competitor.",
    "service_schema_name": "AI Receptionist for Junk Removal",
    "eyebrow": "For Junk Removal",
    "h1_html": "AI Receptionist <em>for Junk Removal</em>",
    "answer_block": "A junk removal answering service answers every call the moment it rings, even while your crew is loading a truck or driving to the dump, asks what needs to go and where, gives the caller a quick ballpark, and books the haul on your calendar. You keep your own number, and every call stays yours.",
    "sections": [
        {"h2_html": "The call you miss is the truck someone <em>else sends today</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone who just decided the garage has to be cleared, or who needs a couch gone before a move, wants it handled today. They search, they call, and they book whoever answers and can come soonest. Junk removal lives on that impulse more than almost any trade, because the customer is not comparing five bids, they are looking for the first company that picks up and says a truck can be there. But your crew is on a haul with their hands full of a mattress, backed into a driveway across town, or making a run to the transfer station, so the call rings out and the job, along with the full-truck ticket behind it, goes to the next number on the list.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A junk removal answering service picks up on the first ring, asks what needs to go and where, gives the caller a quick ballpark so they are not left guessing, and puts the job on your calendar while your crew keeps working. The haul is captured and scheduled instead of lost to whoever happened to answer.</p>'},
        {"h2_html": "Built around how <em>junk removal jobs come in</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The calls come while you are least able to take them, mid-lift, mid-drive, or halfway down a flight of basement stairs, and a lot of them are not calls at all, they are text and web quote requests with a photo of the pile attached. A voicemail box cannot answer any of that, and a generic call center reading a script does not know a single-item pickup from a full estate cleanout, or what either should roughly cost.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers every call and every after-hours request, including the weekend garage cleanout and the evening can-you-come-tomorrow that a voicemail would lose.</li><li>Asks the questions you would: what is the pile, how much is there, is it curbside or a full-house clear-out, are there appliances or heavy items, and how soon it needs to be gone.</li><li>Gives a sensible ballpark from your own pricing and books the job on your calendar, then texts you the details so the truck shows up with the right space.</li><li>Handles a repeat customer or a referral differently from a first-time caller, so the people who already trust you never reach a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one full truck</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. One garage cleanout or one full-truck haul you would have lost to a phone that rang out is usually worth more than the service costs for months, and the same-day work it books on the spot is the kind you can price with confidence. Everything it captures after that first save is on top. The point is to stop handing your best jobs to the company that simply answered while your crew had their hands full of a couch.</p>'},
        {"h2_html": "You own the number, the calls, and the <em>customer list</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every address, and every job detail is yours and exportable any time, so the customer list you are building is an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The junk removal answering service is one piece of the Top Shelf platform, and it hands every job it captures to the same CRM that follows up on quotes and reminds past customers, so a booked haul or a photo quote never slips.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Saturday garage cleanout, booked while the crew is <em>on a haul</em>",
        "body_html": 'It is Saturday morning and a homeowner finally decides the packed garage has to go before the weekend is over. They search for junk removal and call the first two companies they find. One goes to voicemail. Yours answers, asks what is in there, learns it is a two-car garage of furniture and boxes with an old fridge in the corner, gives a ballpark for a full truck, and books the crew for that afternoon. Your team was across town unloading at the transfer station the whole time and never touched the phone. You come back to the job already on the calendar, with the address, the pile, and the customer number attached. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever switch.'),
        ("Can it give a customer a price?",
         'It gives a sensible ballpark from the pricing you set, single item, half load, full truck, so the caller is not left guessing and is more likely to book on the spot. The firm number still comes from you or the crew once they see the pile, and you decide how much the service quotes on its own.'),
        ("Can it handle the text and web quote requests too, not just calls?",
         'Yes. A lot of junk removal leads arrive as a text or a web form with a photo of the pile, and those get answered and captured the same way a call does, so a quote request at nine at night is booked or followed up instead of sitting unread until morning.'),
        ("Will it actually book the job on my calendar?",
         'Yes. It puts the haul straight on your calendar based on the windows you are running that day, and texts you the details right away, so the crew knows what is coming and shows up with the right truck and enough space.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We load your pricing, your questions, and your calendar for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for junk removal"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-junk-removal.html", "The CRM that follows up on every job you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing hauls to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and quote requests your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ============================= CRM for Junk Removal =============================
{
    "slug": "crm-for-junk-removal",
    "trade_slug": "junk_removal", "trade_plural": "junk removal companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Junk Removal",
    "title": "CRM for Junk Removal | Top Shelf Business Solutions",
    "og_title": "CRM for Junk Removal",
    "meta_desc": "A CRM for junk removal chases every open quote and past customer for you, so the pile someone asked about and the home you cleared last year come back.",
    "service_schema_name": "CRM for Junk Removal",
    "eyebrow": "For Junk Removal",
    "h1_html": "CRM <em>for Junk Removal</em>",
    "answer_block": "A CRM for junk removal keeps every lead, past customer, and open quote in one place and follows up for you, so the photo quote a homeowner is still thinking about and the family whose garage you cleared two years ago both call you next instead of the company that stayed in touch. Your customer list quietly becomes your pipeline.",
    "sections": [
        {"h2_html": "The quotes you already sent are the hauls you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most junk removal companies do not have a lead problem. They have a follow-up problem. Someone texts a photo of a basement full of stuff, you send back a ballpark, they say they need to check with their spouse or line up a free weekend, and then you get busy and never circle back. They call two other companies, and the job goes to whoever followed up, not always the lowest price. The quote was never dead. It just needed one more message a couple of days later, and that is the thing there is never time for between hauls.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open quote in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not you remember. The homeowner still deciding hears from you again while the other companies go quiet, and the haul comes back to you.</p>'},
        {"h2_html": "Every home you clear out is a customer <em>more than once</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">People declutter more than once. The garage this spring becomes the attic next winter, then the move-out cleanout, the deck tear-off, the estate clear-out when a parent downsizes. You have already been to the house, they already trust your crew with the keys and the mess, so the next load is yours if you stay in touch. But you cannot personally remember to reach back out to a few thousand past customers, so most of that repeat work goes to whoever they find on Google when they forget your name.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, address, job history, and photo lives in one place instead of a phone full of old texts and your memory.</li><li>Reminders go out on a schedule you set, a spring-cleaning nudge, a check-in after a move, a note when a season people declutter in comes around, so the work returns without you tracking dates.</li><li>You can see who has not booked in a while and reach the right customer with the right reason at the right time.</li></ul>'},
        {"h2_html": "Referrals and repeat work are the <em>cheapest truck you fill</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A customer you cleared out last year is not disloyal when they call another company. They just lost your card and never saved your number. A light, steady touch, a thank-you, a seasonal reminder, a quick note that you also handle appliances and construction debris, keeps your name in their phone so the next load, and the neighbor they recommend you to, comes to you. It costs almost nothing, and it is the difference between a one-time job and a customer who calls you every time something has to go.</p>'},
        {"h2_html": "You own the list, and it plugs into <em>the whole system</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the answering service, so a call it books lands in your database and gets followed up on automatically, and to online booking, so a scheduled haul is logged against the right customer with their history already attached. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The basement quote that <em>closes itself</em>",
        "body_html": 'A homeowner texts you a photo of a basement they want emptied, and you send back a ballpark on a Monday. They say they need to sort a few things first, which normally is the last you hear of it. Instead the CRM sends a friendly check-in two days later and a short note a few days after that, both written to sound like you. The other companies they messaged never followed up, so when the basement is ready on Saturday, yours is the only name still in front of them, and they book without shopping any further. You never sat down to chase it. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing customers and past jobs?",
         'Yes. Your current customers, leads, and job history come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already have actually work for you.'),
        ("Will it really follow up on quotes automatically?",
         'Yes, on the schedule you approve. An open photo quote gets a check-in a couple of days later and another after that, all sent for you, so a homeowner comparing companies keeps hearing from you while the others go quiet. You can jump in and message anyone directly any time.'),
        ("Can it bring back past customers?",
         'Yes. You set the cadence, a nudge when a season people declutter in comes around, a check-in after a move, a reminder that you also take appliances or renovation debris, and it goes out automatically so repeat hauls and referrals come back without you tracking every name.'),
        ("How is this different from just having their number in my phone?",
         'A phone full of old texts does not follow up, does not remember who you cleared out last year, and does not tell you which quote is going cold. The CRM does all of that on a schedule, so the repeat work actually shows up instead of depending on you to remember.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your customers, build your follow-up and reminder sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where hauls are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for junk removal"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-junk-removal.html", "The answering service that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting quotes and customers <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your quotes and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================== Marketing for Junk Removal ==========================
{
    "slug": "marketing-for-junk-removal",
    "trade_slug": "junk_removal", "trade_plural": "junk removal companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Junk Removal",
    "title": "Marketing for Junk Removal | Top Shelf Business Solutions",
    "og_title": "Marketing for Junk Removal",
    "meta_desc": "Junk removal marketing keeps your Google Business Profile active and your reviews and map pack working, so you catch the searcher who wants a pile gone today.",
    "service_schema_name": "Marketing for Junk Removal",
    "eyebrow": "For Junk Removal",
    "h1_html": "Marketing <em>for Junk Removal</em>",
    "answer_block": "Junk removal marketing keeps you visible where local demand actually shows up, your Google Business Profile, your reviews, and the map pack, so when someone nearby searches for a company to haul a pile away today, your name is the active, well-reviewed one they call instead of the company that let its profile go stale.",
    "sections": [
        {"h2_html": "Junk removal demand is <em>local and right now</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody shops around for a junk removal company for weeks. The need appears the moment a garage feels unbearable, a tenant leaves a unit packed with stuff, or a renovation ends with a pile of debris in the driveway, and it is intensely local, because the customer wants a truck that can be at their door today, not one across the metro. That means the whole game is being visible and trusted in your service area at the exact moment someone nearby needs a haul, not running clever ads to people who do not have a pile yet. The customer who searches at noon wants a truck by dinner, so the company whose listing looks alive and close is the one that catches that urgency. Get found first in that moment and the job is usually yours.</p>'},
        {"h2_html": "Your Google Business Profile is the <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for junk removal near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and above the ads. A profile that sits untouched for months looks abandoned next to one with recent before-and-after photos of cleared garages, a friendly crew, current hours, and a steady stream of reviews. Photos of a clean, branded truck and a full load hauled out of a driveway tell a searcher you do this every day, not as a side gig. Keeping it active, complete, and honest is a quiet advertisement running in the exact spot a customer looks the moment they decide the stuff has to go.</p>'},
        {"h2_html": "Reviews are how a stranger decides to <em>let your crew in</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A junk removal job means letting a couple of workers into your garage, your basement, or a family home to carry things out, so the customer leans hard on reviews before they ever pick up the phone. Recent reviews that mention an on-time, friendly crew that cleaned up after themselves do more to win the call than any slogan, because they answer the only question a nervous customer has: are these people I want in my home. A searcher scans the star rating and the count of recent reviews in a few seconds and rarely looks past the first few names, so a thin or dated profile quietly loses the call before you ever know it rang. A steady flow of them keeps you near the top of the choices a searcher trusts, and it is reputation you own, tied to your own profile, not a lead-seller.</p>'},
        {"h2_html": "Show up in the towns you cover, and stay ready for the <em>season</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and it sends you calls from thirty minutes outside your range. Focusing on the specific towns and neighborhoods you serve, with a profile, photos, and content built around those areas, is what puts you in the map pack where you can actually take the work. Demand also swings with the calendar, spring cleaning, summer move-outs, garages before the holidays, estate cleanouts after them, and being visible right before each wave beats scrambling once it hits. A single well-timed post before a busy weekend can put you in front of a whole neighborhood clearing out at the same time. This is the public-facing side of the business, aimed at people who are not your customer yet, while the private follow-up to people already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "Moving weekend, and you are <em>already at the top</em>",
        "body_html": 'It is the last weekend of the month and half the apartments in town are turning over, leaving behind broken furniture and everything nobody wanted to pack. Because your Google profile has been kept active all year, with recent before-and-after photos, current hours, and a steady flow of reviews about a crew that showed up on time and swept up after, you sit at the top of the map pack when everyone searches for junk removal at once. The people who need a truck that afternoon call the names they can see and trust first, and yours is right there. The company that let its profile go quiet is nowhere on the map. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with before-and-after job photos, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current whenever someone searches for junk removal near them.'),
        ("What does focusing on my service area actually mean?",
         'It means building your profile and content around the specific towns and neighborhoods you can reach quickly, instead of spreading a budget across a whole metro. That is what gets you into the map pack where the local, ready-to-book calls are.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with people already in your database. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at people who are not your customer yet but need to find and trust you the moment they decide the stuff has to go.'),
        ("Can you help me get ahead of the busy seasons?",
         'Yes. We time your visibility to the waves that matter, spring cleaning, summer moves, garages before the holidays, cleanouts after, so you are already in front of people before the rush instead of scrambling once the calls start.'),
        ("How long before I see it working?",
         'A neglected profile can climb in the map pack within weeks once it is active and complete, and it compounds from there as reviews and photos build. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for junk removal"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-junk-removal.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the company they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ====================== Websites & SEO for Junk Removal ======================
{
    "slug": "websites-seo-for-junk-removal",
    "trade_slug": "junk_removal", "trade_plural": "junk removal companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Junk Removal",
    "title": "Websites & SEO for Junk Removal | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Junk Removal",
    "meta_desc": "A junk removal website built for SEO ranks for junk removal near me and your city, and captures the caller, or a photo of the pile, instead of a lead-seller.",
    "service_schema_name": "Websites & SEO for Junk Removal",
    "eyebrow": "For Junk Removal",
    "h1_html": "Websites &amp; SEO <em>for Junk Removal</em>",
    "answer_block": "A junk removal website built for SEO ranks for the searches someone makes the moment they want a pile gone, junk removal near me, furniture pickup, garage cleanout, shows up in the map pack for the towns you cover, and lets them call or send a photo, so the job is yours instead of a lead-seller.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for junk removal in your town and the top of the page is often a national booking brand, a directory, or a pay-per-lead service, not the local crew. Those sites publish thousands of pages and have years of authority behind them, so when someone searches, they land there first, fill out a form, and that lead gets sold, sometimes to three companies at once, sometimes back to you for a fee out of your own margin. Your site not ranking is not a vanity problem. It is the reason a job you should have gotten for free gets sold to you, or handed to whoever is on rotation that week.</p>'},
        {"h2_html": "Rank for what a customer types when they <em>want it gone</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national brand this year for a broad term, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you cover, and for the exact things people search when the stuff has to go: junk removal near me, furniture removal, appliance pickup, garage and basement cleanout, hot tub or shed teardown, construction debris hauling. Each service you run, junk hauling, appliance and mattress disposal, hoarding and estate cleanouts, deserves a page of its own, because that is what people actually type, and a page that names the exact job reads as the obvious one to call. Pages built around the services you actually run and the areas you actually serve are what search engines, and a customer standing in front of a pile, reward with the click.</p>'},
        {"h2_html": "A visitor with a full garage should reach you in <em>one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone who just decided the junk has to go is on a phone, not a desktop, and they are not going to read three paragraphs. The site has to load fast, put a tap-to-call button and your service area in front of them right away, and make it dead simple to snap a photo of the pile and send it for a quote, which is how a lot of these jobs actually start. A pretty site that buries the phone number and hides the quote form is a wasted visit, and a visitor should never leave without an easy way to reach you or show you what they have.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A lot of that deciding happens in the evening, after someone has finally hauled everything into a pile and wants it gone, which is exactly when a photo quote form that actually works, instead of a voicemail box nobody is checking, captures the job while the crews down the road are closed for the night.</p>'},
        {"h2_html": "The calls are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a pay-per-lead service disappears the day you stop paying, and the lead was never really yours anyway. A website you own keeps ranking, keeps capturing calls and photo quotes, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you. The reviews you gather and the local pages you build stack up over time, so a site that ranks this year ranks stronger next year rather than resetting to zero when a budget runs out. The site plugs into the same CRM that follows up on every lead it captures and the answering service that picks up the calls it drives, so nothing it earns you slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A driveway full of debris finds <em>you</em>, not a directory",
        "body_html": 'A homeowner two towns over finishes a bathroom remodel and is left with a driveway full of old tile, a torn-out vanity, and busted drywall. They search junk removal near me on their phone. Instead of a national directory that would sell the lead to three crews, they find your site ranking for that town, with a page about construction debris and a button to snap a photo and get a quote right at the top. They send a picture of the pile, you reply with a ballpark, and the job is yours. You paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big directories?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the service searches a national brand has no reason to target well, garage cleanouts, appliance pickup, debris hauling, which is exactly where a local crew can win.'),
        ("How is this different from paying for leads?",
         'A pay-per-lead service rents you a job that it also sells to your competitors, and it stops the day you stop paying. A website you own captures calls and photo quotes that are yours alone and keeps working long after it is built, without a per-lead fee coming out of every haul.'),
        ("Can customers send a photo of the pile from the site?",
         'Yes, and they should be able to in one tap, because that is how a lot of junk removal jobs start. The site makes it easy to snap a picture and request a quote, and it lands in your CRM so you can reply with a ballpark fast.'),
        ("Most of my calls are same-day. Does a website even help?",
         'Especially then. A same-day search happens on a phone the moment someone wants a pile gone, and the crew that shows up in the map pack with a tap-to-call button and real reviews gets the job. A site built for that moment is exactly what captures it.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for junk removal"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-junk-removal.html", "Staying visible in your service area beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your calls, whether you work with us or not. No credit card, never a call center.",
},
]
