"""Per-page content specs for the SEO corpus (plan §5), movers batch. Same contract as
scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, mover-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber content reworded.

Home Services hub. Four service angles here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client."
per the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ========================== AI Receptionist for Movers ==========================
{
    "slug": "ai-receptionist-for-movers", "demo": True,
    "trade_slug": "movers", "trade_plural": "movers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Movers",
    "title": "AI Receptionist for Movers | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Movers",
    "meta_desc": "A moving company answering service answers every quote call, even when your crews are on a truck, captures the move details, and books the estimate for you.",
    "service_schema_name": "AI Receptionist for Movers",
    "eyebrow": "For Movers",
    "h1_html": "AI Receptionist <em>for Movers</em>",
    "answer_block": "A moving company answering service answers every quote call the moment it rings, even when your crews are all on a truck and cannot reach the phone, gathers the move details, where from, where to, how big, what day, and books the estimate on your calendar so the move belongs to you instead of the mover who picked up first.",
    "sections": [
        {"h2_html": "The quote call you miss is the move that <em>books the next mover</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone planning a move is not calling one company. They line up three or four, work down the list, and book the first one that answers, sounds like a real outfit, and can hold their date. Moving runs on that more than almost any trade, because the customer has a hard deadline, a lease ending or a closing that will not move, and they cannot sit around waiting for a callback. But on moving day every mover you have is on a truck, wrapping a dresser or carrying a couch down three flights, nowhere near a phone, so the call rings out and the job, along with the deposit that would have held the date, goes to whoever answered.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A moving company answering service picks up on the first ring, stays calm and professional, asks where they are moving from and to, how big the place is, and what day they need, and either books the estimate or the move right there. The job is captured and sitting on your calendar instead of lost to the company down the road that happened to be between loads.</p>'},
        {"h2_html": "Built around how <em>movers actually get calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your calls do not arrive evenly through the month. They bunch up at the end of it when leases turn over, they climb all summer when the whole town seems to move at once, and the busiest hours on the phone are the exact hours your crews are out on trucks and cannot answer. A voicemail box cannot quote a move, and a generic call center reading a script does not know a studio apartment from a four-bedroom house, or a quick local move from a long-distance haul that needs real planning.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24 hours a day, including the packed Saturdays, the end-of-month crunch, and the summer stretch when every crew you have is already loading a truck.</li><li>Asks what you would ask: where from, where to, how many bedrooms, stairs or an elevator, whether they need packing, and the date they have to be out.</li><li>Captures the details and books the in-home or virtual estimate straight onto your calendar, and texts you a big move worth calling back yourself right away.</li><li>Treats a repeat customer or a referral from a past move differently from a cold caller, so the people who already trust your crew never land in a voicemail box.</li></ul>'},
        {"h2_html": "The math is <em>one booked move</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. One full-house move or one long-distance job you would have lost while your crew was carrying furniture is often worth more than the service costs for months, and the busy season, when the most work is on the line, is exactly when the most calls go unanswered. Everything it captures after that first save is on top. The point is to stop handing your booked weekends to the company that simply answered faster.</p>'},
        {"h2_html": "You own the number, the calls, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, both addresses, and every move detail is yours and exportable any time, so your customer list is an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The answering service is one piece of the Top Shelf platform, and it hands every call it captures to the same CRM that follows up, so an estimate that has not booked yet never quietly slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Saturday move, booked while your <em>crew is on the truck</em>",
        "body_html": 'It is the last Saturday of the month and every crew you have is out, one loading a two-bedroom across town and the other halfway to a delivery. A family whose lease ends Monday is calling movers and lands on you. Normally that rings out and they book the next name on their list. Instead the call is answered on the first ring, the details get taken, where they are moving from and to, that it is a two-bedroom with a flight of stairs, that it has to be done before the weekend is over, and an estimate is booked for that evening while a note pings your phone. You finish the day with a new move on the calendar instead of never knowing the call came in. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current phone number?",
         'Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever leave.'),
        ("Can it quote a move, or just take a message?",
         'It does not guess at a price. It gathers everything an accurate quote needs, where from, where to, the size of the place, stairs or an elevator, packing, and the date, then books the in-home or virtual estimate on your calendar. You still set the price, but the move is captured instead of lost.'),
        ("What happens during the summer and end-of-month rush?",
         'That is exactly when it earns its keep. It answers every call at once, no matter how many come in while your crews are on trucks, so the busiest days of your year stop being the days you miss the most work.'),
        ("Is it going to sound like a robot to my customers?",
         'It answers naturally and is upfront instead of pretending to be a person. Someone about to trust a crew with everything they own mostly wants to know a real company is handling it, and a steady voice that takes the details beats a voicemail box every time. You can hear it handle a live call before you decide.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We configure your questions, your calendar, and your booking rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for movers"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-movers.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing booked moves to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many quote calls and booked weekends your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ================================ CRM for Movers ================================
{
    "slug": "crm-for-movers",
    "trade_slug": "movers", "trade_plural": "movers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Movers",
    "title": "CRM for Movers | Top Shelf Business Solutions",
    "og_title": "CRM for Movers",
    "meta_desc": "A CRM for moving companies follows up on every estimate and past customer for you, so the moves you quoted and the people you moved keep coming back to you.",
    "service_schema_name": "CRM for Movers",
    "eyebrow": "For Movers",
    "h1_html": "CRM <em>for Movers</em>",
    "answer_block": "A CRM for moving companies keeps every lead, past customer, and open estimate in one place and follows up for you, so the family still comparing three quotes and the customer you moved two years ago both call you next instead of the company that stayed in touch. Your customer list quietly becomes your booked calendar.",
    "sections": [
        {"h2_html": "The estimates you already gave are the moves you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most movers do not have a lead problem. They have a follow-up problem. You quote a family on a three-bedroom move, they say they are still gathering prices, and then the season swallows you and you never circle back. They collect two more estimates and book whoever followed up, not always the lowest bid. The estimate was never dead. It just needed one more call or text a few days later, and that is the thing there is never time for when your crews are out and the phone will not stop.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open estimate in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not you remember. The family weighing three movers hears from you again while the other two go quiet, and the move comes back around to you.</p>'},
        {"h2_html": "Every person you move is a customer <em>for the next one</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Past customers are the cheapest moves a company can get. You have already carried their couch, they already trust your crew inside their home, and the next move, the apartment upgrade in two years, the first house, the parents downsizing, is yours if you stay in touch. But you cannot personally remember to reach back out to everyone you have ever moved, so most of that repeat work drifts to whoever they find online once they have forgotten your name.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, both addresses, move history, and your notes live in one place instead of a stack of paper estimates and whatever you can remember.</li><li>You can see who moved a year or two back, the exact people coming due to move again, and reach them before a competitor turns up in their search.</li><li>Thank-you and referral asks go out automatically after a move, so the happy customer who would gladly recommend you actually gets asked while the good experience is still fresh.</li></ul>'},
        {"h2_html": "The referral and the repeat move are a <em>goldmine you already own</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A crew that did a careful, on-time job is the easiest recommendation a customer ever makes, and people about to move almost always ask their friends who to call. A steady, light touch, a thank-you after the truck pulls away, a quick check that everything arrived fine, a note when the season comes back around, keeps your name in their phone and turns one good move into two or three more through the people they talk to. It costs almost nothing, and it is the difference between a one-time job and a customer who quietly sends you work for years. The same list quietly turns your best referral sources into partners, the apartment complex that hands your card to every move-out, the realtor who recommends a crew at closing, all sitting in one place where a thank-you or a check-in goes out on schedule without you thinking about it.</p>'},
        {"h2_html": "You own the list, and it works with the rest of the system",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the answering service, so a call it captures lands in your database and gets followed up on automatically, and to your booking, so a scheduled estimate is logged against the right customer with their full move history already attached. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The estimate that <em>closes itself</em>",
        "body_html": 'You quote a family on a two-bedroom move on a Monday and they tell you they are getting one more price. Normally that is the last you hear of it. Instead the CRM sends a friendly check-in two days later and a short note a few days after that, both written to sound like you. The other two movers never followed up, so when the family is ready on Friday, yours is the only name still in front of them, and they book with you without shopping any further. You never sat down to chase it. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing customers and past moves?",
         'Yes. Your current customers, leads, and move history come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already have actually book you work.'),
        ("Will it really follow up on estimates automatically?",
         'Yes, on the schedule you approve. An open quote gets a check-in a few days later and another after that, all sent for you, so a family comparing movers keeps hearing from you while the others go quiet. You can jump in and message anyone directly any time.'),
        ("Can it help me get repeat moves and referrals?",
         'Yes. It flags customers who moved a year or two back and are due to move again, and it sends automatic thank-you and referral asks after a move, so the repeat work and the recommendations come back around without you keeping track.'),
        ("How is this different from just having their number in my phone?",
         'A phone full of contacts does not follow up, does not remember who is due to move again, and does not tell you which estimate is going cold. The CRM does all of that on a schedule, so the repeat work and the quotes you already gave actually turn into booked moves.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your customers, build your follow-up and referral sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where moves are slipping through today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for movers"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-movers.html", "The answering service that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting estimates and customers <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your estimates and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ============================= Marketing for Movers =============================
{
    "slug": "marketing-for-movers",
    "trade_slug": "movers", "trade_plural": "movers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Movers",
    "title": "Marketing for Movers | Top Shelf Business Solutions",
    "og_title": "Marketing for Movers",
    "meta_desc": "Moving company marketing keeps your Google Business Profile active and your name first in the map pack, so you catch the rush the moment someone needs to move.",
    "service_schema_name": "Marketing for Movers",
    "eyebrow": "For Movers",
    "h1_html": "Marketing <em>for Movers</em>",
    "answer_block": "Marketing for movers keeps you visible where moving demand actually shows up, your Google Business Profile and the map pack, so when someone nearby searches for a mover as their move date closes in, your name is the active, well-reviewed one they call instead of the company that let its profile go stale.",
    "sections": [
        {"h2_html": "Moving demand is <em>local and seasonal</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody books a mover months ahead on a whim. The demand appears the moment a lease is signed, a house closes, or a job starts in a new city, and it is intensely local, because a customer wants a crew based near them, not one driving an hour in from across the metro. It also swings hard with the calendar, the end of every month as leases turn over, and the long summer stretch when it feels like the whole town moves at once. So the whole game is being visible and trusted in your service area at the exact moment someone nearby needs to move, not running clever ads at people who have no move on the horizon. Get found first in that moment and the job is usually yours.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for movers near them, the map pack, those three local listings with the star ratings, is the first thing they see, sitting above the websites and above the ads. A profile left untouched for months looks abandoned next to one with recent photos of real crews and clean trucks, current hours, and a steady flow of reviews. For a customer about to hand a crew everything they own, that freshness reads as proof you are a real, working company. Keeping the profile active, complete, and honest is a quiet advertisement running in the exact spot people look the week they have to move. A steady stream of honest reviews does double duty here, it is the trust a nervous customer is looking for and one of the signals that lifts you in the map pack, so the more real moves you turn into reviews, the higher you sit the next time someone nearby searches.</p>'},
        {"h2_html": "Show up in the <em>towns you actually serve</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Marketing to a whole metro is expensive and forgettable, and it drums up calls for moves an hour past the range you actually want to drive. Focusing on the specific towns and neighborhoods you serve, with a profile, photos, and content built around those areas, is what puts you in the map pack where you can genuinely take the work. It is a tighter, cheaper target than a citywide spend, and it is the one that turns into moves your crews can reach without burning half a day sitting in traffic. It is also how you win the second and third towns over, the neighboring suburbs a searcher there would never assume you cover, because your profile and your local pages name those areas plainly instead of leaving people to guess how far your trucks will actually drive on moving day.</p>'},
        {"h2_html": "Be ready before the season, and stay in front of past customers",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Moving demand runs on a calendar you can see coming, the end-of-month lease turnover, the summer peak, the quiet stretch after the holidays, and being visible right before each wave beats scrambling once the phone is ringing off the hook. A steady local presence, seasonal posts, photos from real jobs, the occasional tip on packing or on picking a mover you can trust, keeps you top of mind for the next move and reminds past customers you are still the crew to call. This is the public-facing side of the business; the private follow-up to people already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The summer rush, and you are <em>already at the top</em>",
        "body_html": 'Summer arrives and half the town seems to move inside the same six weeks, leases ending, families relocating before school starts, everyone searching for a mover at once. Because your Google profile has been kept active all year, with recent photos of your crews and trucks, current hours, and a steady flow of reviews, you are sitting at the top of the map pack when the searches spike. The people who need to move that month call the names they can see and trust first, and yours is right there in front of them. The company that let its profile go quiet is nowhere on the map. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with photos of real jobs, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current whenever someone searches for a mover near them.'),
        ("What does focusing on my service area actually mean?",
         'It means building your profile and content around the specific towns and neighborhoods your crews can reach easily, instead of spreading a budget across a whole metro. That is what gets you into the map pack where the local, ready-to-move calls are.'),
        ("How is this different from the CRM follow-up?",
         'The CRM follows up privately with people already in your database. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at people who are not your customer yet but need to find and trust you the week they decide to move.'),
        ("Can you help me get ahead of the busy season?",
         'Yes. We time your visibility to the waves that matter, the end-of-month turnover and the summer peak, so you are already in front of people before the rush instead of scrambling once every crew is booked solid.'),
        ("How long before I see it working?",
         'A neglected profile can climb in the map pack within weeks once it is active and complete, and it compounds from there as reviews and content build. Setup is included, and a free audit will show you what your current online presence looks like to someone searching near you today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for movers"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-movers.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the mover they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================== Websites & SEO for Movers ==========================
{
    "slug": "websites-seo-for-movers",
    "trade_slug": "movers", "trade_plural": "movers",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Movers",
    "title": "Websites & SEO for Movers | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Movers",
    "meta_desc": "A moving company website built for SEO ranks for movers near me and your city, and earns the trust of a customer handing strangers everything they own.",
    "service_schema_name": "Websites & SEO for Movers",
    "eyebrow": "For Movers",
    "h1_html": "Websites &amp; SEO <em>for Movers</em>",
    "answer_block": "A moving company website built for SEO ranks for the searches people make when planning a move, movers near me, local movers, long-distance moving, shows up in the map pack for the towns you cover, and earns the trust of someone handing strangers everything they own, so the move is yours instead of a lead-seller's.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a mover in your town and the top of the page is often a directory, a national booking middleman, or a moving-lead marketplace, not the local company. Those sites publish thousands of pages and carry years of authority, so when someone searches, they land there first, fill out a form, and that lead gets sold, sometimes to several movers at once, sometimes back to you for a fee out of your own margin. Moving is one of the worst trades for this; whole businesses exist only to catch your customers first and sell them on. Your site not ranking is not a vanity problem. It is the reason a call you should have had for free gets sold to you, or handed to three competitors right alongside you.</p>'},
        {"h2_html": "Rank for what someone types when they are <em>planning a move</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national marketplace this year for the broadest term, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you serve, and for the exact searches someone makes when a move is bearing down on them: movers near me, local movers in your city, apartment movers, long-distance moving, last-minute movers. Pages built around the moves you actually run and the areas you actually cover are what search engines, and people with a move date they cannot push, reward with the click. It is also where the specialty and higher-value work lives, the piano or the gun safe, the office or warehouse move, the packing-only job, the long-haul relocation, all searches a national marketplace never bothers to answer well, and every one of them is a page you can own outright while the directories chase the generic term.</p>'},
        {"h2_html": "Someone trusting you with everything they own reads your site <em>before they call</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A move is not a low-trust purchase. The customer is about to let a crew of strangers into their home and hand over everything they own, so before they ever call they are reading your site to decide whether you look like a real, established, insured company or just a truck and a phone number. A clear site with real photos of your crews, your license and insurance stated plainly, honest reviews, and a simple way to ask for a quote is what turns a nervous visitor into a booked move.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">And a lot of that deciding happens late at night, when someone finally sits down after the kids are asleep to sort out their move, which is exactly when a quote form that actually works, instead of a voicemail box nobody is checking, captures the job while your competitors are asleep.</p>'},
        {"h2_html": "The calls are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you pour into a lead marketplace disappears the day you stop paying, and the lead was never really yours anyway, it was sold to your competitors in the same breath. A website you own keeps ranking, keeps capturing quote requests, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you tomorrow. The site plugs into the same CRM that follows up on every quote it captures and the answering service that picks up the calls it drives, so nothing it earns you slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A late-night quote request finds <em>you</em>, not a marketplace",
        "body_html": 'A family two towns over has just signed a lease and sits down at ten at night to finally deal with the move. They search for movers in their area on a phone. Instead of a national marketplace that would sell their details to several companies at once, they find your site ranking for that town, with a page about local moves, your license and insurance stated plainly, real reviews, and a quote form right there. They fill it out before bed, it lands in your system overnight, and you follow up first thing in the morning. The move is yours, you paid nothing per lead, and no middleman ever touched it. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big moving marketplaces?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the local and specialty move searches a national marketplace has no reason to target well, which is exactly where a local mover can win.'),
        ("How is this different from buying moving leads?",
         'A lead marketplace rents you a customer it also sells to your competitors, and it stops the day you stop paying. A website you own captures quote requests that are yours alone and keeps working long after it is built, without a per-lead fee coming out of every move.'),
        ("Do I need to rank for every town I serve?",
         'You rank for the ones that matter most first. We build pages for your core service areas and the highest-intent searches, then expand, rather than spreading thin across a whole metro at once.'),
        ("Why does the site itself matter so much for a mover?",
         'Because a customer is about to trust a crew with everything they own. Before they call, they read your site to see whether you look established, licensed, and reviewed. A clear, honest site with real photos and an easy quote form is often what decides between you and the next company on the list.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for movers"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-movers.html", "Staying visible in your service area beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the marketplaces and lead-sellers taking your calls, whether you work with us or not. No credit card, never a call center.",
},
]
