"""Per-page content specs for the SEO corpus (plan §5), bankruptcy attorneys batch. Same
contract as scripts/corpus_specs.py: generate_corpus.py imports SPECS and owns the mechanics
(shell, schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict
below owns the UNIQUE, hand-written, bankruptcy-firm-specific substance that clears the
uniqueness gate. Never templated find-and-replace, never the plumber, personal-injury,
criminal-defense, family-law, or estate-planning content reworded.

Legal hub, shared with the personal-injury, criminal-defense, family-law, and estate-planning
batches, so these dicts are written bankruptcy-distinct on purpose: a caller in financial
crisis and ashamed, usually forced to act by a hard deadline (a wage garnishment, a
foreclosure sale date, a repossession, a lawsuit), who calls quietly, compares a couple of
firms, and retains the one that answers with dignity and a clear next step; Chapter 7 versus
Chapter 13 questions; the levers are answering the anxious call without judgment, following up
the consults who freeze out of fear and shame, and the means-test and document-gathering
intake; marketing that is reassuring and non-shaming, a judgment-free local reputation and
reviews that speak to being treated with respect; and a private, plain-language site with a
discreet contact option, not just a big phone number. Four service angles are here in one file
(the ai-receptionist dict carries "demo": True). Each example body ends with the literal
"Illustrative example, not a client." per the honesty rule; if the generator also appends that
line, dedupe there. Attorney advertising ethics: nothing here promises or implies that a debt
will be discharged or any other outcome, and the AI intake never gives legal advice.
"""

SPECS = [
# ==================== AI Receptionist for Bankruptcy Attorneys ====================
{
    "slug": "ai-receptionist-for-bankruptcy-attorneys", "demo": True,
    "trade_slug": "bankruptcy_attorneys", "trade_plural": "bankruptcy attorneys",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "AI Receptionist for Bankruptcy Attorneys",
    "title": "AI Receptionist for Bankruptcy Attorneys | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Bankruptcy Attorneys",
    "meta_desc": "A bankruptcy answering service answers every anxious call with dignity, runs the debt and means-test intake, and books the consultation while you are in court.",
    "service_schema_name": "AI Receptionist for Bankruptcy Attorneys",
    "eyebrow": "For Bankruptcy Attorneys",
    "h1_html": "AI Receptionist <em>for Bankruptcy Attorneys</em>",
    "answer_block": "A bankruptcy answering service answers every call the moment it rings, meets a caller in financial crisis with calm and dignity instead of a voicemail, captures the debt and means-test intake a case needs, and books the consultation while you are in court. Your number stays yours, and so does every caller it brings in.",
    "sections": [
        {"h2_html": "The garnished paycheck and the foreclosure date do not wait for <em>Monday</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">By the time most people call a bankruptcy attorney, something has already forced their hand. A paycheck came in short because wages are being garnished, a foreclosure sale date is set, a car was repossessed or is about to be, or a lawsuit and a court date just landed in the mailbox. The relief they need is on a clock, and the person calling is frightened, embarrassed, and half-expecting to be judged for letting it get this far. That combination is unlike any other legal call: the urgency of a hard deadline sitting on top of real shame.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">So they call quietly, often on a break or after the kids are asleep, and if they reach a voicemail the shame usually wins and they hang up rather than leave a message about their debts on a machine. Then they try the next firm. A bankruptcy answering service answers on the first ring, stays warm and matter-of-fact with someone braced to be looked down on, finds out whether a garnishment, a sale date, or a lawsuit is already running, and books the consultation before the moment, and the nerve, passes.</p>'},
        {"h2_html": "Built for a caller who is <em>ashamed and up against a deadline</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Bankruptcy calls do not sound like other legal calls. The person may lower their voice because a spouse does not know how bad it has gotten, or open with an apology for even calling. Some are only starting to wonder whether bankruptcy is an option; others have a garnishment hitting Friday and need to know their choices now. A voicemail box cannot reassure a person in that state, and a generic call center reading a script cannot tell a true deadline from a caller who is still just gathering courage, or capture the facts a bankruptcy file actually starts with.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers day and night, so the person who can only call after work, or a spouse calling on their behalf, reaches a calm human instead of a machine.</li><li>Meets the questions people actually ask, whether they would file Chapter 7 or Chapter 13, whether filing can stop a garnishment or a foreclosure, what happens to the house and the car, without ever giving legal advice.</li><li>Gathers what a bankruptcy matter starts with: a rough picture of the debts and income, whether wages are being garnished, whether a foreclosure, repossession, or lawsuit has a date attached, and whether they have filed before.</li><li>Recognizes a returning client or a referral and treats them differently from a first-time caller, so someone who already trusts your firm never lands in a voicemail box.</li></ul>'},
        {"h2_html": "People retain the firm that answers with <em>dignity and a clear next step</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone in financial crisis is not shopping on price, and they rarely call just one firm. They try a couple, quietly, and they retain the one that treats them like a person and gives them a clear next step instead of making them feel worse. The firm that answers, listens without judgment, and says in plain terms what happens now is the one that earns the retainer, and that first call is where it is won or lost. A bankruptcy answering service is built to be that calm, respectful first voice at the hour the other firms send the caller to voicemail.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The math is forgiving. A single Chapter 7 or Chapter 13 matter you would have lost to a weekend voicemail is usually worth far more to your firm than the service costs, and everything it captures after that is on top. The point is not to chase volume; it is to stop handing the person who finally worked up the nerve to call to whichever firm simply picked up first.</p>'},
        {"h2_html": "You <em>own</em> the number, the intake, and the client list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The service runs on the number your firm already advertises, or a new one put in your name, never ours, and everything that comes through it stays yours and exportable whenever you want it. The people you spend real money to reach become an asset your firm keeps instead of a list you effectively rent back each month, and there is no long contract holding your data. The answering service is one piece of the Top Shelf platform, and it hands each consultation it books to the same CRM that follows up, so a person who is still deciding is never left to go cold. And it stays firmly in its lane: it answers, reassures, and writes down the facts, and it never gives legal advice, never tells a caller which chapter to file, and never promises that any debt will be discharged. Those judgments belong to your attorneys alone.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A garnished paycheck on a Friday, <em>captured while you sleep</em>",
        "body_html": 'A man opens his paycheck and finds it hundreds short because a creditor has started garnishing his wages, and that night, ashamed and scared, he starts quietly calling bankruptcy attorneys from the garage so his family does not hear. The first firm he tries sends him to voicemail, and he almost gives up. Yours answers gently, does not make him feel judged, learns that the garnishment just started and that he has never filed before, and books him a consultation for the next morning with a note that the timing matters. You arrive to the intake already written up, with his number attached, instead of never knowing he called. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current firm phone number?",
         'Yes. It can answer on your existing number, or set up a new one registered in your name. Either way the number and every intake that comes through it belong to your firm and go with you if you ever leave.'),
        ("Can it actually run intake, not just take a message?",
         'Yes, that is the point. It gathers what a bankruptcy matter starts with, a rough picture of the debts and income, whether wages are being garnished, whether a foreclosure, repossession, or lawsuit has a date attached, and whether they have filed before, and writes it up so an attorney can pick it up cold. You decide exactly which questions it asks.'),
        ("Will it flag a real deadline, like a garnishment or a foreclosure sale, to my attorney?",
         'It flags the calls you tell it to treat as urgent, wages already being garnished, a foreclosure sale date that is close, a repossession, a lawsuit with a fast deadline, and alerts your on-call attorney right away so a real person can follow up. You set what counts as drop-everything.'),
        ("Is it going to give the caller legal advice or promise their debt will be wiped out?",
         'No, and this matters. It answers, reassures, and captures the facts; it never advises on the case, never tells a caller whether to file Chapter 7 or Chapter 13, and never promises that any debt will be discharged. Every legal question and every decision about taking a matter stays with your attorneys. Someone ashamed and frightened mostly needs to feel that a real firm is handling it without judgment, and a calm voice that gets the details beats a voicemail box.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We build your intake questions, your booking, and your urgent-case rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current phone setup is missing.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for bankruptcy attorneys"),
        ("solution-ai-phone.html", "How the AI phone and intake system works"),
        ("crm-for-bankruptcy-attorneys.html", "The CRM that follows up on every consultation you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop sending your most anxious callers to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and after-hours consultations your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ========================= CRM for Bankruptcy Attorneys =========================
{
    "slug": "crm-for-bankruptcy-attorneys",
    "trade_slug": "bankruptcy_attorneys", "trade_plural": "bankruptcy attorneys",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "CRM for Bankruptcy Attorneys",
    "title": "CRM for Bankruptcy Attorneys | Top Shelf Business Solutions",
    "og_title": "CRM for Bankruptcy Attorneys",
    "meta_desc": "A CRM for bankruptcy attorneys follows up with the consultations that stall out of shame and keeps clients on track through the paperwork a filing needs.",
    "service_schema_name": "CRM for Bankruptcy Attorneys",
    "eyebrow": "For Bankruptcy Attorneys",
    "h1_html": "CRM <em>for Bankruptcy Attorneys</em>",
    "answer_block": "A CRM for bankruptcy attorneys chases the consultations that stall because fear and shame stop people from moving, and keeps signed clients on track through the means test and the document gathering a filing demands. The person who almost let their case slide files with your firm because it followed up with care.",
    "sections": [
        {"h2_html": "The consultation that stalls out of <em>fear and shame</em> is the one that never files",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most bankruptcy firms do not have a call problem. They have a follow-through problem, and it is a particular kind. Someone comes in, learns what filing could do for a situation that has gotten out of hand, and agrees it is the right move, and then nothing happens. Bankruptcy feels like an admission of failure, so the fear settles back in the moment they leave. A creditor calls and promises to work something out. The stack of paperwork feels impossible to face. So they go quiet, and the case that could have given them a fresh start sits untouched while the garnishment keeps taking and the sale date keeps coming.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every consultation that has not turned into a filing in front of you and follows up for you, on a schedule you set, with messages that sound like your firm and never shame anyone. It is not a sales chase; it is a steady, respectful reminder that you are ready when they are and that the clock on their debt is still running. The person who froze after the first meeting hears from you again at the right moment, instead of surfacing months later with fewer options, or filing somewhere else after a relative finally pushed them.</p>'},
        {"h2_html": "The document gathering and the <em>means test</em> are where signed clients disappear",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Signing the client is the start of the hardest stretch, not the end of it. A bankruptcy filing runs on paperwork, pay stubs, tax returns, bank statements, a complete list of every debt and creditor, and the means test that has to be worked out, and it all has to come from a client who is stressed, embarrassed, and not used to pulling documents together. That is exactly where cases stall. The client means to send it, dreads it, and lets it slip, and a matter that should have been filed weeks ago drifts while the situation gets worse. Chasing every missing document by hand is the first thing that falls off your plate in a busy week.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every client, consultation, deadline, and note sits in one place instead of scattered across message slips, a shared inbox, and three people remembering different things.</li><li>Automatic reminders nudge a client for the specific documents still missing, so the file keeps moving toward a filing instead of stalling halfway through intake.</li><li>Check-ins reach the client before a hearing, a meeting of creditors, or a deadline, so nothing slips because everyone assumed someone else was watching it.</li><li>A clear view of who has gone quiet lets you reach a stuck client before the case falls apart, not after.</li></ul>'},
        {"h2_html": "Your referrals come from <em>past clients and the professionals who cannot help them</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Bankruptcy runs on its own quiet web of referrals, and it is not the web an injury or estate practice has. A past client who was treated with respect through the lowest point of their finances is the one who quietly tells a coworker or a sibling, when their turn comes, exactly who to call, and some of them will need you again themselves down the road. Just as important are the professionals who meet people in trouble but cannot help them: a family or personal injury attorney whose client is drowning in debt, a real estate agent facing a client\'s foreclosure, a credit counselor who has taken someone as far as counseling can. None of that stays warm on its own, and it is delicate, because money trouble is private and a referral is a personal vouch. A CRM keeps a light, respectful touch on past clients and referral sources, a thank-you when someone sends a person your way, a periodic hello, so your firm is the first name that comes up the next time someone in that circle is quietly going under.</p>'},
        {"h2_html": "One list, wired to your calls and every <em>step of the case</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every client and every note belongs to you and can be exported whenever you like, never sealed inside a tool you lease by the month. The CRM is one piece of the Top Shelf platform: the consultations your answering service books flow into it and the follow-up begins on its own, and each meeting, hearing, and document deadline hangs on the right person so nothing lives in two systems or falls out of both. Your bankruptcy case and petition software still prepares the schedules and the filing itself. The CRM works the human side of a stressful process: the people too scared to move forward, the clients stuck in the paperwork, and the past clients and professionals who send you the next matter. It carries the relationship while your attorneys carry the law, and it never promises a client a thing about how their debts will be resolved.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The consult that froze, and <em>filed a month later</em>",
        "body_html": 'A woman comes in about a mounting pile of medical and credit card debt, agrees that filing makes sense, and takes home the list of documents she needs to gather. Then the shame catches up with her, a card company offers a payment plan, and she goes quiet. Normally that is the last you hear of it. Instead the CRM, seeing the consultation never turned into a filing, sends a gentle, no-pressure check-in a couple of weeks later and another after that, both written to sound like your firm. When the payment plan collapses and a garnishment notice arrives, yours is the only firm that stayed kindly in touch, so she calls back and moves forward without shopping around. Nobody on your team had to remember her. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import the clients and consultations I already have?",
         'Yes. Your current clients, the people who came in for a consultation, and your notes all come in and live in one place, and every bit of it stays yours and exportable. The point is to put the relationships your firm has already built to work instead of letting them sit forgotten in a phone and an inbox.'),
        ("Will it follow up on someone who consulted but got cold feet?",
         'Yes, on the schedule you approve. A consultation that never turns into a filing gets a gentle, no-pressure check-in later and another after that, sent for you, so someone stalled by fear or shame keeps hearing that you are ready whenever they are. You can step in and reach anyone yourself any time.'),
        ("Can it help clients get through the document gathering and means test?",
         'Yes, and for a bankruptcy practice that is often the biggest win. It reminds a client for the specific documents still missing and checks in ahead of a hearing or a meeting of creditors, so the file keeps moving toward a filing instead of stalling halfway through intake. It organizes the follow-up; your team still handles the legal work.'),
        ("Can it keep my referral sources warm?",
         'Yes. It keeps an organized, light touch on past clients and the professionals who send you work, a family or injury attorney, a real estate agent, a credit counselor, so a thank-you and a periodic hello go out and those relationships stay warm instead of fading. That quiet network is where a lot of bankruptcy work comes from.'),
        ("How is this different from my bankruptcy case and petition software?",
         'It sits alongside it. That software prepares the schedules, the means test, and the filing itself. This runs everything around it: the consultations you have not signed, the clients stuck in the paperwork, and the past clients and professionals who refer you. The two do different jobs, and setup is included so it is working within days.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for bankruptcy attorneys"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-bankruptcy-attorneys.html", "The AI receptionist that feeds it every consultation"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting frightened clients <em>slip away</em>",
    "cta_sub": "Get a free audit of how many of your consultations, stalled files, and past clients are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ====================== Marketing for Bankruptcy Attorneys ======================
{
    "slug": "marketing-for-bankruptcy-attorneys",
    "trade_slug": "bankruptcy_attorneys", "trade_plural": "bankruptcy attorneys",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "Marketing for Bankruptcy Attorneys",
    "title": "Marketing for Bankruptcy Attorneys | Top Shelf Business Solutions",
    "og_title": "Marketing for Bankruptcy Attorneys",
    "meta_desc": "Bankruptcy attorney marketing keeps your Google profile active and your reviews reassuring, so someone drowning in debt trusts your firm enough to call.",
    "service_schema_name": "Marketing for Bankruptcy Attorneys",
    "eyebrow": "For Bankruptcy Attorneys",
    "h1_html": "Marketing <em>for Bankruptcy Attorneys</em>",
    "answer_block": "Bankruptcy attorney marketing keeps your firm visible and reassuring where people quietly look for a way out of debt, your Google Business Profile and your reviews, so when someone facing garnishment or foreclosure searches nearby, your name is the judgment-free one they feel safe enough to call.",
    "sections": [
        {"h2_html": "The search for a way out of debt happens <em>quietly, and in private</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody is proud to be looking for a bankruptcy attorney. It usually means admitting the debt has won, and it is often hidden from the people closest to them, a spouse who does not know how bad it is, parents they do not want to worry, coworkers who cannot find out. So the search happens quietly, late at night, on a personal phone, and the person compares a couple of firms and reads reviews before they let anyone in. That changes what your marketing has to do. You are not catching someone in a single frantic moment the way an accident does; you are staying visible and looking safe through the private stretch of time a person spends working up the nerve to call about their money.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Get found and look trustworthy through that window and the call is usually yours. A firm that shows up thin, stale, and barely reviewed loses to the one that looks present, human, and kind, no matter how good the attorney behind the quiet profile is. Because so much of this search happens in secret, with no friend to ask, what a person can see about you online carries the weight a personal referral would carry in another field.</p>'},
        {"h2_html": "The loud, wipe-out-your-debt act <em>scares people off</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A lot of bankruptcy advertising leans on one of two wrong notes. Some of it shouts, promising to erase every debt overnight, which reads as too good to be true to a cautious, embarrassed person and makes a serious decision feel like a gimmick. The rest is cold and clinical, all statutes and chapters, which confirms every fear that this will be humiliating and confusing. Neither is what wins. What reassures the person searching in shame is a profile that looks calm, current, and genuinely human: a real firm with real people, plain language about how they can help, and reviews that describe being treated with respect and never talked down to. Getting that tone right is frequently what separates a call from a closed tab.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Reviews that speak to being treated with dignity, judged by no one, and guided in plain language, which reassure a frightened person far more than any promise about erasing debt.</li><li>Accurate practice areas, hours, address, and phone number, so someone reaching out in a hard moment never hits wrong or missing information.</li><li>Current photos and an honest, human picture of how you work, so your firm reads as approachable people rather than a debt-relief billboard.</li><li>The questions an ashamed first-timer actually asks, whether they will lose the house, whether anyone has to know, answered plainly and without judgment right where they will see them.</li></ul>'},
        {"h2_html": "Be known for the <em>relief someone is actually searching for</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A generic bankruptcy banner blends into every other firm on the page. What people actually search, and what earns real local standing, is the specific thing pressing on them: whether Chapter 7 or Chapter 13 fits their situation, whether filing can stop a garnishment or a foreclosure, how to deal with debt they cannot pay. Being known in your area as the firm for the exact relief you genuinely provide, with a profile and content built around it, is worth far more than a wide, shallow presence across every angle at once, and it draws the people you can actually help. It matters more in bankruptcy than in most fields, because word of mouth here is muted: people rarely broadcast that they filed, so the referral that would carry another business travels quietly, if at all, and being easy to find for the exact worry someone has, at the moment they finally search, has to do that work instead.</p>'},
        {"h2_html": "Reviews that speak to <em>respect</em>, earned within the rules",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Reviews carry enormous weight with someone choosing a bankruptcy attorney, because they are about to hand a stranger the most embarrassing details of their life. But they behave differently here than in most trades. Clients are deeply private about having filed and reluctant to post publicly about it, so the reviews you do have need to be genuine, gathered with care, and collected only from the people willing to give them, never pressured or paid for. When a review speaks to being treated with dignity, having a frightening process made clear, and never being made to feel like a failure, it reassures the next ashamed caller more than anything you could say about yourself. And all of it stays inside the rules for attorney advertising: no promising or implying that a debt will be discharged or a specific outcome reached, no fabricated or incentivized reviews, no misleading claims. This is the side of your firm the public sees, aimed at people who are not yours yet; the private follow-up with the people already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A quiet, late-night search that ends <em>at your firm</em>",
        "body_html": 'A man who has not told his wife how far behind they are spends two weeks reading quietly at night before he trusts anyone with it. Every time he looks, your firm\'s profile is active, with recent reviews that describe people being treated with respect and never made to feel judged. The firm one listing down looks abandoned, old reviews, missing hours, no sign anyone is home, and another shouts about wiping out all your debt fast, which only makes him more suspicious. He calls you, because yours is the only one that feels both real and safe to tell the truth to. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with updates, real replies to reviews, and local content on a regular schedule, and keep your practice areas, hours, and service area accurate, so it looks current and cared for whenever someone searches for a bankruptcy attorney near them.'),
        ("I do not want to look like a loud debt-relief mill. Can marketing reflect a calmer tone?",
         'Yes, and for most bankruptcy firms that is the smarter position. We build your profile and reviews around calm, judgment-free, plain-language help, which is what someone quietly searching in shame is actually looking for, rather than the shout-it-from-the-rooftops promises that make a serious decision feel like a gimmick.'),
        ("My clients are private and will not post reviews. How does that work?",
         'We ask only the clients who are willing, and never pressure anyone or pay for a review. Even a few honest ones that speak to being treated with respect and having the process made clear do the reassuring, and we help you reply to each with care, which matters more here than sheer volume.'),
        ("Is this allowed under attorney advertising rules?",
         'Yes, and working within those rules is the whole approach. No promising or implying that a debt will be discharged or a particular outcome reached, no fake or paid reviews, no misleading claims. We keep your real profile active and your genuine reviews visible, which is both allowed and what actually earns an anxious person\'s trust.'),
        ("How is this different from the CRM follow-up?",
         'The CRM works quietly on the people already in your world: consultations you have not signed, past clients, and the professionals who refer you. Marketing is the public side: being visible, current, and trustworthy to the person drowning in debt who has never heard of you and is quietly searching for a way out tonight.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for bankruptcy attorneys"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-bankruptcy-attorneys.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the firm they feel <em>safe enough to call</em>",
    "cta_sub": "Get a free audit of how visible and trustworthy your firm looks to someone quietly searching for a bankruptcy attorney in your area right now, whether you work with us or not. No credit card, never a call center.",
},
# =================== Websites & SEO for Bankruptcy Attorneys ===================
{
    "slug": "websites-seo-for-bankruptcy-attorneys",
    "trade_slug": "bankruptcy_attorneys", "trade_plural": "bankruptcy attorneys",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "Websites & SEO for Bankruptcy Attorneys",
    "title": "Websites & SEO for Bankruptcy Attorneys | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Bankruptcy Attorneys",
    "meta_desc": "A bankruptcy attorney website built for SEO ranks for Chapter 7 and stop-garnishment searches in your city and turns a private, ashamed researcher into a call.",
    "service_schema_name": "Websites & SEO for Bankruptcy Attorneys",
    "eyebrow": "For Bankruptcy Attorneys",
    "h1_html": "Websites &amp; SEO <em>for Bankruptcy Attorneys</em>",
    "answer_block": "A bankruptcy attorney website built for SEO ranks for what a person types when the debt becomes unmanageable, a Chapter 7 attorney near me, how to stop a garnishment, a bankruptcy lawyer in your city, and meets them with a calm, private, plain-language page that turns an ashamed researcher into a consultation that belongs to your firm.",
    "sections": [
        {"h2_html": "Your site is the first proof you will treat them <em>without judgment</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone weighing bankruptcy is not landing on your site in a panic so much as in dread. They have put this off for a long time, they are ashamed to be there at all, and something, a garnishment, a foreclosure notice, a lawsuit, has finally forced them to look. In the first few seconds they are asking one quiet question: will this firm treat me like a person trying to fix a hard situation, or like a failure, or a mark. A site that opens cleanly, explains Chapter 7 and Chapter 13 in plain language, and shows real people and honest reviews answers that with a yes. A cold, jargon-heavy template, or a loud one promising to erase everything, answers it with a no, no matter how good the attorney behind it is.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">For bankruptcy the website is doing two jobs at once. It has to lower the shame that keeps a person from reaching out, and it has to feel safe enough that they will hand your firm the most embarrassing details of their life. That combination, dignity plus plain-language clarity, is what carries an ashamed researcher from reading to requesting a consultation, instead of closing the tab and telling themselves they will deal with it later, when later usually means fewer options.</p>'},
        {"h2_html": "Rank for the <em>chapter and the worry</em>, not a slogan",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not top a national legal directory this year for a broad phrase like bankruptcy lawyer, and you do not have to. The searches that turn into cases are specific and local: a Chapter 7 attorney nearby, a Chapter 13 lawyer in your city, how to stop a wage garnishment, how to stop a foreclosure, help with medical or credit card debt. People type the exact thing pressing on them, and a national directory has no reason to answer a state-specific or situation-specific question well, which is exactly the ground a real local firm can take. Pages built around the relief you genuinely provide and the community you actually serve are what a search engine, and increasingly an AI answer, can put in front of the right person.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Plain-language pages on the questions people actually ask, the difference between Chapter 7 and Chapter 13, whether filing can stop a garnishment or a foreclosure, what happens to the house and the car.</li><li>Pages built around the relief you truly offer and paired with your city and state, because what a filing protects is set by rules that vary and people want a firm that knows theirs.</li><li>Content that reads as genuinely helpful rather than a pitch, which is what both earns the trust and holds up in search over time.</li><li>A calm, honest tone throughout, with no claims that a debt will be discharged, because over-promising drives a cautious person away and crosses an advertising line.</li></ul>'},
        {"h2_html": "Ashamed, on a phone, and needing to reach you <em>quietly</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The visitor is often on a phone, embarrassed, and not ready to say the words I need to file bankruptcy out loud to a stranger, sometimes not even ready for anyone in the house to know they are looking. The site has to make the first step feel small, and, just as important for this kind of trouble, it has to offer a private way to reach out and not only a big phone number, because for many people that discretion is the very thing that decides whether they make contact at all. Every extra click, every demanding form, every wall of dense legal language is a reason for an already-overwhelmed person to give up and keep putting it off.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Opens fast and reads calmly on a phone, because that is where most of your visitors are quietly looking.</li><li>A discreet, low-pressure message option for the person who cannot say it out loud yet, alongside a clear phone option for the one ready to talk now.</li><li>Plain, gentle explanations of a confusing and frightening process, with no jargon and no promises about how a case will end.</li><li>Real people and honest reviews up front, so a wary visitor can decide in seconds that your firm is real and safe to contact.</li></ul>'},
        {"h2_html": "The consultations belong to <em>you</em>, not a lead-seller",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Run a search for a bankruptcy attorney in your town and look at who actually sits on top. Often it is not a local firm at all, it is a directory or a pay-per-lead company that has outranked every attorney in the area and then sells the person who clicks, sometimes to several firms at once, sometimes back to you for a fee skimmed from a retainer a struggling client is already scraping together. For as long as you have no real site of your own, those quiet, struggling searchers belong to a middleman instead of you. Owning the page changes the whole arrangement: the person reaches your firm and no one else, nothing is skimmed off the top of a fee they can barely afford, and the site keeps ranking and compounding for years rather than vanishing the day you stop paying a lead bill. It is registered to your firm, not a platform that can drop you or raise the rate, and it feeds the same CRM and answering service that catch and follow up on every consultation it earns. It works to bring people to your door; it never promises a single one of them an outcome.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A stop-garnishment search that finds <em>your firm, not a middleman</em>",
        "body_html": 'A woman whose paycheck was just garnished sits down late one night, after everyone is asleep, and searches how to stop a wage garnishment in her city. Instead of a directory that would take her information and sell it to three firms, she finds your site ranking for exactly that, calm and plainly written, clearly a real local firm that knows her state, with reviews from people who felt they were treated with respect. She sees a private way to reach out, sends a short message rather than making a call she is not ready to make out loud, and it comes straight to you with no middleman in between. Illustrative example, not a client.'},
    "faqs": [
        ("What bankruptcy terms can my site realistically rank for?",
         'The specific and local ones: your firm name, and the relief you provide paired with your city and state, a Chapter 7 or Chapter 13 attorney near you, how to stop a garnishment or a foreclosure, help with medical or credit card debt, plus the plain-language questions people ask about them. That is the ground a local firm can take, not the broad national terms a directory locked up years ago.'),
        ("Can the site offer a private way to reach out, not just a phone number?",
         'Yes, and for bankruptcy it should. Many people cannot bring themselves to say it out loud, or cannot talk freely at home, so a discreet, low-pressure message option turns a hesitant visitor into a consultation you would otherwise have lost to a call they were not ready to make.'),
        ("Can pages that just answer common questions really bring in clients?",
         'Yes, and in bankruptcy it is one of the strongest things a site can do. The person asking whether Chapter 7 or Chapter 13 fits, or whether filing can stop a garnishment, is often a client in the making, and the firm that answers plainly earns both the ranking and the trust. Explaining the process well is what turns a cautious reader into a booked consultation.'),
        ("How is this different from paying for leads or a directory?",
         'A pay-per-lead service or directory rents you a contact it also sells to other firms, and it goes dark the day you stop paying. A website your firm owns keeps the consultation to itself and goes on ranking for years after it is built, with nothing skimmed off a retainer a struggling client is already stretching to cover.'),
        ("How long until it starts ranking?",
         'The narrow, local, and question-based searches can begin to move within weeks; the broader and more competitive terms take longer and build over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for bankruptcy attorneys"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-bankruptcy-attorneys.html", "Staying visible in your community beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the bankruptcy searches in <em>your own city</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your consultations, whether you work with us or not. No credit card, never a call center.",
},
]
