"""Per-page content specs for the SEO corpus (plan §5), estate planning attorneys batch. Same
contract as scripts/corpus_specs.py: generate_corpus.py imports SPECS and owns the mechanics
(shell, schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict
below owns the UNIQUE, hand-written, estate-planning-firm-specific substance that clears the
uniqueness gate. Never templated find-and-replace, never the plumber, personal-injury,
family-law, or immigration content reworded.

Legal hub, shared with the personal-injury, family-law, and immigration batches, so these
dicts are written estate-planning-distinct on purpose: proactive, non-crisis, relationship
work, wills, trusts, powers of attorney, and probate; a planning-minded, often older caller
who has been putting it off rather than someone in an emergency, so the pitch is trust,
clarity, and making a daunting task easy, never speed-to-lead; the two biggest levers are the
financial-advisor and CPA referral relationships that feed the practice and the database of
past clients whose plans need periodic review as life and law change, plus the estate
administration work that returns later; the consultation as the front door for the researcher
who keeps deferring; and a reassuring, educational website and reviews that win the trust to
hand over a legacy. Four service angles are here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client."
per the honesty rule; if the generator also appends that line, dedupe there. Attorney
advertising ethics: nothing here promises or implies that a plan will avoid taxes or probate
or any other outcome, and the AI intake never gives legal advice.
"""

SPECS = [
# ==================== AI Receptionist for Estate Planning Attorneys ====================
{
    "slug": "ai-receptionist-for-estate-planning-attorneys", "demo": True,
    "trade_slug": "estate_planning_attorneys", "trade_plural": "estate planning attorneys",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "AI Receptionist for Estate Planning Attorneys",
    "title": "AI Receptionist for Estate Planning Attorneys | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Estate Planning Attorneys",
    "meta_desc": "An estate planning answering service answers every call about a will, trust, or probate, books the consultation, and flags an urgent matter to your attorney.",
    "service_schema_name": "AI Receptionist for Estate Planning Attorneys",
    "eyebrow": "For Estate Planning Attorneys",
    "h1_html": "AI Receptionist <em>for Estate Planning Attorneys</em>",
    "answer_block": "An estate planning answering service answers every call the moment it rings, meets the person who has finally decided to make a will or trust with a calm, patient human instead of a voicemail, captures the intake, and books the consultation while you are in a signing. Your number stays yours, and so does every caller it brings in.",
    "sections": [
        {"h2_html": "The call you miss is the plan that slides back to <em>someday</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone deciding to call an estate planning attorney has usually been meaning to do it for years. Making a will or a trust means sitting with the questions most people would rather not face: who raises the children if both parents are gone, who makes the decisions if you cannot, what happens to the house and the savings you spent a life building. It is the easiest thing in the world to put off, so the moment a person finally works up the resolve and picks up the phone is fragile. Reach a voicemail and that resolve tends to drain away, and the whole matter slides back onto the someday pile, sometimes for another year, sometimes until a family is left sorting out the mess with no plan at all.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">This is not a race against the firm that simply answers faster. It is a race against a person\'s own urge to keep putting it off. A calm, unhurried human on the line, right when they have finally decided to deal with it, is what turns a long-postponed intention into a booked consultation. But you are heads-down drafting a trust, walking a client through a signing, or already gone for the day, so the call rolls to voicemail. An estate planning answering service answers on the first ring, meets the caller with patience, learns what has brought them in, and puts the consultation on your calendar instead of letting the moment pass.</p>'},
        {"h2_html": "Built for how an estate planning firm <em>actually gets calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The people who call an estate practice are not one kind of caller, and they rarely call in a panic. An adult child phones in the evening, worried about a parent who is starting to slip. A couple who just had a baby or bought a house decides it is finally time. Someone who just lost a spouse or a parent needs to know what probate even involves. A financial advisor\'s office calls to hand you a client. A voicemail box cannot meet any of them, and a generic call center reading a script does not know a simple will from a trust, or which of these calls is one you would want to know about right away.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers day and night, so the adult child who can only call after work and the older client who quietly hates phone trees both reach a real, patient conversation instead of a machine.</li><li>Runs the intake an estate matter actually starts with: whether it is for them or a parent, whether they already have a will or trust, whether there are minor children, a business, or property in more than one state, and whether a loved one has recently passed and they need help with probate.</li><li>Recognizes a call from a financial advisor, a CPA, or an insurance agent referring a client, and treats that referral with the care a professional relationship deserves.</li><li>Handles a returning client whose plan may need updating, or someone sent by a past client, differently from a first-time caller, so the people who already trust your firm never land in a voicemail box.</li></ul>'},
        {"h2_html": "Most estate calls are not emergencies, so the <em>time-sensitive ones slip through</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most of what comes in can wait a few days, and that is exactly why the calls that cannot wait get buried. Someone who was just handed a hard diagnosis and wants their affairs in order before treatment starts. A client heading into surgery or a long trip who needs documents signed first. An adult child whose parent is declining and needs a power of attorney arranged while the parent still has the capacity to sign one. A family that just lost someone and does not realize an estate can carry deadlines. None of those should sit in a weekend voicemail, and a generic message service has no way to tell them apart from a caller who is only beginning to wonder whether they need a will.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">You decide what counts as time-sensitive, and when a caller describes one of those situations the answering service flags it to your on-call attorney at once so a real person can follow up quickly, while the routine consultations simply land on your calendar. And the math is forgiving: a single estate plan or a probate matter you would otherwise have lost to a voicemail is usually worth far more to your firm than the service costs, and everything it captures after that is on top.</p>'},
        {"h2_html": "You <em>own</em> the number, the intake, and the client list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The service runs on the number your firm already advertises, or a new one put in your name, never in ours. Every caller, every intake, and every detail is yours and exportable whenever you want it. That matters more in estate work than in almost any practice, because your client list is not a one-time thing: those people come back years later to update a plan, their families return to you for administration when someone passes, and the advisors who refer them are a pipeline you never want to lose track of. The answering service is one piece of the Top Shelf platform, and it hands each consultation it books to the same CRM that follows up, so a person who has not signed yet never quietly goes cold. And it stays firmly in its lane: it listens, reassures, and writes down the facts, and it never gives legal advice, never tells a caller which documents they need, and never predicts how an estate will be handled or taxed. Those judgments belong to your attorneys alone.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A late call about an aging parent, <em>captured while you sleep</em>",
        "body_html": 'It is past six in the evening when a man gets home from visiting his father, who has begun to forget things, and finally makes the call he has been meaning to make for months. The first firm he tries has closed for the day and sends him to voicemail. Yours answers, stays patient, learns that his father is still competent but slipping, that there is a house and some retirement savings, and that nothing has ever been put in writing, then books a consultation for later that week and notes that the timing here matters. You arrive in the morning to the intake already written up, with his number attached, instead of never knowing he called and a family quietly losing the window to plan. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current firm phone number?",
         'Yes. It can answer on your existing number, or set up a new one registered in your name. Either way the number and every intake that comes through it belong to your firm and go with you if you ever leave.'),
        ("Can it actually run intake, not just take a message?",
         'Yes, that is the point. It asks what your intake staff would, whether the matter is for them or a parent, whether they already have a will or trust, whether there are minor children or a business, and whether someone has passed and they need probate help, and it writes it up so an attorney can pick it up cold. It can also recognize a referral from a financial advisor or CPA and treat it with extra care. You decide exactly which questions it asks.'),
        ("Will it flag a time-sensitive matter, like a new diagnosis or a probate deadline, to my attorney?",
         'It flags the calls you tell it to treat as urgent, a caller with a serious diagnosis who wants documents in place, a parent declining who needs a power of attorney while they can still sign, a family facing a deadline after a death, and alerts your on-call attorney right away so a real person can follow up. You set what counts as time-sensitive.'),
        ("Is it going to give the caller legal advice or tell them what documents they need?",
         'No, and this matters. It listens, reassures, and captures the facts; it never advises on a matter, never tells a caller whether they need a will or a trust, and never predicts how an estate will be handled or taxed. Every legal question and every decision about taking a matter stays with your attorneys. A caller mostly needs to feel that a real, steady firm is handling it, and a patient voice that gets the details beats a voicemail box.'),
        ("How fast can it be running?",
         'Setup is included with no separate onboarding fee. We build your intake questions, your booking, and your time-sensitive rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current phone setup is missing.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for estate planning attorneys"),
        ("solution-ai-phone.html", "How the AI phone and intake system works"),
        ("crm-for-estate-planning-attorneys.html", "The CRM that follows up on every consultation you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting a long-put-off decision go to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and after-hours consultations your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ========================= CRM for Estate Planning Attorneys =========================
{
    "slug": "crm-for-estate-planning-attorneys",
    "trade_slug": "estate_planning_attorneys", "trade_plural": "estate planning attorneys",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "CRM for Estate Planning Attorneys",
    "title": "CRM for Estate Planning Attorneys | Top Shelf Business Solutions",
    "og_title": "CRM for Estate Planning Attorneys",
    "meta_desc": "A CRM for estate planning attorneys follows up on every consultation, reminds past clients when a plan needs review, and keeps referral partners close.",
    "service_schema_name": "CRM for Estate Planning Attorneys",
    "eyebrow": "For Estate Planning Attorneys",
    "h1_html": "CRM <em>for Estate Planning Attorneys</em>",
    "answer_block": "A CRM for estate planning attorneys keeps every client, referral partner, and unsigned consultation in one place and follows up for you, so the person still meaning to finish their will, the past client whose trust is out of date, and the advisor who refers you all stay with your firm. Your client list becomes a pipeline that renews itself.",
    "sections": [
        {"h2_html": "The client who keeps meaning to finish their plan is the one who <em>never does</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most estate planning firms do not have a call problem. They have a follow-through problem, and it is a particular kind. Someone comes in for a consultation, agrees they need a will or a trust, takes the folder home to gather account numbers and think about who they want as guardian and executor, and then life closes back over the whole thing. There is no deadline forcing it, nobody is chasing them, and the task is unpleasant enough that it slides to the bottom of the list. Months pass. They were never a bad prospect. They simply needed a reason to pick it back up, and that is the nudge there is never time to send between drafting and signings.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every consultation that has not turned into a finished plan in front of you and follows up for you, on a schedule you set, with messages that sound like your firm and never pressure. It is not a sales chase; it is a patient reminder that the plan still matters and that you are ready whenever they are. The person who took the folder home and stalled hears from you again at the right moment, instead of letting another year go by, or finally getting the plan done somewhere else after a friend pushed them into it.</p>'},
        {"h2_html": "A will written years ago quietly <em>stops working</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Here is the part of estate planning most firms leave on the table. A plan is not finished the day it is signed; it goes stale. The couple named a guardian who has since moved across the country. A named executor has passed away. There is a new child or grandchild the plan never mentions, a divorce or a remarriage, a house bought, a business sold, a move to a new state whose laws work differently. The tax rules shift under everyone every few years. A plan nobody has revisited is the plan that fails at the exact moment a family is counting on it, and the client almost never thinks to come back on their own. A steady reminder to review is worth real money to your firm and real peace of mind to them.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every client, plan, and note lives in one place, so you can see at a glance whose documents are aging and who has not been in for a review in years.</li><li>Automatic review reminders go out on the cadence you set, so a client hears from you when it is time to dust off the plan, and the update work comes back to your firm instead of never happening at all.</li><li>When a client mentions a life change, a birth, a death, a move, a marriage, you can flag it so the plan gets revisited before it quietly falls out of date.</li><li>The people whose plans you refresh stay your clients, and their families stay close for the administration work that comes later.</li></ul>'},
        {"h2_html": "Your pipeline is <em>advisors, CPAs, and the families you have already helped</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">More than almost any other practice, estate planning runs on professional referral relationships. Financial advisors, CPAs, insurance agents, and wealth managers each sit on a book of clients who all need a will or a trust and who trust their advisor to point them to a lawyer. One good relationship can send a steady stream of work for years, and it runs both ways, since you send clients back to them too. But those relationships go cold the moment they are neglected, and a busy attorney cannot keep a mental list of who sent whom or who is due for a thank-you. A CRM keeps a light, organized touch on every referral source, a note when they send someone your way, a check-in so you stay top of mind, a heads-up when a shared client\'s plan is done, so you are the name that comes up the next time an advisor\'s client asks who to call. The same steady touch keeps past clients close, and past clients are how the administration and probate work, the matters that arrive when someone passes, come back to the firm the family already trusts.</p>'},
        {"h2_html": "One list, wired to your calls and every <em>plan you have written</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every client and every note belongs to you and can be exported whenever you like, never sealed inside a tool you lease by the month. The CRM is one piece of the Top Shelf platform: the consultations your answering service books flow into it and the follow-up begins on its own, and each meeting and next step hangs on the right person so nothing lives in two systems or falls out of both. Your estate planning drafting and practice-management software still holds the documents themselves, the matter files, and the legal deadlines. The CRM works the human side of a relationship that is meant to last decades: the people who have not finished their plan, the clients whose documents are quietly going out of date, and the advisors and families who send you the next matter. It carries the relationship while your attorneys carry the law and make every legal decision, and it never promises a client a thing about how their estate will be handled or taxed.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The trust that gets reviewed <em>before it fails</em>",
        "body_html": 'A couple set up a living trust with you six years ago, and you have not spoken since. Normally that is where the relationship quietly ends, until something goes wrong and a family discovers the plan no longer fits. Instead the CRM sends a gentle review reminder on the cadence you set, and it lands just as the couple has welcomed a second grandchild and watched the relative they named as guardian move out of state. They come back in, update the plan while it can still be done calmly, and leave feeling looked after rather than sold to. Years later, when one of them passes, there is no question which firm the family calls to handle it. Nobody on your team had to keep the date in their head. Illustrative example, not a client.'},
    "faqs": [
        ("Does it import my existing clients and matters?",
         'Yes. Your current clients, past consultations, and matter notes come in and live in one place, all of it yours and exportable. The point is to put the relationships your firm has already built to work instead of letting them sit in a phone and an inbox.'),
        ("Will it follow up on someone who came in but never finished their plan?",
         'Yes, on the schedule you approve. A consultation that has not turned into a signed plan gets a gentle, no-pressure check-in later and another after that, sent for you, so a person who took the folder home and stalled keeps hearing that you are ready whenever they are. You can step in and reach anyone yourself any time.'),
        ("Can it remind past clients to review and update their will or trust?",
         'Yes, and for an estate practice that is often the biggest win. You set the cadence, and it reminds clients when their documents are aging or when a life change means the plan should be revisited, so the update work comes back to you and, just as important, the plan actually still works when a family needs it.'),
        ("Can it help me stay in front of the financial advisors and CPAs who refer me?",
         'Yes. It keeps an organized, light touch on your referral sources, a thank-you when they send someone, a check-in so you stay top of mind, so those relationships stay warm instead of fading. In estate planning that professional network is often the single largest source of new matters, and it is exactly what tends to get neglected when everyone is busy.'),
        ("How is this different from my estate planning drafting and practice-management software?",
         'It sits alongside it. That software holds the documents, the matter files, and the legal deadlines. This runs everything around them: the consultations you have not signed, the past clients whose plans are going stale, and the advisors and families who refer you. The two do different jobs, and setup is included so it is working within days.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for estate planning attorneys"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-estate-planning-attorneys.html", "The AI receptionist that feeds it every consultation"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting good plans and good referrers <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your unfinished plans, past clients, and referral relationships are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ====================== Marketing for Estate Planning Attorneys ======================
{
    "slug": "marketing-for-estate-planning-attorneys",
    "trade_slug": "estate_planning_attorneys", "trade_plural": "estate planning attorneys",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "Marketing for Estate Planning Attorneys",
    "title": "Marketing for Estate Planning Attorneys | Top Shelf Business Solutions",
    "og_title": "Marketing for Estate Planning Attorneys",
    "meta_desc": "Estate planning attorney marketing keeps your Google Business Profile active and your reviews warm, so someone making a will trusts your firm enough to call.",
    "service_schema_name": "Marketing for Estate Planning Attorneys",
    "eyebrow": "For Estate Planning Attorneys",
    "h1_html": "Marketing <em>for Estate Planning Attorneys</em>",
    "answer_block": "Estate planning attorney marketing keeps your firm visible and trusted where people quietly do their homework, your Google Business Profile and your reviews, so when someone finally decides to make a will or set up a trust and searches nearby, your name is the clear, reassuring one they feel safe handing their family's future to.",
    "sections": [
        {"h2_html": "Choosing an estate planning attorney is a <em>calm, careful, high-trust decision</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Nobody hires an estate planning attorney on impulse. Something usually nudges them into it, a new baby, a first house, a parent\'s death, a diagnosis, retirement on the horizon, and then they take their time. They read, they compare a couple of firms, they look at reviews, and they think about it before they ever pick up the phone, because this is a decision about who raises their children, who speaks for them if they cannot, and where everything they have built goes when they are gone. That patience changes what your marketing has to do. You are not catching someone in a single frantic moment the way an accident does; you are staying visible and looking trustworthy across the quiet stretch of time a person spends working up to the call.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Get found and look trustworthy through that window and the consultation is usually yours. A firm that shows up thin, stale, and barely reviewed loses to the one that looks present, warm, and clearly good at making a daunting thing simple, no matter how skilled the attorney behind the quiet profile actually is. Because this decision is so personal, what a person can see about you before they call carries the weight a close friend\'s recommendation would carry anywhere else.</p>'},
        {"h2_html": "Reassuring and clear beats <em>stiff and expensive-looking</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A lot of people avoid estate planning because they assume it will be confusing, morbid, and pricey, and a cold, jargon-heavy, ultra-corporate presence confirms every one of those fears. That is the opposite of what wins here. The firm that gets the call looks approachable and human: real people, plain language, and reviews that describe an attorney who made an intimidating process feel simple, explained the options without talking down, and did not pressure or nickel-and-dime. You are not trying to look like the most aggressive lawyer in town; you are trying to look like the one a nervous person would feel comfortable sitting across from while they sort out the most personal decisions of their life.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Reviews that speak to being guided patiently, having the choices explained in plain English, and never being pressured, which reassure a hesitant person far more than any boast.</li><li>Accurate practice areas, hours, address, and phone number, so someone finally ready to deal with this never hits wrong or missing information.</li><li>Current photos and an honest, human picture of how you work, so your firm reads as approachable people rather than an intimidating institution.</li><li>The questions a first-timer actually has, what a consultation costs, whether they need a will or a trust, how long it takes, answered plainly right where they will see them.</li></ul>'},
        {"h2_html": "Be known for the <em>plan someone is actually looking for</em>, in your state",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A generic estate planning banner blends into every other firm on the page. What people actually search for, and what earns real local standing, is the specific thing on their mind: a living trust, a simple will, a power of attorney, probate and estate administration, special needs planning, or passing down a family business. And estate law is set state by state, so being known locally as the firm that handles these matters, in the state whose rules actually govern them, is worth far more than a wide, shallow presence spread across everything at once. There is another reason to look established and well regarded in public: the financial advisors and CPAs who send you the most work quietly check your reputation before they attach their own name to a referral, and satisfied families talk. A strong, active local presence does double duty, drawing the person searching on their own and reinforcing the professional relationships that feed you.</p>'},
        {"h2_html": "Reviews you can trust with a <em>legacy</em>, earned within the rules",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Reviews carry enormous weight with someone choosing an estate planning attorney, because they are about to hand over decisions most people never discuss with anyone. But they behave differently here than in most trades. Clients are private about their money and their families and reluctant to post about their estate, so the reviews you do have need to be genuine, gathered with care, and collected only from the people willing to give them, never pressured or paid for. When a review speaks to being treated with patience, having a confusing process made clear, and feeling that the plan is finally handled, it reassures the next cautious caller more than anything you could say about yourself. And all of it stays inside the rules for attorney advertising: no promising or implying that a plan will avoid all taxes or probate, no fabricated or incentivized reviews, no misleading claims. This is the side of your firm the public sees, aimed at people who are not yours yet; the private follow-up with the clients and referral sources already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A new grandchild, and a search that ends <em>at your firm</em>",
        "body_html": 'A woman holds her first grandchild and realizes she and her husband still have nothing in writing, no will, no plan, nothing. She does not call anyone that day; she spends the next two weeks reading quietly and comparing a few firms. Every time she looks, your profile is active, with recent reviews that describe an attorney who made the whole thing painless and explained every choice without pressure. The firm one listing down looks abandoned, old reviews, missing hours, no sign anyone is home, and another reads as a cold, corporate operation that makes her tense just looking at it. She books with you, because yours is the only one that feels both capable and kind. Illustrative example, not a client.'},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         'Yes. We keep it active with updates, real replies to reviews, and local content on a regular schedule, and keep your practice areas, hours, and service area accurate, so it looks current and cared for whenever someone searches for an estate planning attorney near them.'),
        ("I do not want to look like a stuffy, expensive firm. Can marketing reflect a warmer tone?",
         'Yes, and for most estate firms that is the smarter position. We build your profile and reviews around calm, clear, approachable guidance, an attorney who makes a daunting thing simple, which is exactly what a nervous person quietly researching this is looking for, rather than the cold, corporate image that makes them assume it will be confusing and overpriced.'),
        ("My clients are private about their money and will not post reviews. How does that work?",
         'We ask only the clients who are willing, and never pressure anyone or pay for a review. Even a few honest ones that speak to being guided patiently and having the process made clear do the reassuring, and we help you reply to each with care, which matters more here than sheer volume.'),
        ("Is this allowed under attorney advertising rules?",
         'Yes, and working within those rules is the whole approach. No promising or implying that a plan will avoid all taxes or probate, no fake or paid reviews, no misleading claims. We keep your real profile active and your genuine reviews visible, which is both allowed and what actually earns a cautious person\'s trust.'),
        ("How is this different from the CRM follow-up?",
         'The CRM works quietly on the people already in your world: consultations you have not signed, past clients whose plans are aging, and the advisors and CPAs who refer you. Marketing is the public side: being visible, current, and trustworthy to the person who has never heard of you and is quietly deciding whether to finally make a plan.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for estate planning attorneys"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-estate-planning-attorneys.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the firm they trust with <em>their family's future</em>",
    "cta_sub": "Get a free audit of how visible and trustworthy your firm looks to someone deciding to make an estate plan in your area right now, whether you work with us or not. No credit card, never a call center.",
},
# =================== Websites & SEO for Estate Planning Attorneys ===================
{
    "slug": "websites-seo-for-estate-planning-attorneys",
    "trade_slug": "estate_planning_attorneys", "trade_plural": "estate planning attorneys",
    "hub_name": "Legal", "hub_slug": "industry-legal.html",
    "breadcrumb_leaf": "Websites & SEO for Estate Planning Attorneys",
    "title": "Websites & SEO for Estate Planning Attorneys | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Estate Planning Attorneys",
    "meta_desc": "An estate planning attorney website built for SEO ranks for living trust and will searches in your city and turns a cautious researcher into a consultation.",
    "service_schema_name": "Websites & SEO for Estate Planning Attorneys",
    "eyebrow": "For Estate Planning Attorneys",
    "h1_html": "Websites &amp; SEO <em>for Estate Planning Attorneys</em>",
    "answer_block": "An estate planning attorney website built for SEO ranks for what a planning-minded person actually searches, a living trust in your city, an estate planning attorney near me, what happens without a will, and answers those questions so clearly that a cautious researcher who has been putting it off finally books the consultation, with your firm and no one else.",
    "sections": [
        {"h2_html": "Your site has to make an intimidating subject feel <em>simple and safe</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone weighing an estate plan is not landing on your site in a panic, they are researching, carefully and a little reluctantly, because the whole subject feels confusing and morbid and they have been meaning to deal with it for a long time. In the first few seconds they are asking one quiet question: will this firm make this simple and treat me straight, or is it another dense, expensive-looking place I will click away from so I can keep putting it off. A site that opens cleanly, explains wills, trusts, and powers of attorney in plain language, and shows real people and honest reviews answers that with a yes. A cold, generic template answers it with a no, no matter how good the attorney behind it is.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">For estate work the website is doing two jobs at once. It has to lower the wall of dread that keeps a person procrastinating, and it has to earn enough trust that they will hand your firm the most personal decisions they will ever make. That combination, clarity plus trust, is what carries a cautious researcher from reading to requesting a consultation, instead of closing the tab and telling themselves they will get to it someday.</p>'},
        {"h2_html": "Answer the questions people <em>actually type</em>, and you rank and earn trust at once",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">People do not search estate planning in the abstract. They type the exact question weighing on them, and in this field those questions are the whole opportunity. Someone wondering whether they need a will or a trust, what happens if they die without one in their state, what a power of attorney actually does, or how probate works is a person on the edge of becoming a client, and a page that answers plainly is what a search engine, and increasingly an AI answer, puts in front of them. Doing that explaining is not a giveaway; it is the trust-builder. The firm patient enough to make a confusing thing clear on its website is the one a reader believes will be patient with them in person. A national directory has no reason to answer a state-specific question well, which is exactly the ground a real local firm can take.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Plain-language pages on the questions people actually ask, whether they need a will or a trust, what happens without one, what a power of attorney does, how probate works in your state.</li><li>Pages built around the services you truly offer, living trusts, wills, powers of attorney, probate and estate administration, special needs and business succession planning, so you are found for the exact matter someone has in mind.</li><li>Your city and state attached to those pages, because estate law is state-specific and people want an attorney who knows the rules where they live.</li><li>Content that reads as genuinely helpful rather than a sales pitch, which is what both earns the trust and holds up in search over time.</li></ul>'},
        {"h2_html": "Cautious, often older, and needing an easy way to <em>reach you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The visitor is doing homework on a topic they find daunting, and a good share of them are older and reading at the kitchen table, not racing on a phone. A site that buries the phone number, demands a long form, or hides the point behind a clever, cluttered layout gives an already-hesitant person one more reason to give up and keep procrastinating. The site has to make the first step feel small and low-pressure, and it has to be genuinely easy to read and move through, whatever the age of the person and whatever device is in front of them.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Reads clearly and is simple to navigate, because many of your visitors are older and will not fight tiny text or a maze of a layout.</li><li>Plain, honest explanations of a confusing process, with no jargon and no claims about avoiding all taxes or probate.</li><li>A simple, low-pressure way to request a consultation for the person who would rather start in writing, alongside an obvious phone option for the one ready to talk now.</li><li>Loads fast and works on a phone, a tablet, or a desktop, because people look into this on whatever happens to be in front of them.</li></ul>'},
        {"h2_html": "The consultations are <em>yours</em>, not a directory's",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search your own city for an estate planning attorney and the top results are often not local firms at all, they are directories and pay-per-lead services that outrank every attorney in the area and then sell the person who clicks, sometimes to several firms at once, sometimes back to you for a fee out of your own pocket. For as long as you have no real site of your own, those careful, planning-minded searchers belong to a middleman instead of to you. A site your firm owns and ranks flips that: the person reaches you and only you, nothing is skimmed off the top of every matter, and the page keeps working and compounding for years rather than vanishing the day you stop paying a lead bill. The work you put into it this year keeps paying off the next. It is registered to your firm, not a platform that can drop you or raise the rate, and it feeds the same CRM and answering service that catch and follow up on every consultation it earns. It works to bring people in; it never promises a single one of them an outcome.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A late-night search that finds <em>your firm, not a middleman</em>",
        "body_html": 'A man who has been meaning to make a will since his kids were born finally sits down late one night and searches what happens if you die without a will in his state. Instead of a directory that would take his information and sell it to three firms, he finds your site ranking for exactly that question, calm and plainly written, clearly a real local firm that knows his state, with reviews from people who felt the process was made easy. He reads enough to feel it will not be as painful as he feared, requests a consultation right there rather than making a call he was not quite ready to make, and it comes straight to you with no middleman in between. Illustrative example, not a client.'},
    "faqs": [
        ("What estate planning terms can my site realistically rank for?",
         'The specific and local ones: your firm name, and the matters you handle paired with your city and state, a living trust, a will, a power of attorney, probate and estate administration near you, plus the plain-language questions people ask about them. That is the ground a local firm can take, not the broad national terms a directory locked up years ago.'),
        ("Can pages that just answer common questions really bring in clients?",
         'Yes, and in estate planning it is one of the strongest things a site can do. The person asking whether they need a will or a trust, or what happens without one, is often a client in the making, and the firm that answers plainly earns both the search ranking and the trust. Explaining the process well is what turns a cautious reader into a booked consultation.'),
        ("How is this different from paying for leads or a directory?",
         'A pay-per-lead service or directory rents you a contact it also sells to other firms, and it goes dark the day you stop paying. A website your firm owns keeps the consultation to itself and goes on ranking for years after it is built, with nothing skimmed off each matter you take.'),
        ("My clients skew older. Can a website really reach them?",
         'Yes, and it is worth building with them in mind. Older clients research online more than firms assume, so a site that is easy to read, simple to navigate, and clear about how to reach you turns them into consultations, while a cramped, clever layout sends them away. Meeting them where they are is exactly the point.'),
        ("How long until it starts ranking?",
         'The narrow, local, and question-based searches can begin to move within weeks; the broader and more competitive terms take longer and build over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-legal.html", "Everything Top Shelf does for estate planning attorneys"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-estate-planning-attorneys.html", "Staying visible in your community beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the estate planning searches in <em>your own city</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your consultations, whether you work with us or not. No credit card, never a call center.",
},
]
