"""Per-page content specs for the ELECTRICIANS batch (Home Services hub). Same model as
corpus_specs.py: generate_corpus.py owns the mechanics (shell, schema, GA4 events, interlinks,
keyword-first title/slug/H1/first-sentence); each dict owns the unique, trade-specific substance
that clears the uniqueness gate. Seven pages: AI receptionist (with live demo), CRM, online
booking, review software, websites and SEO, marketing, and automation. The generator appends
the "Illustrative example, not a client." line to every example, so it is never in body_html here.
"""

SPECS = [
# ============================ AI Receptionist for Electricians ============================
{
    "slug": "ai-receptionist-for-electricians", "demo": True,
    "trade_slug": "electricians", "trade_plural": "electricians",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Electricians",
    "title": "AI Receptionist for Electricians | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Electricians",
    "meta_desc": "An AI receptionist for electricians answers every no-power and safety call, triages the emergency, and books the job while your techs are already out on a call.",
    "service_schema_name": "AI Receptionist for Electricians",
    "eyebrow": "For Electricians",
    "h1_html": "AI Receptionist <em>for Electricians</em>",
    "answer_block": "An AI receptionist for electricians answers every call the moment it comes in, day or night, finds out whether it is a sparking outlet, a dead panel, or a planned install, and books the job onto your schedule while your techs are already out on a call. You keep your own number, and every lead is yours.",
    "sections": [
        {"h2_html": "The call you miss is the emergency that <em>hires the next electrician</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a homeowner smells something burning, sees an outlet spark, or loses power to half the house, they do not leave a voicemail. They call the next electrician on the list, and the one after that, until someone picks up. You are in a panel, up a ladder, or on a commercial job with your phone in the truck, so the call rolls to voicemail and the job is gone. That is not a small miss. A panel replacement or an emergency service call is real money walking straight to whoever answered.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist closes that gap. It answers on the first ring, stays calm, finds out whether this is a safety emergency or planned work, gets the address and the problem, and either books the visit on your schedule or flags a true emergency for you right now, then texts you the details before you are off the ladder.</p>'},
        {"h2_html": "Built around how <em>electricians actually work</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your day is not a desk with a phone on it. You are in crawl spaces and attics, on rooftops and inside panels, and the calls that matter most, the after-hours no-power call and the Saturday burning-smell call, come in exactly when you cannot stop to answer. A voicemail box does not triage anything, and a generic call center does not know a breaker that tripped once and reset from one that will not, or a quick service call from a full panel upgrade.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24/7, including the 11 p.m. half-the-house-has-no-power call and the weekend safety call.</li><li>Triages the way you would: any burning smell, sparking, or heat, is there any power at all, has the breaker been reset.</li><li>Books the visit on your real schedule and texts you the address and the problem on the spot.</li><li>Handles a true safety emergency differently from a routine inspection, so an urgent call is never treated like a tire-kicker.</li></ul>'},
        {"h2_html": "Safety calls need <em>triage, not a voicemail box</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">There is a real difference between a breaker that tripped once and reset fine and a panel that keeps tripping, buzzing, or smells hot. One can wait for a scheduled slot, the other should not. The AI receptionist asks the questions that sort them, whether there is a burning smell, whether any power is still on, whether it is safe to stay in the home, so a genuine hazard gets your attention right away and a routine issue gets booked for your next opening instead of pulling you off a job for nothing.</p>'},
        {"h2_html": "You own the number, the leads, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing phone number, or a new one registered in your name, not ours. Every caller, every job, and every contact detail is yours and stays yours, exportable any time. There is no long contract and no holding your data hostage to keep you paying. The AI receptionist is one piece of the Top Shelf platform, and it plugs into the same CRM that follows up on every quote and past customer, so nothing it captures goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Saturday-night panel call, while you are <em>on another job</em>",
        "body_html": "It is 9 p.m. Saturday and a homeowner loses power to half the house right after something buzzed at the panel. You are finishing a commercial job across town with your phone in the truck. Instead of voicemail, your AI receptionist answers, confirms there is no burning smell and the main is still on, and books you for first thing Sunday, or flags it to you live if it sounds like a real hazard. Before you pack up, your phone already has the address, the problem, and the appointment. You never lost the customer to the next electrician on their list."},
    "faqs": [
        ("Does it work with my current phone number?",
         "Yes. It can answer on your existing number, or set up a new one registered in your name. Either way the number and every lead that comes through it belong to you and go with you if you ever leave."),
        ("Can it tell a real emergency from a routine call?",
         "It triages with the questions you would ask: any burning smell, sparking, or heat, is there any power at all, has the breaker been reset. A genuine hazard gets flagged to you right away, and routine work gets booked for your next opening instead of interrupting the job you are already on."),
        ("Can it actually book the visit?",
         "Yes. It books onto your real schedule based on your availability, sends you the address and problem by text right away, and can confirm the time with the caller. You set the rules, like how much notice you need and which blocks are open for work."),
        ("Is this going to sound like a robot to my customers?",
         "It answers naturally and professionally, and it is upfront rather than pretending to be a person. When someone has no power, what they care about is that a real process is handling their call instead of a voicemail box. You can hear how it takes a live call before you decide."),
        ("How fast can it be running?",
         "Setup is included and there is no separate onboarding fee. We configure the triage questions, your calendar, and the emergency-versus-routine flows for you, so it is answering your calls in days, not weeks. Start with a free audit and we will show you exactly what your current setup is missing.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for electricians"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-electricians.html", "The CRM that follows up on every lead you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing emergency calls to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and jobs your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ================================= CRM for Electricians =================================
{
    "slug": "crm-for-electricians",
    "trade_slug": "electricians", "trade_plural": "electricians",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Electricians",
    "title": "CRM for Electricians | Top Shelf Business Solutions",
    "og_title": "CRM for Electricians",
    "meta_desc": "A CRM for electricians follows up on every panel-upgrade quote and past customer for you, so the jobs people take weeks to approve still come back to you.",
    "service_schema_name": "CRM for Electricians",
    "eyebrow": "For Electricians",
    "h1_html": "CRM <em>for Electricians</em>",
    "answer_block": "A CRM for electricians keeps every quote, past customer, and lead in one place and follows up for you, so a homeowner still weighing a panel upgrade and a landlord who called you last year both come back to you instead of the next electrician they happen to find. Your customer list quietly becomes your pipeline.",
    "sections": [
        {"h2_html": "The quotes you already sent are the jobs you are <em>losing</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most electricians do not have a lead problem. They have a follow-up problem. You quote a panel upgrade, the homeowner says they need to think it over, and you never hear back, not because the price was wrong but because a panel upgrade is a considered purchase people sit on for weeks, and nobody stayed in touch while they did. The quote was never dead. It just needed a check-in every few days, and that is the thing there is never time for between service calls.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM catches every quote and lead and works it on a schedule you set, with texts and emails that go out on time whether or not you remember. The homeowner who is still deciding on that upgrade gets a friendly nudge, still sees your name, and still calls you when they are ready instead of the electrician who happened to follow up.</p>'},
        {"h2_html": "Your past customers <em>are</em> the business",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The homeowner you did a repair for last year is the cheapest job you will ever get. They already trust you inside their home, and a repeat call or a referral costs you nothing to win. But you cannot personally remember to touch hundreds of past customers on the right cadence, so most of that goodwill sits unused and slowly forgets who you are.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, note, and past job lives in one place instead of your head, your truck, and a stack of invoices.</li><li>Maintenance reminders, safety-check nudges, and seasonal touches go out on schedule, so past customers hear from you without you setting a single reminder.</li><li>You see who is worth a call, so the ten minutes you have goes to the homeowner who is actually close to saying yes.</li></ul>'},
        {"h2_html": "Quote follow-up that <em>happens without you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A panel upgrade, a rewire, a generator or EV charger install, these are the jobs people compare and delay on, and they are exactly the jobs a steady follow-up wins. When you send a quote, the CRM starts a sequence: a check-in the next day, a helpful answer to the usual permit and timeline questions a few days later, a last nudge before it goes cold. You approve the messages once, and every quote you send gets worked the same way, whether you sent one this week or a dozen.</p>'},
        {"h2_html": "You own the customer list, and it plugs into everything",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time. Your list is an asset you own, not something you rent access to. The CRM is one piece of the Top Shelf platform and connects to the AI receptionist, so a call it captures lands in your list and gets followed up on automatically, and to online booking, so a scheduled install is logged against the right customer instead of a sticky note on the dash.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The panel-upgrade quote you <em>forgot about</em> gets approved",
        "body_html": "You quote a homeowner for a panel upgrade in the spring. They say they need to talk it over, and you would normally lose track of them by summer. Instead the CRM keeps a light touch going, a quick check-in, a note answering the permit question they had, all sent for you. In July the homeowner texts that they are ready to move forward, and they text you, because yours is the name that stayed in front of them. You did not lift a finger to keep that quote alive."},
    "faqs": [
        ("Does it import my existing customers and past jobs?",
         "Yes. Your current customers, leads, and past jobs come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already have actually work for you."),
        ("Will it really follow up on my quotes automatically?",
         "Yes, on the schedule you approve. Every quote you send starts a follow-up sequence of texts and emails, and past customers get maintenance and check-in nudges on a cadence you set. You can always jump in and message someone directly."),
        ("Does this help with past customers, or just new quotes?",
         "Both, and past customers are where the quiet money is. A repeat call and a referral cost nothing to win and come from people who already trust you in their home, and the CRM keeps you in front of them so that work actually shows up."),
        ("Do I keep my customer list if I stop?",
         "Yes. Your customers and notes are in your name and exportable any time. You own the list, you are not renting access to your own business."),
        ("How long until it is set up?",
         "Setup is included with no separate onboarding fee. We bring in your customers, set up the quote-follow-up sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where jobs are slipping through today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for electricians"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-electricians.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting good quotes <em>go cold</em>",
    "cta_sub": "Get a free audit of how many of your quotes and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ============================ Online Booking for Electricians ============================
{
    "slug": "online-booking-for-electricians",
    "trade_slug": "electricians", "trade_plural": "electricians",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for Electricians",
    "title": "Online Booking for Electricians | Top Shelf Business Solutions",
    "og_title": "Online Booking for Electricians",
    "meta_desc": "Online booking for electricians lets homeowners self-schedule non-urgent work like installs and inspections on your real availability, straight to your calendar.",
    "service_schema_name": "Online Booking for Electricians",
    "eyebrow": "For Electricians",
    "h1_html": "Online Booking <em>for Electricians</em>",
    "answer_block": "Online booking for electricians lets a homeowner pick a time for non-urgent work, an EV charger install, a panel inspection, adding a circuit, straight from your website or a text link, on your real availability, so you stop playing phone tag and the job lands on your schedule with the details you need to show up ready.",
    "sections": [
        {"h2_html": "Phone tag is quietly costing you <em>the easy jobs</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner wants an EV charger installed or a panel inspected before they sell. It is not an emergency, so they are happy to schedule, but you are on a job, you call back that evening, they miss it, you trade voicemails, and two days later they booked the electrician who could lock in a time on the spot. The job was never the problem. The back and forth was. For planned work, the worst thing you can do is make someone wait for a callback.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets them grab an open slot the moment they think of it, day or night, without reaching you first. You come off a job to find the install already on your schedule instead of a missed call you now have to chase.</p>'},
        {"h2_html": "It sorts the routine work <em>from the emergencies</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Self-scheduling is for the work that can wait: installs, inspections, adding a circuit or a ceiling fan, quotes for planned upgrades. The booking form asks what the job is and offers only those appointment types, so a homeowner books an EV charger install for next week while a true no-power emergency is still told to call you. You keep control: how much notice you need, how long each visit runs, buffer time to drive between jobs, and which hours are open at all.</p>'},
        {"h2_html": "A booking link everywhere a customer <em>finds you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The link goes anywhere a customer already meets you: your website, your Google Business Profile, your email signature, and the text you send after a first call. Every one of those turns from a dead end that needs a callback into a place someone can book you in one tap. A homeowner comparing two electricians for a generator install on a Sunday night can put the visit on your calendar before they close the tab.</p>'},
        {"h2_html": "On your real calendar, and the job shows up",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar you already use so it can never double-book you against a job you already have, and it sends the customer a confirmation and a reminder, which is what actually cuts down no-shows on scheduled work. Every booking is logged against the right customer in your CRM, and it works alongside the AI receptionist, which can book a caller who would rather talk than tap. The leads and the calendar stay yours.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Sunday-night EV charger install books <em>while you sleep</em>",
        "body_html": "It is 8 p.m. Sunday and a homeowner just bought an electric car and wants a charger installed. It is not urgent, so instead of leaving a voicemail they will have to trade calls over, they land on your site, see your reviews, and book a charger install for Thursday morning from the calendar right there on the page. You wake up Monday to the job already scheduled, with the address, the panel details you asked for, and the customer confirmed. No phone tag, no lost job."},
    "faqs": [
        ("Does it sync to my Google or Outlook calendar?",
         "Yes. It reads your real calendar so it only ever offers times you are actually free, and new bookings drop straight onto it. It cannot double-book you against a job you already have scheduled."),
        ("Will homeowners try to book real emergencies through it?",
         "You control which appointment types it offers, so it is set up for planned work like installs, inspections, and quotes. Someone with a true no-power or safety emergency is pointed to call you directly, where the AI receptionist can triage it."),
        ("Can it respect drive time and stop back-to-back bookings?",
         "Yes. You set how much notice you need, how long each visit runs, and how much buffer to leave between jobs, so you are never booked with no time to get across town."),
        ("Will it cut down on no-shows?",
         "It helps. Automatic confirmations and reminders by text and email are the single biggest lever on no-shows, and every booking includes them. Someone who booked themselves and got a reminder is far more likely to be there than a loosely agreed callback."),
        ("How fast can it be live?",
         "Setup is included, no separate fee. We connect your calendar, set up your appointment types and rules, and put the link on your site and Google profile, so it is taking bookings in days. Start with a free audit and we will show you where you are losing planned jobs today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for electricians"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-electricians.html", "The AI receptionist that can book callers too"),
        ("crm-for-electricians.html", "The CRM every booking is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let customers book the easy jobs <em>while you work</em>",
    "cta_sub": "Get a free audit of how many planned jobs your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# =========================== Review Software for Electricians ===========================
{
    "slug": "review-software-for-electricians",
    "trade_slug": "electricians", "trade_plural": "electricians",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for Electricians",
    "title": "Review Software for Electricians | Top Shelf Business Solutions",
    "og_title": "Review Software for Electricians",
    "meta_desc": "Review software for electricians asks every happy customer for a Google review at the right moment, so your reputation earns trust for work inside the home.",
    "service_schema_name": "Review Software for Electricians",
    "eyebrow": "For Electricians",
    "h1_html": "Review Software <em>for Electricians</em>",
    "answer_block": "Review software for electricians asks every satisfied customer for a review at the right moment, makes leaving one a single tap, and helps you respond to each, so your reputation keeps earning the trust homeowners need before they let an electrician work inside their home.",
    "sections": [
        {"h2_html": "Homeowners check reviews before they let you <em>inside</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Before a homeowner lets an electrician into their house and near their panel, they Google you and read what other customers said. Electrical work is not something people take chances on, so a thin profile with a few old reviews quietly costs you jobs you never even hear about, because the homeowner just called the electrician with the wall of recent five-star reviews instead. Your reputation is doing the hiring whether you manage it or not.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The problem is not that your customers are unhappy. It is that happy customers forget to post, and asking feels awkward when you are packing up your tools. Review software solves the timing and the awkwardness so the reputation you have already earned actually shows up online.</p>'},
        {"h2_html": "Ask at the moment they are <em>happiest</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The best time to ask is right after you finish the job and the power is back on, the outlet works, the new panel is clean and labeled, and the customer is relieved and grateful. The software sends the ask automatically at that moment, by text and email, with a link that takes them straight to your Google profile in one tap. No cornering people, no cards that ask for a review, and no reaching out three weeks later when the relief has worn off.</p>'},
        {"h2_html": "Respond to every review, good or <em>bad</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A thoughtful reply to each review tells the next homeowner that you stand behind your work, and responding is one of the signals that helps you show up in local search. The software flags every new review the moment it lands and helps you reply quickly, so a rare critical one gets a calm, professional response instead of silence, and every good one gets a thank you. For a trade that works inside the home, that visible engagement is trust you can point to.</p>'},
        {"h2_html": "More reviews, more calls, compounding",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Recent reviews feed your Google Business Profile, which lifts you in the local results a homeowner sees when they search for an electrician near them, which brings more customers, which brings more reviews. It builds on itself. Your reputation is yours, tied to your own profile. Review requests are part of the Top Shelf platform and fire automatically off a job marked complete in your CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "One finished panel becomes <em>your next job</em>",
        "body_html": "You wrap up a panel upgrade on a Friday, everything labeled and tested. That afternoon, the software texts your relieved customer a thank-you with a one-tap link, and they post a warm review before dinner. A week later a neighbor is looking for an electrician to add a circuit, Googles electricians nearby, and reads that exact review at the top of your profile. They call you instead of a name they have never heard of. You never asked twice, and you were already on your next job when it happened."},
    "faqs": [
        ("Which review sites does it work with?",
         "It focuses on Google, which is where most homeowners look first and what feeds your local search ranking. It can also point past customers to your other profiles. We follow each platform's own rules, including that a review should come from someone you actually did work for."),
        ("When does it ask for the review?",
         "Right after the job is done, when the customer is happiest, sent automatically by text and email with a one-tap link. You can adjust the timing and the wording so it sounds like you."),
        ("Is automating review requests allowed?",
         "Asking every customer for an honest review is fine and encouraged. What is not allowed is filtering out unhappy customers or paying for reviews, and this does not do that. It simply asks everyone at the right moment and makes it easy to say yes."),
        ("What happens if I get a bad review?",
         "You find out immediately instead of weeks later, and the software helps you post a calm, professional response. One thoughtful reply to a critical review, sitting under a wall of genuine positive ones, often reassures the next reader more than a perfect record would."),
        ("How long until it is running?",
         "Setup is included with no separate fee. We connect your Google profile, set the timing and the message, and tie it to your completed jobs, so requests start going out in days. Start with a free audit and we will show you how your reputation stacks up against the electricians you compete with.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for electricians"),
        ("solution-reviews.html", "How the review system works"),
        ("crm-for-electricians.html", "The CRM that triggers the ask when a job is done"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Turn finished jobs into <em>your next call</em>",
    "cta_sub": "Get a free audit of how your online reputation compares to the electricians you compete with, whether you work with us or not. No credit card, never a call center.",
},
# ============================ Websites & SEO for Electricians ============================
{
    "slug": "websites-seo-for-electricians",
    "trade_slug": "electricians", "trade_plural": "electricians",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Electricians",
    "title": "Websites & SEO for Electricians | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Electricians",
    "meta_desc": "An electrician website built for SEO ranks for electrician near me in your city and captures the call directly, instead of losing it to a directory or a competitor.",
    "service_schema_name": "Websites & SEO for Electricians",
    "eyebrow": "For Electricians",
    "h1_html": "Websites &amp; SEO <em>for Electricians</em>",
    "answer_block": "An electrician website built for SEO ranks for electrician near me and your city, shows up in local search when someone has no power or needs a panel upgrade, and captures the call the moment they land, so the lead belongs to you instead of a directory or a paid competitor.",
    "sections": [
        {"h2_html": "The directories are not competing with you, they are <em>selling your call to your competitors</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Angi, Thumbtack, and Yelp outrank most individual electrician sites because they publish endlessly and have years of authority behind them. A homeowner searching for an electrician near them usually lands on a directory first, fills out one form, and that single lead gets sold to several electricians at once, who then race each other to the bottom on price. Your site not ranking is not just a vanity problem. It is the reason a call you should have gotten for free gets sold back to you, and shared with the electricians you are trying to beat.</p>'},
        {"h2_html": "Rank for the searches you can <em>actually win</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for every broad term, and you do not need to. You can rank for electrician near me in your specific city, for your own name, and for the exact services you want more of, like panel upgrade, EV charger installation, or generator install in your town, where a national site has nothing local to say and yours can. Content built around the neighborhoods you serve, the work you actually do, and the questions homeowners ask about permits and inspections is what search engines, and homeowners, reward.</p>'},
        {"h2_html": "A visitor should not be able to leave your site <em>without a way to reach you</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner who lands on your site with a sparking outlet should be one tap from calling you, and one who is researching a panel upgrade should be able to request a quote without hunting for a phone number. The site puts click-to-call and a quote request on every page, so a visitor becomes a booked call or a lead in your CRM instead of a bounce in your traffic report. Speed matters most on the emergency searches, where the first easy-to-reach electrician wins the job.</p>'},
        {"h2_html": "The traffic is <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a directory profile or a shared-lead service disappears the day you stop paying. A website you own keeps ranking, keeps capturing calls, and keeps compounding in value for as long as it exists, and it is registered to you. The site plugs into the same CRM that follows up on every lead it captures, so nothing it earns you goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A homeowner skips the directory and calls <em>you</em> instead",
        "body_html": "Someone searches for an electrician near them after a breaker keeps tripping and, instead of a directory form that gets sold to four companies, finds your site ranking with a page about your city and a clear click-to-call at the top. They tap it and reach you directly, or request a quote and your CRM follows up before they even close the tab. You paid nothing per lead, and no directory shared that call with the electricians down the road."},
    "faqs": [
        ("Do I still need Angi and Thumbtack if I have my own site?",
         "Maybe, for now. Some homeowners still start there. The point is not to replace them, it is to also own a channel where the calls are entirely yours instead of shared or sold to three other electricians."),
        ("Will my site actually rank for electrician near me?",
         "For your specific city and the services you name, realistically yes over time. Broad national terms are harder, but local searches like electrician near me in your town, panel upgrade, or EV charger install are exactly where a local electrician can win."),
        ("How fast do people expect to reach an electrician?",
         "On an emergency search, fast. That is why the site leads with click-to-call on every page, so a homeowner with no power reaches you in one tap instead of filling out a form and waiting for a callback."),
        ("I already have a website. Why do I need another?",
         "A template site that does not rank and does not capture calls is not doing the job. This one is built to rank for the services and neighborhoods you want and to turn visitors into calls and quotes in your own CRM, not just sit there."),
        ("How long until it starts ranking?",
         "Local, specific searches can start moving within weeks; broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for electricians"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-electricians.html", "Staying visible in your area beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the calls in <em>your own city</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories selling your calls to everyone else, whether you work with us or not. No credit card, never a call center.",
},
# ============================== Marketing for Electricians ==============================
{
    "slug": "marketing-for-electricians",
    "trade_slug": "electricians", "trade_plural": "electricians",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Electricians",
    "title": "Marketing for Electricians | Top Shelf Business Solutions",
    "og_title": "Marketing for Electricians",
    "meta_desc": "Marketing for electricians keeps your Google Business Profile active and your name in front of local demand, so you are the electrician people already call.",
    "service_schema_name": "Marketing for Electricians",
    "eyebrow": "For Electricians",
    "h1_html": "Marketing <em>for Electricians</em>",
    "answer_block": "Marketing for electricians keeps you visible where local demand actually shows up, on your Google Business Profile and in local search, so when a homeowner has a dead outlet or is finally ready for that EV charger, your name is the one they already know to call.",
    "sections": [
        {"h2_html": "Electrical work runs on <em>who they already know</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most homeowners do not shop hard for an electrician. When something goes wrong, they call the name they already recognize, the truck they have seen in the neighborhood, the company a neighbor mentioned, the magnet that has been on the fridge for two years. Winning that recognition before someone has a problem is worth more than any single ad, because by the time an outlet is sparking, they are calling from memory, not running a careful search.</p>'},
        {"h2_html": "Your Google Business Profile is the new <em>truck on the street</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for an electrician near them, your Google Business Profile is often the first thing they see, before your website and before a directory. A profile that sits untouched for months looks abandoned next to one with recent photos of finished panels, service updates, and fresh reviews. Keeping it active is a quiet, constant advertisement running in the exact moment a homeowner is looking for someone to call.</p>'},
        {"h2_html": "Show up for the work you <em>want more of</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Not all electrical work is equal, and marketing lets you lean toward the jobs you want. If you want more EV charger and generator installs, or more panel upgrades, your profile posts, photos, and local content can feature exactly that work, so you build a reputation for it and show up when a homeowner searches for it. It is slower than a blast of ads, and it is the approach that actually shapes the kind of calls you get.</p>'},
        {"h2_html": "The customers you already served forget you faster than you think",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Past customers and the people who already know your work are your cheapest source of jobs, and also the easiest to lose touch with. A steady, low-effort presence, a seasonal safety reminder, a photo of a recent job, a note in the neighborhood group, keeps you top of mind without turning into a sales pitch, so the next call and the referral come to you and not to whichever electrician they happened to see most recently. This is the public-facing side of your business; the private follow-up to people already in your list is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The neighbor who calls <em>after seeing your name for months</em>",
        "body_html": "You keep your Google profile active with photos of finished panels and EV charger installs, and you post in the neighborhood group now and then. A homeowner a few streets over does not need an electrician yet, but keeps noticing your name and your work. Months later a breaker starts tripping and they need someone that day, and instead of searching cold, they call the electrician whose name they already knew from the neighborhood. You never spoke to them once before that call."},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         "Yes. We keep it active with job photos, service updates, and local content on a regular schedule, so it looks current whenever someone searches for an electrician near them."),
        ("Can I focus my marketing on the jobs I want more of?",
         "Yes. If you want more panel upgrades, EV charger installs, or generator work, the posts, photos, and content lean toward that work, so you build recognition for it and show up when someone searches for it."),
        ("How is this different from the CRM follow-up?",
         "The CRM follows up privately with people already in your list. Marketing is the public-facing side, your Google profile, local content, and neighborhood visibility, aimed at homeowners who are not your customer yet but will recognize your name when they need an electrician."),
        ("Does this help me show up in the map results?",
         "An active, complete Google Business Profile with fresh photos and reviews is one of the things that helps you appear in the local map results. We keep it current, which is exactly what a stale profile is missing."),
        ("How long before I see it working?",
         "Recognition builds over months, not days, which is why most electricians never stick with it long enough to see it pay off. Setup is included, and a free audit will show you what your current online presence actually looks like to someone searching near you today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for electricians"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-electricians.html", "The reviews that feed the same Google profile"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the electrician they <em>already know</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# ============================= Automation for Electricians =============================
{
    "slug": "automation-for-electricians",
    "trade_slug": "electricians", "trade_plural": "electricians",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for Electricians",
    "title": "Automation for Electricians | Top Shelf Business Solutions",
    "og_title": "Automation for Electricians",
    "meta_desc": "Automation for electricians follows up on quotes, sends appointment reminders, and keeps dispatch on track, so no job or customer slips during a booked week.",
    "service_schema_name": "Automation for Electricians",
    "eyebrow": "For Electricians",
    "h1_html": "Automation <em>for Electricians</em>",
    "answer_block": "Automation for electricians keeps every quote, appointment, and job on track without you remembering, following up on panel-upgrade estimates, sending reminders before each visit, and keeping dispatch moving, so nothing slips during a week when your techs are booked days out.",
    "sections": [
        {"h2_html": "A booked week runs on <em>reminders nobody sees you send</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When your techs are booked days out, the work is not the hard part, the coordination is. A customer needs a reminder the day before so they are home, a quote from last week needs a nudge before it goes cold, a tech needs the address and scope before they roll, and every one of those is a small task that slips during a busy stretch. A customer who is not reminded and misses the window, or a quote nobody followed up on, is money lost to a full schedule, not an empty one.</p>'},
        {"h2_html": "Every quote, followed up <em>automatically</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The jobs electricians quote and wait on, panel upgrades, rewires, generator and EV charger installs, are exactly the ones a steady follow-up wins. When you send a quote, the automation starts a sequence: a check-in the next day, a helpful note a few days later, a last nudge before it goes cold. You still make every real call. The routine follow-up is simply handled, on time, on every quote, whether you sent one this week or a dozen.</p>'},
        {"h2_html": "Reminders that cut the <em>no-shows and the callbacks</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Before each scheduled visit, the customer gets an automatic confirmation and a reminder, so they are home when your tech arrives and you are not eating a wasted trip across town. After the work is done, a follow-up can go out to check everything is working and to ask for a review while the job is fresh. None of it depends on you remembering during a week when you are already stretched thin.</p>'},
        {"h2_html": "Dispatch and follow-through, <em>kept on track</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">As a job moves, the right people get the right update: the tech gets the address and scope, the customer gets an on-the-way or running-late note, and a job that needs a permit or an inspection gets a reminder so it does not stall. A lead that went quiet can resurface on a schedule instead of falling out of your memory entirely. It all runs against the same database as your CRM, so nothing here duplicates a customer or a note.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A booked week where nothing <em>slips through</em>",
        "body_html": "Your schedule is full three days out. Without you touching your phone, each customer gets a reminder the day before their visit, the panel-upgrade quote you sent Monday gets a friendly check-in Wednesday, and the homeowner waiting on an inspection gets a note the day it is scheduled. You never sat down to send any of it, and nobody fell through the cracks just because the week was busy."},
    "faqs": [
        ("What does the automation actually handle?",
         "The routine follow-through around your jobs: quote follow-up sequences, appointment confirmations and reminders, after-job check-ins and review requests, and nudges on jobs waiting for a permit or inspection. You still make every real decision and call."),
        ("Does this replace me talking to customers?",
         "No. It handles the routine reminders and follow-ups so you are not the one remembering to send them during a busy week. You step in personally for anything that actually needs a conversation."),
        ("Will reminders really cut down no-shows?",
         "They help a lot. An automatic confirmation and a reminder before each visit are the single biggest lever on missed appointments, so your techs are not driving to homes where nobody is there."),
        ("What happens to quotes and leads that go quiet?",
         "They get a scheduled follow-up instead of being forgotten. You set how long a quote or lead should sit before it gets another nudge, so old opportunities keep getting a reason to come back instead of sitting in a list."),
        ("How long does setup take?",
         "Setup is included with no separate fee. We build the quote, reminder, and follow-up sequences around how you already work, so it is running within days. Start with a free audit and we will show you what is currently falling through during your busy weeks.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for electricians"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-electricians.html", "The database every workflow runs against"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a job <em>slip in a busy week</em>",
    "cta_sub": "Get a free audit of what is currently falling through the cracks between your quotes, your reminders, and your schedule, whether you work with us or not. No credit card, never a call center.",
},
]
