"""Per-page content specs for the SEO corpus (plan §5), Pest Control Companies batch.
generate_corpus.py imports SPECS from a specs module; each dict is one page's UNIQUE,
hand-written, trade-specific content. The generator owns the mechanics (shell, schema,
events, interlinks, keyword placement); the spec owns the substance that clears the
uniqueness gate. Never templated find-and-replace off another trade.

Pest control is a recurring-revenue business first. The money is in quarterly and monthly
protection plans that only pay off if they renew and get rebooked, so retention, auto-rebooking,
and converting a one-time job into a plan run through every page. On top of that sits the panic
call, a wasp nest by the door, roaches in the kitchen, bed bugs, a rat in the pantry, a termite
find, where an anxious homeowner wants someone today and hangs up on a voicemail box. Demand is
local and seasonal (ants and mosquitoes in the summer heat, rodents pushing indoors when it
turns cold, termites swarming in spring), techs run density-packed routes, termite and
real-estate wood-destroying-insect inspections carry closing deadlines and annual warranties,
and reviews matter enormously because the customer is deciding who to let into their home over
something scary or embarrassing. The urgency is the panic call lost to voicemail AND churn on
the recurring plans, and both pages have to speak to that. SPECS[0] is the AI receptionist and
carries "demo": True, so the generator drops in the live-call demo (same as every batch).
Honesty rules: no invented stats, prices, or clients; benefits are hedged ("often", "typically");
each example ends with the literal "Illustrative example, not a client." per the honesty rule; if
the generator also appends that line, dedupe there.
"""

SPECS = [
# ================ AI Receptionist for Pest Control Companies ================
{
    "slug": "ai-receptionist-for-pest-control-companies", "demo": True,
    "trade_slug": "pest-control-companies", "trade_plural": "pest control companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Pest Control Companies",
    "title": "AI Receptionist for Pest Control Companies | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Pest Control Companies",
    "meta_desc": "An AI receptionist for pest control companies answers every panic call, triages the wasp nest from routine service, and books it while your techs are out on route.",
    "service_schema_name": "AI Receptionist for Pest Control Companies",
    "eyebrow": "For Pest Control Companies",
    "h1_html": "AI Receptionist <em>for Pest Control Companies</em>",
    "answer_block": "An AI receptionist for pest control companies answers every call the moment it rings, day or night, tells a wasp nest or a kitchen full of roaches apart from a routine quarterly service, and books the job while your techs are out on their routes. You keep your own number, and every call stays yours.",
    "sections": [
        {"h2_html": "The panic call you miss is the customer who <em>dials the next exterminator</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner who just found a wasp nest by the front door, a mouse in the pantry, or bed bugs in the mattress is not going to leave a voicemail. They are anxious, they want it gone today, and they hang up and call the next exterminator on the list until someone picks up. Pest control runs on that panic more than almost any trade, because the customer is scared of what is in their home and about to let a stranger in to deal with it. But your techs are out on their routes, mid-treatment under a sink or up on a ladder, and the office line rings and rings, so the call rolls to voicemail and the job, along with the protection plan it could have become, goes to whoever answered.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">An AI receptionist answers on the first ring, stays calm with a rattled caller, finds out whether it is stinging insects, rodents, bed bugs, or a routine quarterly visit, gets the address, and either books the stop or flags it to you as urgent on the spot. The job is captured and scheduled instead of lost to the company down the road.</p>'},
        {"h2_html": "Built around how a <em>pest control company actually books work</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your calls do not keep office hours, and they do not all mean the same thing. A wasp nest by a swing set where the kids play needs someone today, bed bugs need an inspection and prep before treatment, and a quarterly service is just another stop on the route. A voicemail box cannot tell those apart, and a generic call center reading a script does not know a carpenter ant from a termite or which one can wait until next week.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers after hours and on weekends, when the wasp nest and the rat in the kitchen that turn into same-day jobs tend to show up.</li><li>Triages the way you would: stinging insects, rodents, roaches, bed bugs, or termites, one-time or recurring, and how fast someone needs to be there.</li><li>Gets the address, books routine and quarterly stops into the right area and day so a tech is not driving across town for one visit, and flags the true emergencies to you at once.</li><li>Knows a plan member from a first-time caller, so the customers already on a recurring agreement never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one saved account</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. A single panic call that turns into a recurring protection plan is worth far more than the one-time fee, because it bills every quarter for years, and one bed bug or termite job you would have lost on a weekend often covers the service for months. Everything it captures after that first save is on top. The point is to stop handing your best accounts to the exterminator who simply answered faster.</p>'},
        {"h2_html": "You own the number, the calls, and the customer list",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every address, and every job detail is yours and exportable any time, so the customer list, the thing that turns into recurring revenue, is an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The AI receptionist is one piece of the Top Shelf platform, and it hands every call it captures to the same CRM that follows up, so a quote or a plan renewal never slips.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Saturday wasp nest, booked while you are <em>on another route</em>",
        "body_html": "It is Saturday afternoon and a homeowner finds a wasp nest right over the door their kids use. They search for an exterminator and call the first three they see. Two go to voicemail. Yours answers, stays calm, confirms nobody has been stung and where the nest is, gets the address, and books the stop for that afternoon while flagging it to your phone as urgent. You finish the account you are already on and roll straight to it, instead of hearing about the job Monday after they hired someone else. Illustrative example, not a client."},
    "faqs": [
        ("Does it work with my current phone number?",
         "Yes. It can answer on your existing business number, or set up a new one registered in your name. Either way the number and every call that comes through it belong to you and go with you if you ever leave."),
        ("Can it tell a real emergency from a routine service call?",
         "Yes, that is the point. It asks the questions you would, stinging insects or rodents, bed bugs or termites, one-time or a scheduled quarterly visit, and treats a wasp nest by the door as urgent while booking a routine service into a normal slot. You set what counts as a drop-everything job."),
        ("Will it actually book the stop on my route?",
         "Yes. Routine and quarterly visits land on your calendar in the right area and day so your techs are not crossing town for one stop, and you get a text with the details right away. For a true emergency it can book the first opening and alert you at once."),
        ("Is it going to sound like a robot to an anxious customer?",
         "It answers naturally and calmly, and it is upfront instead of pretending to be a person. Someone who just found bed bugs mostly needs to know a real exterminator is handling it, and a steady voice that captures the details beats a voicemail box every time. You can hear it handle a live call before you decide."),
        ("How fast can it be running?",
         "Setup is included with no separate onboarding fee. We configure your triage questions, your calendar, and your emergency rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pest control companies"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-pest-control-companies.html", "The CRM that follows up on every lead you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing panic calls to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many calls and after-hours jobs your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# ==================== CRM for Pest Control Companies ====================
{
    "slug": "crm-for-pest-control-companies",
    "trade_slug": "pest-control-companies", "trade_plural": "pest control companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Pest Control Companies",
    "title": "CRM for Pest Control Companies | Top Shelf Business Solutions",
    "og_title": "CRM for Pest Control Companies",
    "meta_desc": "A CRM for pest control companies tracks every recurring plan and rebooks the next visit for you, so the accounts you earned keep billing instead of quietly lapsing.",
    "service_schema_name": "CRM for Pest Control Companies",
    "eyebrow": "For Pest Control Companies",
    "h1_html": "CRM <em>for Pest Control Companies</em>",
    "answer_block": "A CRM for pest control companies keeps every customer, past job, open quote, and recurring plan in one place and follows up for you, so a lapsing quarterly account and the one-time bed bug job that should become a protection plan both stay yours. The customer list you already have quietly becomes recurring revenue.",
    "sections": [
        {"h2_html": "Your recurring plans are the <em>revenue you keep losing to churn</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A recurring service plan is the best revenue in pest control. It is predictable, it comes back every quarter or every month, and a plan member calls you first instead of shopping around when something new shows up. But a plan only pays off if it stays active, and retention depends on someone rebooking the next visit and catching a member before they drift away. With hundreds of accounts and techs running full routes, that is exactly the task that slips, and a lapsed member quietly slips to a competitor the next time ants come through the kitchen.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM tracks every plan, its cadence, and the next service due, and rebooks it on schedule while reaching out to any account going quiet. The members you already earned keep renewing, and the recurring revenue you built does not walk out the door one forgotten visit at a time.</p>'},
        {"h2_html": "Every one-time job is a <em>protection plan waiting to happen</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner who called once for a wasp nest or a single roach treatment has already let you in the door and seen your work. The next step, the one that actually builds the business, is turning that one-time job into a recurring plan, and that conversion depends on a well-timed follow-up that never happens between stops. The CRM keeps every one-time customer in front of you and follows up for you.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every customer, address, service history, and note lives in one place instead of a truck full of paper tickets and your memory.</li><li>One-time customers get a follow-up that offers the protection plan while the visit is still fresh, so more of them convert to recurring accounts.</li><li>You can see which members are overdue and reach the right account with the right reminder before it lapses.</li></ul>'},
        {"h2_html": "A termite warranty and an aging account are <em>renewals with a date on them</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every termite job you have done carries an annual warranty or bond that has to be renewed, and every customer you have ever treated has a service history that tells you when they are due again. That information sits in your files doing nothing. A CRM keeps the renewal date and the history on record for every account, so you can reach a homeowner about their termite renewal before it expires, or a lapsed customer before the next season, instead of letting a warranty quietly drop or a good account go cold. You are not cold-calling anyone. You are reaching people you already served.</p>'},
        {"h2_html": "You own the list, and it works with the rest of the system",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every note is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the AI receptionist, so a call it answers lands in your database and gets followed up automatically, and to online booking, so a scheduled visit is logged against the right customer with their full history already attached. Nothing you have earned goes cold.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The one-time roach job that <em>becomes a plan</em>",
        "body_html": "You treat a homeowner once for roaches on a Tuesday, collect the one-time fee, and on a normal week that is the last you hear of them. Instead the CRM sends a friendly check-in a few days later that mentions your quarterly protection plan and what it covers, written to sound like you. The roaches are gone, they remember how easy you made it, and they sign up for recurring service that now bills every quarter. You never sat down to sell it, and a single job turned into an account for years. Illustrative example, not a client."},
    "faqs": [
        ("Does it import my existing customers and plans?",
         "Yes. Your current customers, one-time jobs, recurring plans, and service history come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already have actually work for you."),
        ("Can it rebook recurring plan visits for me?",
         "Yes. It tracks every plan and its cadence, quarterly, bi-monthly, or monthly, rebooks the next service on schedule, and reaches out to any account going quiet before it lapses. You can step in and talk to anyone directly whenever you want."),
        ("Will it help me turn one-time jobs into recurring plans?",
         "Yes. A one-time customer gets a follow-up that offers your protection plan while the visit is still fresh in their mind, so more of them convert to recurring accounts instead of being a single fee you never hear from again."),
        ("Can it track termite warranty renewals?",
         "Yes. It keeps the renewal or bond date on record for every termite job and reaches out before it expires, so a warranty does not quietly drop and the renewal revenue stays yours."),
        ("How long until it is set up?",
         "Setup is included with no separate onboarding fee. We bring in your customers and plans, build your follow-up and rebooking sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will find the gaps where revenue is slipping through today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pest control companies"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-pest-control-companies.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting plans and accounts <em>go cold</em>",
    "cta_sub": "Get a free audit of how many recurring plans and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ================ Online Booking for Pest Control Companies ================
{
    "slug": "online-booking-for-pest-control-companies",
    "trade_slug": "pest-control-companies", "trade_plural": "pest control companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Online Booking for Pest Control Companies",
    "title": "Online Booking for Pest Control Companies | Top Shelf Business Solutions",
    "og_title": "Online Booking for Pest Control Companies",
    "meta_desc": "Online booking for pest control companies lets customers self-book a quarterly service, termite inspection, or treatment on your real route availability, no phone tag.",
    "service_schema_name": "Online Booking for Pest Control Companies",
    "eyebrow": "For Pest Control Companies",
    "h1_html": "Online Booking <em>for Pest Control Companies</em>",
    "answer_block": "Online booking for pest control companies lets a customer pick a time for the work that is not a panic, a quarterly service, a termite inspection, a mosquito treatment, straight from your website or a text link on your real route availability, so you stop playing phone tag and the visit lands on the right day and area.",
    "sections": [
        {"h2_html": "Not every pest call is a <em>same-day panic</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A wasp nest over the door needs a phone and a fast truck. But a lot of pest control work is not urgent at all: a homeowner wants to start a quarterly plan, book a termite inspection, get the mosquitoes handled before a backyard party, or price out rodent exclusion, and they would happily book it themselves if you let them. Making those customers call during business hours, wait on hold, and trade voicemails is how routine work quietly slips to the company that made booking easier.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A booking link lets them grab an open slot the moment they think of it, at night or on a lunch break, without reaching you first. You come off a route to the visit already on the calendar instead of a missed call you now have to chase between stops.</p>'},
        {"h2_html": "It sorts the panic from the <em>routine</em> before it books",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Self-scheduling does not mean sending a wasp nest to a slot next week. The booking form asks what is going on first, and a true emergency, stinging insects, a rodent inside, a fresh bed bug find, gets pointed straight to your line to call right now, while genuinely routine work, a quarterly service, an inspection, a mosquito treatment, books itself onto your calendar. Bed bug jobs can be routed to an inspection slot first, since they need a look and some prep before treatment. You set the rules: which jobs are bookable online, how long each takes, and how much notice you need.</p>'},
        {"h2_html": "Book into the <em>right route</em>, not across town",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A pest control day lives and dies by route density, and a booking tool that ignores where your trucks already are just creates windshield time. This one can offer a customer the days you are already working their area, so a new quarterly stop drops into an existing route instead of sending a tech thirty minutes out for a single visit. The link goes anywhere someone meets you, your website, your Google Business Profile, your email signature, and the text you send after a call, and every one of those becomes a place to book you in one tap. A real-estate agent who needs a termite inspection before a closing date can lock in a slot before they close the tab, instead of leaving a voicemail that stalls the sale.</p>'},
        {"h2_html": "On your real calendar, and the customer actually shows",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">It syncs to the calendar you already use so it can never double-book a tech against a stop you already have, and it sends the customer a confirmation and a reminder, which is what actually cuts no-shows. A tech driving to an empty house is a wasted stop you never get back on a full route. Every booking is logged against the right customer in your CRM, and it works alongside the AI receptionist, which can also book the caller who would rather talk than tap.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A termite inspection, booked <em>before the closing slips</em>",
        "body_html": "It is 8pm and a real-estate agent realizes the buyer's loan needs a termite inspection before a closing at the end of the week. Your office is closed. Instead of leaving a voicemail that will stall the sale, they land on your site and book a wood-destroying insect inspection for Thursday morning from the calendar right there on the page, into a day you are already working that neighborhood. You wake up to the job already set, with the address and the deadline attached, and the closing stays on track because you were the easiest to book. Illustrative example, not a client."},
    "faqs": [
        ("Does it sync to my Google or Outlook calendar?",
         "Yes. It reads your real calendar so it only ever offers times you are actually free, and new bookings drop straight onto it. It cannot double-book a tech against a stop you already have scheduled."),
        ("Will a wasp nest or a rodent inside try to book a slot next week?",
         "No. The form asks what is going on first, and a true emergency, stinging insects, a rodent indoors, a fresh bed bug find, is pointed to your line to call right now instead of booking a future slot. Only the work you mark as routine can self-schedule."),
        ("Can it book new stops into the areas my trucks already cover?",
         "Yes. You set which days you work which areas, and the tool can offer a customer the days you are already near them, so a new quarterly visit drops into an existing route instead of sending a tech across town for one stop."),
        ("Will it cut down on no-shows?",
         "It helps. Automatic confirmations and reminders by text and email are the single biggest lever on no-shows, and every booking includes them. A customer who booked themselves and got a reminder is far more likely to be home than a loosely agreed callback."),
        ("How fast can it be live?",
         "Setup is included, no separate fee. We connect your calendar, set up your job types, service areas, and rules, and put the link on your site and profile, so it is taking bookings in days. Start with a free audit and we will show you where you are losing routine jobs today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pest control companies"),
        ("solution-booking.html", "How the online booking system works"),
        ("ai-receptionist-for-pest-control-companies.html", "The AI receptionist that can book callers too"),
        ("crm-for-pest-control-companies.html", "The CRM every booking is logged into"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Let customers book you <em>while you run your routes</em>",
    "cta_sub": "Get a free audit of how many routine jobs your current callback process is costing you, whether you work with us or not. No credit card, never a call center.",
},
# ================ Review Software for Pest Control Companies ================
{
    "slug": "review-software-for-pest-control-companies",
    "trade_slug": "pest-control-companies", "trade_plural": "pest control companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Review Software for Pest Control Companies",
    "title": "Review Software for Pest Control Companies | Top Shelf Business Solutions",
    "og_title": "Review Software for Pest Control Companies",
    "meta_desc": "Review software for pest control companies collects Google reviews the moment a pest is confirmed gone and helps you answer each one, so anxious homeowners trust you enough to book.",
    "service_schema_name": "Review Software for Pest Control Companies",
    "eyebrow": "For Pest Control Companies",
    "h1_html": "Review Software <em>for Pest Control Companies</em>",
    "answer_block": "Review software for pest control companies asks each satisfied customer for a Google review once the pests are confirmed gone, turns leaving one into a quick tap, and helps you answer every reply, so an anxious homeowner deciding who to trust in their home sees recent five-star proof and calls you before your competitor.",
    "sections": [
        {"h2_html": "People read your reviews before they <em>let you inside</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Hiring an exterminator is not like hiring most trades. The customer is about to let someone into the bedroom to deal with bed bugs, or into the kitchen over a roach problem they are embarrassed to admit, and they size you up the only way a stranger can, by reading what other people in the same spot said afterward. Before they ever dial, they scroll your reviews looking for someone who was discreet, thorough, and did not make them feel judged. A profile with a few stale reviews reads as a gamble, and the nervous homeowner quietly picks the company whose recent reviews put them at ease.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">That is rarely a sign your work is worse. Satisfied customers just move on once the problem is handled and never think to post, and you feel awkward bringing it up while you are loading the sprayer back onto the truck. Review software closes that gap for you, so the trust you keep earning in person finally shows up online where the next worried customer is deciding.</p>'},
        {"h2_html": "The review only pest control earns: <em>not one since</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">There is a kind of review pest control earns that almost no other trade does: the customer who writes that they have not seen a single roach since your visit, or that the ants marching across the counter every summer are finally gone for good. That line, not one since, is the most persuasive proof a nervous searcher can find, because it answers the one thing they actually care about, whether the treatment holds. Reviews that name the exact pest go even further. Someone typing bed bug treatment into Google and finding a review that says you cleared a bed bug problem two doors down is far likelier to call than they would be off a generic star rating. The software nudges customers toward describing what you handled, so your profile fills with the specific wins that pull in the next person facing the same thing.</p>'},
        {"h2_html": "Ask when the plan proves itself, <em>not just after the first spray</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Timing is trickier here than in a one-and-done trade. A first treatment might knock down what the customer can see, but they are not truly at ease until a week or two later when nothing has returned, and a request sent too early misses that feeling entirely. The software can hold the ask until the follow-up visit or the point where the pest is confirmed gone, then send it by text and email with a one-tap link to your profile. Your recurring plan members are the real prize here: someone who has stayed on quarterly service for a year without a hitch writes the review that sells the plan itself, and the software can prompt them at a natural moment instead of only chasing one-time jobs.</p>'},
        {"h2_html": "Answer the hard ones with care, and let it <em>compound</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Replies matter more when the subject is sensitive. A customer who worked up the nerve to review a bed bug job deserves a warm, discreet thank-you that never repeats the embarrassing details, and a rare unhappy review, a missed window or a treatment that needed a second round, deserves a composed public answer that shows the next reader how you make it right. The software flags each new review as it posts so nothing sits ignored. Every genuine review you gather strengthens your Google Business Profile, which is what pushes you up the local map when someone nearby searches for an exterminator, which brings the calls that produce the next round of reviews. That loop belongs to you, attached to your own profile rather than a directory, and the requests fire on their own from a job you close out in your CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A bed bug review that becomes <em>next month's booking</em>",
        "body_html": "You finish a bed bug job for a family on a Monday and set the standard follow-up. Two weeks later, once they confirm nothing has returned, an automatic message invites them to share how it went, and they leave a relieved review that mentions how carefully you treated the bedrooms and that there has not been a bite since. A month on, someone three streets away wakes up to bites of their own, looks for help, and finds that review sitting at the top of your profile. It is the exact reassurance they needed, so they call you and no one else. Illustrative example, not a client."},
    "faqs": [
        ("Will people really review something as private as bed bugs or roaches?",
         "More often than you would think. A customer who was mortified and then genuinely helped is usually glad to reassure their neighbors, and the ask makes it painless. You can also steer the wording so they praise your work without spelling out the details, and your discreet reply signals that you keep sensitive jobs quiet."),
        ("Some of my treatments need a follow-up. When does it ask?",
         "You pick the trigger. Rather than firing the second you drive off, it can wait for the follow-up visit or the point where the pest is confirmed gone, which is when the customer actually feels the result and writes the strongest review. The timing and message are yours to set."),
        ("Can it collect reviews from my recurring plan members too?",
         "Yes, and they are often your best. A member who has stayed on quarterly service without an issue for a year writes the review that convinces the next homeowner to sign a plan rather than book a single spray. The software can prompt plan members at a natural moment, not just chase one-off jobs."),
        ("Is automating the requests within Google's rules?",
         "Yes. Asking everyone you served for an honest review is exactly what Google wants. The lines you cannot cross are gating, quietly skipping the customers who might complain, and buying reviews outright, and the software does neither. It invites every real customer and makes leaving feedback effortless."),
        ("How fast is it working, and which sites does it cover?",
         "It centers on Google, where an anxious searcher looks first and where your local ranking is decided, and it can point past customers to your other profiles too. Setup is handled for you at no extra cost, so it is sending within days, and a free audit will first show you how your reputation reads next to the exterminators nearby.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pest control companies"),
        ("solution-reviews.html", "How the review system works"),
        ("crm-for-pest-control-companies.html", "The CRM that triggers the ask when a job is done"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Make a job well done into <em>your next booking</em>",
    "cta_sub": "See a free audit of how your reputation reads next to the pest control companies nearby, whether you work with us or not. No credit card, never a call center.",
},
# ================ Websites & SEO for Pest Control Companies ================
{
    "slug": "websites-seo-for-pest-control-companies",
    "trade_slug": "pest-control-companies", "trade_plural": "pest control companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Pest Control Companies",
    "title": "Websites & SEO for Pest Control Companies | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Pest Control Companies",
    "meta_desc": "A pest control company website built for SEO ranks for exterminator near me, bed bug treatment, and termite inspection, and turns the panic search into a call you own.",
    "service_schema_name": "Websites & SEO for Pest Control Companies",
    "eyebrow": "For Pest Control Companies",
    "h1_html": "Websites &amp; SEO <em>for Pest Control Companies</em>",
    "answer_block": "A pest control company website built for SEO puts you in front of the homeowner who just found bed bugs, wasps, or a rat and is searching for help right now, ranks you in the local map results for the towns you cover, and turns that anxious visitor into a phone call, so the job is yours and not a directory's to resell.",
    "sections": [
        {"h2_html": "When someone finds a pest, they search and <em>call within minutes</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner who spots a scorpion by the crib, hears scratching in the attic after dark, or wakes up covered in bites is not researching for a week. They grab the nearest phone, type in whatever they just saw, and call one of the first names that comes up, usually within minutes and usually one sitting at the top of the local map. If your business is not on that screen, you do not exist for that job, no matter how skilled your crew is or how many years you have run routes in that town. Fear moves fast, and the click goes to whoever is already there.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Showing up in that instant is the entire job of search. It decides whether the frightened call reaches your phone or the company across town, on the very day someone in your area is desperate to hand the problem to somebody they can trust.</p>'},
        {"h2_html": "Every pest and every town is <em>its own page</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Broad terms belong to the national directories, and you will not beat them this year, but you do not have to. The searches that turn into real jobs are specific: bed bug treatment, termite inspection, wasp nest removal, rodent control, mosquito service, each one tied to a city or a neighborhood. A page built for a single pest in a single town, written for the people who actually live there, is something a faceless directory has no reason to create and you can own outright. Do that across the pests you treat and the areas your trucks already run, and you start collecting the exact, high-intent searches a generic listing will never rank for.</p>'},
        {"h2_html": "Your rankings rise and fall with the <em>seasons</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Pest search volume is not steady, and that is an advantage once you plan for it. Mosquito and ant searches surge in the summer heat, rodent searches climb as the nights turn cold and mice move indoors, termite swarm searches spike for a few weeks each spring. Content built and refreshed ahead of each wave, a mosquito page ready before June, a rodent page updated before the first freeze, is what ranks when the searches actually arrive rather than scrambling once they do. Google rewards a page that has been live and earning trust for a while, so the company that published ahead of the season is the one sitting on top when the whole town starts typing at once.</p>'},
        {"h2_html": "Stop renting your own calls from a <em>directory</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Pay a lead service and you are buying a call it may hand to two or three other companies at the same moment, and the whole thing evaporates the day your card stops going through. A site you own behaves the opposite way: it keeps ranking, keeps ringing your phone, and grows more valuable the longer it stays live, and the domain and the leads belong to you rather than a platform that can cut you off tomorrow. Because it feeds the same CRM and AI receptionist that catch and follow up every call, the work it brings in gets captured instead of falling into the gap between a click and a callback.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A midnight rodent search that <em>ends on your page</em>",
        "body_html": "At eleven at night a homeowner hears something moving in the walls and searches rodent control in their town from bed. A directory would grab that search and sell it on to whoever pays the most. Instead they land on your page for rodent work in their exact area, see that you handle it and that their own neighbors trusted you, and tap the number at the top. You pick up in the morning to a booked job that cost you nothing per lead, with no broker ever wedged between you and the customer. Illustrative example, not a client."},
    "faqs": [
        ("Can I really rank for specific pests like bed bugs or termites?",
         "Yes, and that is exactly where a local company wins. A term like bed bug treatment or termite inspection tied to your city is too specific for a national directory to serve well, so a real page about that pest in that area, written for the people searching it, can climb where a broad term never could."),
        ("How does seasonal search change what you build?",
         "Pest demand and the searches behind it move with the calendar, so the work is timed to it. A mosquito page goes live before summer, a rodent page is refreshed before the cold sets in, termite content is ready for swarm season, because a page has to be established before the wave hits to rank when it does."),
        ("Do you build a separate page for each service area?",
         "Yes, starting with the towns and neighborhoods your routes already cover. Each area gets its own real page rather than one thin list of city names, which is what lets you appear in the map results for a specific place instead of blurring across a whole metro."),
        ("Someone with a wasp nest just wants to call. Does a website even matter?",
         "That is exactly when it matters most. Fear sends people straight to their phone, and they tap the first credible local result they see, the one with a visible number, real reviews, and a page that says you handle wasps. A fast site that leads with your phone number is what converts that moment of panic into a booked visit."),
        ("How soon will it rank, and do I own it?",
         "Specific local searches often start climbing within a few weeks and compound from there, while the broadest terms take longer. The site, the domain, and every lead it captures are registered to you, never rented, and a free audit will first show you where your current presence stands to someone searching nearby right now.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pest control companies"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-pest-control-companies.html", "Staying visible in your service area beyond your site"),
        ("crm-for-pest-control-companies.html", "Where every captured lead lands and gets followed up"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the searches for every pest in <em>your area</em>",
    "cta_sub": "See a free audit of where your website and map-pack presence stand against the directories that intercept your calls today, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Marketing for Pest Control Companies ====================
{
    "slug": "marketing-for-pest-control-companies",
    "trade_slug": "pest-control-companies", "trade_plural": "pest control companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Pest Control Companies",
    "title": "Marketing for Pest Control Companies | Top Shelf Business Solutions",
    "og_title": "Marketing for Pest Control Companies",
    "meta_desc": "Marketing for pest control companies wins recurring plan members and whole-street referrals, then keeps you first in the local map pack where the panic search lands.",
    "service_schema_name": "Marketing for Pest Control Companies",
    "eyebrow": "For Pest Control Companies",
    "h1_html": "Marketing <em>for Pest Control Companies</em>",
    "answer_block": "Marketing for pest control companies goes after the accounts worth having, recurring plan members and the neighbors who ask after they see your truck, and keeps you first in the local map pack when someone nearby searches in a panic, so your name is the one an anxious homeowner calls instead of the company that let its listing go quiet.",
    "sections": [
        {"h2_html": "A plan member is worth <em>years, not one visit</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The math of pest control marketing is different from a one-off trade. When a new customer signs a recurring plan, they are not a single ticket, they are quarterly revenue that can run for years, plus a termite renewal and the odd extra treatment on top. That changes what a lead is worth and where the budget should go. Chasing one-time sprays is a treadmill, while marketing aimed at protection plans buys an account that keeps paying long after the ad has done its work. The goal is not the cheapest call this week, it is the customer still on the books three summers from now.</p>'},
        {"h2_html": "One treated house, and the <em>whole street asks</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Pests do not respect property lines. Roaches, termites, and rodents work their way down a block, so when you treat one house the neighbors often have the same trouble brewing and have just watched your truck park next door. That is an opening no other trade gets quite so cleanly. A yard sign, a quick word with the people next door, a neighborhood post, and a simple referral offer can turn one job into a cluster of them on the same street, which also tightens your drive time. Reviews tied to a recognizable local road pull in the rest, because people trust the company their own neighbors already let inside.</p>'},
        {"h2_html": "Get in front of each pest <em>before its season</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Pest demand runs on a calendar you can predict, and the advantage goes to whoever is early. A mosquito and tick push before the summer cookouts begin, a rodent-proofing message as the first cold nights arrive, termite awareness during the spring swarms, each campaign timed to land just before people start noticing the problem themselves. Reach a homeowner while the worry is fresh and you catch them before they even search, and a seasonal one-time call is the easiest thing in the world to grow into a year-round plan. Wait until the phones are already ringing and you are fighting every competitor for the same attention.</p>'},
        {"h2_html": "The map pack is where the <em>panic search lands</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a frightened homeowner searches for an exterminator, the three local listings with star ratings sit above everything else, and that is usually where the decision gets made. A listing left stale, old hours, no fresh photos, a trickle of reviews, reads like a company that might not even answer, while an active one with recent job photos and steady reviews reads like the safe choice. Keeping that listing current, accurate, and full of proof is the cheapest, highest-return marketing in the trade, because it works in the exact instant someone nearby needs help. This is the public face of the business; the quiet outreach to the customers you have already served runs through the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The truck next door that <em>books the whole block</em>",
        "body_html": "You treat a home for termites on a quiet street early one spring. Your truck sits out front for a couple of hours, a neighbor wanders over to ask what you found, and because your Google profile is active and full of local reviews, two more houses on the same block look you up that week and book inspections of their own. One becomes a termite job, another signs up for a quarterly plan. A single account turned into three, all within a few minutes of each other on the same route, without a dollar of new ad spend. Illustrative example, not a client."},
    "faqs": [
        ("Should marketing chase one-time sprays or recurring plans?",
         "Recurring plans, in almost every case. A one-time spray is a single payment, while a plan member renews for years and refers their neighbors, so a lead that becomes a plan is worth far more than a cheaper one that never comes back. We point the message at the accounts with real lifetime value, not the lowest-cost call this week."),
        ("Can you really turn one job into more houses on the same block?",
         "Yes, because pests are a shared-street problem. When you treat one home, the neighbors often have the same issue and have already seen your truck, so yard signs, a neighborly knock, local posts, and a referral offer can cluster several jobs onto one route and cut your drive time between them."),
        ("How do you time campaigns around pest seasons?",
         "By getting in front of each pest just before people start seeing it. Mosquitoes and ticks before summer, rodent-proofing before the cold, termites during the spring swarms, each push lands while the worry is building, which is also the easiest moment to move a one-time call onto a year-round plan."),
        ("Do you keep my Google Business Profile current for me?",
         "Yes, keeping it fresh is part of the work. Recent job photos, accurate hours and services, seasonal posts, and a steady stream of new reviews all go up on a schedule, so it reads like a company that will actually pick up when a nervous homeowner is scanning the map for someone to trust."),
        ("How is this different from the CRM, and how soon does it work?",
         "Marketing is the public side, your map listing and reviews and the local visibility that reaches people who are not yet your customers. The CRM works privately on the customers already in your system. A neglected profile can climb the map within weeks and compounds from there, and a free audit shows how visible you are to a searcher nearby right now.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pest control companies"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("review-software-for-pest-control-companies.html", "The reviews that feed the same Google profile"),
        ("websites-seo-for-pest-control-companies.html", "The website that captures the demand this drives"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the first listing a <em>frightened homeowner sees</em>",
    "cta_sub": "See a free audit of how visible your business really is on the local map and to the neighbors you want as plan members, whether you work with us or not. No credit card, never a call center.",
},
# ==================== Automation for Pest Control Companies ====================
{
    "slug": "automation-for-pest-control-companies",
    "trade_slug": "pest-control-companies", "trade_plural": "pest control companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Automation for Pest Control Companies",
    "title": "Automation for Pest Control Companies | Top Shelf Business Solutions",
    "og_title": "Automation for Pest Control Companies",
    "meta_desc": "Automation for pest control companies rebooks recurring plans, sends on-my-way and prep texts, and follows up after every job, so routes stay full and nothing gets missed.",
    "service_schema_name": "Automation for Pest Control Companies",
    "eyebrow": "For Pest Control Companies",
    "h1_html": "Automation <em>for Pest Control Companies</em>",
    "answer_block": "Automation for pest control companies handles the texts and reminders around every job for you, the notice that rebooks a quarterly plan, the prep and on-my-way message before a visit, the review request and plan offer after the work is done, so your routes stay full and nothing depends on you remembering between stops.",
    "sections": [
        {"h2_html": "Recurring plan visits that <em>rebook themselves</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The recurring plan is the whole business, and it only works if the next visit actually gets scheduled. Every quarterly service and every monthly stop has to be rebooked for the plan to keep billing and the customer to stay yours, and doing that by hand, reminding hundreds of members their next service is due, is exactly the task that slips when the office is buried and the techs are on full routes. A plan visit that never gets rebooked is a member quietly sliding toward churn.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">Automation sends each member their rebooking notice on schedule, at the right point in their cadence, with a link to confirm or pick a time, so the recurring visits fill back in on their own and the plan proves its worth without anyone in the office chasing a list.</p>'},
        {"h2_html": "Prep and on-my-way texts, so <em>the visit actually works</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A pest treatment often needs the customer to do something first, pull things out from under the sink, secure pets and kids away from where you will spray, or run through the prep a bed bug job requires, and a customer who was not told is a wasted trip. Automation sends the confirmation, a prep reminder with exactly what to do before you arrive, and an on-my-way text with a realistic window when the tech heads out, all sent for you. The customer is ready when you get there, the house is set up for the treatment to work, and you are not the one stopping to type it between stops.</p>'},
        {"h2_html": "The follow-up after the job <em>runs itself</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The job is not really done when you drive away. A quick check that the problem has stopped, an automatic review request while the customer is still relieved, and, for a one-time job, an offer to move onto the recurring protection plan all matter, and all are easy to forget once you are onto the next stop. Automation fires each one on time, so a finished job turns into a review, a plan member, and a customer for years instead of a single fee you never hear from again.</p>'},
        {"h2_html": "Warranties, lapsed members, and cold quotes <em>come back on schedule</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A termite warranty due to renew, a plan member who drifted off, and a bed bug or termite quote that went quiet are not dead, they are just waiting for a reason to act. A scheduled renewal reminder before a warranty expires, a seasonal nudge to a lapsed member, and a check-in on an open quote bring that work back around automatically instead of falling out of your memory. It runs against the same database as your CRM, so nothing here duplicates a customer or a note, and every automated touch is logged where you can see it.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A plan member who never has to <em>remember their next service</em>",
        "body_html": "A homeowner is on your quarterly protection plan. As their next service comes due, the automation sends a rebooking notice with a link to confirm the time, then a prep reminder the day before telling them to move the patio furniture and keep the dog inside, and an on-my-way text when your tech leaves the stop before them. The visit happens without a single phone call from your office, the treatment works because the yard was ready, and the plan renews on the strength of actually getting used. You never sat down to schedule any of it. Illustrative example, not a client."},
    "faqs": [
        ("What messages does it actually send?",
         "The routine ones around a job: the rebooking notice for a recurring plan, an appointment confirmation, a prep reminder with what to do before you arrive, an on-my-way text when the tech heads out, and a follow-up with a review request after the work is done. You approve the wording so it all sounds like you."),
        ("Can it rebook my recurring plan visits automatically?",
         "Yes. It tracks each plan's cadence and sends the member a rebooking notice when their next service is due, with a link to confirm or pick a time, so the recurring visits fill back in without anyone in the office working a list."),
        ("Can it send the prep instructions customers need before a treatment?",
         "Yes. A prep reminder goes out before the visit with exactly what the customer needs to do, clear areas, secure pets and kids, or run through bed bug prep, so the tech is not driving to a house that is not ready and the treatment actually works."),
        ("Will it handle warranties, lapsed members, and cold quotes?",
         "Yes. It can send a renewal reminder before a termite warranty expires, a seasonal nudge to a member who drifted off, and a check-in on an open quote, all on a schedule you set and all logged against the customer in your CRM."),
        ("How long does setup take?",
         "Setup is included with no separate fee. We build the rebooking, prep, on-my-way, and follow-up sequences around how you already run your routes, so it is working within days. Start with a free audit and we will show you what is currently slipping between your calls, your trucks, and your plans.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pest control companies"),
        ("solution-automation.html", "How the automation and workflow system works"),
        ("crm-for-pest-control-companies.html", "The database every workflow runs against"),
        ("online-booking-for-pest-control-companies.html", "How the visits these reminders drive get booked"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Never let a plan visit or a quote <em>go quiet</em>",
    "cta_sub": "Get a free audit of what is currently slipping between your routes, your plans, and your follow-ups, whether you work with us or not. No credit card, never a call center.",
},
]
