"""Per-page content specs for the SEO corpus (plan §5), dentists batch. Same contract as
scripts/corpus_specs.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, dentist-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber content reworded.

Medical & Dental hub. Four service angles are here in one file (the ai-receptionist dict
carries "demo": True). Each example body ends with the literal "Illustrative example, not a
client." per the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ============================ AI Receptionist for Dentists ============================
{
    "slug": "ai-receptionist-for-dentists", "demo": True,
    "trade_slug": "dentists", "trade_plural": "dentists",
    "hub_name": "Medical & Dental", "hub_slug": "industry-medical-dental.html",
    "breadcrumb_leaf": "AI Receptionist for Dentists",
    "title": "AI Receptionist for Dentists | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Dentists",
    "meta_desc": "A dental answering service that answers every new-patient call, handles insurance and scheduling questions, and books it while your front desk is chairside.",
    "service_schema_name": "AI Receptionist for Dentists",
    "eyebrow": "For Dentists",
    "h1_html": "AI Receptionist <em>for Dentists</em>",
    "answer_block": "A dental answering service built for dentists answers every new-patient call the moment it rings, days, nights, and weekends, handles the insurance and scheduling questions that tie up your front desk, and books the appointment on your calendar while your team is chairside. You keep your number, and every patient belongs to you.",
    "sections": [
        {"h2_html": "The call your front desk misses is the new patient who <em>books somewhere else</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A new patient calling for the first time almost never leaves a voicemail. If the line is busy or rolls over, they scroll down and call the next practice, and the one after that, until a real voice picks up and gets them scheduled. Your front desk is not ignoring them. They are checking a patient out, on hold with an insurer verifying benefits, or turning a room over, and the phone rings through to voicemail while they are a few feet away with their hands full. The call that got missed was not a wrong number. It was a new patient, and a new patient is worth years of cleanings, fillings, the occasional crown, and the friends and family they refer once they trust you.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A dental answering service answers on the first ring, no matter what the front desk is in the middle of. It greets the caller warmly, answers the questions that come up on almost every new-patient call, and gets them onto the schedule while they are still on the line. The new patient is booked instead of lost to the practice down the road that happened to pick up.</p>'},
        {"h2_html": "Built around the calls a <em>dental front desk</em> actually fields",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Not every call is an emergency, but the phone at a dental office almost never stops. People call to ask whether you take their insurance, to move an appointment, to start as a new patient, or because a filling fell out at dinner and they want to be seen tomorrow. Every one of those is a real person deciding whether your practice is easy to deal with, and a voicemail box cannot answer a single question or book a single visit.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers days, evenings, and weekends, so the new mover searching on a Sunday and the patient with a broken tooth on a holiday reach a real answer instead of a recording.</li><li>Handles the routine questions that tie up the front desk: your hours, where you are, whether you take their insurance, and what a first visit looks like.</li><li>Collects new-patient details and books the appointment straight onto your calendar, so your team is not re-keying it or playing phone tag later.</li><li>Tells an existing patient with a lost crown or real pain apart from a general question, and flags the urgent ones to your team the moment they come in.</li></ul>'},
        {"h2_html": "It handles patient details the way a <em>dental office has to</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A dental practice cannot treat phone conversations casually, because the moment a caller starts describing what is wrong they are sharing health information. The answering service is set up with that in mind. It collects only what it needs to book the visit, keeps that information inside your systems instead of scattering it, and is built to handle patient details with the care a medical or dental office is held to. Your team decides what it asks, what it stores, and what it repeats back, so a first-time caller gets the same discretion on the phone that they would get in your chair. Nobody is left describing their symptoms to a voicemail that anyone might play back later.</p>'},
        {"h2_html": "You own the number, the patients, and the <em>schedule it fills</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing office number, or a new one registered to your practice, not to us. Every caller, every new-patient record, and every appointment it books is yours, exportable any time, so the patient list you are building stays an asset you own instead of something you rent back month to month. There is no long contract holding your data hostage. The answering service is one piece of the Top Shelf platform, so a call it answers lands in the same CRM that sends the reminders and recall notices, and the new patient it books today is the one your system keeps bringing back for years.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Saturday toothache, on the schedule before <em>Monday</em>",
        "body_html": 'It is Saturday afternoon and a man three towns over cracks a tooth on a popcorn kernel. He searches for a dentist, calls the first two he finds, and both ring to a weekend voicemail. Yours answers, asks a few calm questions, sees he is in real pain, and books him first thing Monday while flagging it to your team as urgent. He stops calling around because someone finally helped him. You open the office Monday to a new patient already on the schedule, with his name, his insurance, and the problem noted, instead of hearing he found a dentist who picked up. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my current office number?",
         'Yes. It can answer on the number your patients already call, or set up a new one registered to your practice. Either way the number and every call that comes through it belong to you and stay with you if you ever leave.'),
        ("Can it answer insurance and scheduling questions?",
         'Yes, those are the calls it handles best. It can tell people your hours, where you are, whether you accept their plan, and what a first visit involves, and it books or reschedules right on your calendar. You decide exactly what it is allowed to say about coverage.'),
        ("What about a patient who is actually in pain?",
         'It tells an urgent call apart from a routine one. Someone with real pain, a knocked-out tooth, or serious swelling gets booked into your soonest opening and flagged to your team at once, while a general question is handled without pulling anyone away from a chair.'),
        ("Is patient information handled carefully?",
         'Yes. It is built to treat what a caller shares with the discretion a dental office is held to, collecting only what it needs to book the visit and keeping it inside your systems. You control what it asks and what it stores.'),
        ("How fast can it be answering?",
         'Setup is included with no separate onboarding fee. We configure your questions, your insurance answers, and your scheduling rules for you, so it is picking up in days, not weeks. Start with a free audit and we will show you how many calls your front desk is missing right now.')],
    "related": [
        ("industry-medical-dental.html", "Everything Top Shelf does for dentists"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-dentists.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop sending new patients to <em>voicemail</em>",
    "cta_sub": "Get a free audit that finds the gap in your new-patient calls: how many roll to voicemail and book elsewhere while your front desk is chairside, whether you work with us or not. No credit card, never a call center.",
},
# ================================ CRM for Dentists ================================
{
    "slug": "crm-for-dentists",
    "trade_slug": "dentists", "trade_plural": "dentists",
    "hub_name": "Medical & Dental", "hub_slug": "industry-medical-dental.html",
    "breadcrumb_leaf": "CRM for Dentists",
    "title": "CRM for Dentists | Top Shelf Business Solutions",
    "og_title": "CRM for Dentists",
    "meta_desc": "A CRM for dentists brings back patients overdue for a cleaning and the treatment they accepted but never booked, so your patient list keeps filling the chair.",
    "service_schema_name": "CRM for Dentists",
    "eyebrow": "For Dentists",
    "h1_html": "CRM <em>for Dentists</em>",
    "answer_block": "A CRM for dentists keeps every patient, lead, and unscheduled treatment plan in one place and reaches out for you, so the family overdue for a cleaning and the patient who accepted a crown but never booked it both come back instead of drifting to another office. Your patient list quietly becomes your schedule.",
    "sections": [
        {"h2_html": "The treatment a patient already <em>said yes to</em> is the production you are losing",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Most practices are not short on demand. They are short on follow-up. A patient sits in the chair, hears they need a crown or an implant or that this is the year to finally straighten things out, and they say yes in the room. Then they want to check with a spouse, wait until January when their benefits reset, or just think it over, and they walk out with the treatment unscheduled. Between hygiene checks and a full book, nobody circles back, and a case that was already accepted quietly ages out. It was never a no. It just needed one warm reminder a week or two later, which is exactly the thing a busy front desk never has time for.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every unscheduled treatment plan in front of you and follows up on a schedule you set, with messages that go out on time whether or not anyone remembers. The patient who meant to book the crown hears from you again while it is still on their mind, and the production you already earned in the chair actually makes it onto the schedule.</p>'},
        {"h2_html": "Recall is the <em>goldmine</em> most practices leave sitting",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">The patients you have already treated are the cheapest, easiest chair to fill. They know you, they trust the office, and their next cleaning, filling, or crown is yours if you stay in touch. But a practice with thousands of patients cannot personally remember who is due in March and who fell off the schedule two years ago, so a huge amount of recurring hygiene production quietly slips to whichever office a lapsed patient stumbles onto when they finally book again.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every patient, their history, their last visit, and what they are due for next lives in one place instead of scattered across your practice software and whatever the front desk happens to remember.</li><li>Recall and recare reminders go out on schedule, the six-month cleaning, the hygiene visit a patient keeps putting off, the follow-up a treatment needs, so the chair fills without anyone tracking dates by hand.</li><li>You can see exactly who has lapsed and reach the right patient with the right message at the right time, instead of hoping they remember you first.</li></ul>'},
        {"h2_html": "The patient who <em>drifted away</em> is still yours to bring back",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A patient who has not been in for two years has usually not fired you. Life got busy, their insurance changed, they moved across town, or they simply forgot to rebook after one canceled appointment. A light, steady touch, a friendly note that they are overdue, a reminder that their benefits are there to use, a quick check that a past crown or filling is still holding up, is often all it takes to bring them back through the door. It costs almost nothing next to chasing brand-new patients with ads, and it turns a name sitting dormant in your system into a booked hygiene visit and, often, the treatment that gets found once they are back in the chair.</p>'},
        {"h2_html": "You own the patient list, and it works with the <em>rest of the office</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every patient and every note is yours and exportable any time, handled with the discretion a dental office is held to, not locked away inside software you only rent. The CRM is one piece of the Top Shelf platform. It connects to the answering service, so a new patient it books lands in your database ready for recall, and to online booking, so a scheduled visit is logged against the right record with the full history already attached. The list you have spent years building finally works for you instead of just sitting there recording who came in.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The crown that finally <em>gets scheduled</em>",
        "body_html": 'A patient comes in for a cleaning in October, and the exam turns up a cracked molar that needs a crown. She says yes but wants to wait for January when her benefits reset, and she leaves without booking. Normally that is the last anyone thinks of it. Instead the CRM holds the plan and sends her a friendly reminder in early January that her benefits are fresh and the tooth is still waiting, written to sound like the office she already trusts. She books that week, before the crack turns into a bigger problem or a different dentist. Nobody at the front desk had to remember. Illustrative example, not a client.'},
    "faqs": [
        ("Does it work with my practice management software?",
         'It sits alongside it as your follow-up and outreach layer. Your patients, their history, and what they are due for come in and stay yours and exportable, so the list you already have starts actively bringing people back instead of just recording who came in.'),
        ("Will it really follow up on unscheduled treatment?",
         'Yes, on the schedule you approve. A case a patient accepted but did not book gets a warm reminder a week or two later, and another when their benefits reset, all sent for you. You can jump in and message any patient directly whenever you want.'),
        ("Can it handle recall and recare reminders?",
         'Yes. You set the cadence, the six-month cleaning, an overdue hygiene visit, the recare a treatment needs, and the reminders go out automatically so the chair fills without your team working a spreadsheet of due dates.'),
        ("Is patient data kept private?",
         'Yes. Patient information is handled with the care a dental office is held to and stays inside your systems, and it is always yours to export. You control what the CRM stores and what each message says.'),
        ("How long until it is set up?",
         'Setup is included with no separate onboarding fee. We bring in your patients, build your recall and treatment-follow-up sequences, and connect it to your phones and calendar, so it is working in days. Start with a free audit and we will show you where production is slipping today.')],
    "related": [
        ("industry-medical-dental.html", "Everything Top Shelf does for dentists"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-dentists.html", "The AI receptionist that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting recall and treatment <em>go cold</em>",
    "cta_sub": "Get a free audit that finds the gap in your recall and unscheduled treatment: how many patients and accepted cases are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# =========================== Marketing for Dentists ===========================
{
    "slug": "marketing-for-dentists",
    "trade_slug": "dentists", "trade_plural": "dentists",
    "hub_name": "Medical & Dental", "hub_slug": "industry-medical-dental.html",
    "breadcrumb_leaf": "Marketing for Dentists",
    "title": "Marketing for Dentists | Top Shelf Business Solutions",
    "og_title": "Marketing for Dentists",
    "meta_desc": "Dental marketing that keeps your Google profile active and your reviews fresh, so the new patient searching for a dentist nearby finds you first and books.",
    "service_schema_name": "Marketing for Dentists",
    "eyebrow": "For Dentists",
    "h1_html": "Marketing <em>for Dentists</em>",
    "answer_block": "Dental marketing keeps your practice visible where new patients actually look, your Google Business Profile, the map, and your reviews, so the person searching for a dentist nearby finds an active, well-reviewed office and picks you instead of the practice that let its profile go stale. It is how new patients find you before they ever call.",
    "sections": [
        {"h2_html": "A new patient picks the dentist they can <em>find and trust</em> first",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone needs a dentist, whether they just moved, their old one retired, or a tooth started hurting, they do not ask around for weeks. They search for a dentist near them, glance at the map, and look at who has the most reviews and the highest ratings close by. They are about to let a stranger work inside their mouth, so those stars and that recent activity are the fastest trust they can get before they ever call. A practice with a thin, untouched profile quietly loses those searches to the office with a fuller one, and you never see the patient who scrolled right past you.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The care you deliver in the chair is probably excellent. The problem is that a great practice with a neglected online presence looks, to a stranger searching at 9pm, about the same as a mediocre one. Marketing closes that distance so the reputation you have actually earned is the one a new patient sees.</p>'},
        {"h2_html": "Your Google Business Profile is the <em>front door</em> now",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When a new patient searches for a dentist near them, the map with its three local listings sits at the top, above the websites and above the ads. A profile that has not been touched in months, with old hours, no recent photos, and stale reviews, looks abandoned next to an office that keeps it current. Keeping yours active, complete, and honest, real photos of the office and the team, accurate hours, the insurance plans you take, a steady stream of recent reviews, is a quiet advertisement running in the exact spot people look when they are ready to book. Wrong hours or a missing phone number does more than look sloppy. It quietly sends a ready-to-book patient to an office whose information they can actually trust. It is the cheapest visibility a practice can own, and most leave it sitting untouched.</p>'},
        {"h2_html": "Be the practice patients find in the <em>town you actually serve</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A dental patient wants an office they can get to easily, close to home, close to work, easy to reach on the way to school, so the patients worth reaching live in a fairly tight radius around your practice. Marketing to a whole metro is expensive and brings calls from people who will never actually drive to you. Focusing your profile, your reviews, and your local content on the neighborhoods you truly serve is what puts you in the map for the searches that turn into booked chairs. The local map rewards an office that is both close to the searcher and clearly relevant to what they typed, which is something an area-focused profile earns and a generic citywide push never does. And because reviews carry so much weight in that decision, steadily earning fresh ones from happy patients is the single strongest signal you can send a stranger comparing offices at midnight.</p>'},
        {"h2_html": "Time your visibility to when patients <em>actually book</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Dental demand has a rhythm. Insurance benefits expire at the end of the year and patients scramble to use them before they vanish, new-year resolutions send people looking for a dentist in January, and back-to-school season brings families booking checkups all at once. Being visible right before each of those waves beats scrambling once they hit. A steady local presence, timely posts, fresh reviews, current information, keeps you top of mind for the new patient deciding now. This is the public-facing side of the practice, aimed at people who are not your patients yet. The private follow-up to the patients already in your system, recall and reactivation, is the CRM, and the two work best together.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "December benefits, and you are <em>the office they can see</em>",
        "body_html": 'It is early December and a family realizes their dental benefits reset at the end of the month, so they finally search for a dentist to use them before they disappear. Because your Google profile has been kept active all year, with recent photos, accurate hours, the plans you accept listed, and a steady flow of reviews, you sit near the top of the map when they look. They see an office that is clearly open, busy, and trusted, and they call you instead of the practice two listings down with three old reviews. The office that let its profile go quiet never comes up. Illustrative example, not a client.'},
    "faqs": [
        ("Do you keep my Google Business Profile updated for me?",
         'Yes. We keep it active with photos of the office and team, posts, and accurate information on a regular schedule, and we keep your hours, services, and the insurance plans you accept current, so it looks alive whenever someone searches for a dentist nearby.'),
        ("What does focusing on my area actually mean?",
         'It means building your profile, reviews, and content around the neighborhoods your patients realistically come from, instead of spreading a budget across a whole metro. That is what gets you into the local map where new patients are choosing an office.'),
        ("How is this different from the CRM?",
         'The CRM follows up privately with patients already in your system, recall and reactivation. Marketing is the public-facing side, your Google profile, reviews, and local visibility, aimed at new patients who need to find and trust you before they have ever been in.'),
        ("Can you help me get ahead of seasonal demand?",
         'Yes. We time your visibility to the waves that matter for a dental office, end-of-year benefits, the January new-patient rush, back-to-school checkups, so you are already visible before people start searching instead of catching up after.'),
        ("How long before it starts working?",
         'A neglected profile can climb in the local map within weeks once it is active and complete, and it compounds as reviews and content build. Setup is included, and a free audit will show you exactly how visible your practice looks to someone searching nearby today.')],
    "related": [
        ("industry-medical-dental.html", "Everything Top Shelf does for dentists"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-dentists.html", "The website that captures the demand this drives"),
        ("crm-for-dentists.html", "The CRM that turns new patients into recurring visits"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the dentist they <em>can already see</em>",
    "cta_sub": "Get a free audit that finds the gap in your local visibility and reviews: how easily a new patient nearby can actually find and trust you right now, whether you work with us or not. No credit card, never a call center.",
},
# ========================= Websites & SEO for Dentists =========================
{
    "slug": "websites-seo-for-dentists",
    "trade_slug": "dentists", "trade_plural": "dentists",
    "hub_name": "Medical & Dental", "hub_slug": "industry-medical-dental.html",
    "breadcrumb_leaf": "Websites & SEO for Dentists",
    "title": "Websites & SEO for Dentists | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Dentists",
    "meta_desc": "A dental website built for SEO ranks for dentist near me and the services you offer, and turns a new patient in pain into a booking instead of a directory.",
    "service_schema_name": "Websites & SEO for Dentists",
    "eyebrow": "For Dentists",
    "h1_html": "Websites &amp; SEO <em>for Dentists</em>",
    "answer_block": "A dental website built for SEO ranks for what a new patient types when they need care, dentist near me, emergency dentist, and the treatments you offer, shows up on the map for the towns you cover, and captures the patient the moment they land, so the booking is yours, not a directory's.",
    "sections": [
        {"h2_html": "A patient in pain judges your practice by your <em>website in seconds</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A person with a throbbing tooth at 10pm is on their phone, searching for a dentist and opening the first few sites they find. In a few seconds they decide whether each practice looks like somewhere they would trust with their mouth. A site that loads slowly, looks like it was built a decade ago, or does not work right on a phone tells them the office might be just as behind, and they back out and try the next one. A clean, fast, modern site does the opposite: it signals a practice that has its act together, which is exactly what someone about to sit in your chair wants to believe.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">The site does not have to be fancy. It has to load fast, put your phone number, location, and the treatments you offer right in front of a visitor, and make calling or booking a single tap. A beautiful site that hides the phone number wastes the patient it just earned. Someone in pain should never have to hunt for how to reach you.</p>'},
        {"h2_html": "Rank for what a patient <em>actually searches</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national booking directory this year for the broadest terms, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you serve, and for the exact searches new patients make: dentist near me, emergency dentist, and the treatments you actually want more of, implants, Invisalign, teeth whitening, root canals, same-day crowns. Pages built around the services you provide and the areas you cover are what search engines, and a patient deciding where to go, reward with the click. A page that explains, in plain language, what a root canal or a first implant visit is actually like also answers the quiet questions a nervous patient is already typing, which is the kind of content that earns both the ranking and the trust. That is where a local practice wins the searches a faceless directory has no reason to answer well.</p>'},
        {"h2_html": "Stop letting a directory <em>rent you your own patients</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for a dentist in your town and the top of the page is often a booking middleman or a directory, not a local office. Those sites publish thousands of pages and have years of authority behind them, so a new patient lands there first, and that lead gets handed out, sometimes to several practices at once, sometimes back to you for a fee that comes straight out of the value of a patient you should have gotten for free. A website that ranks on its own keeps the patient yours from the first click. There is no per-lead charge skimming the lifetime of every new patient, and no middleman standing between you and the person searching for exactly what you do.</p>'},
        {"h2_html": "The patients it earns are <em>yours to keep</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a pay-per-lead service disappears the day you stop paying, and the patient was never really yours. A website you own keeps ranking, keeps earning bookings, and keeps compounding in value for as long as it exists, registered to your practice, not to a platform that can drop you or raise the rent. It plugs into the same CRM that follows up on every new-patient lead it captures and puts them into recall, and the answering service that picks up the calls it drives, so a patient the site earns at midnight is booked, followed up, and brought back for years instead of slipping away before morning.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A late-night toothache finds <em>you</em>, not a directory",
        "body_html": 'A woman new to town wakes at midnight with a molar that will not stop aching and searches emergency dentist near me on her phone. Instead of a national directory that would sell her details to a handful of offices, she finds your site ranking for that search, loading fast, with an emergency page and a tap-to-call button right at the top. She calls, your answering service books her for the morning, and she is a patient before she has even met you. You paid nothing per lead, and no middleman ever touched the booking. Illustrative example, not a client.'},
    "faqs": [
        ("Will my site actually outrank the big directories?",
         'Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the treatment and emergency searches a national directory has no reason to target well, which is exactly where a local practice can win.'),
        ("How is this different from paying for patient leads?",
         'A pay-per-lead service rents you a patient it may also sell to other offices, and it stops the day you stop paying. A website you own captures patients who are yours alone and keeps working long after it is built, with no per-lead fee skimming every new patient.'),
        ("What should a dental website actually have?",
         'The essentials a new patient needs, fast: your treatments, your location and hours, the insurance you take, real photos, easy tap-to-call and online booking, and pages for the services you want more of. It has to load quickly and work perfectly on a phone, since that is where most patients find you.'),
        ("Do I need a page for every treatment I offer?",
         'You start with the ones that matter most, the emergencies and the treatments you want to grow, then expand. A focused set of strong service and location pages ranks better than one thin page trying to cover everything at once.'),
        ("How long until it starts ranking?",
         'Local, specific searches can start moving within weeks, while broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today.')],
    "related": [
        ("industry-medical-dental.html", "Everything Top Shelf does for dentists"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-dentists.html", "Staying visible in your area beyond your site"),
        ("crm-for-dentists.html", "Where every new-patient lead lands and gets followed up"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit that finds the gap between your website and the practices taking your new-patient searches, whether you work with us or not. No credit card, never a call center.",
},
]
