"""Per-page content specs for the SEO corpus (plan §5), pool service batch. Same contract as
scripts/specs_plumbers.py: generate_corpus.py imports SPECS and owns the mechanics (shell,
schema, events, interlinks, keyword-first title/slug/H1/first-sentence); each dict below owns
the UNIQUE, hand-written, pool-service-specific substance that clears the uniqueness gate. Never
templated find-and-replace, never the plumber content reworded.

Home Services hub. Four service angles are here in one file (the ai-receptionist dict carries
"demo": True). Each example body ends with the literal "Illustrative example, not a client." per
the honesty rule; if the generator also appends that line, dedupe there.
"""

SPECS = [
# ========================= AI Receptionist for Pool Service =========================
{
    "slug": "ai-receptionist-for-pool-service", "demo": True,
    "trade_slug": "pool_service", "trade_plural": "pool service companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "AI Receptionist for Pool Service",
    "title": "AI Receptionist for Pool Service | Top Shelf Business Solutions",
    "og_title": "AI Receptionist for Pool Service",
    "meta_desc": "A pool service answering service answers every new-customer call, sorts a green-to-clean from weekly cleaning, and books it while your tech is at a pool.",
    "service_schema_name": "AI Receptionist for Pool Service",
    "eyebrow": "For Pool Service",
    "h1_html": "AI Receptionist <em>for Pool Service</em>",
    "answer_block": "A pool service answering service that never sleeps answers every new-customer call the moment it rings, tells a routine weekly-cleaning inquiry from a green-to-clean emergency or a failed pump, and books the job while your tech is elbow-deep in an equipment pad. You keep your own number, and every call belongs to you.",
    "sections": [
        {"h2_html": "The call you miss is a season <em>signed by someone else</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner shopping for weekly pool service is choosing a company for the whole swim season, and usually years after that, because once a reliable tech is on the route people rarely switch. That first call is worth far more than a single visit. But the person best able to answer it, the owner or the tech, is out on a route with wet hands, testing water, or down in an equipment pad with no free hand for the phone. So the call rolls to voicemail, and a homeowner who wants their pool handled today simply calls the next company on the list until one picks up.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A pool service answering service answers on the first ring, day or night, finds out whether they want recurring service, a one-time cleanup, or a repair, gets the address and the pool details, and books the visit or the quote on the spot. The recurring customer you would have lost to voicemail is captured instead of signed up by the company that happened to answer.</p>'},
        {"h2_html": "Built around how pool service calls <em>actually come in</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Your phone does not ring on a schedule. A pump fails on a Saturday, a pool turns green after a storm, a homeowner decides it is finally time to book a spring opening, and the calls that turn into recurring contracts often come in while you are already standing at another pool on your route. A voicemail box cannot tell a signed route customer with a real problem from a first-time caller shopping for weekly service, and a generic call center reading a script does not know a cartridge filter from a green-to-clean, or which one can wait until tomorrow.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Answers 24/7, including the weekend pump failure and the spring-opening rush when every pool owner calls in the same few weeks.</li><li>Triages the way you would: recurring weekly service, a one-time or green-to-clean cleanup, equipment repair, or a full opening or closing, and how soon someone needs to be there.</li><li>Gets the address, the pool type, and the details, books routine work straight onto your calendar, and texts you the jobs that need a same-day look right away.</li><li>Treats a customer already on your route differently from a stranger, so the people paying you every month never hit a voicemail.</li></ul>'},
        {"h2_html": "The math is <em>one recurring customer</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You do not need to catch many calls for this to pay for itself. A single weekly-service customer you would have lost to voicemail is worth their monthly rate across the whole season, and often for years, because a good pool company keeps a customer for as long as they own the pool. Everything it captures after that first save is on top. The point is to stop handing your steadiest, most valuable customers to whoever picked up faster.</p>'},
        {"h2_html": "You own the number, the calls, and the <em>customer list</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">This runs on your existing business number, or a new one registered in your name, not ours. Every caller, every address, and every pool detail is yours and exportable any time, so the customer list that is the real value of a pool route stays an asset you keep instead of something you rent back month to month. There is no long contract holding your data hostage. The answering service is one piece of the Top Shelf platform, and it hands every call it captures to the same CRM that manages your routes and follows up, so a repair quote or a new signup never slips through.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A Saturday pump failure, booked while you <em>work another pool</em>",
        "body_html": "It is a hot Saturday afternoon and a homeowner's pump quits, so the pool starts clouding over with a party planned for Sunday. They search for a pool company and call the first three. Two go to voicemail, because those owners are out on their own routes. Yours answers, asks what the pump is doing, confirms the water is still circulating enough to hold overnight, gets the address, and books a same-day visit while flagging it to your phone. You finish the pool you are standing at and drive to a job already on your calendar, with the address, the equipment, and the customer's number attached, instead of hearing about it after they hired someone else. Illustrative example, not a client."},
    "faqs": [
        ("Can it handle the spring opening rush when the phone never stops?",
         "Yes, that is exactly when it earns its keep. During opening season it answers every call at once, no busy signal and no voicemail, books the openings and weekly-service signups onto your calendar, and flags anything urgent, so the surge that used to overwhelm one phone turns into a full schedule instead of missed calls."),
        ("Will it know a real problem from a routine call?",
         "Yes. It asks what you would ask: is the pump running, is the water green or just a little cloudy, is this recurring service, a repair, or an opening, and how soon someone needs to be there. A cloudy pool that can wait books as routine, while a dead pump before a weekend gets flagged to you at once. You set what counts as same-day."),
        ("Does it actually book the job, or just take a message?",
         "It books. Recurring service, cleanings, and openings land straight on your calendar based on your availability, and you get a text with the details right away. For anything that needs a same-day look it can grab your first open slot and alert you, so you decide whether to reroute a tech today."),
        ("Will it sound like a robot to someone whose pool just turned green?",
         "It answers naturally and calmly, and it is upfront rather than pretending to be a person. A homeowner staring at a green pool mainly needs to know a real pool company is on it, and a steady voice that books the visit beats a voicemail box. You can hear it handle a live call before you decide."),
        ("How fast can it be running?",
         "Setup is included with no separate onboarding fee. We configure your triage questions, your calendar, and your same-day rules for you, so it is answering in days, not weeks. Start with a free audit and we will show you what your current setup is missing.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pool service companies"),
        ("solution-ai-phone.html", "How the AI phone and chat system works"),
        ("crm-for-pool-service.html", "The CRM that follows up on every call you capture"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop losing new customers to <em>voicemail</em>",
    "cta_sub": "Get a free audit of how many new-customer calls and after-hours jobs your current setup is missing, whether you work with us or not. No credit card, never a call center.",
},
# =============================== CRM for Pool Service ===============================
{
    "slug": "crm-for-pool-service",
    "trade_slug": "pool_service", "trade_plural": "pool service companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "CRM for Pool Service",
    "title": "CRM for Pool Service | Top Shelf Business Solutions",
    "og_title": "CRM for Pool Service",
    "meta_desc": "A CRM for pool service manages recurring routes, chases every repair quote, and wins back lapsed or seasonal customers, so earned revenue keeps coming back.",
    "service_schema_name": "CRM for Pool Service",
    "eyebrow": "For Pool Service",
    "h1_html": "CRM <em>for Pool Service</em>",
    "answer_block": "A CRM for pool service keeps every route customer, repair quote, and past client in one place and works them for you, so your weekly recurring base stays put, the equipment quotes a homeowner is sitting on close, and the customer who dropped off last winter comes back this spring instead of calling someone else.",
    "sections": [
        {"h2_html": "The repair quotes you already sent are <em>money sitting still</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Pool companies do not usually have a lead problem, they have a follow-up problem. You are at a pool, you spot a failing heater or a cracked filter, and you text over a quote for the fix. The homeowner says they need to think about it, then you move on to the next stop and never circle back. They sit on it, or collect another price, and a job you were standing on top of quietly evaporates. The quote was never dead. It needed one more nudge a few days later, and that is the thing there is never time for between stops on a full route.</p><p style="color:var(--ink-2);line-height:1.85;max-width:64ch;margin-top:1rem">A CRM keeps every open quote in front of you and follows up on a schedule you set, with texts and emails that go out on time whether or not you remember. The homeowner deciding on a new pump hears from you again while the reminder does the work, and the repair comes back to you instead of the company that simply followed up first.</p>'},
        {"h2_html": "Your recurring routes are the <em>whole business</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A weekly-service customer is not one job, they are revenue every month for as long as they own the pool, and the value of a pool company is basically the size and stickiness of its route book. That base slips away quietly: a card on file expires and a payment fails, a customer goes cold and nobody notices, a seasonal client never gets asked to come back. None of it lands as a dramatic loss, it just disappears one address at a time until the route is thinner than it was.</p><ul style="color:var(--ink-2);line-height:2;max-width:64ch;margin-top:.8rem"><li>Every route customer, address, pool profile, service history, and note lives in one place instead of a clipboard, a spreadsheet, and your memory.</li><li>You can see at a glance who is due to renew, whose payment failed, and who has gone quiet, and reach the right customer before they drift.</li><li>Recurring billing and service reminders run on a schedule, so a renewal or a seasonal restart gets prompted automatically instead of forgotten.</li></ul>'},
        {"h2_html": "The customer who dropped off is <em>still yours to win back</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner who cancelled over the winter, or who only runs the pool part of the year, has not left for good. They just stopped, and never got a reason to start again. A short, well-timed nudge before opening season, a note that it is time to think about getting the pool ready, a reminder to a customer you have not serviced in a while, brings that revenue back around. It costs almost nothing, and reactivating someone you already served is far cheaper than winning a stranger. A pool company that works its lapsed and seasonal list every spring is sitting on a goldmine most never bother to touch.</p>'},
        {"h2_html": "You own the list, and it works with the <em>rest of the system</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every customer and every pool profile is yours and exportable any time, not locked inside software you rent. The CRM is one piece of the Top Shelf platform and connects to the answering service, so a new-customer call it captures lands in your database and gets followed up on automatically, and to online booking, so a scheduled opening or repair is logged against the right customer with their full pool history already attached. Nothing you have earned goes quiet.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The heater quote that <em>closes itself</em>",
        "body_html": "You are at a routine weekly stop in March and you notice the pool heater is on its last season, so you text the homeowner a quote to replace it before opening weather hits. They tell you they want to think about it, and normally that is the last you hear of it. Instead the CRM sends a friendly check-in two days later and a short note the next week, both written to sound like you. By the time the first warm weekend arrives and they actually want the pool ready, yours is the only quote still in front of them, and they book the replacement without shopping around. You never sat down to chase it. Illustrative example, not a client."},
    "faqs": [
        ("Does it import my existing route and customers?",
         "Yes. Your current route customers, past clients, pool profiles, and service history come in and live in one place, and everything stays yours and exportable. The point is to make the customer list you already built actually work for you instead of sitting on a clipboard."),
        ("Will it really chase repair quotes on its own?",
         "Yes, on the schedule you approve. An open quote for a pump, a heater, or a green-to-clean gets a check-in a few days later and another after that, all sent for you, so a homeowner sitting on the decision keeps hearing from you. You can jump in and message anyone directly any time."),
        ("Can it help me win back seasonal and lapsed customers?",
         "Yes. You set the timing, a nudge before opening season, a note to a customer who has gone quiet, a reminder to a part-year pool owner, and the CRM sends it automatically, so revenue you already earned once comes back around instead of drifting off to another company."),
        ("How is this different from the answering service?",
         "The answering service is the front door, it catches new calls the moment they ring. The CRM works the customers you already have: your recurring routes, the quotes you already sent, and the people who lapsed. One captures new demand, the other makes sure nothing you already earned slips away."),
        ("How long until it is set up?",
         "Setup is included with no separate onboarding fee. We bring in your customers and routes, build your quote-follow-up and reactivation sequences, and connect it to your calls and calendar, so it is working in days. Start with a free audit and we will show you where revenue is slipping today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pool service companies"),
        ("solution-crm.html", "How the CRM and follow-up system works"),
        ("ai-receptionist-for-pool-service.html", "The answering service that feeds it every call"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Stop letting quotes and customers <em>go quiet</em>",
    "cta_sub": "Get a free audit of how many of your quotes, renewals, and past customers are going unworked right now, whether you work with us or not. No credit card, never a call center.",
},
# ============================= Marketing for Pool Service =============================
{
    "slug": "marketing-for-pool-service",
    "trade_slug": "pool_service", "trade_plural": "pool service companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Marketing for Pool Service",
    "title": "Marketing for Pool Service | Top Shelf Business Solutions",
    "og_title": "Marketing for Pool Service",
    "meta_desc": "Pool service marketing keeps your Google Business Profile active and first in the map pack, so homeowners pick you when it is time to open or service the pool.",
    "service_schema_name": "Marketing for Pool Service",
    "eyebrow": "For Pool Service",
    "h1_html": "Marketing <em>for Pool Service</em>",
    "answer_block": "Pool service marketing keeps you visible where homeowners actually choose a pool company, your Google Business Profile and the map pack, so when someone nearby needs weekly service, an opening, or a green pool cleaned up, your active, well-reviewed name is the one they trust with their pool and their chemistry.",
    "sections": [
        {"h2_html": "Choosing a pool company is a <em>trust decision</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A homeowner handing over their pool is not buying a one-time fix, they are giving a stranger a key to the backyard every week and trusting them with expensive equipment and the water their family swims in. So they do not pick at random. They look for a company that is clearly active, local, and well-reviewed, and they look in the one place everyone checks first, a quick search for a pool company near them. Being the name that looks established and trusted in that moment is most of the battle, and it is intensely local, because nobody hires a company thirty minutes away to show up every single week.</p>'},
        {"h2_html": "Your Google Business Profile is the <em>storefront</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">When someone searches for pool service near them, the map pack, those three local listings with the star ratings, is the first thing they see, above the websites and above the ads. A profile that has sat untouched for months looks abandoned next to one with recent photos of clean water and equipment work, current hours, and a steady stream of reviews. Keeping it active, complete, and honest is a quiet advertisement running in the exact spot a homeowner looks when they decide who to trust with their pool. Reviews carry the heaviest weight here, because a stranger about to hand over backyard access reads them like a background check.</p>'},
        {"h2_html": "Show up in the <em>towns you actually service</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">A weekly route only works when the stops sit close together, so a customer thirty minutes outside your area is a call you do not even want. Marketing to a whole metro is expensive, forgettable, and brings you the wrong calls. Focusing on the specific towns and neighborhoods you already run, with a profile, photos, and content built around those areas, is what puts you in the map pack where the customers you can actually route are looking. It is a tighter and cheaper target than a citywide spend, and it fills your route with pools you can reach on the same day without wrecking your drive time.</p>'},
        {"h2_html": "Be ready before the <em>spring rush</em>, and stay in front all year",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Pool demand swings hard with the calendar. The phone barely rings in the cold months, then spring arrives and half your area wants the pool opened and a weekly service lined up inside the same few weeks. Being visible right before that wave, instead of scrambling once it hits, is the difference between filling your route for the season and picking up the leftovers. A steady local presence, seasonal posts, real job photos, the occasional tip on keeping water clear, keeps you top of mind through the summer and reminds past customers you are still the ones to call. This is the public-facing side of the business, the private follow-up to people already in your database is the CRM.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "The first warm weekend, and you are <em>already at the top</em>",
        "body_html": "The first real warm weekend of the year hits, and half the neighborhood decides on the same Saturday that it is time to get the pool going. They search for a pool company near them, and because your Google profile has been kept active all winter, with recent photos of clean pools, current hours, and a steady flow of reviews, you sit at the top of the map pack when everyone looks at once. The homeowners lining up weekly service for the season call the names they can see and trust first, and yours is right there. The company that let its profile go quiet over the winter is nowhere on the map. Illustrative example, not a client."},
    "faqs": [
        ("Do you post to my Google Business Profile for me?",
         "Yes. We keep it active with photos of real pool and equipment work, updates, and local content on a regular schedule, and keep your hours, services, and service area accurate, so it looks current whenever a homeowner searches for a pool company near them."),
        ("Why do reviews matter so much for pool service?",
         "Because a homeowner is about to give you weekly access to their backyard and trust you with costly equipment, so they read reviews like a background check. A steady stream of recent, honest reviews on your profile is often what decides who gets the call, and keeping them coming is a core part of the work."),
        ("What does focusing on my service area actually mean?",
         "It means building your profile and content around the specific towns and neighborhoods your route can reach easily, instead of spreading a budget across a whole metro. That is what gets you into the map pack where the local customers you can actually service every week are looking."),
        ("Can you help me get ahead of opening season?",
         "Yes. We time your visibility to the spring rush, when most of a year's new weekly customers get signed in a few short weeks, so you are already in front of homeowners before the wave instead of chasing the leftovers after everyone else filled their routes."),
        ("How long before I see it working?",
         "A neglected profile can climb in the map pack within weeks once it is active and complete, and it compounds from there as reviews and content build. Setup is included, and a free audit will show you what your current online presence looks like to a homeowner searching near you today.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pool service companies"),
        ("solution-marketing.html", "How the marketing and reputation system works"),
        ("websites-seo-for-pool-service.html", "The website that captures the demand this drives"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Be the pool company they <em>can already see</em>",
    "cta_sub": "Get a free audit of how visible you actually are in your service area and on Google right now, whether you work with us or not. No credit card, never a call center.",
},
# =========================== Websites & SEO for Pool Service ===========================
{
    "slug": "websites-seo-for-pool-service",
    "trade_slug": "pool_service", "trade_plural": "pool service companies",
    "hub_name": "Home Services", "hub_slug": "industry-home-services.html",
    "breadcrumb_leaf": "Websites & SEO for Pool Service",
    "title": "Websites & SEO for Pool Service | Top Shelf Business Solutions",
    "og_title": "Websites & SEO for Pool Service",
    "meta_desc": "A pool service website built for SEO ranks for pool service near me and weekly cleaning in your city, then captures the request instead of a lead-seller.",
    "service_schema_name": "Websites & SEO for Pool Service",
    "eyebrow": "For Pool Service",
    "h1_html": "Websites &amp; SEO <em>for Pool Service</em>",
    "answer_block": "A pool service website built for SEO ranks for what a homeowner types when they want their pool handled, pool service near me, weekly pool cleaning, green pool cleanup, and takes the service request the moment they land, so the customer is yours instead of a lead-seller renting your own calls back to you.",
    "sections": [
        {"h2_html": "The lead-sellers are not competing with you, they are <em>renting you back your own calls</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Search for pool service in your town and the top of the page is often a directory or a pay-per-lead app, not the local company that actually shows up every week. Those sites publish thousands of pages and have years of authority behind them, so a homeowner searching lands there first, fills out a form, and that lead gets sold, sometimes to three companies at once, sometimes back to you for a fee out of your own margin. It stings more in pool work than most trades, because the lead they sell is often a recurring customer worth a whole season, handed off for the price of a single click. Your site not ranking is not a vanity problem, it is the reason a customer who should have found you for free gets sold to you instead.</p>'},
        {"h2_html": "Rank for what a homeowner types when they <em>want their pool handled</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">You will not outrank a national directory this year for the broadest term, and you do not need to. You can rank for your own name, for the specific towns and neighborhoods you cover, and for the exact searches a homeowner makes: pool service near me, weekly pool cleaning in your city, green pool cleanup, pool opening, pump and heater repair. Pages built around the services you actually run and the areas you actually route are what search engines, and homeowners ready to hire, reward with the click. A page about green-to-clean work catches the homeowner staring at a swamp, and a page about weekly service catches the one who just wants the whole chore off their plate for good.</p>'},
        {"h2_html": "A homeowner ready to hire should reach you in <em>one tap</em>",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Someone who has just decided they are done skimming their own pool is usually on a phone, and they are not going to read three long paragraphs. The site has to load fast, put a tap-to-call button and your service area in front of them right away, and make requesting weekly service or a repair quote a matter of a few taps. A slow or confusing site sends that ready-to-hire homeowner back to the search results and straight on to the next company. A visitor should never leave without an easy way to reach you, whether they want to call now or send a request for you to follow up on.</p>'},
        {"h2_html": "The customers are <em>yours</em>, permanently",
         "body_html": '<p style="color:var(--ink-2);line-height:1.85;max-width:64ch">Every dollar you put into a pay-per-lead app disappears the day you stop paying, and the customer was never really yours in the first place. A website you own keeps ranking, keeps capturing service requests, and keeps compounding in value for as long as it exists, and it is registered to you, not a platform that can drop you. That matters more in pool service than in most trades, because a customer your own site earns can stay on your route for years, not just for one job. The site plugs into the same CRM that follows up on every request it captures and the answering service that catches the calls it drives, so nothing it earns you slips away.</p>'}],
    "example": {
        "eyebrow": "How it plays out",
        "h2_html": "A green pool finds <em>you</em>, not a directory",
        "body_html": "A homeowner two towns over comes home from vacation to a pool gone green and searches green pool cleanup on their phone. Instead of a national directory that would sell the lead to three companies, they find your site ranking for that town, with a page about green-to-clean work and a tap-to-call button right at the top. They call you directly, you clean it up that week, and because you were the one who rescued it, they sign up for weekly service on the spot. You paid nothing per lead, no middleman ever touched it, and a one-time cleanup turned into a customer for the whole season. Illustrative example, not a client."},
    "faqs": [
        ("Will my site actually outrank the big directories?",
         "Not for the broadest terms overnight. It can realistically rank for your name, your specific towns and neighborhoods, and the pool-specific searches a national directory has no reason to target well, weekly cleaning, green-to-clean, equipment repair, which is exactly where a local pool company can win."),
        ("How is this different from buying leads?",
         "A pay-per-lead app rents you a contact it also sells to your competitors, and it stops the day you stop paying. A website you own captures requests that are yours alone and keeps working long after it is built, with no per-lead fee skimming your margin, and in pool service that captured customer can stay on your route for years."),
        ("Do I need to rank for every town I service?",
         "You rank for the ones that matter most first. We build pages for your core route areas and the highest-intent searches, then expand, rather than spreading thin across a whole metro at once and pulling in calls too far out to service weekly."),
        ("Can the site take service requests, not just show my number?",
         "Yes. It can take a weekly-service signup or a repair request and drop it straight into your CRM to be followed up on, and it pairs with the answering service for the homeowner who would rather call. Either way the request is captured the moment they are ready, not lost to a callback they forget."),
        ("How long until it starts ranking?",
         "Local, specific searches can start moving within weeks, broader terms take longer and compound over months. Setup is included with no separate fee, and a free audit will show you where your current site, or lack of one, stands today and where you are losing customers to lead-sellers.")],
    "related": [
        ("industry-home-services.html", "Everything Top Shelf does for pool service companies"),
        ("solution-websites-seo.html", "How the website and SEO system works"),
        ("marketing-for-pool-service.html", "Staying visible in your service area beyond your site"),
        ("booking.html", "Book a 15-minute call to see it"),
        ("contact.html", "Get your free business audit")],
    "cta_h2_html": "Own the search results for <em>your own town</em>",
    "cta_sub": "Get a free audit of how your website and local search presence compare to the directories and lead-sellers taking your calls, whether you work with us or not. No credit card, never a call center.",
},
]
