#!/usr/bin/env python3
"""Wire the home-services corpus money pages into the industry-home-services.html hub as a
grouped "Deep Dives by Trade" bridge block (plan §6: every corpus page needs >=1 contextual
inbound). Reads the trade spec modules (scripts/specs_*.py for home-services trades), groups
each trade's pages, and inserts/replaces one block before the hub's FAQ. Idempotent.

Run:  python scripts/wire_hub.py
"""
import os, re, sys, io, importlib
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))

HUB = "industry-home-services.html"
TRADE_MODULES = ["specs_plumbers", "specs_hvac", "specs_electricians", "specs_roofers", "specs_garage_door",
                 "specs_landscapers", "specs_painters", "specs_handyman_services",
                 "specs_pest_control_companies", "specs_house_cleaning_companies"]
# short link label per service slug-prefix
SERVICE_LABEL = {
    "ai-receptionist": "AI receptionist", "crm": "CRM & follow-up", "online-booking": "Online booking",
    "review-software": "Review software", "websites-seo": "Websites & SEO", "marketing": "Marketing",
    "automation": "Automation",
}
MARK_START = "<!-- DEEP-DIVES-HS:start (generated by scripts/wire_hub.py) -->"
MARK_END = "<!-- DEEP-DIVES-HS:end -->"

def service_of(slug):
    return slug.split("-for-")[0]

def build_block():
    groups = []
    for mod in TRADE_MODULES:
        try:
            specs = getattr(importlib.import_module(mod), "SPECS", [])
        except Exception:
            continue
        if not specs:
            continue
        trade = specs[0]["trade_plural"]
        # order services consistently
        order = list(SERVICE_LABEL.keys())
        specs_sorted = sorted(specs, key=lambda d: order.index(service_of(d["slug"])) if service_of(d["slug"]) in order else 99)
        items = "\n".join(
            f'          <li><a href="{d["slug"]}.html">{SERVICE_LABEL.get(service_of(d["slug"]), service_of(d["slug"]))}</a></li>'
            for d in specs_sorted)
        groups.append(f'''      <div class="reveal" style="min-width:200px">
        <h3 style="font-family:var(--sans);font-size:.82rem;letter-spacing:.12em;text-transform:uppercase;color:var(--gold);margin-bottom:.7rem">{trade.title()}</h3>
        <ul style="list-style:none;line-height:1.9;font-size:.98rem">
{items}
        </ul>
      </div>''')
    if not groups:
        return ""
    cols = "\n".join(groups)
    return f'''{MARK_START}
<section class="section rule-top">
  <div class="container">
    <div class="section-head">
      <span class="eyebrow reveal">By Trade &amp; Service</span>
      <h2 class="display display-lg reveal" style="margin-top:1.6rem">Deep Dives for <em>Home Services</em></h2>
    </div>
    <div class="reveal" style="display:flex;flex-wrap:wrap;gap:2.4rem 3rem;margin-top:1.6rem">
{cols}
    </div>
  </div>
</section>
{MARK_END}
'''

def main():
    html = open(HUB, encoding="utf-8").read()
    block = build_block()
    if not block:
        print("no trade specs found; nothing to wire"); return
    if MARK_START in html:  # replace existing
        html = re.sub(re.escape(MARK_START) + r".*?" + re.escape(MARK_END) + r"\n?", block, html, flags=re.S)
    else:  # insert before the FAQ section
        m = re.search(r"<!-- =+ FAQ =+ -->", html)
        anchor = m.group() if m else None
        if not anchor:
            print("could not find FAQ anchor in hub; aborting"); return
        html = html.replace(anchor, block + "\n" + anchor, 1)
    open(HUB, "w", encoding="utf-8", newline="").write(html)
    n = html.count('-for-')
    print(f"wired {HUB}: Deep Dives block with links to home-services money pages")

if __name__ == "__main__":
    main()
