#!/usr/bin/env python3
"""Turn the 10 solution-*.html pages into SERVICE pillars (plan §6 grid): add a marker-based,
idempotent "By Trade" directory block to each solution page that has money pages, linking EVERY
`<service-prefix>-for-<trade>.html` money page for that service, grouped by industry umbrella.

Trade pillars link all SERVICES for one trade; service pillars link all TRADES for one service ->
a fully cross-linked grid feeding every money page from two hubs. This ADDS a link block to an
existing page (no new URLs). Reverse wiring already exists: every money page links up to its own
solution page (its in-body "Related" block) and its trade pillar (wire_pillars.py PILLAR-UP block).

Reuses generate_pillars.discover() for the token -> (trade_plural, hub_name) map and
generate_pillars._money_title() for the exact keyword anchor. Idempotent, like wire_hub.py.

Run:  python scripts/wire_service_pillars.py
"""
import os, re, sys, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import generate_pillars as gp  # importing this sets sys.stdout to UTF-8 (via generate_corpus)
esc = gp.esc

# solution page -> (service display name, [money-page prefixes], one-sentence intro)
SERVICE_MAP = {
    "solution-ai-phone.html": ("AI Receptionist", ["ai-receptionist"],
        "Every trade misses calls in its own way. Here is how the AI receptionist answers and books for yours."),
    "solution-crm.html": ("CRM", ["crm"],
        "The follow-up that wins the job looks different in every trade. Here is what the CRM does for yours."),
    "solution-marketing.html": ("Marketing", ["marketing"],
        "What it takes to get found and stay busy changes by trade. Here is the marketing built for yours."),
    "solution-websites-seo.html": ("Websites & SEO", ["websites-seo"],
        "A site earns its keep differently for each trade. Here is what a Top Shelf website does for yours."),
    "solution-reviews.html": ("Review Software", ["review-software"],
        "The right moment to ask for a review is not the same in every trade. Here is how it works for yours."),
    "solution-booking.html": ("Online Booking", ["online-booking"],
        "What should book itself and what needs a call depends on the trade. Here is booking built for yours."),
    "solution-automation.html": ("Automation", ["automation"],
        "The reminders and follow-ups that keep work moving differ by trade. Here is the automation for yours."),
}
# industry umbrella display order
HUB_ORDER = ["Home Services", "Auto", "Medical & Dental", "Medical/Dental", "Legal",
             "Real Estate", "Salon, Spa & Fitness", "Salon/Spa/Fitness"]

MARK_START = "<!-- BY-TRADE:start (generated by scripts/wire_service_pillars.py) -->"
MARK_END = "<!-- BY-TRADE:end -->"
FAQ_RE = re.compile(r"<!-- =+ FAQ =+ -->")


def _hub_rank(name):
    return HUB_ORDER.index(name) if name in HUB_ORDER else 99


def build_block(service, intro, pages):
    """pages = list of (hub_name, anchor, slug), already collected."""
    by_hub = {}
    for hub, anchor, slug in pages:
        by_hub.setdefault(hub, []).append((anchor, slug))
    cols = []
    for hub in sorted(by_hub, key=_hub_rank):
        items = "\n".join(
            f'          <li><a href="{slug}.html">{anchor}</a></li>'
            for anchor, slug in sorted(by_hub[hub], key=lambda x: x[0].lower()))
        cols.append(f'''      <div class="reveal" style="min-width:240px;flex:1 1 280px">
        <h3 style="font-family:var(--sans);font-size:.82rem;letter-spacing:.12em;text-transform:uppercase;color:var(--gold);margin-bottom:.7rem">{esc(hub)}</h3>
        <ul style="list-style:none;line-height:1.85;font-size:.96rem">
{items}
        </ul>
      </div>''')
    return f'''{MARK_START}
<section class="section rule-top">
  <div class="container">
    <div class="section-head">
      <span class="eyebrow reveal">By Trade</span>
      <h2 class="display display-lg reveal" style="margin-top:1.6rem">{esc(service)} for <em>Every Trade</em></h2>
      <p class="reveal" style="color:var(--ink-3);max-width:64ch;margin-top:1rem">{esc(intro)}</p>
    </div>
    <div class="reveal" style="display:flex;flex-wrap:wrap;gap:2.4rem 3rem;margin-top:1.6rem">
{chr(10).join(cols)}
    </div>
  </div>
</section>
{MARK_END}
'''


def main():
    disc = gp.discover()                      # token -> {trade_plural, hub_name, ...}
    hub_of = {tok: d["hub_name"] for tok, d in disc.items()}
    total_pages = 0
    for sol, (service, prefixes, intro) in SERVICE_MAP.items():
        if not os.path.exists(sol):
            print(f"!! {sol} missing; skip"); continue
        pages = []
        for pref in prefixes:
            for f in sorted(glob.glob(f"{pref}-for-*.html")):
                if f.startswith("for-"):
                    continue
                tok = f[:-5].split("-for-", 1)[1]
                hub = hub_of.get(tok)
                if not hub:
                    print(f"   note: {f} token '{tok}' not in discovery; skip"); continue
                pages.append((hub, gp._money_title(f), f[:-5]))
        if not pages:
            print(f"{sol}: 0 money pages; no block"); continue
        html = open(sol, encoding="utf-8").read()
        block = build_block(service, intro, pages)
        if MARK_START in html:
            html = re.sub(re.escape(MARK_START) + r".*?" + re.escape(MARK_END) + r"\n?", block, html, flags=re.S)
        else:
            m = FAQ_RE.search(html)
            if m:
                html = html.replace(m.group(), block + "\n" + m.group(), 1)
            else:
                i = html.rfind("</main>")
                if i == -1:
                    print(f"!! {sol}: no FAQ anchor and no </main>; skip"); continue
                html = html[:i] + block + "\n" + html[i:]
        open(sol, "w", encoding="utf-8", newline="").write(html)
        print(f"wired {sol}: {service} by trade, {len(pages)} links across {len(set(p[0] for p in pages))} hubs")
        total_pages += len(pages)
    print(f"done; {total_pages} money-page links added across service pillars")


if __name__ == "__main__":
    main()
