#!/usr/bin/env python3
"""Wire the colony question pages into their hub as a grouped "Common Questions" bridge
block, so every colony page has >=1 contextual inbound (plan §6; else seo_audit's orphan
check fails it). Reads scripts/colony_specs_*.py, groups topics by hub then trade, and
inserts/replaces one block before each hub's FAQ. Idempotent.

Run:  python scripts/wire_colony.py
"""
import os, re, sys, io, glob, importlib
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))

MARK_START = "<!-- COMMON-QS:start (generated by scripts/wire_colony.py) -->"
MARK_END = "<!-- COMMON-QS:end -->"

def load_topics():
    topics = []
    for sf in sorted(glob.glob(os.path.join(ROOT, "scripts", "colony_specs_*.py"))):
        mod = os.path.splitext(os.path.basename(sf))[0]
        try:
            topics += getattr(importlib.import_module(mod), "TOPICS", [])
        except Exception as e:
            print(f"note: {mod} not loaded ({e})")
    return topics

def block_for(hub_topics):
    # group by trade_plural
    by_trade = {}
    for t in hub_topics:
        by_trade.setdefault(t.get("trade_plural", ""), []).append(t)
    cols = []
    for trade, ts in by_trade.items():
        items = "\n".join(f'          <li><a href="{t["slug"]}.html">{re.sub(r"<[^>]+>", "", t["h1"])}</a></li>' for t in ts)
        cols.append(f'''      <div class="reveal" style="min-width:260px;flex:1 1 300px">
        <h3 style="font-family:var(--sans);font-size:.82rem;letter-spacing:.12em;text-transform:uppercase;color:var(--gold);margin-bottom:.7rem">{trade.title()}</h3>
        <ul style="list-style:none;line-height:1.75;font-size:.96rem">
{items}
        </ul>
      </div>''')
    return f'''{MARK_START}
<section class="section rule-top">
  <div class="container">
    <div class="section-head">
      <span class="eyebrow reveal">Answers</span>
      <h2 class="display display-lg reveal" style="margin-top:1.6rem">Common Questions We <em>Hear</em></h2>
    </div>
    <div class="reveal" style="display:flex;flex-wrap:wrap;gap:2rem 3rem;margin-top:1.6rem">
{chr(10).join(cols)}
    </div>
  </div>
</section>
{MARK_END}
'''

def wire_hub(hub_file, hub_topics):
    if not hub_topics or not os.path.exists(hub_file):
        return
    html = open(hub_file, encoding="utf-8").read()
    block = block_for(hub_topics)
    if MARK_START in html:
        html = re.sub(re.escape(MARK_START) + r".*?" + re.escape(MARK_END) + r"\n?", block, html, flags=re.S)
    else:
        m = re.search(r"<!-- =+ FAQ =+ -->", html)
        if not m:
            print(f"no FAQ anchor in {hub_file}; skipping"); return
        html = html.replace(m.group(), block + "\n" + m.group(), 1)
    open(hub_file, "w", encoding="utf-8", newline="").write(html)
    print(f"wired {hub_file}: Common Questions block ({len(hub_topics)} colony links)")

def main():
    topics = load_topics()
    if not topics:
        print("no colony topics found yet"); return
    by_hub = {}
    for t in topics:
        by_hub.setdefault(t["hub_slug"], []).append(t)
    for hub, ts in by_hub.items():
        wire_hub(hub, ts)

if __name__ == "__main__":
    main()
