#!/usr/bin/env python3
"""Wire the trade PILLARS both ways (plan §6):

  1. DOWN  — each industry hub (industry-*.html) gets a "Trades We Serve" block linking to
             every one of its `for-<trade>.html` pillars.
  2. UP    — each money page (`<service>-for-<trade>.html`) and each colony question page for a
             trade gets a small contextual "part of the complete <trade> guide" link UP to its
             `for-<trade>.html` pillar, so the colony -> pillar -> money authority flow is closed.

Only pillars that actually exist on disk are wired (so it is safe to run before every pillar is
built). Idempotent + marker-based, like wire_hub.py / wire_colony.py. Reuses the exact token /
money / colony discovery from generate_pillars.py (single source of truth). Run AFTER
generate_pillars.py (and after wire_hub.py / wire_colony.py):

  python scripts/wire_pillars.py
"""
import os, re, sys, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import generate_pillars as gp  # importing this sets sys.stdout to UTF-8 (via generate_corpus)
esc = gp.esc

HUB_START = "<!-- TRADE-PILLARS:start (generated by scripts/wire_pillars.py) -->"
HUB_END = "<!-- TRADE-PILLARS:end -->"
UP_START = "<!-- PILLAR-UP:start (generated by scripts/wire_pillars.py) -->"
UP_END = "<!-- PILLAR-UP:end -->"
FAQ_RE = re.compile(r"<!-- =+ FAQ =+ -->")


def _read(p):
    return open(p, encoding="utf-8", errors="replace").read()


def _write(p, s):
    open(p, "w", encoding="utf-8", newline="").write(s)


def hub_block(hub_name, pillars):
    """pillars = sorted list of (token, trade_plural)."""
    items = "\n".join(
        f'          <li><a href="for-{tok}.html">{esc(tp).title()}</a></li>' for tok, tp in pillars)
    return f'''{HUB_START}
<section class="section rule-top">
  <div class="container">
    <div class="section-head">
      <span class="eyebrow reveal">Trades We Serve</span>
      <h2 class="display display-lg reveal" style="margin-top:1.6rem">Built for Your <em>{esc(hub_name)}</em> Business</h2>
    </div>
    <ul class="reveal" style="list-style:none;display:flex;flex-wrap:wrap;gap:.6rem 2.4rem;line-height:2.1;font-size:1.02rem;margin-top:1.4rem">
{items}
    </ul>
  </div>
</section>
{HUB_END}
'''


def wire_hub(hub_file, pillars):
    if not os.path.exists(hub_file):
        print(f"!! hub {hub_file} missing; skip"); return
    html = _read(hub_file)
    block = hub_block(pillars[0][2], [(t, tp) for t, tp, _ in pillars])
    if HUB_START in html:
        html = re.sub(re.escape(HUB_START) + r".*?" + re.escape(HUB_END) + r"\n?", block, html, flags=re.S)
    else:
        m = FAQ_RE.search(html)
        if not m:
            print(f"!! {hub_file}: no FAQ anchor; skip"); return
        html = html.replace(m.group(), block + "\n" + m.group(), 1)
    _write(hub_file, html)
    print(f"wired {hub_file}: Trades We Serve ({len(pillars)} pillars)")


def up_block(token, trade_plural):
    return f'''{UP_START}
<section class="section rule-top">
  <div class="container">
    <p class="reveal" style="color:var(--ink-3);max-width:64ch">Part of everything Top Shelf builds for <a href="for-{token}.html">{esc(trade_plural)}</a>. <a href="for-{token}.html">See the complete {esc(trade_plural)} guide <span class="arr">&rarr;</span></a></p>
  </div>
</section>
{UP_END}
'''


def inject_up(page_file, token, trade_plural):
    if not os.path.exists(page_file):
        return False
    html = _read(page_file)
    block = up_block(token, trade_plural)
    if UP_START in html:
        new = re.sub(re.escape(UP_START) + r".*?" + re.escape(UP_END) + r"\n?", block, html, flags=re.S)
    else:
        i = html.rfind("</main>")
        if i == -1:
            return False
        new = html[:i] + block + "\n" + html[i:]
    if new != html:
        _write(page_file, new)
    return True


def main():
    disc = gp.discover()
    # keep only trades whose pillar exists on disk
    live = {tok: d for tok, d in disc.items() if os.path.exists(f"for-{tok}.html")}
    if not live:
        print("no pillars on disk yet (run generate_pillars.py first)"); return

    # 1) DOWN: group pillars by hub and wire each industry hub
    hubs = {}
    for tok, d in live.items():
        hubs.setdefault(d["hub_slug"], []).append((tok, d["trade_plural"], d["hub_name"]))
    for hub_file, pillars in sorted(hubs.items()):
        pillars.sort(key=lambda x: x[1])
        wire_hub(hub_file, pillars)

    # 2) UP: inject the pillar link into every money + colony page of each live trade
    up_pages = 0
    for tok, d in live.items():
        targets = [f"{slug}.html" for slug, _ in d["money"]] + [f"{slug}.html" for slug, _ in d["colony"]]
        for pf in targets:
            if inject_up(pf, tok, d["trade_plural"]):
                up_pages += 1
    print(f"injected up-to-pillar link into {up_pages} money/colony pages across {len(live)} trades")


if __name__ == "__main__":
    main()
