#!/usr/bin/env python3
"""Wire corpus money pages into their industry hub as a grouped "Deep Dives by Trade" block
(plan §6: every corpus page needs >=1 contextual inbound). Auto-discovers scripts/specs_*.py,
groups by hub_slug, and inserts/replaces one block before each hub's FAQ anchor. Idempotent.

Generalized 2026-09-19 from home-services-only to EVERY hub (home-services / medical-dental /
legal / auto / ...). A hub that already carries -for- money-page links but NO marker is treated
as manually wired and skipped, so the hand-built real-estate "Deep Dives" section is left alone.

Run:  python scripts/wire_hub.py
"""
import os, re, sys, io, glob, importlib
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, "scripts"))

SERVICE_LABEL = {
    "ai-receptionist": "AI receptionist", "crm": "CRM & follow-up", "online-booking": "Online booking",
    "review-software": "Review software", "websites-seo": "Websites & SEO", "marketing": "Marketing",
    "automation": "Automation", "payments": "Payments", "pos": "POS & inventory", "memberships": "Memberships",
}
MARK_START = "<!-- DEEP-DIVES:start (generated by scripts/wire_hub.py) -->"
MARK_END = "<!-- DEEP-DIVES:end -->"
BLOCK_RE = re.compile(r"<!-- DEEP-DIVES(?:-HS)?:start.*?DEEP-DIVES(?:-HS)?:end -->\n?", re.S)
FAQ_RE = re.compile(r"<!-- =+ FAQ =+ -->")

def service_of(slug):
    return slug.split("-for-")[0]

def build_block(specs_by_trade, hub_name):
    order = list(SERVICE_LABEL.keys())
    groups = []
    for trade, specs in specs_by_trade:
        specs_sorted = sorted(specs, key=lambda d: order.index(service_of(d["slug"])) if service_of(d["slug"]) in order else 99)
        items = "\n".join(
            f'          <li><a href="{d["slug"]}.html">{SERVICE_LABEL.get(service_of(d["slug"]), service_of(d["slug"]))}</a></li>'
            for d in specs_sorted)
        groups.append(f'''      <div class="reveal" style="min-width:200px">
        <h3 style="font-family:var(--sans);font-size:.82rem;letter-spacing:.12em;text-transform:uppercase;color:var(--gold);margin-bottom:.7rem">{trade.title()}</h3>
        <ul style="list-style:none;line-height:1.9;font-size:.98rem">
{items}
        </ul>
      </div>''')
    cols = "\n".join(groups)
    return f'''{MARK_START}
<section class="section rule-top">
  <div class="container">
    <div class="section-head">
      <span class="eyebrow reveal">By Trade &amp; Service</span>
      <h2 class="display display-lg reveal" style="margin-top:1.6rem">Deep Dives for <em>{hub_name}</em></h2>
    </div>
    <div class="reveal" style="display:flex;flex-wrap:wrap;gap:2.4rem 3rem;margin-top:1.6rem">
{cols}
    </div>
  </div>
</section>
{MARK_END}
'''

def main():
    hubs = {}  # hub_slug -> {"name":..., "trades": {trade_plural: [specs]}}
    for sf in sorted(glob.glob(os.path.join(ROOT, "scripts", "specs_*.py"))):
        mod = os.path.splitext(os.path.basename(sf))[0]
        try:
            specs = getattr(importlib.import_module(mod), "SPECS", [])
        except Exception as e:
            print(f"note: {mod} not loaded ({e})"); continue
        if not specs:
            continue
        h = hubs.setdefault(specs[0]["hub_slug"], {"name": specs[0]["hub_name"], "trades": {}})
        h["trades"].setdefault(specs[0]["trade_plural"], []).extend(specs)
    total = 0
    for hub_slug, h in sorted(hubs.items()):
        if not os.path.exists(hub_slug):
            print(f"!! hub {hub_slug} missing; skip"); continue
        html = open(hub_slug, encoding="utf-8").read()
        # A hub may carry a hand-built Deep Dives section with no marker (e.g. real-estate's
        # realtor list, whose pages live in corpus_specs.py not specs_*.py). We do NOT skip it:
        # its specs_*.py trades still get their own marker block before the FAQ, and the hand-built
        # section is never touched because BLOCK_RE only matches our own marker.
        specs_by_trade = sorted(h["trades"].items())
        block = build_block(specs_by_trade, h["name"])
        if BLOCK_RE.search(html):
            html = BLOCK_RE.sub(lambda m: block, html)
        else:
            m = FAQ_RE.search(html)
            if not m:
                print(f"!! {hub_slug}: no FAQ anchor; skip"); continue
            html = html.replace(m.group(), block + "\n" + m.group(), 1)
        open(hub_slug, "w", encoding="utf-8", newline="").write(html)
        n = sum(len(s) for _, s in specs_by_trade)
        total += n
        print(f"wired {hub_slug}: {len(specs_by_trade)} trade(s), {n} money-page links")
    print(f"done; {total} links across {len(hubs)} hub(s)")

if __name__ == "__main__":
    main()
